#!/usr/bin/env python3
"""Generate analysis/naming2/verify_audio2_fixes.tsv (the corrections of the static adversarial check of audio pass 2) from the ROM + the song table.

Rows (old_name = current semantic name in the tree):
  1. SoundDrv_StopChannelTrackEnded -> SoundDrv_StopChannelTrackNotRunning   (the code tests track flags < $C0, which a paused / restarted track also satisfies)
  2. Data_SoundDrv_Streams -> SoundSong01_Track0                              (names one track, not 'the streams'; completes the SoundSong01_Track* family)
  3. SoundSongNN_Header / SoundSongNN_TrackK for the ids $29..$46 -> SoundSfxNN_Header / SoundSfxNN_TrackK  (the 30 effect records: every caller passes these ids to
     Sound_PlaySfx, none to Sound_PlayMusic*; the sound-test screen of the ROM labels the B button 'SOUND' and the A button 'MUSIC')
Usage: python3 make_fixes_tsv.py [ROOT] > out.tsv     (default: write analysis/naming2/verify_audio2_fixes.tsv in ROOT)
"""
import os, sys, io, contextlib, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
with contextlib.redirect_stdout(io.StringIO()):
    import decode_streams as D
ROOT = D.ROOT

HEAD = ('# old_name\tnew_name\tkind\tstatus\tevidence\n'
        '# analysis/naming2/verify_audio2_fixes.tsv -- corrections from the static adversarial check of audio pass 2 (docs/research/audio2_verify_static.md); '
        'old_name = current semantic name in the tree.  Generated by analysis/audio2_verify/make_fixes_tsv.py\n'
        '# Block A: two single corrections.  Block B: the 30 sound-effect records (ids $29-$46) get the prefix SoundSfx instead of SoundSong (75 rows); drop block B to keep the SoundSong prefix.\n')

rows = []
rows.append(('SoundDrv_StopChannelTrackEnded', 'SoundDrv_StopChannelTrackNotRunning', 'label', 'PROBABLE',
             'name corrected, behaviour unchanged: the only test before this label is cp $C0 / jr c on the owning track flags in SoundDrv_ServiceChannelGate (04:4BEB; its only referrer, '
             'not SoundDrv_UpdateChannel which jumps to SoundDrv_StopChannel itself); flags < $C0 holds for an ended track (SoundDrv_CmdEnd writes 0) but also for a paused music track '
             '(SoundDrv_PauseMusicCore does res 7,[hl] (04:4443) on the flags of the four music tracks) and for a track just restarted (SoundDrv_StartTrack writes $A0), so TrackEnded states a cause the code does not test'))
rows.append(('Data_SoundDrv_Streams', 'SoundSong01_Track0', 'data', 'CONFIRMED',
             'the label sits on 04:574D = word 0 of the header of song id $01 (04:58BC): the stream of track 0 of song $01, the same family as SoundSong01_Track1..3 (04:5788, 04:57F3, 04:5832); '
             'the old name read as "all streams" but only names this one track (the byte range 04:574D-7E8C holds the streams of ids $01-$0D)'))

# block B
users = {}
for n, r in D.records.items(): users.setdefault((r['bank'], r['header']), []).append(n)
blockB = []
for (bank, h), ids in sorted(users.items()):
    n = min(ids)
    if not (0x29 <= n <= 0x46): continue
    ev_hdr = (f'stream header of sound effect id ${n:02X} (record 04:5515 + 8*id of Table_SoundDrv_Songs, {D.records[n]["count"]} track(s)): prefix corrected from SoundSong to SoundSfx because '
              f'id ${n:02X} is an effect, not a song: the ROM passes the ids $29-$46 only to Sound_PlaySfx (367 call sites with an immediate id, none to Sound_PlayMusic / Sound_PlayMusicOrResume, '
              'which get $01-$1D), the unreferenced sound-test screen labels its B button (Sound_PlaySfx) "SOUND" and its A button (Sound_PlayMusic) "MUSIC", and docs/research/audio_format.md '
              'section 1 counts these 30 records as sound effects; only the prefix changes')
    blockB.append((f'SoundSong{n:02X}_Header', f'SoundSfx{n:02X}_Header', 'data', 'PROBABLE', ev_hdr))
    for k in range(D.records[n]['count']):
        blockB.append((f'SoundSong{n:02X}_Track{k}', f'SoundSfx{n:02X}_Track{k}', 'data', 'PROBABLE',
                       f'stream of track {k} of sound effect id ${n:02X} (word {k} of the header SoundSfx{n:02X}_Header): prefix corrected from SoundSong to SoundSfx, same reason as the header '
                       f'(id ${n:02X} is played only through Sound_PlaySfx; per-id execution not checked); only the prefix changes'))
out = HEAD + '\n'.join('\t'.join(r) for r in rows) + '\n# ---- block B: sound effects ($29-$46): SoundSong -> SoundSfx\n' + '\n'.join('\t'.join(r) for r in blockB) + '\n'
dest = os.path.join(ROOT, 'analysis/naming2/verify_audio2_fixes.tsv')
if len(sys.argv) > 2 and sys.argv[2] == '--stdout': sys.stdout.write(out)
else:
    open(dest, 'w', encoding='utf-8').write(out)
    print(f'wrote {dest}: {len(rows)} + {len(blockB)} rows')
