#!/usr/bin/env python3
"""Generate the macro sources of the monkey campaigns (traces/inputs/monkey_camp_*.macro), deterministically.

A campaign is one scenario made of many short random-input segments.  Every segment starts with a power cycle (`reset`: the
save RAM and the adapter configuration are kept, the adapter session restarts), waits for the boot, optionally sets one fake-Internet
fault (`net ...`), and then mashes buttons with the harness's seeded monkey (`monkey N SEED GAP PROFILE`, see mgba_trace.c).  Segment
parameters (seed, profile, tap gap, fault, adapter unplug/replug in the middle) come from a small LCG seeded per campaign, so
re-running this script rewrites byte-identical files.  Nothing here is coverage-guided; the point is breadth.

usage: make_campaigns.py            (writes traces/inputs/monkey_camp_*.macro)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INPUTS = ROOT / "traces" / "inputs"

FAULTS = [
    [],
    [],
    ["pop_fail=user"], ["pop_fail=pass"], ["pop_fail=stat"], ["pop_fail=retr"], ["pop_fail=connect"],
    ["smtp_fail=rcpt"], ["smtp_fail=data"], ["smtp_fail=connect"], ["smtp_fail=end"],
    ["http_status=500"], ["http_missing=500"], ["http_trunc=300"], ["http_nolen=1"],
    ["dns=nx"], ["dns=drop"], ["tcp=refuse"], ["tcp=reset"],
    ["cgi=200/-/-/cgb/30303030"], ["cgi=401/-/fake/-/-"], ["cgi=200/-/-/html/3c623e4f4b3c2f623e"],
]
PROFILES = ["mix", "a", "nav", "kb", "menu", "combo", "mix", "a", "menu"]

CAMPAIGNS = {
    # name: (segments, frames per segment, seed base, description of the start state)
    "monkey_camp_reg": (28, 6000, 100, "freshly registered cartridge ('register': registered adapter, first-run tutorial pending)"),
    "monkey_camp_tut": (28, 6000, 200, "set-up cartridge after the tutorial ('tutorial_profile')"),
    "monkey_camp_rich": (36, 6000, 300, "cartridge with mails, address book, bookmarks ('browser_errors')"),
    "monkey_camp_blank": (24, 5000, 400, "blank cartridge and blank adapter (the initial-registration wizard)"),
    "monkey_camp_hid": (32, 6000, 500, "cartridge after the hidden mail-server run ('mail_server_hidden': empty server, mails in the mailbox)"),
    "monkey_camp_reg2": (28, 6000, 600, "cartridge registered through the hidden wizard variant ('register_hidden', tutorial pending)"),
}


class Lcg:
    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFF

    def next(self, n):
        self.s = (self.s * 1664525 + 1013904223) & 0xFFFFFFFF
        return (self.s >> 8) % n


def campaign(name, nseg, frames, seed0, start):
    r = Lcg(seed0)
    L = ["# Scenario '%s': monkey campaign, %d segments of %d frames from %s." % (name, nseg, frames, start),
         "# Generated by tools/trace/make_campaigns.py (deterministic). Every segment: power cycle (`reset`), boot, an optional fake-Internet fault",
         "# (`net ...`), then `monkey <frames> <seed> <gap> <profile>` (seeded random taps; profiles mix a nav kb menu combo, see mgba_trace.c);",
         "# a few segments unplug the adapter for a while (`unplug` / `plug`). The fake Internet has latency 2 frames, mails on the POP3 server",
         "# and the richer synthetic web site (see scenarios.tsv). Purpose: breadth; absence of coverage proves nothing."]
    for i in range(nseg):
        seed = seed0 * 100 + i * 7 + 1
        prof = PROFILES[r.next(len(PROFILES))]
        gap = [4, 8, 12, 16, 20, 24, 32, 40][r.next(8)]
        fault = FAULTS[r.next(len(FAULTS))]
        unplug = r.next(6) == 0
        L.append("# --- segment %d: seed %d profile %s gap %d faults %s%s" % (i, seed, prof, gap, ",".join(fault) or "none", " unplug" if unplug else ""))
        if i:
            L.append("reset")
            L.append("net pop_fail=none")
            L.append("net smtp_fail=none")
            L += ["net http_status=0", "net http_missing=404", "net http_trunc=-1", "net http_nolen=0", "net dns=ok", "net tcp=ok", "net cgi=none"]
        L.append("wait 400")
        L.append("waitstable 60 max 600")
        for f in fault:
            L.append("net " + f)
        if unplug:
            L.append("monkey %d %d %d %s" % (frames // 3, seed, gap, prof))
            L.append("unplug")
            L.append("monkey %d %d %d %s" % (frames // 6, seed + 1, gap, prof))
            L.append("plug")
            L.append("monkey %d %d %d %s" % (frames - frames // 3 - frames // 6, seed + 2, gap, prof))
        else:
            L.append("monkey %d %d %d %s" % (frames, seed, gap, prof))
        if i % 8 == 7:
            L.append("shot seg%d_end" % i)
    return "\n".join(L) + "\n"


def main():
    for name, (n, fr, seed, start) in CAMPAIGNS.items():
        (INPUTS / (name + ".macro")).write_text(campaign(name, n, fr, seed, start))
        print("wrote", name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
