# gfx/png.mk -- GENERATED by tools/png_rules.py from gfx/png_rules.tsv (do not edit by hand); included by the Makefile.
#
# PNG is the editable source of every graphic listed in gfx/png_rules.tsv: the binary the .asm INCBINs is rebuilt from its PNG whenever the PNG
# is newer (rgbgfx for tile sheets, tools/font_png.py for font sheets).  A fresh git checkout has arbitrary mtimes, so the rules may run for every
# file; they are deterministic and give back the committed bytes (the old file is kept when the bytes are identical).  The size of a binary must
# not change (the ROM layout is pinned by layout.link): a PNG that converts to another size is refused with an explanation.
#
# Variables used (defined in the Makefile): RGBGFX, PYTHON, Q.  Without rgbgfx / python3 the rules are not included (the committed binaries are used).

# rebuild $@ from $<: $@.tmp was written by the converter; size must be PNG_SIZE; identical bytes keep the old file (only touched)
define png_finish
got=$$(wc -c < $@.tmp); \
if [ "$$got" != "$(PNG_SIZE)" ]; then \
	echo "error: $< converts to $$got bytes but the ROM needs exactly $(PNG_SIZE) for $@: do not resize the image or add/remove tiles/glyphs"; \
	if [ -n "$(PYTHON_OK)" ]; then $(PYTHON) tools/png_check.py --file $<; fi; \
	rm -f $@.tmp; exit 1; fi; \
if cmp -s $@.tmp $@ 2>/dev/null; then rm -f $@.tmp; touch $@; \
else \
	if [ -n "$(PYTHON_OK)" ]; then $(PYTHON) tools/png_check.py --file $< || { rm -f $@.tmp; exit 1; }; fi; \
	mv -f $@.tmp $@; echo "  -> $@ changed"; \
fi
endef


ifneq ($(RGBGFX_VERSION),)
PNG_TILE_OUTS := \
	gfx/account/screens_bank4a/tiles_4040.2bpp \
	gfx/account/screens_bank4a/tiles_4240.2bpp \
	gfx/account/screens_bank4a/tiles_4640.2bpp \
	gfx/account/screens_bank4a/tiles_4a40.2bpp \
	gfx/account/screens_bank4a/tiles_4e40.2bpp \
	gfx/account/screens_bank4a/tiles_5860.2bpp \
	gfx/account/screens_bank4a/tiles_5870.2bpp \
	gfx/account/screens_bank4a/tiles_5c70.2bpp \
	gfx/account/screens_bank4b/tiles_42d0.2bpp \
	gfx/account/screens_bank4b/tiles_46d0.2bpp \
	gfx/account/screens_bank4b/tiles_5080.2bpp \
	gfx/account/screens_bank4b/tiles_5420.2bpp \
	gfx/account/screens_bank4b/tiles_5878.2bpp \
	gfx/account/screens_bank5d/tiles_4800.2bpp \
	gfx/account/screens_bank5d/tiles_4c00.2bpp \
	gfx/account/screens_bank5d/tiles_5320.2bpp \
	gfx/account/screens_bank5d/tiles_5720.2bpp \
	gfx/account/screens_bank5d/tiles_5df0.2bpp \
	gfx/account/screens_bank5d/tiles_61f0.2bpp \
	gfx/account/screens_bank5d/tiles_63f0.2bpp \
	gfx/account/screens_bank5d/tiles_65f0.2bpp \
	gfx/account/screens_bank5d/tiles_6900.2bpp \
	gfx/account/screens_bank5d/tiles_6c00.2bpp \
	gfx/account/screens_bank5d/tiles_6e00.2bpp \
	gfx/account/screens_bank5e/tiles_4800.2bpp \
	gfx/account/screens_bank5e/tiles_4c00.2bpp \
	gfx/account/screens_bank5e/tiles_4e10.2bpp \
	gfx/account/screens_bank5e/tiles_5210.2bpp \
	gfx/account/screens_bank5e/tiles_57e0.2bpp \
	gfx/account/screens_bank5e/tiles_5800.2bpp \
	gfx/account/screens_bank5e/tiles_5c00.2bpp \
	gfx/account/screens_bank5e/tiles_60d0.2bpp \
	gfx/account/screens_bank5e/tiles_64d0.2bpp \
	gfx/account/screens_bank5e/tiles_6ba0.2bpp \
	gfx/account/screens_bank5e/tiles_6fa0.2bpp \
	gfx/account/screens_bank71/tiles_4000.2bpp \
	gfx/account/screens_bank71/tiles_4300.2bpp \
	gfx/account/screens_bank71/tiles_4500.2bpp \
	gfx/account/screens_bank71/tiles_4890.2bpp \
	gfx/account/screens_bank71/tiles_5340.2bpp \
	gfx/account/screens_bank71/tiles_5740.2bpp \
	gfx/account/screens_bank71/tiles_5b40.2bpp \
	gfx/account/screens_bank71/tiles_5dc0.2bpp \
	gfx/account/screens_bank71/tiles_61c0.2bpp \
	gfx/account/screens_bank71/tiles_6440.2bpp \
	gfx/account/screens_bank71/tiles_6580.2bpp \
	gfx/address_book/address_picker/addr_book_tiles8f00.2bpp \
	gfx/address_book/address_picker/addr_pick_tiles9300.2bpp \
	gfx/address_book/address_picker/addr_pick_tiles9700.2bpp \
	gfx/address_book/address_picker/tiles_6fd0.2bpp \
	gfx/address_book/entry_screen_bank29/tiles_5b10.2bpp \
	gfx/address_book/entry_screen_bank29/tiles_5e50.2bpp \
	gfx/address_book/entry_screen_bank29/tiles_6250.2bpp \
	gfx/address_book/entry_screen_bank2a/addr_book_entry_tiles8000.2bpp \
	gfx/address_book/entry_screen_bank2a/addr_book_entry_tiles8f00.2bpp \
	gfx/address_book/name_editor/tiles_61f0.2bpp \
	gfx/address_book/name_editor/tiles_65f0.2bpp \
	gfx/address_book/name_editor/tiles_66f0.2bpp \
	gfx/address_book/save_confirm/addr_save_confirm_tiles9300.2bpp \
	gfx/address_book/save_confirm/addr_save_confirm_tiles9700.2bpp \
	gfx/address_book/save_sender_address/save_sender_addr_tiles9300.2bpp \
	gfx/address_book/save_sender_address/tiles_4fe0.2bpp \
	gfx/address_book/shared_tiles_bank28/tiles_4bd0.2bpp \
	gfx/address_book/shared_tiles_bank28/tiles_4fd0.2bpp \
	gfx/address_book/unreferenced_confirm_screen/tiles_7740.2bpp \
	gfx/address_book/unreferenced_confirm_screen/tiles_7b70.2bpp \
	gfx/bank41/tiles_4000.2bpp \
	gfx/bank41/tiles_4d50.2bpp \
	gfx/bank41/tiles_5aa0.2bpp \
	gfx/bank41/tiles_67f0.2bpp \
	gfx/bank42/tiles_4000.2bpp \
	gfx/bank42/tiles_4802.2bpp \
	gfx/bank42/tiles_4900.2bpp \
	gfx/bank42/tiles_4d50.2bpp \
	gfx/bank42/tiles_4f00.2bpp \
	gfx/bank42/tiles_52c0.2bpp \
	gfx/bank42/tiles_52e0.2bpp \
	gfx/bank42/tiles_5aa0.2bpp \
	gfx/bank42/tiles_5e90.2bpp \
	gfx/bank42/tiles_5f92.2bpp \
	gfx/bank42/tiles_62a0.2bpp \
	gfx/bank42/tiles_63a0.2bpp \
	gfx/bank42/tiles_63b0.2bpp \
	gfx/bank42/tiles_67f0.2bpp \
	gfx/bank42/tiles_6810.2bpp \
	gfx/bank42/tiles_69b0.2bpp \
	gfx/bank42/tiles_6ff2.2bpp \
	gfx/bank42/tiles_70f0.2bpp \
	gfx/bank43/tiles_4000.2bpp \
	gfx/bank43/tiles_4d50.2bpp \
	gfx/bank43/tiles_5aa0.2bpp \
	gfx/bank43/tiles_67f0.2bpp \
	gfx/bank44/tiles_4000.2bpp \
	gfx/bank44/tiles_4d50.2bpp \
	gfx/bank44/tiles_5aa0.2bpp \
	gfx/bank44/tiles_67f0.2bpp \
	gfx/bank45/tiles_4000.2bpp \
	gfx/bank45/tiles_4d50.2bpp \
	gfx/bank45/tiles_5aa0.2bpp \
	gfx/bank45/tiles_67f0.2bpp \
	gfx/bank46/tiles_4000.2bpp \
	gfx/bank46/tiles_4d50.2bpp \
	gfx/bank46/tiles_5aa0.2bpp \
	gfx/bank46/tiles_67f0.2bpp \
	gfx/bank52/tiles_4080.2bpp \
	gfx/bank5b/tiles_4000.2bpp \
	gfx/bank5b/tiles_5200.2bpp \
	gfx/bank60/tiles_4360.2bpp \
	gfx/bank60/tiles_4455.2bpp \
	gfx/bank60/tiles_4b50.2bpp \
	gfx/bank60/tiles_4dd0.2bpp \
	gfx/bank60/tiles_52c0.2bpp \
	gfx/bank60/tiles_52d0.2bpp \
	gfx/bank60/tiles_5640.2bpp \
	gfx/bank60/tiles_5740.2bpp \
	gfx/bank60/tiles_5800.2bpp \
	gfx/bank60/tiles_5d50.2bpp \
	gfx/bank60/tiles_6010.2bpp \
	gfx/bank60/tiles_6060.2bpp \
	gfx/bank60/tiles_62b0.2bpp \
	gfx/bank60/tiles_64c0.2bpp \
	gfx/bank60/tiles_6580.2bpp \
	gfx/bank60/tiles_6640.2bpp \
	gfx/bank60/tiles_70a0.2bpp \
	gfx/bank60/tiles_76f0.2bpp \
	gfx/bank61/tiles_4cc0.2bpp \
	gfx/bank61/tiles_4f63.2bpp \
	gfx/bank61/tiles_58b0.2bpp \
	gfx/bank61/tiles_65c0.2bpp \
	gfx/browser/frames_0_1/tiles_4000.2bpp \
	gfx/browser/frames_0_1/tiles_4010.2bpp \
	gfx/browser/frames_0_1/tiles_4040.2bpp \
	gfx/browser/frames_0_1/tiles_4080.2bpp \
	gfx/browser/frames_0_1/tiles_4090.2bpp \
	gfx/browser/frames_0_1/tiles_40c0.2bpp \
	gfx/browser/frames_0_1/tiles_40d0.2bpp \
	gfx/browser/frames_0_1/tiles_4100.2bpp \
	gfx/browser/frames_0_1/tiles_4e50.2bpp \
	gfx/browser/frames_2_3/tiles_5ba0.2bpp \
	gfx/browser/frames_2_3/tiles_68f0.2bpp \
	gfx/browser/menus/browser_menu2_tiles0.2bpp \
	gfx/browser/menus/browser_menu2_tiles1.2bpp \
	gfx/browser/menus/browser_menu3_tiles0.2bpp \
	gfx/browser/menus/browser_menu3_tiles1.2bpp \
	gfx/browser/page_list/page_list_tiles_5400.2bpp \
	gfx/browser/page_list/page_list_tiles_5800.2bpp \
	gfx/browser/page_list/tiles_55d0.2bpp \
	gfx/browser/page_list/tiles_5810.2bpp \
	gfx/browser/page_list/tiles_5ef1.2bpp \
	gfx/browser/page_list/tiles_6301.2bpp \
	gfx/browser/page_list/tiles_63e0.2bpp \
	gfx/browser/start_choice/browser_start_tiles0.2bpp \
	gfx/browser/start_choice/browser_start_tiles1.2bpp \
	gfx/browser/start_choice/browser_start_tiles2.2bpp \
	gfx/browser/start_choice/browser_start_tiles3.2bpp \
	gfx/browser/start_choice/browser_start_tiles4.2bpp \
	gfx/browser/start_choice/tiles_4530.2bpp \
	gfx/browser/start_choice/tiles_49e0.2bpp \
	gfx/comm/comm_scene/tiles_5490.2bpp \
	gfx/comm/comm_scene/tiles_5890.2bpp \
	gfx/comm/comm_scene/tiles_5c90.2bpp \
	gfx/comm/comm_scene/tiles_6090.2bpp \
	gfx/comm/comm_scene/tiles_6490.2bpp \
	gfx/comm/comm_scene/tiles_6690.2bpp \
	gfx/comm/comm_scene/tiles_6890.2bpp \
	gfx/comm/comm_scene/tiles_6a90.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_526a.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_52c0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_56c0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_5ac0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_5dc0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_60c0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_64c0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_68c0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_6ac0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_6ec0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_71c0.2bpp \
	gfx/comm/connect_dialog_bank56/tiles_75c0.2bpp \
	gfx/comm/connect_dialog_screen/connect_dialog_blank_tile.2bpp \
	gfx/comm/connection_icon/conn_icon_tiles0.2bpp \
	gfx/comm/connection_icon/conn_icon_tiles1.2bpp \
	gfx/comm/notice_dialog/tiles_5a20.2bpp \
	gfx/comm/notice_dialog/tiles_5e20.2bpp \
	gfx/comm/notice_dialog/tiles_5fc0.2bpp \
	gfx/comm/notice_dialog/tiles_5fd0.2bpp \
	gfx/comm/notice_dialog/tiles_62f0.2bpp \
	gfx/comm/notice_dialog/tiles_66f0.2bpp \
	gfx/comm/notice_dialog/tiles_6890.2bpp \
	gfx/comm/notice_dialog/tiles_68a0.2bpp \
	gfx/comm/time_summary/tiles_42a0.2bpp \
	gfx/comm/time_summary/tiles_46a0.2bpp \
	gfx/comm/time_summary/tiles_4db0.2bpp \
	gfx/comm/time_summary/tiles_51b0.2bpp \
	gfx/comm/time_summary/tiles_58c0.2bpp \
	gfx/comm/time_summary/tiles_5cc0.2bpp \
	gfx/comm/time_summary/tiles_5ee1.2bpp \
	gfx/dialog/dialog_window/dialog_window_tiles.2bpp \
	gfx/error/comm_error_screen/comm_err_gfx_bg9000.2bpp \
	gfx/error/comm_error_screen/comm_err_gfx_bg9400.2bpp \
	gfx/error/comm_error_screen/comm_err_gfx_obj8000.2bpp \
	gfx/error/comm_error_screen/comm_err_gfx_obj8100.2bpp \
	gfx/error/no_adapter/no_adapter_gfx_8000.2bpp \
	gfx/error/no_adapter/no_adapter_gfx_8800.2bpp \
	gfx/error/no_adapter/no_adapter_gfx_8c00.2bpp \
	gfx/error/no_adapter/no_adapter_gfx_9000.2bpp \
	gfx/error/no_adapter/no_adapter_gfx_9400.2bpp \
	gfx/error/no_adapter/tiles_6480.2bpp \
	gfx/error/non_cgb_screen/non_cgb_tiles.2bpp \
	gfx/error/non_cgb_screen/tiles_4060.2bpp \
	gfx/help/help_screens_a/tiles_4e90.2bpp \
	gfx/help/help_screens_a/tiles_5290.2bpp \
	gfx/help/help_screens_a/tiles_5690.2bpp \
	gfx/help/help_screens_a/tiles_5a90.2bpp \
	gfx/help/help_screens_a/tiles_5ab0.2bpp \
	gfx/help/help_screens_a/tiles_5eb0.2bpp \
	gfx/help/help_screens_b/tiles_69f0.2bpp \
	gfx/help/help_screens_b/tiles_6a10.2bpp \
	gfx/help/help_screens_b/tiles_6a20.2bpp \
	gfx/help/help_screens_b/tiles_6e20.2bpp \
	gfx/help/mobile_dictionary/mobile_dict_tiles0.2bpp \
	gfx/help/mobile_dictionary/mobile_dict_tiles1.2bpp \
	gfx/help/mobile_dictionary/mobile_dict_tiles2.2bpp \
	gfx/keyboard/panels_bank5d/tiles_4000.2bpp \
	gfx/keyboard/panels_bank5d/tiles_4400.2bpp \
	gfx/keyboard/panels_bank5f/tiles_4000.2bpp \
	gfx/keyboard/panels_bank5f/tiles_4400.2bpp \
	gfx/keyboard/panels_bank5f/tiles_4800.2bpp \
	gfx/keyboard/panels_bank5f/tiles_49d0.2bpp \
	gfx/keyboard/panels_bank5f/tiles_5900.2bpp \
	gfx/keyboard/panels_bank5f/tiles_5d00.2bpp \
	gfx/keyboard/panels_bank5f/tiles_6100.2bpp \
	gfx/keyboard/tiles_bank62/tiles_4000.2bpp \
	gfx/keyboard/tiles_bank62/tiles_4400.2bpp \
	gfx/keyboard/tiles_bank62/tiles_4800.2bpp \
	gfx/keyboard/tiles_bank62/tiles_4a40.2bpp \
	gfx/keyboard/tiles_bank62/tiles_4b00.2bpp \
	gfx/keyboard/tiles_bank62/tiles_4f00.2bpp \
	gfx/keyboard/tiles_bank62/tiles_5300.2bpp \
	gfx/keyboard/tiles_bank62/tiles_5540.2bpp \
	gfx/keyboard/tiles_bank62/tiles_5600.2bpp \
	gfx/keyboard/tiles_bank62/tiles_5a00.2bpp \
	gfx/keyboard/tiles_bank62/tiles_5e00.2bpp \
	gfx/keyboard/tiles_bank62/tiles_6040.2bpp \
	gfx/keyboard/tiles_bank62/tiles_6100.2bpp \
	gfx/keyboard/tiles_bank62/tiles_6500.2bpp \
	gfx/keyboard/tiles_bank62/tiles_6900.2bpp \
	gfx/keyboard/tiles_bank62/tiles_6b40.2bpp \
	gfx/keyboard/tiles_bank66/tiles_4000.2bpp \
	gfx/keyboard/tiles_bank66/tiles_4400.2bpp \
	gfx/keyboard/tiles_bank66/tiles_4800.2bpp \
	gfx/keyboard/tiles_bank66/tiles_4a40.2bpp \
	gfx/keyboard/tiles_bank66/tiles_4e40.2bpp \
	gfx/keyboard/tiles_bank66/tiles_5240.2bpp \
	gfx/keyboard/tiles_bank66/tiles_5480.2bpp \
	gfx/keyboard/tiles_bank66/tiles_5880.2bpp \
	gfx/keyboard/tiles_bank66/tiles_5c80.2bpp \
	gfx/keyboard/tiles_bank66/tiles_5ec0.2bpp \
	gfx/keyboard/tiles_bank66/tiles_62c0.2bpp \
	gfx/keyboard/tiles_bank66/tiles_66c0.2bpp \
	gfx/keyboard/tiles_bank66/tiles_6900.2bpp \
	gfx/keyboard/tiles_bank66/tiles_6a90.2bpp \
	gfx/mail/address_editor/mail_addr_obj_tiles.2bpp \
	gfx/mail/address_editor/mail_addr_tiles.2bpp \
	gfx/mail/address_editor/mail_addr_tiles2.2bpp \
	gfx/mail/address_editor/mail_addr_tiles3.2bpp \
	gfx/mail/address_editor/tiles_7940.2bpp \
	gfx/mail/body_editor/mail_body_obj_tiles.2bpp \
	gfx/mail/body_editor/mail_body_tiles.2bpp \
	gfx/mail/body_editor/mail_body_tiles2.2bpp \
	gfx/mail/body_view/mail_body_tiles_42c0.2bpp \
	gfx/mail/body_view/mail_body_tiles_44d0.2bpp \
	gfx/mail/comm_result/mail_result_tiles_6bf0.2bpp \
	gfx/mail/comm_result/mail_result_tiles_6ff0.2bpp \
	gfx/mail/comm_result/mail_result_tiles_73f0.2bpp \
	gfx/mail/comm_result/mail_result_tiles_7490.2bpp \
	gfx/mail/connect_screen/mail_connect_tiles_5060.2bpp \
	gfx/mail/connect_screen/mail_connect_tiles_5460.2bpp \
	gfx/mail/connect_screen/mail_connect_tiles_5860.2bpp \
	gfx/mail/connect_screen/mail_connect_tiles_5c60.2bpp \
	gfx/mail/connect_screen/mail_connect_tiles_5e60.2bpp \
	gfx/mail/connect_screen/mail_connect_tiles_6260.2bpp \
	gfx/mail/connect_screen/mail_connect_tiles_6660.2bpp \
	gfx/mail/connect_screen/mail_connect_tiles_6860.2bpp \
	gfx/mail/connect_screen/mail_connect_tiles_6c60.2bpp \
	gfx/mail/connect_screen_bank29/tiles_5400.2bpp \
	gfx/mail/draft_menu/mail_draft_menu_tiles8000.2bpp \
	gfx/mail/draft_menu/mail_draft_menu_tiles9300.2bpp \
	gfx/mail/mail_title_entry/mail_title_tiles8000.2bpp \
	gfx/mail/mail_title_entry/mail_title_tiles8800.2bpp \
	gfx/mail/mail_title_entry/mail_title_tiles9300.2bpp \
	gfx/mail/mail_viewer/mail_view_tiles8000.2bpp \
	gfx/mail/mail_viewer/mail_view_tiles9000.2bpp \
	gfx/mail/mail_viewer/mail_view_tiles9400.2bpp \
	gfx/mail/received_mail_grid/mail_grid_tiles8000.2bpp \
	gfx/mail/received_mail_grid/mail_grid_tiles9000.2bpp \
	gfx/mail/received_mail_grid/mail_grid_tiles9400.2bpp \
	gfx/mail/result_screens/mail_server_status_tiles_5060.2bpp \
	gfx/mail/server_status/mail_server_status_tiles_6f30.2bpp \
	gfx/mail/server_status/mail_server_status_tiles_7330.2bpp \
	gfx/mail/server_status_bank26/mail_server_status_tiles_7420.2bpp \
	gfx/mail/server_status_bank26/tiles_7840.2bpp \
	gfx/mail/session_scenery/mail_session_tiles_59e0.2bpp \
	gfx/mail/session_scenery/mail_session_tiles_5de0.2bpp \
	gfx/mail/session_scenery/mail_session_tiles_61e0.2bpp \
	gfx/mail/session_scenery/mail_session_tiles_62e0.2bpp \
	gfx/mail/session_scenery/mail_session_tiles_66e0.2bpp \
	gfx/mail/session_scenery/mail_session_tiles_67e0.2bpp \
	gfx/mail/session_scenery/mail_session_tiles_6be0.2bpp \
	gfx/mail/session_scenery/mail_session_tiles_6fe0.2bpp \
	gfx/mail/session_scenery/tiles_66f0.2bpp \
	gfx/mail_menu/mail_menu/mail_menu_tiles0.2bpp \
	gfx/mail_menu/mail_menu/mail_menu_tiles1.2bpp \
	gfx/mail_menu/mail_menu/mail_menu_tiles2.2bpp \
	gfx/mail_menu/mail_menu/mail_menu_tiles3.2bpp \
	gfx/mail_menu/mail_menu/mail_menu_tiles4.2bpp \
	gfx/mail_menu/mail_menu/mail_menu_tiles5.2bpp \
	gfx/mail_server/delete_all_screen/mail_server_delete_all_tiles_54b0.2bpp \
	gfx/mail_server/delete_all_screen/mail_server_delete_all_tiles_58b0.2bpp \
	gfx/mail_server/delete_all_screen/mail_server_delete_all_tiles_5b50.2bpp \
	gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_5f20.2bpp \
	gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_6150.2bpp \
	gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_6550.2bpp \
	gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_67e0.2bpp \
	gfx/mail_server/delete_progress/mail_srv_del_progress_tiles0.2bpp \
	gfx/mail_server/delete_progress/mail_srv_del_progress_tiles1.2bpp \
	gfx/mail_server/delete_progress/mail_srv_del_progress_tiles2.2bpp \
	gfx/mail_server/tidy_screen/mail_server_mgr_tiles0.2bpp \
	gfx/mail_server/tidy_screen/mail_server_mgr_tiles1.2bpp \
	gfx/mail_server/tidy_screen/mail_server_mgr_tiles2.2bpp \
	gfx/mail_server/tidy_screen/mail_server_mgr_tiles3.2bpp \
	gfx/mail_server/tidy_screen/mail_server_mgr_tiles4.2bpp \
	gfx/mail_server/tidy_screen/mail_server_mgr_tiles5.2bpp \
	gfx/mail_server/tidy_screen/tiles_5af0.2bpp \
	gfx/mailbox/mailbox/mailbox_tiles_5a10.2bpp \
	gfx/mailbox/mailbox/mailbox_tiles_5e10.2bpp \
	gfx/mailbox/mailbox/mailbox_tiles_5f10.2bpp \
	gfx/mailbox/mailbox/mailbox_tiles_6310.2bpp \
	gfx/mailbox/mailbox/mailbox_tiles_69f0.2bpp \
	gfx/mailbox/mailbox/mailbox_tiles_6cf0.2bpp \
	gfx/mailbox/mailbox/tiles_6bd1.2bpp \
	gfx/profile/profile_editor/profile_tiles8800.2bpp \
	gfx/profile/profile_editor/profile_tiles9300.2bpp \
	gfx/profile/profile_editor/profile_tiles9700.2bpp \
	gfx/registration/screens_bank58/tiles_4000.2bpp \
	gfx/registration/screens_bank58/tiles_41d0.2bpp \
	gfx/registration/screens_bank58/tiles_4450.2bpp \
	gfx/registration/screens_bank58/tiles_46d0.2bpp \
	gfx/registration/screens_bank58/tiles_4e50.2bpp \
	gfx/registration/screens_bank58/tiles_5350.2bpp \
	gfx/registration/screens_bank58/tiles_5850.2bpp \
	gfx/registration/screens_bank58/tiles_5ad0.2bpp \
	gfx/registration/screens_bank58/tiles_6d40.2bpp \
	gfx/registration/screens_bank58/tiles_7460.2bpp \
	gfx/registration/screens_bank58/tiles_7650.2bpp \
	gfx/registration/screens_bank58/tiles_7790.2bpp \
	gfx/settings/screens_bank4a/tiles_5f80.2bpp \
	gfx/settings/screens_bank4a/tiles_6080.2bpp \
	gfx/settings/screens_bank4a/tiles_6480.2bpp \
	gfx/settings/screens_bank4a/tiles_68d0.2bpp \
	gfx/settings/screens_bank4a/tiles_6920.2bpp \
	gfx/settings/screens_bank4a/tiles_6d20.2bpp \
	gfx/settings/screens_bank4b/tiles_5b90.2bpp \
	gfx/settings/screens_bank4b/tiles_6a90.2bpp \
	gfx/settings/screens_bank4b/tiles_6e90.2bpp \
	gfx/settings/screens_bank4b/tiles_70b0.2bpp \
	gfx/settings/screens_bank4b/tiles_76d0.2bpp \
	gfx/settings/screens_bank4b/tiles_7ad0.2bpp \
	gfx/settings/screens_bank4d/tiles_4000.2bpp \
	gfx/settings/screens_bank4d/tiles_4200.2bpp \
	gfx/settings/screens_bank4d/tiles_4510.2bpp \
	gfx/settings/screens_bank4d/tiles_4610.2bpp \
	gfx/settings/screens_bank4d/tiles_4a10.2bpp \
	gfx/settings/screens_bank4d/tiles_4d10.2bpp \
	gfx/settings/screens_bank4d/tiles_5010.2bpp \
	gfx/settings/screens_bank4d/tiles_5110.2bpp \
	gfx/settings/screens_bank4d/tiles_5510.2bpp \
	gfx/settings/screens_bank4d/tiles_5d50.2bpp \
	gfx/settings/screens_bank4d/tiles_5d70.2bpp \
	gfx/settings/screens_bank4d/tiles_6170.2bpp \
	gfx/settings/screens_bank4d/tiles_6570.2bpp \
	gfx/settings/screens_bank4d/tiles_6870.2bpp \
	gfx/settings/screens_bank4d/tiles_6c70.2bpp \
	gfx/settings/screens_bank4d/tiles_6d70.2bpp \
	gfx/settings/screens_bank4d/tiles_7170.2bpp \
	gfx/settings/screens_bank4d/tiles_7470.2bpp \
	gfx/settings/screens_bank5d/tiles_7360.2bpp \
	gfx/settings/screens_bank5d/tiles_7760.2bpp \
	gfx/settings/screens_bank5e/tiles_4000.2bpp \
	gfx/settings/screens_bank5e/tiles_4400.2bpp \
	gfx/title/logo/title_logo_tiles0.2bpp \
	gfx/title/logo/title_logo_tiles1.2bpp \
	gfx/title/title_screen/title_tiles0.2bpp \
	gfx/title/title_screen/title_tiles1.2bpp \
	gfx/title/title_screen/title_tiles2.2bpp \
	gfx/title/title_screen/title_tiles3.2bpp \
	gfx/title/title_screen/title_tiles4.2bpp \
	gfx/title/title_screen/title_tiles5.2bpp \
	gfx/title/title_screen/title_tiles6.2bpp \
	gfx/top_menu/top_menu/tiles_49a0.2bpp \
	gfx/top_menu/top_menu/tiles_4da0.2bpp \
	gfx/top_menu/top_menu/tiles_51a0.2bpp \
	gfx/top_menu/top_menu/tiles_55a0.2bpp \
	gfx/top_menu/top_menu/tiles_59a0.2bpp \
	gfx/top_menu/top_menu/tiles_5ba0.2bpp \
	gfx/top_menu/top_menu/tiles_5fa0.2bpp \
	gfx/unreferenced/page_list_prototype/tiles_62b0.2bpp \
	gfx/unreferenced/page_list_prototype/tiles_66b0.2bpp \
	gfx/unreferenced/page_list_prototype/tiles_6ae0.2bpp \
	gfx/unreferenced/page_list_prototype_objects/tiles_7830.2bpp \


gfx/account/screens_bank4a/tiles_4040.2bpp: PNG_SIZE := 512
gfx/account/screens_bank4a/tiles_4240.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank4a/tiles_4640.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank4a/tiles_4a40.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank4a/tiles_4e40.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank4a/tiles_5860.2bpp: PNG_SIZE := 16
gfx/account/screens_bank4a/tiles_5870.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank4a/tiles_5c70.2bpp: PNG_SIZE := 64
gfx/account/screens_bank4b/tiles_42d0.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank4b/tiles_46d0.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank4b/tiles_5080.2bpp: PNG_SIZE := 896
gfx/account/screens_bank4b/tiles_5420.2bpp: PNG_SIZE := 1104
gfx/account/screens_bank4b/tiles_5420.2bpp: PNG_PAD := -x 11
gfx/account/screens_bank4b/tiles_5878.2bpp: PNG_SIZE := 32
gfx/account/screens_bank5d/tiles_4800.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5d/tiles_4c00.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5d/tiles_5320.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5d/tiles_5720.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5d/tiles_5df0.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5d/tiles_61f0.2bpp: PNG_SIZE := 512
gfx/account/screens_bank5d/tiles_63f0.2bpp: PNG_SIZE := 512
gfx/account/screens_bank5d/tiles_65f0.2bpp: PNG_SIZE := 64
gfx/account/screens_bank5d/tiles_6900.2bpp: PNG_SIZE := 768
gfx/account/screens_bank5d/tiles_6c00.2bpp: PNG_SIZE := 512
gfx/account/screens_bank5d/tiles_6e00.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5e/tiles_4800.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5e/tiles_4c00.2bpp: PNG_SIZE := 256
gfx/account/screens_bank5e/tiles_4e10.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5e/tiles_5210.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5e/tiles_57e0.2bpp: PNG_SIZE := 32
gfx/account/screens_bank5e/tiles_5800.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5e/tiles_5c00.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5e/tiles_60d0.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5e/tiles_64d0.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5e/tiles_6ba0.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank5e/tiles_6fa0.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank71/tiles_4000.2bpp: PNG_SIZE := 768
gfx/account/screens_bank71/tiles_4300.2bpp: PNG_SIZE := 512
gfx/account/screens_bank71/tiles_4500.2bpp: PNG_SIZE := 912
gfx/account/screens_bank71/tiles_4500.2bpp: PNG_PAD := -x 7
gfx/account/screens_bank71/tiles_4890.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank71/tiles_5340.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank71/tiles_5740.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank71/tiles_5b40.2bpp: PNG_SIZE := 640
gfx/account/screens_bank71/tiles_5dc0.2bpp: PNG_SIZE := 1024
gfx/account/screens_bank71/tiles_61c0.2bpp: PNG_SIZE := 640
gfx/account/screens_bank71/tiles_6440.2bpp: PNG_SIZE := 320
gfx/account/screens_bank71/tiles_6580.2bpp: PNG_SIZE := 256
gfx/address_book/address_picker/addr_book_tiles8f00.2bpp: PNG_SIZE := 144
gfx/address_book/address_picker/addr_pick_tiles9300.2bpp: PNG_SIZE := 1024
gfx/address_book/address_picker/addr_pick_tiles9700.2bpp: PNG_SIZE := 256
gfx/address_book/address_picker/tiles_6fd0.2bpp: PNG_SIZE := 512
gfx/address_book/entry_screen_bank29/tiles_5b10.2bpp: PNG_SIZE := 768
gfx/address_book/entry_screen_bank29/tiles_5e50.2bpp: PNG_SIZE := 1024
gfx/address_book/entry_screen_bank29/tiles_6250.2bpp: PNG_SIZE := 64
gfx/address_book/entry_screen_bank2a/addr_book_entry_tiles8000.2bpp: PNG_SIZE := 176
gfx/address_book/entry_screen_bank2a/addr_book_entry_tiles8f00.2bpp: PNG_SIZE := 224
gfx/address_book/name_editor/tiles_61f0.2bpp: PNG_SIZE := 1024
gfx/address_book/name_editor/tiles_65f0.2bpp: PNG_SIZE := 256
gfx/address_book/name_editor/tiles_66f0.2bpp: PNG_SIZE := 768
gfx/address_book/save_confirm/addr_save_confirm_tiles9300.2bpp: PNG_SIZE := 1024
gfx/address_book/save_confirm/addr_save_confirm_tiles9700.2bpp: PNG_SIZE := 64
gfx/address_book/save_sender_address/save_sender_addr_tiles9300.2bpp: PNG_SIZE := 560
gfx/address_book/save_sender_address/save_sender_addr_tiles9300.2bpp: PNG_PAD := -x 13
gfx/address_book/save_sender_address/tiles_4fe0.2bpp: PNG_SIZE := 512
gfx/address_book/shared_tiles_bank28/tiles_4bd0.2bpp: PNG_SIZE := 1024
gfx/address_book/shared_tiles_bank28/tiles_4fd0.2bpp: PNG_SIZE := 512
gfx/address_book/unreferenced_confirm_screen/tiles_7740.2bpp: PNG_SIZE := 288
gfx/address_book/unreferenced_confirm_screen/tiles_7b70.2bpp: PNG_SIZE := 144
gfx/bank41/tiles_4000.2bpp: PNG_SIZE := 2560
gfx/bank41/tiles_4d50.2bpp: PNG_SIZE := 2560
gfx/bank41/tiles_5aa0.2bpp: PNG_SIZE := 2560
gfx/bank41/tiles_67f0.2bpp: PNG_SIZE := 2560
gfx/bank42/tiles_4000.2bpp: PNG_SIZE := 1344
gfx/bank42/tiles_4802.2bpp: PNG_SIZE := 160
gfx/bank42/tiles_4900.2bpp: PNG_SIZE := 176
gfx/bank42/tiles_4d50.2bpp: PNG_SIZE := 432
gfx/bank42/tiles_4f00.2bpp: PNG_SIZE := 960
gfx/bank42/tiles_52c0.2bpp: PNG_SIZE := 32
gfx/bank42/tiles_52e0.2bpp: PNG_SIZE := 1136
gfx/bank42/tiles_52e0.2bpp: PNG_PAD := -x 9
gfx/bank42/tiles_5aa0.2bpp: PNG_SIZE := 944
gfx/bank42/tiles_5aa0.2bpp: PNG_PAD := -x 5
gfx/bank42/tiles_5e90.2bpp: PNG_SIZE := 208
gfx/bank42/tiles_5f92.2bpp: PNG_SIZE := 416
gfx/bank42/tiles_62a0.2bpp: PNG_SIZE := 160
gfx/bank42/tiles_63a0.2bpp: PNG_SIZE := 16
gfx/bank42/tiles_63b0.2bpp: PNG_SIZE := 240
gfx/bank42/tiles_67f0.2bpp: PNG_SIZE := 16
gfx/bank42/tiles_6810.2bpp: PNG_SIZE := 400
gfx/bank42/tiles_6810.2bpp: PNG_PAD := -x 7
gfx/bank42/tiles_69b0.2bpp: PNG_SIZE := 784
gfx/bank42/tiles_69b0.2bpp: PNG_PAD := -x 15
gfx/bank42/tiles_6ff2.2bpp: PNG_SIZE := 160
gfx/bank42/tiles_70f0.2bpp: PNG_SIZE := 160
gfx/bank43/tiles_4000.2bpp: PNG_SIZE := 2560
gfx/bank43/tiles_4d50.2bpp: PNG_SIZE := 2560
gfx/bank43/tiles_5aa0.2bpp: PNG_SIZE := 2560
gfx/bank43/tiles_67f0.2bpp: PNG_SIZE := 2560
gfx/bank44/tiles_4000.2bpp: PNG_SIZE := 2560
gfx/bank44/tiles_4d50.2bpp: PNG_SIZE := 2560
gfx/bank44/tiles_5aa0.2bpp: PNG_SIZE := 2560
gfx/bank44/tiles_67f0.2bpp: PNG_SIZE := 2560
gfx/bank45/tiles_4000.2bpp: PNG_SIZE := 2560
gfx/bank45/tiles_4d50.2bpp: PNG_SIZE := 2560
gfx/bank45/tiles_5aa0.2bpp: PNG_SIZE := 2560
gfx/bank45/tiles_67f0.2bpp: PNG_SIZE := 2560
gfx/bank46/tiles_4000.2bpp: PNG_SIZE := 2560
gfx/bank46/tiles_4d50.2bpp: PNG_SIZE := 2560
gfx/bank46/tiles_5aa0.2bpp: PNG_SIZE := 2560
gfx/bank46/tiles_67f0.2bpp: PNG_SIZE := 2560
gfx/bank52/tiles_4080.2bpp: PNG_SIZE := 2944
gfx/bank5b/tiles_4000.2bpp: PNG_SIZE := 4608
gfx/bank5b/tiles_5200.2bpp: PNG_SIZE := 1152
gfx/bank60/tiles_4360.2bpp: PNG_SIZE := 240
gfx/bank60/tiles_4455.2bpp: PNG_SIZE := 1136
gfx/bank60/tiles_4455.2bpp: PNG_PAD := -x 9
gfx/bank60/tiles_4b50.2bpp: PNG_SIZE := 560
gfx/bank60/tiles_4b50.2bpp: PNG_PAD := -x 13
gfx/bank60/tiles_4dd0.2bpp: PNG_SIZE := 1184
gfx/bank60/tiles_4dd0.2bpp: PNG_PAD := -x 6
gfx/bank60/tiles_52c0.2bpp: PNG_SIZE := 16
gfx/bank60/tiles_52d0.2bpp: PNG_SIZE := 880
gfx/bank60/tiles_5640.2bpp: PNG_SIZE := 176
gfx/bank60/tiles_5740.2bpp: PNG_SIZE := 112
gfx/bank60/tiles_5800.2bpp: PNG_SIZE := 768
gfx/bank60/tiles_5d50.2bpp: PNG_SIZE := 704
gfx/bank60/tiles_6010.2bpp: PNG_SIZE := 80
gfx/bank60/tiles_6060.2bpp: PNG_SIZE := 592
gfx/bank60/tiles_6060.2bpp: PNG_PAD := -x 11
gfx/bank60/tiles_62b0.2bpp: PNG_SIZE := 448
gfx/bank60/tiles_64c0.2bpp: PNG_SIZE := 112
gfx/bank60/tiles_6580.2bpp: PNG_SIZE := 128
gfx/bank60/tiles_6640.2bpp: PNG_SIZE := 2656
gfx/bank60/tiles_6640.2bpp: PNG_PAD := -x 10
gfx/bank60/tiles_70a0.2bpp: PNG_SIZE := 1616
gfx/bank60/tiles_70a0.2bpp: PNG_PAD := -x 11
gfx/bank60/tiles_76f0.2bpp: PNG_SIZE := 912
gfx/bank60/tiles_76f0.2bpp: PNG_PAD := -x 7
gfx/bank61/tiles_4cc0.2bpp: PNG_SIZE := 672
gfx/bank61/tiles_4f63.2bpp: PNG_SIZE := 656
gfx/bank61/tiles_4f63.2bpp: PNG_PAD := -x 7
gfx/bank61/tiles_58b0.2bpp: PNG_SIZE := 656
gfx/bank61/tiles_58b0.2bpp: PNG_PAD := -x 7
gfx/bank61/tiles_65c0.2bpp: PNG_SIZE := 800
gfx/browser/frames_0_1/tiles_4000.2bpp: PNG_SIZE := 16
gfx/browser/frames_0_1/tiles_4010.2bpp: PNG_SIZE := 48
gfx/browser/frames_0_1/tiles_4040.2bpp: PNG_SIZE := 64
gfx/browser/frames_0_1/tiles_4080.2bpp: PNG_SIZE := 16
gfx/browser/frames_0_1/tiles_4090.2bpp: PNG_SIZE := 48
gfx/browser/frames_0_1/tiles_40c0.2bpp: PNG_SIZE := 16
gfx/browser/frames_0_1/tiles_40d0.2bpp: PNG_SIZE := 48
gfx/browser/frames_0_1/tiles_4100.2bpp: PNG_SIZE := 2560
gfx/browser/frames_0_1/tiles_4e50.2bpp: PNG_SIZE := 2560
gfx/browser/frames_2_3/tiles_5ba0.2bpp: PNG_SIZE := 2560
gfx/browser/frames_2_3/tiles_68f0.2bpp: PNG_SIZE := 2560
gfx/browser/menus/browser_menu2_tiles0.2bpp: PNG_SIZE := 1024
gfx/browser/menus/browser_menu2_tiles1.2bpp: PNG_SIZE := 256
gfx/browser/menus/browser_menu3_tiles0.2bpp: PNG_SIZE := 1024
gfx/browser/menus/browser_menu3_tiles1.2bpp: PNG_SIZE := 256
gfx/browser/page_list/page_list_tiles_5400.2bpp: PNG_SIZE := 464
gfx/browser/page_list/page_list_tiles_5400.2bpp: PNG_PAD := -x 3
gfx/browser/page_list/page_list_tiles_5800.2bpp: PNG_SIZE := 16
gfx/browser/page_list/tiles_55d0.2bpp: PNG_SIZE := 560
gfx/browser/page_list/tiles_55d0.2bpp: PNG_PAD := -x 13
gfx/browser/page_list/tiles_5810.2bpp: PNG_SIZE := 160
gfx/browser/page_list/tiles_5ef1.2bpp: PNG_SIZE := 992
gfx/browser/page_list/tiles_5ef1.2bpp: PNG_PAD := -x 2
gfx/browser/page_list/tiles_6301.2bpp: PNG_SIZE := 192
gfx/browser/page_list/tiles_63e0.2bpp: PNG_SIZE := 256
gfx/browser/start_choice/browser_start_tiles0.2bpp: PNG_SIZE := 1024
gfx/browser/start_choice/browser_start_tiles1.2bpp: PNG_SIZE := 1024
gfx/browser/start_choice/browser_start_tiles2.2bpp: PNG_SIZE := 1024
gfx/browser/start_choice/browser_start_tiles3.2bpp: PNG_SIZE := 1024
gfx/browser/start_choice/browser_start_tiles4.2bpp: PNG_SIZE := 1024
gfx/browser/start_choice/tiles_4530.2bpp: PNG_SIZE := 176
gfx/browser/start_choice/tiles_49e0.2bpp: PNG_SIZE := 1024
gfx/comm/comm_scene/tiles_5490.2bpp: PNG_SIZE := 1024
gfx/comm/comm_scene/tiles_5890.2bpp: PNG_SIZE := 1024
gfx/comm/comm_scene/tiles_5c90.2bpp: PNG_SIZE := 1024
gfx/comm/comm_scene/tiles_6090.2bpp: PNG_SIZE := 1024
gfx/comm/comm_scene/tiles_6490.2bpp: PNG_SIZE := 512
gfx/comm/comm_scene/tiles_6690.2bpp: PNG_SIZE := 512
gfx/comm/comm_scene/tiles_6890.2bpp: PNG_SIZE := 512
gfx/comm/comm_scene/tiles_6a90.2bpp: PNG_SIZE := 512
gfx/comm/connect_dialog_bank56/tiles_526a.2bpp: PNG_SIZE := 80
gfx/comm/connect_dialog_bank56/tiles_52c0.2bpp: PNG_SIZE := 1024
gfx/comm/connect_dialog_bank56/tiles_56c0.2bpp: PNG_SIZE := 1024
gfx/comm/connect_dialog_bank56/tiles_5ac0.2bpp: PNG_SIZE := 768
gfx/comm/connect_dialog_bank56/tiles_5dc0.2bpp: PNG_SIZE := 768
gfx/comm/connect_dialog_bank56/tiles_60c0.2bpp: PNG_SIZE := 1024
gfx/comm/connect_dialog_bank56/tiles_64c0.2bpp: PNG_SIZE := 1024
gfx/comm/connect_dialog_bank56/tiles_68c0.2bpp: PNG_SIZE := 512
gfx/comm/connect_dialog_bank56/tiles_6ac0.2bpp: PNG_SIZE := 1024
gfx/comm/connect_dialog_bank56/tiles_6ec0.2bpp: PNG_SIZE := 768
gfx/comm/connect_dialog_bank56/tiles_71c0.2bpp: PNG_SIZE := 1024
gfx/comm/connect_dialog_bank56/tiles_75c0.2bpp: PNG_SIZE := 512
gfx/comm/connect_dialog_screen/connect_dialog_blank_tile.2bpp: PNG_SIZE := 16
gfx/comm/connection_icon/conn_icon_tiles0.2bpp: PNG_SIZE := 1024
gfx/comm/connection_icon/conn_icon_tiles1.2bpp: PNG_SIZE := 512
gfx/comm/notice_dialog/tiles_5a20.2bpp: PNG_SIZE := 1024
gfx/comm/notice_dialog/tiles_5e20.2bpp: PNG_SIZE := 416
gfx/comm/notice_dialog/tiles_5fc0.2bpp: PNG_SIZE := 16
gfx/comm/notice_dialog/tiles_5fd0.2bpp: PNG_SIZE := 800
gfx/comm/notice_dialog/tiles_62f0.2bpp: PNG_SIZE := 1024
gfx/comm/notice_dialog/tiles_66f0.2bpp: PNG_SIZE := 416
gfx/comm/notice_dialog/tiles_6890.2bpp: PNG_SIZE := 16
gfx/comm/notice_dialog/tiles_68a0.2bpp: PNG_SIZE := 800
gfx/comm/time_summary/tiles_42a0.2bpp: PNG_SIZE := 1024
gfx/comm/time_summary/tiles_46a0.2bpp: PNG_SIZE := 1024
gfx/comm/time_summary/tiles_4db0.2bpp: PNG_SIZE := 1024
gfx/comm/time_summary/tiles_51b0.2bpp: PNG_SIZE := 1024
gfx/comm/time_summary/tiles_58c0.2bpp: PNG_SIZE := 1024
gfx/comm/time_summary/tiles_5cc0.2bpp: PNG_SIZE := 512
gfx/comm/time_summary/tiles_5ee1.2bpp: PNG_SIZE := 4592
gfx/comm/time_summary/tiles_5ee1.2bpp: PNG_PAD := -x 1
gfx/dialog/dialog_window/dialog_window_tiles.2bpp: PNG_SIZE := 1024
gfx/error/comm_error_screen/comm_err_gfx_bg9000.2bpp: PNG_SIZE := 1024
gfx/error/comm_error_screen/comm_err_gfx_bg9400.2bpp: PNG_SIZE := 384
gfx/error/comm_error_screen/comm_err_gfx_obj8000.2bpp: PNG_SIZE := 32
gfx/error/comm_error_screen/comm_err_gfx_obj8100.2bpp: PNG_SIZE := 32
gfx/error/no_adapter/no_adapter_gfx_8000.2bpp: PNG_SIZE := 64
gfx/error/no_adapter/no_adapter_gfx_8800.2bpp: PNG_SIZE := 960
gfx/error/no_adapter/no_adapter_gfx_8c00.2bpp: PNG_SIZE := 1024
gfx/error/no_adapter/no_adapter_gfx_9000.2bpp: PNG_SIZE := 1024
gfx/error/no_adapter/no_adapter_gfx_9400.2bpp: PNG_SIZE := 768
gfx/error/no_adapter/tiles_6480.2bpp: PNG_SIZE := 64
gfx/error/non_cgb_screen/non_cgb_tiles.2bpp: PNG_SIZE := 1968
gfx/error/non_cgb_screen/non_cgb_tiles.2bpp: PNG_PAD := -x 5
gfx/error/non_cgb_screen/tiles_4060.2bpp: PNG_SIZE := 1056
gfx/help/help_screens_a/tiles_4e90.2bpp: PNG_SIZE := 1024
gfx/help/help_screens_a/tiles_5290.2bpp: PNG_SIZE := 1024
gfx/help/help_screens_a/tiles_5690.2bpp: PNG_SIZE := 1024
gfx/help/help_screens_a/tiles_5a90.2bpp: PNG_SIZE := 32
gfx/help/help_screens_a/tiles_5ab0.2bpp: PNG_SIZE := 1024
gfx/help/help_screens_a/tiles_5eb0.2bpp: PNG_SIZE := 1024
gfx/help/help_screens_b/tiles_69f0.2bpp: PNG_SIZE := 32
gfx/help/help_screens_b/tiles_6a10.2bpp: PNG_SIZE := 16
gfx/help/help_screens_b/tiles_6a20.2bpp: PNG_SIZE := 1024
gfx/help/help_screens_b/tiles_6e20.2bpp: PNG_SIZE := 1024
gfx/help/mobile_dictionary/mobile_dict_tiles0.2bpp: PNG_SIZE := 512
gfx/help/mobile_dictionary/mobile_dict_tiles1.2bpp: PNG_SIZE := 1024
gfx/help/mobile_dictionary/mobile_dict_tiles2.2bpp: PNG_SIZE := 768
gfx/keyboard/panels_bank5d/tiles_4000.2bpp: PNG_SIZE := 1024
gfx/keyboard/panels_bank5d/tiles_4400.2bpp: PNG_SIZE := 1024
gfx/keyboard/panels_bank5f/tiles_4000.2bpp: PNG_SIZE := 1024
gfx/keyboard/panels_bank5f/tiles_4400.2bpp: PNG_SIZE := 1024
gfx/keyboard/panels_bank5f/tiles_4800.2bpp: PNG_SIZE := 16
gfx/keyboard/panels_bank5f/tiles_49d0.2bpp: PNG_SIZE := 768
gfx/keyboard/panels_bank5f/tiles_5900.2bpp: PNG_SIZE := 1024
gfx/keyboard/panels_bank5f/tiles_5d00.2bpp: PNG_SIZE := 1024
gfx/keyboard/panels_bank5f/tiles_6100.2bpp: PNG_SIZE := 256
gfx/keyboard/tiles_bank62/tiles_4000.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank62/tiles_4400.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank62/tiles_4800.2bpp: PNG_SIZE := 576
gfx/keyboard/tiles_bank62/tiles_4a40.2bpp: PNG_SIZE := 192
gfx/keyboard/tiles_bank62/tiles_4b00.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank62/tiles_4f00.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank62/tiles_5300.2bpp: PNG_SIZE := 576
gfx/keyboard/tiles_bank62/tiles_5540.2bpp: PNG_SIZE := 192
gfx/keyboard/tiles_bank62/tiles_5600.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank62/tiles_5a00.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank62/tiles_5e00.2bpp: PNG_SIZE := 576
gfx/keyboard/tiles_bank62/tiles_6040.2bpp: PNG_SIZE := 192
gfx/keyboard/tiles_bank62/tiles_6100.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank62/tiles_6500.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank62/tiles_6900.2bpp: PNG_SIZE := 576
gfx/keyboard/tiles_bank62/tiles_6b40.2bpp: PNG_SIZE := 192
gfx/keyboard/tiles_bank66/tiles_4000.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank66/tiles_4400.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank66/tiles_4800.2bpp: PNG_SIZE := 576
gfx/keyboard/tiles_bank66/tiles_4a40.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank66/tiles_4e40.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank66/tiles_5240.2bpp: PNG_SIZE := 576
gfx/keyboard/tiles_bank66/tiles_5480.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank66/tiles_5880.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank66/tiles_5c80.2bpp: PNG_SIZE := 576
gfx/keyboard/tiles_bank66/tiles_5ec0.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank66/tiles_62c0.2bpp: PNG_SIZE := 1024
gfx/keyboard/tiles_bank66/tiles_66c0.2bpp: PNG_SIZE := 576
gfx/keyboard/tiles_bank66/tiles_6900.2bpp: PNG_SIZE := 400
gfx/keyboard/tiles_bank66/tiles_6900.2bpp: PNG_PAD := -x 7
gfx/keyboard/tiles_bank66/tiles_6a90.2bpp: PNG_SIZE := 1792
gfx/mail/address_editor/mail_addr_obj_tiles.2bpp: PNG_SIZE := 192
gfx/mail/address_editor/mail_addr_tiles.2bpp: PNG_SIZE := 1024
gfx/mail/address_editor/mail_addr_tiles2.2bpp: PNG_SIZE := 176
gfx/mail/address_editor/mail_addr_tiles3.2bpp: PNG_SIZE := 688
gfx/mail/address_editor/mail_addr_tiles3.2bpp: PNG_PAD := -x 5
gfx/mail/address_editor/tiles_7940.2bpp: PNG_SIZE := 528
gfx/mail/body_editor/mail_body_obj_tiles.2bpp: PNG_SIZE := 672
gfx/mail/body_editor/mail_body_tiles.2bpp: PNG_SIZE := 960
gfx/mail/body_editor/mail_body_tiles2.2bpp: PNG_SIZE := 256
gfx/mail/body_view/mail_body_tiles_42c0.2bpp: PNG_SIZE := 528
gfx/mail/body_view/mail_body_tiles_44d0.2bpp: PNG_SIZE := 128
gfx/mail/comm_result/mail_result_tiles_6bf0.2bpp: PNG_SIZE := 1024
gfx/mail/comm_result/mail_result_tiles_6ff0.2bpp: PNG_SIZE := 1024
gfx/mail/comm_result/mail_result_tiles_73f0.2bpp: PNG_SIZE := 160
gfx/mail/comm_result/mail_result_tiles_7490.2bpp: PNG_SIZE := 768
gfx/mail/connect_screen/mail_connect_tiles_5060.2bpp: PNG_SIZE := 1024
gfx/mail/connect_screen/mail_connect_tiles_5460.2bpp: PNG_SIZE := 1024
gfx/mail/connect_screen/mail_connect_tiles_5860.2bpp: PNG_SIZE := 1024
gfx/mail/connect_screen/mail_connect_tiles_5c60.2bpp: PNG_SIZE := 512
gfx/mail/connect_screen/mail_connect_tiles_5e60.2bpp: PNG_SIZE := 1024
gfx/mail/connect_screen/mail_connect_tiles_6260.2bpp: PNG_SIZE := 1024
gfx/mail/connect_screen/mail_connect_tiles_6660.2bpp: PNG_SIZE := 512
gfx/mail/connect_screen/mail_connect_tiles_6860.2bpp: PNG_SIZE := 1024
gfx/mail/connect_screen/mail_connect_tiles_6c60.2bpp: PNG_SIZE := 1024
gfx/mail/connect_screen_bank29/tiles_5400.2bpp: PNG_SIZE := 1024
gfx/mail/draft_menu/mail_draft_menu_tiles8000.2bpp: PNG_SIZE := 816
gfx/mail/draft_menu/mail_draft_menu_tiles8000.2bpp: PNG_PAD := -x 13
gfx/mail/draft_menu/mail_draft_menu_tiles9300.2bpp: PNG_SIZE := 720
gfx/mail/mail_title_entry/mail_title_tiles8000.2bpp: PNG_SIZE := 16
gfx/mail/mail_title_entry/mail_title_tiles8800.2bpp: PNG_SIZE := 592
gfx/mail/mail_title_entry/mail_title_tiles8800.2bpp: PNG_PAD := -x 11
gfx/mail/mail_title_entry/mail_title_tiles9300.2bpp: PNG_SIZE := 1024
gfx/mail/mail_viewer/mail_view_tiles8000.2bpp: PNG_SIZE := 384
gfx/mail/mail_viewer/mail_view_tiles9000.2bpp: PNG_SIZE := 1024
gfx/mail/mail_viewer/mail_view_tiles9400.2bpp: PNG_SIZE := 512
gfx/mail/received_mail_grid/mail_grid_tiles8000.2bpp: PNG_SIZE := 240
gfx/mail/received_mail_grid/mail_grid_tiles9000.2bpp: PNG_SIZE := 1024
gfx/mail/received_mail_grid/mail_grid_tiles9400.2bpp: PNG_SIZE := 560
gfx/mail/received_mail_grid/mail_grid_tiles9400.2bpp: PNG_PAD := -x 13
gfx/mail/result_screens/mail_server_status_tiles_5060.2bpp: PNG_SIZE := 48
gfx/mail/server_status/mail_server_status_tiles_6f30.2bpp: PNG_SIZE := 1024
gfx/mail/server_status/mail_server_status_tiles_7330.2bpp: PNG_SIZE := 1024
gfx/mail/server_status_bank26/mail_server_status_tiles_7420.2bpp: PNG_SIZE := 1024
gfx/mail/server_status_bank26/tiles_7840.2bpp: PNG_SIZE := 624
gfx/mail/session_scenery/mail_session_tiles_59e0.2bpp: PNG_SIZE := 1024
gfx/mail/session_scenery/mail_session_tiles_5de0.2bpp: PNG_SIZE := 1024
gfx/mail/session_scenery/mail_session_tiles_61e0.2bpp: PNG_SIZE := 256
gfx/mail/session_scenery/mail_session_tiles_62e0.2bpp: PNG_SIZE := 1024
gfx/mail/session_scenery/mail_session_tiles_66e0.2bpp: PNG_SIZE := 16
gfx/mail/session_scenery/mail_session_tiles_67e0.2bpp: PNG_SIZE := 1024
gfx/mail/session_scenery/mail_session_tiles_6be0.2bpp: PNG_SIZE := 1024
gfx/mail/session_scenery/mail_session_tiles_6fe0.2bpp: PNG_SIZE := 1024
gfx/mail/session_scenery/tiles_66f0.2bpp: PNG_SIZE := 240
gfx/mail_menu/mail_menu/mail_menu_tiles0.2bpp: PNG_SIZE := 400
gfx/mail_menu/mail_menu/mail_menu_tiles0.2bpp: PNG_PAD := -x 7
gfx/mail_menu/mail_menu/mail_menu_tiles1.2bpp: PNG_SIZE := 1024
gfx/mail_menu/mail_menu/mail_menu_tiles2.2bpp: PNG_SIZE := 1024
gfx/mail_menu/mail_menu/mail_menu_tiles3.2bpp: PNG_SIZE := 1024
gfx/mail_menu/mail_menu/mail_menu_tiles4.2bpp: PNG_SIZE := 896
gfx/mail_menu/mail_menu/mail_menu_tiles5.2bpp: PNG_SIZE := 1024
gfx/mail_server/delete_all_screen/mail_server_delete_all_tiles_54b0.2bpp: PNG_SIZE := 1024
gfx/mail_server/delete_all_screen/mail_server_delete_all_tiles_58b0.2bpp: PNG_SIZE := 672
gfx/mail_server/delete_all_screen/mail_server_delete_all_tiles_5b50.2bpp: PNG_SIZE := 128
gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_5f20.2bpp: PNG_SIZE := 560
gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_5f20.2bpp: PNG_PAD := -x 13
gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_6150.2bpp: PNG_SIZE := 1024
gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_6550.2bpp: PNG_SIZE := 656
gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_6550.2bpp: PNG_PAD := -x 7
gfx/mail_server/delete_method_screen/mail_server_delete_method_tiles_67e0.2bpp: PNG_SIZE := 128
gfx/mail_server/delete_progress/mail_srv_del_progress_tiles0.2bpp: PNG_SIZE := 1024
gfx/mail_server/delete_progress/mail_srv_del_progress_tiles1.2bpp: PNG_SIZE := 256
gfx/mail_server/delete_progress/mail_srv_del_progress_tiles2.2bpp: PNG_SIZE := 352
gfx/mail_server/tidy_screen/mail_server_mgr_tiles0.2bpp: PNG_SIZE := 1024
gfx/mail_server/tidy_screen/mail_server_mgr_tiles1.2bpp: PNG_SIZE := 16
gfx/mail_server/tidy_screen/mail_server_mgr_tiles2.2bpp: PNG_SIZE := 288
gfx/mail_server/tidy_screen/mail_server_mgr_tiles3.2bpp: PNG_SIZE := 1024
gfx/mail_server/tidy_screen/mail_server_mgr_tiles4.2bpp: PNG_SIZE := 352
gfx/mail_server/tidy_screen/mail_server_mgr_tiles5.2bpp: PNG_SIZE := 1024
gfx/mail_server/tidy_screen/tiles_5af0.2bpp: PNG_SIZE := 1008
gfx/mailbox/mailbox/mailbox_tiles_5a10.2bpp: PNG_SIZE := 1024
gfx/mailbox/mailbox/mailbox_tiles_5e10.2bpp: PNG_SIZE := 256
gfx/mailbox/mailbox/mailbox_tiles_5f10.2bpp: PNG_SIZE := 1024
gfx/mailbox/mailbox/mailbox_tiles_6310.2bpp: PNG_SIZE := 256
gfx/mailbox/mailbox/mailbox_tiles_69f0.2bpp: PNG_SIZE := 208
gfx/mailbox/mailbox/mailbox_tiles_6cf0.2bpp: PNG_SIZE := 384
gfx/mailbox/mailbox/tiles_6bd1.2bpp: PNG_SIZE := 272
gfx/mailbox/mailbox/tiles_6bd1.2bpp: PNG_PAD := -x 15
gfx/profile/profile_editor/profile_tiles8800.2bpp: PNG_SIZE := 832
gfx/profile/profile_editor/profile_tiles9300.2bpp: PNG_SIZE := 1024
gfx/profile/profile_editor/profile_tiles9700.2bpp: PNG_SIZE := 256
gfx/registration/screens_bank58/tiles_4000.2bpp: PNG_SIZE := 464
gfx/registration/screens_bank58/tiles_4000.2bpp: PNG_PAD := -x 3
gfx/registration/screens_bank58/tiles_41d0.2bpp: PNG_SIZE := 640
gfx/registration/screens_bank58/tiles_4450.2bpp: PNG_SIZE := 640
gfx/registration/screens_bank58/tiles_46d0.2bpp: PNG_SIZE := 1920
gfx/registration/screens_bank58/tiles_4e50.2bpp: PNG_SIZE := 1280
gfx/registration/screens_bank58/tiles_5350.2bpp: PNG_SIZE := 1280
gfx/registration/screens_bank58/tiles_5850.2bpp: PNG_SIZE := 640
gfx/registration/screens_bank58/tiles_5ad0.2bpp: PNG_SIZE := 4720
gfx/registration/screens_bank58/tiles_5ad0.2bpp: PNG_PAD := -x 9
gfx/registration/screens_bank58/tiles_6d40.2bpp: PNG_SIZE := 1824
gfx/registration/screens_bank58/tiles_6d40.2bpp: PNG_PAD := -x 14
gfx/registration/screens_bank58/tiles_7460.2bpp: PNG_SIZE := 496
gfx/registration/screens_bank58/tiles_7460.2bpp: PNG_PAD := -x 1
gfx/registration/screens_bank58/tiles_7650.2bpp: PNG_SIZE := 320
gfx/registration/screens_bank58/tiles_7790.2bpp: PNG_SIZE := 960
gfx/settings/screens_bank4a/tiles_5f80.2bpp: PNG_SIZE := 256
gfx/settings/screens_bank4a/tiles_6080.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4a/tiles_6480.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4a/tiles_68d0.2bpp: PNG_SIZE := 80
gfx/settings/screens_bank4a/tiles_6920.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4a/tiles_6d20.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4b/tiles_5b90.2bpp: PNG_SIZE := 2560
gfx/settings/screens_bank4b/tiles_6a90.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4b/tiles_6e90.2bpp: PNG_SIZE := 544
gfx/settings/screens_bank4b/tiles_6e90.2bpp: PNG_PAD := -x 14
gfx/settings/screens_bank4b/tiles_70b0.2bpp: PNG_SIZE := 992
gfx/settings/screens_bank4b/tiles_70b0.2bpp: PNG_PAD := -x 2
gfx/settings/screens_bank4b/tiles_76d0.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4b/tiles_7ad0.2bpp: PNG_SIZE := 768
gfx/settings/screens_bank4d/tiles_4000.2bpp: PNG_SIZE := 512
gfx/settings/screens_bank4d/tiles_4200.2bpp: PNG_SIZE := 784
gfx/settings/screens_bank4d/tiles_4200.2bpp: PNG_PAD := -x 15
gfx/settings/screens_bank4d/tiles_4510.2bpp: PNG_SIZE := 256
gfx/settings/screens_bank4d/tiles_4610.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4d/tiles_4a10.2bpp: PNG_SIZE := 768
gfx/settings/screens_bank4d/tiles_4d10.2bpp: PNG_SIZE := 768
gfx/settings/screens_bank4d/tiles_5010.2bpp: PNG_SIZE := 256
gfx/settings/screens_bank4d/tiles_5110.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4d/tiles_5510.2bpp: PNG_SIZE := 768
gfx/settings/screens_bank4d/tiles_5d50.2bpp: PNG_SIZE := 32
gfx/settings/screens_bank4d/tiles_5d70.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4d/tiles_6170.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4d/tiles_6570.2bpp: PNG_SIZE := 768
gfx/settings/screens_bank4d/tiles_6870.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4d/tiles_6c70.2bpp: PNG_SIZE := 256
gfx/settings/screens_bank4d/tiles_6d70.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank4d/tiles_7170.2bpp: PNG_SIZE := 768
gfx/settings/screens_bank4d/tiles_7470.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank5d/tiles_7360.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank5d/tiles_7760.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank5e/tiles_4000.2bpp: PNG_SIZE := 1024
gfx/settings/screens_bank5e/tiles_4400.2bpp: PNG_SIZE := 1024
gfx/title/logo/title_logo_tiles0.2bpp: PNG_SIZE := 1024
gfx/title/logo/title_logo_tiles1.2bpp: PNG_SIZE := 1024
gfx/title/title_screen/title_tiles0.2bpp: PNG_SIZE := 1024
gfx/title/title_screen/title_tiles1.2bpp: PNG_SIZE := 1024
gfx/title/title_screen/title_tiles2.2bpp: PNG_SIZE := 512
gfx/title/title_screen/title_tiles3.2bpp: PNG_SIZE := 512
gfx/title/title_screen/title_tiles4.2bpp: PNG_SIZE := 1024
gfx/title/title_screen/title_tiles5.2bpp: PNG_SIZE := 1024
gfx/title/title_screen/title_tiles6.2bpp: PNG_SIZE := 1024
gfx/top_menu/top_menu/tiles_49a0.2bpp: PNG_SIZE := 1024
gfx/top_menu/top_menu/tiles_4da0.2bpp: PNG_SIZE := 1024
gfx/top_menu/top_menu/tiles_51a0.2bpp: PNG_SIZE := 1024
gfx/top_menu/top_menu/tiles_55a0.2bpp: PNG_SIZE := 1024
gfx/top_menu/top_menu/tiles_59a0.2bpp: PNG_SIZE := 512
gfx/top_menu/top_menu/tiles_5ba0.2bpp: PNG_SIZE := 1024
gfx/top_menu/top_menu/tiles_5fa0.2bpp: PNG_SIZE := 768
gfx/unreferenced/page_list_prototype/tiles_62b0.2bpp: PNG_SIZE := 1024
gfx/unreferenced/page_list_prototype/tiles_66b0.2bpp: PNG_SIZE := 288
gfx/unreferenced/page_list_prototype/tiles_6ae0.2bpp: PNG_SIZE := 656
gfx/unreferenced/page_list_prototype/tiles_6ae0.2bpp: PNG_PAD := -x 7
gfx/unreferenced/page_list_prototype_objects/tiles_7830.2bpp: PNG_SIZE := 720

%.2bpp: %.png
	@echo "rgbgfx $<"
	$(Q)$(RGBGFX) -c embedded $(PNG_PAD) -o $@.tmp $< || { rm -f $@.tmp; if [ -n "$(PYTHON_OK)" ]; then $(PYTHON) tools/png_check.py --file $<; fi; echo "error: $< cannot be converted to $@ (make png-check lists every problem)"; exit 1; }
	$(Q)$(png_finish)
endif

ifneq ($(PYTHON_OK),)
PNG_FONT_OUTS := \
	data/fonts/ascii_6x12.bin \
	data/fonts/font_8x16_4adb.1bpp \
	data/fonts/font_8x16_4b7b.1bpp \
	data/fonts/font_8x16_4d1b.1bpp \
	data/fonts/font_8x16_4ebb.1bpp \
	data/fonts/font_8x16_53eb.1bpp \
	data/fonts/font_8x16_593b.1bpp \
	data/fonts/font_8x16_59fb.1bpp \
	data/fonts/font_8x16_5a2b.1bpp \
	data/fonts/font_8x16_5a3b.1bpp \
	data/fonts/font_8x16_5a4b.1bpp \
	data/fonts/font_8x16_5a6b.1bpp \
	data/fonts/font_8x16_5a8b.1bpp \
	data/fonts/font_8x16_5a9b.1bpp \
	data/fonts/font_8x16_5abb.1bpp \
	data/fonts/font_8x16_5afb.1bpp \
	data/fonts/font_8x16_5b7b.1bpp \
	data/fonts/font_8x16_5b8b.1bpp \
	data/fonts/font_8x16_5bab.1bpp \
	data/fonts/font_8x16_5bcb.1bpp \
	data/fonts/font_8x16_5beb.1bpp \
	data/fonts/font_8x16_5c0b.1bpp \
	data/fonts/font_8x16_5c5b.1bpp \
	data/fonts/font_8x16_5c9b.1bpp \
	data/fonts/font_8x16_5cfb.1bpp \
	data/fonts/font_8x16_5d5b.1bpp \
	data/fonts/font_8x16_5d6b.1bpp \
	data/fonts/font_8x16_5d7b.1bpp \
	data/fonts/jis12x12_rows_01_08_13.bin \
	data/fonts/jis12x12_rows_16_24.bin \
	data/fonts/jis12x12_rows_25_33_4000.bin \
	data/fonts/jis12x12_rows_25_33_57cd.bin \
	data/fonts/jis12x12_rows_34_42.bin \
	data/fonts/jis12x12_rows_43_51.bin \
	data/fonts/jis12x12_rows_52_60.bin \
	data/fonts/jis12x12_rows_61_69.bin \
	data/fonts/jis12x12_rows_70_78.bin \
	data/fonts/jis12x12_rows_79_84.bin \


data/fonts/ascii_6x12.bin: PNG_SIZE := 1152
data/fonts/ascii_6x12.bin: data/fonts/ascii_6x12.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font6x12 --cells 96 --start 67a8 --size 1152 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_4adb.1bpp: PNG_SIZE := 160
data/fonts/font_8x16_4adb.1bpp: data/fonts/font_8x16_4adb.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 10 --start 4adb --size 160 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_4b7b.1bpp: PNG_SIZE := 416
data/fonts/font_8x16_4b7b.1bpp: data/fonts/font_8x16_4b7b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 26 --start 4b7b --size 416 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_4d1b.1bpp: PNG_SIZE := 416
data/fonts/font_8x16_4d1b.1bpp: data/fonts/font_8x16_4d1b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 26 --start 4d1b --size 416 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_4ebb.1bpp: PNG_SIZE := 1328
data/fonts/font_8x16_4ebb.1bpp: data/fonts/font_8x16_4ebb.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 83 --start 4ebb --size 1328 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_53eb.1bpp: PNG_SIZE := 1360
data/fonts/font_8x16_53eb.1bpp: data/fonts/font_8x16_53eb.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 85 --start 53eb --size 1360 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_593b.1bpp: PNG_SIZE := 192
data/fonts/font_8x16_593b.1bpp: data/fonts/font_8x16_593b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 12 --start 593b --size 192 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_59fb.1bpp: PNG_SIZE := 48
data/fonts/font_8x16_59fb.1bpp: data/fonts/font_8x16_59fb.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 3 --start 59fb --size 48 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5a2b.1bpp: PNG_SIZE := 16
data/fonts/font_8x16_5a2b.1bpp: data/fonts/font_8x16_5a2b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 1 --start 5a2b --size 16 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5a3b.1bpp: PNG_SIZE := 16
data/fonts/font_8x16_5a3b.1bpp: data/fonts/font_8x16_5a3b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 1 --start 5a3b --size 16 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5a4b.1bpp: PNG_SIZE := 32
data/fonts/font_8x16_5a4b.1bpp: data/fonts/font_8x16_5a4b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 2 --start 5a4b --size 32 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5a6b.1bpp: PNG_SIZE := 32
data/fonts/font_8x16_5a6b.1bpp: data/fonts/font_8x16_5a6b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 2 --start 5a6b --size 32 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5a8b.1bpp: PNG_SIZE := 16
data/fonts/font_8x16_5a8b.1bpp: data/fonts/font_8x16_5a8b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 1 --start 5a8b --size 16 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5a9b.1bpp: PNG_SIZE := 32
data/fonts/font_8x16_5a9b.1bpp: data/fonts/font_8x16_5a9b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 2 --start 5a9b --size 32 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5abb.1bpp: PNG_SIZE := 64
data/fonts/font_8x16_5abb.1bpp: data/fonts/font_8x16_5abb.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 4 --start 5abb --size 64 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5afb.1bpp: PNG_SIZE := 128
data/fonts/font_8x16_5afb.1bpp: data/fonts/font_8x16_5afb.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 8 --start 5afb --size 128 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5b7b.1bpp: PNG_SIZE := 16
data/fonts/font_8x16_5b7b.1bpp: data/fonts/font_8x16_5b7b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 1 --start 5b7b --size 16 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5b8b.1bpp: PNG_SIZE := 32
data/fonts/font_8x16_5b8b.1bpp: data/fonts/font_8x16_5b8b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 2 --start 5b8b --size 32 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5bab.1bpp: PNG_SIZE := 32
data/fonts/font_8x16_5bab.1bpp: data/fonts/font_8x16_5bab.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 2 --start 5bab --size 32 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5bcb.1bpp: PNG_SIZE := 32
data/fonts/font_8x16_5bcb.1bpp: data/fonts/font_8x16_5bcb.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 2 --start 5bcb --size 32 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5beb.1bpp: PNG_SIZE := 32
data/fonts/font_8x16_5beb.1bpp: data/fonts/font_8x16_5beb.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 2 --start 5beb --size 32 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5c0b.1bpp: PNG_SIZE := 80
data/fonts/font_8x16_5c0b.1bpp: data/fonts/font_8x16_5c0b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 5 --start 5c0b --size 80 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5c5b.1bpp: PNG_SIZE := 64
data/fonts/font_8x16_5c5b.1bpp: data/fonts/font_8x16_5c5b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 4 --start 5c5b --size 64 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5c9b.1bpp: PNG_SIZE := 96
data/fonts/font_8x16_5c9b.1bpp: data/fonts/font_8x16_5c9b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 6 --start 5c9b --size 96 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5cfb.1bpp: PNG_SIZE := 96
data/fonts/font_8x16_5cfb.1bpp: data/fonts/font_8x16_5cfb.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 6 --start 5cfb --size 96 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5d5b.1bpp: PNG_SIZE := 16
data/fonts/font_8x16_5d5b.1bpp: data/fonts/font_8x16_5d5b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 1 --start 5d5b --size 16 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5d6b.1bpp: PNG_SIZE := 16
data/fonts/font_8x16_5d6b.1bpp: data/fonts/font_8x16_5d6b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 1 --start 5d6b --size 16 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/font_8x16_5d7b.1bpp: PNG_SIZE := 80
data/fonts/font_8x16_5d7b.1bpp: data/fonts/font_8x16_5d7b.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font8x16 --cells 5 --start 5d7b --size 80 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_01_08_13.bin: PNG_SIZE := 15228
data/fonts/jis12x12_rows_01_08_13.bin: data/fonts/jis12x12_rows_01_08_13.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 846 --start 4000 --size 15228 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_16_24.bin: PNG_SIZE := 15228
data/fonts/jis12x12_rows_16_24.bin: data/fonts/jis12x12_rows_16_24.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 846 --start 4000 --size 15228 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_25_33_4000.bin: PNG_SIZE := 6083
data/fonts/jis12x12_rows_25_33_4000.bin: data/fonts/jis12x12_rows_25_33.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 846 --start 4000 --size 6083 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_25_33_57cd.bin: PNG_SIZE := 9135
data/fonts/jis12x12_rows_25_33_57cd.bin: data/fonts/jis12x12_rows_25_33.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 846 --start 57cd --size 9135 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_34_42.bin: PNG_SIZE := 15228
data/fonts/jis12x12_rows_34_42.bin: data/fonts/jis12x12_rows_34_42.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 846 --start 4000 --size 15228 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_43_51.bin: PNG_SIZE := 15228
data/fonts/jis12x12_rows_43_51.bin: data/fonts/jis12x12_rows_43_51.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 846 --start 4000 --size 15228 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_52_60.bin: PNG_SIZE := 15228
data/fonts/jis12x12_rows_52_60.bin: data/fonts/jis12x12_rows_52_60.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 846 --start 4000 --size 15228 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_61_69.bin: PNG_SIZE := 15228
data/fonts/jis12x12_rows_61_69.bin: data/fonts/jis12x12_rows_61_69.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 846 --start 4000 --size 15228 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_70_78.bin: PNG_SIZE := 15228
data/fonts/jis12x12_rows_70_78.bin: data/fonts/jis12x12_rows_70_78.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 846 --start 4000 --size 15228 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

data/fonts/jis12x12_rows_79_84.bin: PNG_SIZE := 10152
data/fonts/jis12x12_rows_79_84.bin: data/fonts/jis12x12_rows_79_84.png
	@echo "font_png $<"
	$(Q)$(PYTHON) tools/font_png.py import --type font12 --cells 564 --start 4000 --size 10152 $< $@.tmp || { rm -f $@.tmp; exit 1; }
	$(Q)$(png_finish)

endif

PNG_OUTS := $(PNG_TILE_OUTS) $(PNG_FONT_OUTS)
