#!/usr/bin/env python3
"""Production source generator: ROM bytes + config/ tables -> RGBDS sources.

    gen_asm.py [regen]  [--config DIR] [--out DIR] [--rom FILE] [--fast] [--strict] [-q]
    gen_asm.py verify   [--config DIR] [--rom FILE] [--keep DIR] [--strict]
    gen_asm.py check    [--config DIR] [--rom FILE] [--strict]

regen   generate src/bankNN.asm + src/ram.inc from the ROM and config/, run the
        internal structural round-trip check, then (unless --fast) assemble and
        link the result in a temp dir and compare it with the ROM; the files in
        --out are written only if every check passes.
verify  generate into a temp dir (never touches --out), assemble + link, compare
        with the ROM and print any differences mapped to regions.
check   generate in memory and run the structural checks only (no files, no rgbasm).

The generated code is byte-exact by construction: every emitted line is
re-parsed / cross-checked against the ROM bytes and every name substituted for
a number is checked to have exactly that numeric value.  See docs/FORMATS.md.
"""
import argparse
import bisect
import concurrent.futures
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import defaultdict
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import sm83                                   # noqa: E402
from lib import mtcfg                         # noqa: E402
from lib.mtcfg import GenError, Diag, Region  # noqa: E402

ROOT = mtcfg.ROOT
BANK_SIZE = mtcfg.BANK_SIZE
GENERATED_HEADER = '; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).'
CALL_FLOWS = ('call', 'callcc', 'rst')
TERMINATORS = ('jp', 'jr', 'ret', 'jphl')


@dataclass
class Label:
    name: str
    origin: str          # 'symbol' | 'region' | 'generic'
    loc: str = ''


def hexb(v: int) -> str:
    return '$%02X' % v


def hexw(v: int) -> str:
    return '$%04X' % v


class BankOut:
    """Collects the lines of one bank and checks that the emitted bytes tile the bank exactly."""

    def __init__(self, model: 'Model', bank: int):
        self.model = model
        self.bank = bank
        self.lines: List[str] = []
        self.pos = 0

    def line(self, text: str = ''):
        if not text and (not self.lines or not self.lines[-1]):
            return                      # never two blank lines in a row
        self.lines.append(text)

    def emit(self, text: str, claim: bytes):
        m = self.model
        absoff = self.bank * BANK_SIZE + self.pos
        if m.rom[absoff:absoff + len(claim)] != claim:
            raise GenError('internal: line %r does not match ROM bytes at %02X:%04X' % (
                text, self.bank, self.pos + (0 if self.bank == 0 else 0x4000)))
        m.verify_line(text, claim, absoff)
        self.lines.append(text)
        self.pos += len(claim)


class Model:
    """Everything the emitter needs: decoded code, label tables, cross references."""

    def __init__(self, rom: bytes, cfg: mtcfg.Config, hw: mtcfg.Hardware, incbin: str = 'baserom.gbc'):
        if len(rom) < BANK_SIZE or len(rom) % BANK_SIZE:
            raise GenError('ROM size %d is not a positive multiple of 16 KiB' % len(rom))
        self.rom = rom
        self.cfg = cfg
        self.hw = hw
        self.incbin = incbin
        self.nbanks = len(rom) // BANK_SIZE
        self.regions = cfg.regions
        self.diag = Diag()
        self.insns: Dict[Tuple[int, int], List[Tuple[int, sm83.Insn]]] = {}
        self.bound: Dict[int, set] = {b: set() for b in range(self.nbanks)}
        self.labels: Dict[int, Dict[int, List[Label]]] = {b: {} for b in range(self.nbanks)}
        self.name_loc: Dict[str, tuple] = {}     # name -> (bank, addr) | ('const',)
        self.name_val: Dict[str, int] = {}       # label name -> runtime address
        self.consts: List[mtcfg.Symbol] = []
        self.ramcodes: List[Region] = []
        self.union: Dict[Tuple[int, int], str] = {}
        self.want: Dict[Tuple[int, int], set] = defaultdict(set)
        self.xref: Dict[Tuple[int, int, str], tuple] = {}
        self.label_addrs: Dict[int, List[int]] = {}
        self.ram_sorted: List[mtcfg.RamVar] = []
        self.ram_exact: Dict[int, mtcfg.RamVar] = {}
        self.stats: Dict[str, int] = defaultdict(int)
        self._build()

    # ------------------------------------------------------------------ build
    def _build(self):
        self._check_zero_regions()
        self._decode()
        self._index_ramcode()
        self._index_ram()
        self._collect_labels()
        self.diag.raise_if_errors()
        self._resolve_xrefs()
        self._collect_refs()
        self.diag.raise_if_errors()
        self._finalize_labels()
        self._check_xref_targets()
        self.diag.raise_if_errors()
        for b in range(self.nbanks):
            self.label_addrs[b] = sorted(self.labels[b])

    def region_at(self, bank: int, addr: int) -> Optional[Region]:
        return mtcfg.region_at(self.regions[bank], addr)

    def run_addr(self, bank: int, addr: int) -> int:
        r = self.region_at(bank, addr)
        if r is not None and r.kind == 'ramcode':
            return r.runaddr + (addr - r.start)
        return addr

    def bytes_of(self, r: Region) -> bytes:
        return self.rom[r.off:r.off + r.size]

    @staticmethod
    def cite(bank: int, addr: int) -> str:
        return '%02X:%04X' % (bank, addr)

    def _check_zero_regions(self):
        for b in range(self.nbanks):
            for r in self.regions[b]:
                if r.kind == 'zero' and any(self.bytes_of(r)):
                    first = next(i for i, v in enumerate(self.bytes_of(r)) if v)
                    self.diag.error(r.loc, "zero region %02X:%04X-%04X contains a non-zero byte at %02X:%04X"
                                    % (b, r.start, r.end, b, r.start + first))
        self.diag.raise_if_errors()

    def _decode(self):
        for b in range(self.nbanks):
            for r in self.regions[b]:
                if r.kind not in ('code', 'ramcode'):
                    continue
                chunk = self.bytes_of(r)
                addr0 = r.runaddr if r.kind == 'ramcode' else r.start
                out = []
                i = 0
                n = len(chunk)
                bound = self.bound[b]
                while i < n:
                    ins = sm83.decode(chunk, i, (addr0 + i) & 0xFFFF)
                    if ins.flow == 'bad' and ins.raw[0] not in sm83.ILLEGAL:
                        full = sm83.decode(self.rom[r.off + i:r.off + i + 3] + b'\0\0\0', 0, 0)
                        self.diag.error(r.loc, '%s region %02X:%04X-%04X: instruction at %02X:%04X (opcode $%02X, %d bytes) '
                                        'crosses the region end' % (r.kind, b, r.start, r.end, b, r.start + i,
                                                                    ins.raw[0], full.length))
                        break
                    out.append((r.start + i, ins))
                    bound.add(r.start + i)
                    i += ins.length
                self.insns[(b, r.idx)] = out
        self.diag.raise_if_errors()

    def _index_ramcode(self):
        self.ramcodes = [r for b in range(self.nbanks) for r in self.regions[b] if r.kind == 'ramcode']
        marked = set()
        for i, a in enumerate(self.ramcodes):
            for c in self.ramcodes[i + 1:]:
                if a.runbank != c.runbank or not (a.runaddr < c.run_end and c.runaddr < a.run_end):
                    continue
                if a.runaddr != c.runaddr:
                    self.diag.error(c.loc, 'ramcode runtime range $%04X-$%04X partially overlaps $%04X-$%04X of %s: '
                                    'overlays must start at the same runaddr' % (
                                        c.runaddr, c.run_end, a.runaddr, a.run_end, a.loc))
                    continue
                marked.add((a.bank, a.idx))
                marked.add((c.bank, c.idx))
        for r in self.ramcodes:
            if (r.bank, r.idx) in marked:
                nm = 'RAMOVL_%04X' % r.runaddr + ('_B%d' % r.runbank if r.runbank is not None else '')
                self.union[(r.bank, r.idx)] = nm

    def ram_targets(self, addr: int) -> List[Region]:
        return [r for r in self.ramcodes if r.runaddr <= addr < r.run_end]

    def _index_ram(self):
        seen = {}
        for v in self.cfg.ram:
            if v.name in seen:
                self.diag.error(v.loc, 'RAM name %s already defined at %s' % (v.name, seen[v.name]))
                continue
            seen[v.name] = v.loc
            if v.addr in self.hw.io and (0xFF00 <= v.addr <= 0xFF7F or v.addr == 0xFFFF):
                self.diag.warn(v.loc, 'address $%04X already has the hardware name %s (hardware name wins)'
                               % (v.addr, self.hw.io[v.addr]))
            self.name_loc[v.name] = ('ram', v.addr)
            self.ram_exact.setdefault(v.addr, v)
        self.ram_sorted = sorted(self.cfg.ram, key=lambda v: (v.addr, v.name))
        self._ram_starts = [v.addr for v in self.ram_sorted]
        self._ram_maxsize = max([v.size for v in self.ram_sorted] or [1])

    def ram_expr(self, addr: int) -> Optional[Tuple[str, int]]:
        """Name expression for a RAM address from config/ram: (text, value) or None."""
        v = self.ram_exact.get(addr)
        if v is not None:
            return v.name, addr
        i = bisect.bisect_right(self._ram_starts, addr) - 1
        while i >= 0:
            v = self.ram_sorted[i]
            if v.addr <= addr < v.addr + v.size:
                return '%s + %d' % (v.name, addr - v.addr), addr
            if v.addr + self._ram_maxsize <= addr:      # nothing that far away can enclose it
                break
            i -= 1
        return None

    # ----------------------------------------------------------------- labels
    def add_label(self, bank: int, addr: int, name: str, origin: str, loc: str):
        r = self.region_at(bank, addr)
        if r is None:
            self.diag.error(loc, 'label %s: address %02X:%04X is outside the bank window' % (name, bank, addr))
            return
        if r.kind in ('code', 'ramcode') and addr not in self.bound[bank]:
            self.diag.error(loc, 'label %s at %02X:%04X is not on an instruction boundary of the %s region %04X-%04X '
                            '(split the region or fix the address)' % (name, bank, addr, r.kind, r.start, r.end))
            return
        if r.kind in ('words', 'ptrtable') and (addr - r.start) % 2:
            self.diag.error(loc, 'label %s at %02X:%04X is not word-aligned inside the %s region %04X-%04X'
                            % (name, bank, addr, r.kind, r.start, r.end))
            return
        prev = self.name_loc.get(name)
        if prev is not None:
            if prev == (bank, addr):
                return
            self.diag.error(loc, 'label collision: name %s already used (%s)%s' % (
                name, {'const': 'const symbol', 'ram': 'RAM variable'}.get(prev[0]) or self.cite(*prev),
                '; overlays of one bank sharing a runaddr need distinct symbols' if origin == 'generic' else ''))
            return
        ra = self.run_addr(bank, addr)
        m = mtcfg.GENERIC.match(name)
        if m and origin != 'generic' and (int(m.group(2), 16), int(m.group(3), 16)) != (bank, ra):
            self.diag.error(loc, 'name %s looks like a generic name for %s:%s but labels %02X:%04X; '
                            'use a different name or the matching address' % (name, m.group(2), m.group(3), bank, ra))
            return
        self.name_loc[name] = (bank, addr)
        self.name_val[name] = ra
        self.labels[bank].setdefault(addr, []).append(Label(name, origin, loc))

    def _collect_labels(self):
        for b in range(self.nbanks):
            for s in self.cfg.symbols.get(b, ()):
                if s.type == 'const':
                    if s.name in self.name_loc:
                        self.diag.error(s.loc, 'name %s already used' % s.name)
                        continue
                    self.name_loc[s.name] = ('const',)
                    self.consts.append(s)
                else:
                    self.add_label(b, s.addr, s.name, 'symbol', s.loc)
        for b in range(self.nbanks):
            for r in self.regions[b]:
                if r.label:
                    self.add_label(b, r.start, r.label, 'region', r.loc)

    def named_at(self, loc) -> Optional[str]:
        for lab in self.labels[loc[0]].get(loc[1], ()):
            if lab.origin != 'generic':
                return lab.name
        return None

    def name_at(self, loc) -> Optional[str]:
        labs = self.labels[loc[0]].get(loc[1])
        return labs[0].name if labs else None

    def has_label(self, loc) -> bool:
        return loc[1] in self.labels[loc[0]]

    # ------------------------------------------------------------ target rules
    def resolve_target(self, src_bank: int, src: Region, target: int) -> Optional[Tuple[int, int]]:
        """Map a CPU address referenced from `src` to ROM coordinates (bank, storage address), or None.

        ROM0 is always bank 0; ROMX addresses belong to the referencing bank when it is itself a
        ROMX bank (code in bank N cannot switch itself away); a reference from ROM0 or from RAM code
        into 4000-7FFF has no defined bank.  RAM addresses resolve only into a unique ramcode region.
        """
        if src.kind == 'ramcode' and src.runaddr <= target < src.run_end:
            return src_bank, src.start + (target - src.runaddr)
        if target < 0x8000:
            if target < 0x4000:
                loc = (0, target)
            elif src_bank != 0 and src.kind != 'ramcode':
                loc = (src_bank, target)
            else:
                return None
            r = self.region_at(*loc)
            if r is not None and r.kind == 'ramcode':
                return None        # bytes stored here run elsewhere: the ROM address is not a label
            return loc
        hits = self.ram_targets(target)
        if len(hits) == 1:
            h = hits[0]
            return h.bank, h.start + (target - h.runaddr)
        return None

    def _want(self, loc, kind: str, force: bool = False, where: str = '') -> bool:
        tb, ta = loc
        if self.has_label(loc):
            return True
        r = self.region_at(tb, ta)
        if r is None:
            return False
        if r.kind in ('code', 'ramcode'):
            if ta in self.bound[tb]:
                self.want[loc].add(kind)
                return True
            self.stats['targets_mid_instruction'] += 1
            return False
        if force:
            if r.kind in ('words', 'ptrtable') and (ta - r.start) % 2:
                self.diag.error(where, 'xref target %02X:%04X is not word-aligned inside its %s region' % (tb, ta, r.kind))
                return False
            self.want[loc].add(kind)
            return True
        return False

    def _insn_at(self, bank: int, addr: int):
        r = self.region_at(bank, addr)
        if r is None or r.kind not in ('code', 'ramcode') or addr not in self.bound[bank]:
            return None, None
        lst = self.insns[(bank, r.idx)]
        i = bisect.bisect_left(lst, addr, key=lambda t: t[0])
        return r, lst[i][1]

    def _resolve_xrefs(self):
        for x in self.cfg.xrefs:
            where = x.loc
            key = (x.bank, x.addr, x.kind)
            if key in self.xref:
                self.diag.error(where, 'duplicate xref for %02X:%04X %s' % (x.bank, x.addr, x.kind))
                continue
            value = None
            kind = 'imm'
            if x.kind == 'word':
                r = self.region_at(x.bank, x.addr)
                if r is None or r.kind not in ('words', 'ptrtable') or (x.addr - r.start) % 2:
                    self.diag.error(where, 'xref word: %02X:%04X is not a word slot of a words/ptrtable region' % (x.bank, x.addr))
                    continue
                value = self.rom[r.off + (x.addr - r.start)] | (self.rom[r.off + (x.addr - r.start) + 1] << 8)
            else:
                r, ins = self._insn_at(x.bank, x.addr)
                if ins is None:
                    self.diag.error(where, 'xref: no instruction starts at %02X:%04X (stale xref?)' % (x.bank, x.addr))
                    continue
                if x.kind == 'branch':
                    value = ins.target
                    kind = 'call' if ins.flow in CALL_FLOWS else 'jump'
                elif x.kind == 'imm' and ins.imm16_kind == 'imm':
                    value = ins.imm16
                elif x.kind == 'mem' and ins.imm16_kind == 'mem':
                    value = ins.imm16
                if value is None:
                    self.diag.error(where, 'xref: instruction at %02X:%04X (%s) has no %s operand' % (
                        x.bank, x.addr, ins.text(), x.kind))
                    continue
            if x.taddr != value:
                self.diag.error(where, 'xref target address $%04X differs from the operand value $%04X at %02X:%04X: '
                                'a name must not change bytes' % (x.taddr, value, x.bank, x.addr))
                continue
            if x.tbank == 'RAM':
                ex = self.ram_expr(x.taddr)
                if ex is None:
                    self.diag.error(where, 'xref target RAM $%04X has no name in config/ram' % x.taddr)
                    continue
                self.xref[key] = ('ram', ex)
                continue
            if x.taddr >= 0x8000:
                hits = [h for h in self.ram_targets(x.taddr) if h.bank == x.tbank]
                if len(hits) != 1:
                    self.diag.error(where, 'xref target $%04X: expected exactly one ramcode region in bank %02X, found %d'
                                    % (x.taddr, x.tbank, len(hits)))
                    continue
                loc = (x.tbank, hits[0].start + (x.taddr - hits[0].runaddr))
            else:
                lo, hi = mtcfg.window(x.tbank)
                if not lo <= x.taddr < hi:
                    self.diag.error(where, 'xref target $%04X is not inside bank %02X window' % (x.taddr, x.tbank))
                    continue
                loc = (x.tbank, x.taddr)
            if self.run_addr(*loc) != x.taddr:
                self.diag.error(where, 'xref target %02X:%04X is stored in a ramcode region that runs at $%04X, not $%04X'
                                % (loc[0], loc[1], self.run_addr(*loc), x.taddr))
                continue
            if not self._want(loc, kind, True, where):
                self.diag.error(where, 'xref target %02X:%04X cannot be labelled (mid-instruction?)' % loc)
                continue
            self.xref[key] = ('loc', loc)
            self.stats['xrefs'] += 1

    def _check_xref_targets(self):
        for key, val in self.xref.items():
            if val[0] == 'loc' and not self.has_label(val[1]):
                raise GenError('internal: xref target %02X:%04X has no label' % val[1])

    def _collect_refs(self):
        for (b, ridx), lst in self.insns.items():
            r = self.regions[b][ridx]
            for sa, ins in lst:
                if ins.target is None or (b, sa, 'branch') in self.xref:
                    continue
                loc = self.resolve_target(b, r, ins.target)
                if loc is None:
                    self.stats['branches_unresolved_bank'] += 1
                    continue
                self._want(loc, 'call' if ins.flow in CALL_FLOWS else 'jump')
        for b in range(self.nbanks):
            for r in self.regions[b]:
                if r.kind != 'ptrtable':
                    continue
                for i in range(0, r.size, 2):
                    if (b, r.start + i, 'word') in self.xref:
                        continue
                    v = self.rom[r.off + i] | (self.rom[r.off + i + 1] << 8)
                    if v == 0:
                        continue        # $0000 is far more likely a null/empty slot than a pointer to 00:0000 (xref word forces it)
                    loc = self.resolve_target(b, r, v)
                    if loc is not None:
                        self._want(loc, 'ptr')

    def _finalize_labels(self):
        for loc in sorted(self.want):
            tb, ta = loc
            if self.has_label(loc):
                continue
            r = self.region_at(tb, ta)
            kinds = self.want[loc]
            if r.kind in ('code', 'ramcode'):
                prefix = 'Function' if 'call' in kinds else 'Label'
            elif r.kind in ('words', 'ptrtable'):
                prefix = 'Table'
            elif r.kind == 'text':
                prefix = 'String'
            else:
                prefix = 'Data'
            name = '%s_%02X_%04X' % (prefix, tb, self.run_addr(tb, ta))
            self.add_label(tb, ta, name, 'generic', '')
            self.stats['generic_' + prefix] += 1
        self.diag.raise_if_errors()

    # ------------------------------------------------------------- operands
    def _hw_name(self, addr: int) -> Optional[Tuple[str, int]]:
        n = self.hw.io.get(addr)
        if n is not None:
            return n, addr
        if 0xFF30 < addr <= 0xFF3F and self.hw.io.get(0xFF30) == '_AUD3WAVERAM':
            return '_AUD3WAVERAM + %d' % (addr - 0xFF30), addr
        return None

    def _substitute(self, text: str, val: int, want: int, what: str) -> str:
        if val != want:
            raise GenError('internal: %s %s has value $%04X but the operand is $%04X' % (what, text, val, want))
        return text

    def render_insn(self, r: Region, sa: int, ins: sm83.Insn) -> str:
        b = r.bank
        st = self.stats

        def branch(t):
            x = self.xref.get((b, sa, 'branch'))
            if x is not None:
                loc = x[1]
            else:
                loc = self.resolve_target(b, r, t)
                if loc is None:
                    return None
            nm = self.name_at(loc)
            if nm is None:
                st['targets_unlabelled'] += 1
                return None
            st['branch_labels'] += 1
            return self._substitute(nm, self.name_val[nm], t, 'label')

        def imm16(v, kind):
            x = self.xref.get((b, sa, 'imm' if kind == 'imm' else 'mem'))
            if x is not None:
                if x[0] == 'ram':
                    st['xref_ram'] += 1
                    return self._substitute(x[1][0], x[1][1], v, 'ram name')
                nm = self.name_at(x[1])
                st['xref_labels'] += 1
                return self._substitute(nm, self.name_val[nm], v, 'label')
            if kind != 'mem':
                return None
            return self._mem_name(v, ins.fmt == 'ld [{i}], a')      # MBC names only for `ld [a16], a` (never `ld [a16], sp`)

        def hram(v):
            return self._mem_name(v, False, ldh=True)

        if ins.flow == 'rst':       # sm83 prints rst vectors numerically; use the label of the vector when there is one
            nm = branch(ins.target)
            return 'rst ' + nm if nm else ins.text()
        return ins.text(branch, imm16, hram)

    def _mem_name(self, addr: int, write: bool, ldh: bool = False) -> Optional[str]:
        st = self.stats
        if 0xFF00 <= addr <= 0xFF7F or addr == 0xFFFF:
            h = self._hw_name(addr)
            if h is not None:
                st['hw_names'] += 1
                return self._substitute(h[0], h[1], addr, 'hardware name')
        if write and not ldh and addr in self.hw.mbc:
            st['mbc_names'] += 1
            return self._substitute(self.hw.mbc[addr], addr, addr, 'MBC name')
        if addr >= 0x8000:
            e = self.ram_expr(addr)
            if e is not None:
                st['ram_names'] += 1
                return self._substitute(e[0], e[1], addr, 'ram name')
        return None

    def word_name(self, r: Region, addr: int, v: int) -> Optional[str]:
        """Symbol/label for a dw value in a words/ptrtable region (or None -> numeric)."""
        x = self.xref.get((r.bank, addr, 'word'))
        if x is not None:
            if x[0] == 'ram':
                return self._substitute(x[1][0], x[1][1], v, 'ram name')
            nm = self.name_at(x[1])
            return self._substitute(nm, self.name_val[nm], v, 'label')
        if v == 0:
            return None                 # never turn a null/empty slot into a label without an explicit xref word row
        loc = self.resolve_target(r.bank, r, v)
        if loc is None:
            return None
        nm = self.name_at(loc) if r.kind == 'ptrtable' else self.named_at(loc)
        if nm is None:
            return None
        self.stats['word_labels'] += 1
        return self._substitute(nm, self.name_val[nm], v, 'label')

    # ------------------------------------------------------------- line checks
    def _tok(self, t: str) -> int:
        t = t.strip()
        if t.startswith('$'):
            return int(t[1:], 16)
        if t in self.name_val:
            return self.name_val[t]
        raise GenError('internal: cannot evaluate %r' % t)

    def verify_line(self, text: str, claim: bytes, absoff: int):
        text = text.split(' ;', 1)[0]
        if text.startswith('\tdb '):
            got = bytes(self._tok(t) for t in text[4:].split(','))
        elif text.startswith('\tdw '):
            got = b''.join(self._tok(t).to_bytes(2, 'little') for t in text[4:].split(','))
        elif text.startswith('\tds '):
            m = re.fullmatch(r'\tds \$([0-9A-F]+), \$([0-9A-F]{2})', text)
            if not m:
                raise GenError('internal: bad ds line %r' % text)
            got = bytes([int(m.group(2), 16)]) * int(m.group(1), 16)
        elif text.startswith('\tINCBIN '):
            m = re.fullmatch(r'\tINCBIN "([^"]+)", \$([0-9A-F]+), \$([0-9A-F]+)', text)
            if not m or m.group(1) != self.incbin:
                raise GenError('internal: bad INCBIN line %r' % text)
            off, n = int(m.group(2), 16), int(m.group(3), 16)
            if off != absoff:
                raise GenError('internal: INCBIN offset $%X but bank position is $%X' % (off, absoff))
            got = self.rom[off:off + n]
        else:
            return
        if got != claim:
            raise GenError('internal: line %r does not round-trip to the ROM bytes' % text)

    # ---------------------------------------------------------------- emission
    def _label_lines(self, out: BankOut, r: Region, addr: int):
        labs = self.labels[r.bank].get(addr)
        if not labs:
            return
        out.line('')
        cite = '%02X:%04X' % (r.bank, addr)
        if r.kind == 'ramcode':
            cite += ' (runs at $%04X)' % self.run_addr(r.bank, addr)
        for i, lab in enumerate(labs):
            out.line('%s::%s' % (lab.name, ' ; ' + cite if i == 0 else ''))

    def _segments(self, r: Region) -> List[Tuple[int, int]]:
        la = self.label_addrs.get(r.bank)
        if la is None:
            la = sorted(self.labels[r.bank])
        lo = bisect.bisect_right(la, r.start)
        hi = bisect.bisect_left(la, r.end)
        pts = [r.start] + la[lo:hi] + [r.end]
        return list(zip(pts, pts[1:]))

    def _emit_db(self, out: BankOut, chunk: bytes):
        for i in range(0, len(chunk), 16):
            part = chunk[i:i + 16]
            out.emit('\tdb ' + ', '.join(hexb(x) for x in part), part)

    def _emit_words(self, out: BankOut, r: Region, a: int, z: int):
        per = 1 if r.kind == 'ptrtable' else 8
        vals = []
        for addr in range(a, z, 2):
            o = r.off + (addr - r.start)
            v = self.rom[o] | (self.rom[o + 1] << 8)
            vals.append((addr, v, self.word_name(r, addr, v) or hexw(v)))
        for i in range(0, len(vals), per):
            part = vals[i:i + per]
            claim = b''.join(v.to_bytes(2, 'little') for _, v, _ in part)
            out.emit('\tdw ' + ', '.join(t for _, _, t in part), claim)

    def _emit_region(self, out: BankOut, r: Region):
        hdr = '; ---- %s $%04X-$%04X (%d bytes)' % (r.kind, r.start, r.end, r.size)
        if r.gap:
            hdr += ' [unclassified gap]'
        else:
            if r.status:
                hdr += ' [%s]' % r.status
            if r.note:
                hdr += ' %s' % r.note
        out.line('')
        out.line(hdr)
        if r.kind in ('code', 'ramcode'):
            self._emit_code(out, r)
            return
        for a, z in self._segments(r):
            self._label_lines(out, r, a)
            chunk = self.rom[r.off + (a - r.start):r.off + (z - r.start)]
            if r.kind == 'zero':
                out.emit('\tds $%X, $00' % len(chunk), chunk)
            elif r.kind == 'raw':
                absoff = out.bank * BANK_SIZE + out.pos
                out.emit('\tINCBIN "%s", $%X, $%X' % (self.incbin, absoff, len(chunk)), chunk)
            elif r.kind in ('data', 'text', 'gfx'):
                self._emit_db(out, chunk)
            elif r.kind in ('words', 'ptrtable'):
                self._emit_words(out, r, a, z)
            else:
                raise GenError('internal: unhandled kind %s' % r.kind)

    def _emit_code(self, out: BankOut, r: Region):
        if r.kind == 'ramcode':
            area = mtcfg.ram_area(r.runaddr, r.size)
            spec = '%s[$%04X]' % (area[2], r.runaddr)
            if r.runbank is not None:
                spec += ', BANK[%d]' % r.runbank
            un = self.union.get((r.bank, r.idx))
            if un:
                out.line('\tLOAD UNION "%s", %s' % (un, spec))
            else:
                out.line('\tLOAD "RAM_%02X_%04X", %s' % (r.bank, r.start, spec))
        for sa, ins in self.insns[(r.bank, r.idx)]:
            self._label_lines(out, r, sa)
            txt = self.render_insn(r, sa, ins)
            if ins.flow == 'bad':
                txt += ' ; illegal opcode'
            out.emit('\t' + txt, ins.raw)
            if ins.flow in TERMINATORS:
                out.line('')
        if r.kind == 'ramcode':
            out.line('\tENDL')

    def bank_source(self, b: int) -> str:
        out = BankOut(self, b)
        out.line(GENERATED_HEADER)
        out.line('; bank %02X' % b)
        out.line('')
        out.line('INCLUDE "constants/hardware.inc"')
        out.line('INCLUDE "ram.inc"')
        cs = self.cfg.symbols.get(b, [])
        cs = [s for s in cs if s.type == 'const']
        if cs:
            out.line('')
            for s in cs:
                out.line('DEF %s EQU $%04X ; %s %s' % (s.name, s.addr, s.status, s.evidence))
                out.line('EXPORT %s' % s.name)
        out.line('')
        if b == 0:
            out.line('SECTION "Bank%02X", ROM0[$0000]' % b)
        else:
            out.line('SECTION "Bank%02X", ROMX[$4000], BANK[$%02X]' % (b, b))
        for r in self.regions[b]:
            self._emit_region(out, r)
        if out.pos != BANK_SIZE:
            raise GenError('internal: bank %02X emitted %d bytes instead of %d' % (b, out.pos, BANK_SIZE))
        return '\n'.join(out.lines).rstrip('\n') + '\n'

    def ram_inc(self) -> str:
        lines = [GENERATED_HEADER,
                 '; RAM / SRAM / HRAM variable names from config/ram/*.tsv (addresses only, no bytes).', '']
        for v in sorted(self.cfg.ram, key=lambda v: (v.addr, v.name)):
            lines.append('DEF %s EQU $%04X ; size %d %s %s %s' % (v.name, v.addr, v.size, v.type, v.status, v.evidence))
        return '\n'.join(lines).rstrip('\n') + '\n'

    def generate(self) -> Dict[str, str]:
        files = {'ram.inc': self.ram_inc()}
        for b in range(self.nbanks):
            files['bank%02x.asm' % b] = self.bank_source(b)
        return files


# ------------------------------------------------------------------ front-end

def load_model(rom_path: Optional[str] = None, cfgdir: Optional[str] = None, hw_path: Optional[str] = None,
               strict: bool = False, extra_xrefs=(), rom: Optional[bytes] = None):
    """Load ROM + config and build the Model.  Returns (model, diag)."""
    rom_path = rom_path or os.path.join(ROOT, 'baserom.gbc')
    cfgdir = cfgdir or os.path.join(ROOT, 'config')
    if rom is None:
        if not os.path.exists(rom_path):
            raise GenError('missing ROM %s (run `make baserom`)' % rom_path)
        with open(rom_path, 'rb') as fh:
            rom = fh.read()
    if len(rom) < BANK_SIZE or len(rom) % BANK_SIZE:
        raise GenError('ROM size %d is not a positive multiple of 16 KiB' % len(rom))
    hw = mtcfg.load_hardware(hw_path)
    diag = Diag(strict)
    cfg = mtcfg.load_config(cfgdir, len(rom) // BANK_SIZE, hw, diag, extra_xrefs)
    diag.raise_if_errors()
    model = Model(rom, cfg, hw, os.path.basename(rom_path))
    return model, diag


def write_files(files: Dict[str, str], outdir: str) -> int:
    os.makedirs(outdir, exist_ok=True)
    changed = 0
    for name, text in sorted(files.items()):
        path = os.path.join(outdir, name)
        if os.path.exists(path):
            with open(path, encoding='utf-8') as fh:
                if fh.read() == text:
                    continue
        with open(path, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(text)
        changed += 1
    return changed


def assemble(files: Dict[str, str], workdir: str, rom_dir: str, jobs: Optional[int] = None) -> Tuple[str, List[str]]:
    """Write `files` to workdir/src, assemble each bank and link.  Returns (rom_path, log)."""
    src, obj = os.path.join(workdir, 'src'), os.path.join(workdir, 'obj')
    os.makedirs(src, exist_ok=True)
    os.makedirs(obj, exist_ok=True)
    write_files(files, src)
    banks = sorted(n for n in files if n.endswith('.asm'))

    def one(name):
        o = os.path.join(obj, name[:-4] + '.o')
        p = subprocess.run(['rgbasm', '-I', src, '-I', rom_dir, '-I', ROOT, '-o', o, os.path.join(src, name)],
                           capture_output=True, text=True, cwd=workdir)
        return name, o, p

    objs, log = [], []
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs or min(16, os.cpu_count() or 4)) as ex:
        for name, o, p in ex.map(one, banks):
            if p.returncode:
                raise GenError('rgbasm failed on %s:\n%s' % (name, p.stderr[:3000]))
            if p.stderr.strip():
                log.append('%s: %s' % (name, p.stderr.strip()[:500]))
            objs.append(o)
    rom = os.path.join(workdir, 'out.gbc')
    p = subprocess.run(['rgblink', '-p', '0x00', '-n', os.path.join(workdir, 'out.sym'), '-o', rom] + objs, capture_output=True, text=True, cwd=workdir)
    if p.returncode:
        raise GenError('rgblink failed:\n%s' % p.stderr[:3000])
    return rom, log


def assemble_and_compare(files, rom: bytes, rom_path: str, cfgdir: str, workdir: str, quiet=False) -> bool:
    import compare_rom
    built_path, log = assemble(files, workdir, os.path.dirname(os.path.abspath(rom_path)))
    for line in log[:10]:
        print('rgbasm warning: ' + line, file=sys.stderr)
    with open(built_path, 'rb') as fh:
        built = fh.read()
    return compare_rom.compare(rom, built, cfgdir, out=(lambda *a, **k: None) if quiet else print)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('mode', nargs='?', default='regen', choices=('regen', 'verify', 'check'))
    ap.add_argument('--config', default=os.path.join(ROOT, 'config'))
    ap.add_argument('--out', default=os.path.join(ROOT, 'src'))
    ap.add_argument('--rom', default=os.path.join(ROOT, 'baserom.gbc'))
    ap.add_argument('--fast', action='store_true', help='regen: skip the rgbasm/rgblink check')
    ap.add_argument('--strict', action='store_true', help='treat config warnings as errors')
    ap.add_argument('--xrefs', action='append', default=[], help='additional xrefs file (same format as config/xrefs.tsv)')
    ap.add_argument('--keep', help='verify: keep the temp build in this directory')
    ap.add_argument('-q', '--quiet', action='store_true')
    a = ap.parse_args(argv)

    try:
        model, diag = load_model(a.rom, a.config, None, a.strict, a.xrefs)
        for w in (diag.warnings + model.diag.warnings)[:25]:
            print('warning: ' + w, file=sys.stderr)
        files = model.generate()
    except GenError as e:
        print('error: %s' % e, file=sys.stderr)
        return 1

    if a.mode == 'check':
        if not a.quiet:
            print('check OK: %d banks generated in memory, structural round-trip passed' % model.nbanks)
        return 0

    with open(a.rom, 'rb') as fh:
        rom = fh.read()
    if a.mode == 'verify' or not a.fast:
        tmp = a.keep or tempfile.mkdtemp(prefix='mtgen_')
        try:
            os.makedirs(tmp, exist_ok=True)
            ok = assemble_and_compare(files, rom, a.rom, a.config, tmp, quiet=(a.mode == 'regen'))
        except GenError as e:
            print('error: %s' % e, file=sys.stderr)
            ok = False
        finally:
            if not a.keep:
                shutil.rmtree(tmp, ignore_errors=True)
        if not ok:
            print('error: generated sources do not rebuild the ROM byte-identically%s' % (
                '; nothing was written' if a.mode == 'regen' else ''), file=sys.stderr)
            return 1
        if a.mode == 'verify':
            stale = []
            for name, text in files.items():
                p = os.path.join(a.out, name)
                if not os.path.exists(p) or open(p, encoding='utf-8').read() != text:
                    stale.append(name)
            if stale:
                print('note: %d file(s) in %s differ from the generated sources (run `make regen`)' % (
                    len(stale), os.path.relpath(a.out, ROOT) if a.out.startswith(ROOT) else a.out))
            return 0

    changed = write_files(files, a.out)
    if not a.quiet:
        print('regen OK: %d banks, %d file(s) rewritten in %s%s' % (
            model.nbanks, changed, a.out, '' if a.fast else ' (assemble+link check passed)'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
