#!/usr/bin/env python3
"""Generate src/bankNN.asm from the ROM and config/regions.tsv.   (baseline v0)

regions.tsv (tab separated, '#' comments):
    bank  start  end  kind  label  status  note
bank: 2 hex digits; start/end: CPU addresses (hex, end exclusive) inside the
bank window (0000-3FFF for bank 00, 4000-7FFF otherwise).  Regions of a bank
must tile the whole window; gaps are filled with `raw` regions automatically.

kinds implemented in v0:  raw (INCBIN from baserom.gbc), zero (ds N,$00),
data (db lines).  Code kinds are added by later work (tools/gen_asm.py owner).
"""
import os, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
ROM = os.path.join(ROOT, 'baserom.gbc')
REG = os.path.join(ROOT, 'config', 'regions.tsv')
NBANKS = 128

def load_regions():
    per = {b: [] for b in range(NBANKS)}
    if os.path.exists(REG):
        for line in open(REG):
            if line.startswith('#') or not line.strip():
                continue
            f = line.rstrip('\n').split('\t')
            if f[0] == 'bank':
                continue
            per[int(f[0], 16)].append(dict(start=int(f[1], 16), end=int(f[2], 16), kind=f[3],
                                           label=f[4], status=f[5] if len(f) > 5 else '', note=f[6] if len(f) > 6 else ''))
    return per

def main():
    rom = open(ROM, 'rb').read()
    per = load_regions()
    os.makedirs(os.path.join(ROOT, 'src'), exist_ok=True)
    for b in range(NBANKS):
        base = 0x0000 if b == 0 else 0x4000
        regs = sorted(per[b], key=lambda r: r['start'])
        full, cur = [], base
        for r in regs:
            if r['start'] < cur:
                sys.exit('bank %02X: overlapping region at %04X' % (b, r['start']))
            if r['start'] > cur:
                full.append(dict(start=cur, end=r['start'], kind='raw', label='', status='', note='gap'))
            full.append(r); cur = r['end']
        if cur < base + 0x4000:
            full.append(dict(start=cur, end=base + 0x4000, kind='raw', label='', status='', note='gap'))
        out = ['; Generated by tools/gen_asm.py -- bank %02X' % b,
               'SECTION "Bank%02X", %s' % (b, 'ROM0[$0000]' if b == 0 else 'ROMX[$4000], BANK[$%02X]' % b), '']
        for r in full:
            off = b * 0x4000 + (r['start'] - base)
            n = r['end'] - r['start']
            chunk = rom[off:off + n]
            if r['label']:
                out.append('%s::' % r['label'])
            if r['kind'] == 'zero' or (r['kind'] == 'raw' and not any(chunk)):
                out.append('\tds $%X, $00' % n)
            elif r['kind'] == 'data':
                for i in range(0, n, 16):
                    out.append('\tdb ' + ', '.join('$%02X' % x for x in chunk[i:i + 16]))
            else:
                out.append('\tINCBIN "baserom.gbc", $%X, $%X' % (off, n))
        open(os.path.join(ROOT, 'src', 'bank%02x.asm' % b), 'w').write('\n'.join(out) + '\n')

if __name__ == '__main__':
    main()
