#!/usr/bin/env python3
"""Production source generator: ROM bytes + config/ tables -> RGBDS sources.

FROZEN BOOTSTRAP TOOL (history/evidence): the tree it generated was committed as the hand-maintained source, so `regen` refuses to write
inside the repository (except build/) unless MT_LEGACY_REGEN=1; generate into a directory outside the repository.  `verify`/`check` are unaffected.

    gen_asm.py [regen]  [--config DIR] [--out DIR] [--rom FILE] [--fast] [--strict] [-q]
    gen_asm.py verify   [--config DIR] [--rom FILE] [--keep DIR] [--strict]
    gen_asm.py check    [--config DIR] [--rom FILE] [--strict]
    gen_asm.py [regen|verify|check] --tree OUTDIR --layout FILE     tree mode (docs/FORMATS.md, "Tree mode")

regen   generate src/bankNN.asm + src/ram.inc from the ROM and config/, run the
        internal structural round-trip check, then (unless --fast) assemble and
        link the result in a temp dir and compare it with the ROM; the files in
        --out are written only if every check passes.
verify  generate into a temp dir (never touches --out), assemble + link, compare
        with the ROM and print any differences mapped to regions.
check   generate in memory and run the structural checks only (no files, no rgbasm).

The generated code is byte-exact by construction: every emitted line is
re-parsed / cross-checked against the ROM bytes and every name substituted for
a number is checked to have exactly that numeric value.  See docs/FORMATS.md.
"""
import argparse
import bisect
import concurrent.futures
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import defaultdict
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import sm83                                   # noqa: E402
from lib import mtcfg                         # noqa: E402
from lib import conv                          # noqa: E402
from lib import textfmt                       # noqa: E402
from lib import layout as layoutlib           # noqa: E402
from lib.mtcfg import GenError, Diag, Region  # noqa: E402

ROOT = mtcfg.ROOT
BANK_SIZE = mtcfg.BANK_SIZE
GENERATED_HEADER = '; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).'
TREE_HEADER = '; Generated by tools/gen_asm.py --tree -- DO NOT EDIT (edit config/ or the layout table and run `make tree`).'
MANIFEST = '.tree_manifest'
CALL_FLOWS = ('call', 'callcc', 'rst')
TERMINATORS = ('jp', 'jr', 'ret', 'jphl')


@dataclass
class Label:
    name: str
    origin: str          # 'symbol' | 'region' | 'generic'
    loc: str = ''


def hexb(v: int) -> str:
    return '$%02X' % v


def hexw(v: int) -> str:
    return '$%04X' % v


class BankOut:
    """Collects the lines of one bank and checks that the emitted bytes tile the bank exactly."""

    def __init__(self, model: 'Model', bank: int):
        self.model = model
        self.bank = bank
        self.lines: List[str] = []
        self.pos = 0

    def line(self, text: str = ''):
        if not text and (not self.lines or not self.lines[-1]):
            return                      # never two blank lines in a row
        self.lines.append(text)

    def emit(self, text: str, claim: bytes):
        m = self.model
        absoff = self.bank * BANK_SIZE + self.pos
        if m.rom[absoff:absoff + len(claim)] != claim:
            raise GenError('internal: line %r does not match ROM bytes at %02X:%04X' % (
                text, self.bank, self.pos + (0 if self.bank == 0 else 0x4000)))
        m.verify_line(text, claim, absoff)
        self.lines.append(text)
        self.pos += len(claim)


class Model:
    """Everything the emitter needs: decoded code, label tables, cross references."""

    def __init__(self, rom: bytes, cfg: mtcfg.Config, hw: mtcfg.Hardware, incbin: str = 'baserom.gbc', strict: bool = False,
                 macros: bool = True, text_comments: bool = True):
        if len(rom) < BANK_SIZE or len(rom) % BANK_SIZE:
            raise GenError('ROM size %d is not a positive multiple of 16 KiB' % len(rom))
        self.rom = rom
        self.macros = macros            # emit `farcall` / `farcall_raw` (constants/macros.inc) instead of call + dw + db
        self.text_comments = text_comments   # decoded text as a trailing comment on every text line (--no-text-comments)
        self._fc = False                # cached far-call convention (False = not looked up yet)
        self.rgbfix_args = None         # --header rgbfix (tree mode): options for the rgbfix step after linking
        self.addr_comments = True       # tree mode may drop the ROM-address comments (--tree-no-addr-comments)
        self.cfg = cfg
        self.hw = hw
        self.incbin = incbin
        self.nbanks = len(rom) // BANK_SIZE
        self.regions = cfg.regions
        self.diag = Diag(strict)         # --strict: warnings raised while building the model (RAM name shadowing, convention entries) are errors
        self.insns: Dict[Tuple[int, int], List[Tuple[int, sm83.Insn]]] = {}
        self.bound: Dict[int, set] = {b: set() for b in range(self.nbanks)}
        self.labels: Dict[int, Dict[int, List[Label]]] = {b: {} for b in range(self.nbanks)}
        self.name_loc: Dict[str, tuple] = {}     # name -> (bank, addr) | ('const',)
        self.name_val: Dict[str, int] = {}       # label name -> runtime address
        self.consts: List[mtcfg.Symbol] = []
        self.ramcodes: List[Region] = []
        self.union: Dict[Tuple[int, int], str] = {}
        self.want: Dict[Tuple[int, int], set] = defaultdict(set)
        self.xref: Dict[Tuple[int, int, str], tuple] = {}
        self.label_addrs: Dict[int, List[int]] = {}
        self.ram_sorted: List[mtcfg.RamVar] = []
        self.ram_exact: Dict[int, mtcfg.RamVar] = {}
        # bank-aware RAM names (config/ram_banked + config/ram_context.tsv): a banked name is used only at an instruction whose
        # containing context range declares a matching WRAM/SRAM bank
        self.banked: Dict[Tuple[str, int], List[mtcfg.BankedRam]] = {}                 # (space, bank) -> rows sorted by address
        self.banked_by_name: Dict[str, mtcfg.BankedRam] = {}
        self._banked_starts: Dict[Tuple[str, int], List[int]] = {}
        self._banked_maxsize: Dict[Tuple[str, int], int] = {}
        self.ctx_at: Dict[Tuple[int, int], Tuple[Optional[int], Optional[int], str, str]] = {}   # (bank, storage addr) -> (wram, sram, wram status, sram status)
        self.stats: Dict[str, int] = defaultdict(int)
        # inline-data conventions (config/conventions.tsv)
        self.conv_table = conv.ConvTable(cfg.conventions, {(x.bank, x.addr): (x.tbank, x.taddr) for x in cfg.xrefs
                                                           if x.kind == 'branch' and x.tbank != 'RAM'})
        self.inline_adopt: Dict[Tuple[int, int], conv.InlineData] = {}      # (bank, addr) -> inline bytes held by a `data` region
        self.inline_cover: Dict[int, Dict[int, tuple]] = {b: {} for b in range(self.nbanks)}   # addr -> (site, label allowed)
        self.inline_slots: Dict[Tuple[int, int], str] = {}                  # (bank, slot addr) -> layout
        self._text_items: Dict[Tuple[int, int], list] = {}
        self._build()

    # ------------------------------------------------------------------ build
    def _build(self):
        for rs in self.regions.values():          # text_charsets.tsv rows must not be crossed by a text region
            for r in rs:
                if r.kind == 'text':
                    self.text_spec(r)
        self._check_zero_regions()
        self._decode()
        self._check_conventions()
        self._index_ramcode()
        self._index_ram()
        self._index_banked()
        self._index_context()
        self._collect_labels()
        self._check_macro_names()
        self.diag.raise_if_errors()
        self._resolve_xrefs()
        self._collect_refs()
        self.diag.raise_if_errors()
        self._finalize_labels()
        self._check_xref_targets()
        self.diag.raise_if_errors()
        for b in range(self.nbanks):
            self.label_addrs[b] = sorted(self.labels[b])

    def region_at(self, bank: int, addr: int) -> Optional[Region]:
        return mtcfg.region_at(self.regions[bank], addr)

    def run_addr(self, bank: int, addr: int) -> int:
        r = self.region_at(bank, addr)
        if r is not None and r.kind == 'ramcode':
            return r.runaddr + (addr - r.start)
        return addr

    def bytes_of(self, r: Region) -> bytes:
        return self.rom[r.off:r.off + r.size]

    @staticmethod
    def cite(bank: int, addr: int) -> str:
        return '%02X:%04X' % (bank, addr)

    def _check_zero_regions(self):
        for b in range(self.nbanks):
            for r in self.regions[b]:
                if r.kind == 'zero' and any(self.bytes_of(r)):
                    first = next(i for i, v in enumerate(self.bytes_of(r)) if v)
                    self.diag.error(r.loc, "zero region %02X:%04X-%04X contains a non-zero byte at %02X:%04X"
                                    % (b, r.start, r.end, b, r.start + first))
        self.diag.raise_if_errors()

    def _decode(self):
        for b in range(self.nbanks):
            for r in self.regions[b]:
                if r.kind not in ('code', 'ramcode'):
                    continue
                addr0 = r.runaddr if r.kind == 'ramcode' else r.start
                res = conv.scan(self.bytes_of(r), addr0, r.start, b, r.kind, self.conv_table)
                if res.cross is not None:
                    at, op, full = res.cross
                    self.diag.error(r.loc, '%s region %02X:%04X-%04X: instruction at %02X:%04X (opcode $%02X, %d bytes) '
                                    'crosses the region end' % (r.kind, b, r.start, r.end, b, at, op, full))
                bound = self.bound[b]
                for sa, it in res.items:
                    if it.flow == 'inline':
                        self._register_inline(b, it)
                    else:
                        bound.add(sa)
                self.insns[(b, r.idx)] = res.items
                if res.overflow is not None:
                    self._inline_overflow(r, res.overflow)
        self.diag.raise_if_errors()

    def _register_inline(self, b: int, it: conv.InlineData, label_at_start: bool = False):
        for k in range(it.length):
            self.inline_cover[b][it.slot + k] = (it.site, label_at_start and k == 0)
        self.inline_slots[(b, it.slot)] = it.conv.layout
        st = self.stats
        st['inline_sites'] += 1
        st['inline_bytes'] += it.length
        st['inline_' + it.conv.layout] += 1

    def _inline_overflow(self, r: Region, ov: conv.Overflow):
        """A convention call whose inline bytes do not fit into the rest of its code region."""
        b = r.bank
        sa, ins = self.insns[(b, r.idx)][ov.index]
        c = ov.conv
        e = sa + ins.length
        what = '%s at %02X:%04X (%s, convention %02X:%04X %s [%s])' % (
            ins.text(), b, sa, ins.raw.hex(), c.bank, c.addr, c.layout, c.loc)
        if ov.have == 0 and r.kind == 'code' and r.idx + 1 < len(self.regions[b]):
            nxt = self.regions[b][r.idx + 1]
            if nxt.start == e and nxt.kind == 'data' and nxt.size >= c.size:
                # tolerated: the bytes right after the call were classified as a `data` region of their own
                it = conv.InlineData(e, e, self.rom[nxt.off:nxt.off + c.size], c, sa)
                self.inline_adopt[(b, e)] = it
                self._register_inline(b, it, label_at_start=True)
                self.stats['inline_adopted'] += 1
                return
        end = e + c.size
        hdr = 'convention call %s: its %d inline byte(s) at %02X:%04X-%04X ' % (what, c.size, b, e, end)
        if ov.have:
            self.diag.error(r.loc, hdr + 'cross the end of the %s region %04X-%04X: move that region edge to $%04X '
                            '(inline data must stay inside one code region), or end the region before the call at $%04X'
                            % (r.kind, r.start, r.end, end, sa))
        elif r.idx + 1 >= len(self.regions[b]):
            self.diag.error(r.loc, hdr + 'would lie beyond the end of bank %02X: end the %s region %04X-%04X before '
                            'the call at $%04X' % (b, r.kind, r.start, r.end, sa))
        else:
            nxt = self.regions[b][r.idx + 1]
            self.diag.error(r.loc, hdr + 'start at the next region %04X-%04X (kind %s, %s): move the end of this %s '
                            'region %04X-%04X to $%04X so the inline bytes belong to it%s' % (
                                nxt.start, nxt.end, nxt.kind, nxt.loc, r.kind, r.start, r.end, end,
                                '' if r.kind == 'code' else '; ramcode never adopts a following data region'))

    def _check_conventions(self):
        for c in self.cfg.conventions:
            r = self.region_at(c.bank, c.addr)
            if r is not None and r.kind == 'code' and c.addr not in self.bound[c.bank]:
                self.diag.warn(c.loc, 'convention entry %02X:%04X is not on an instruction boundary of the code region '
                               '%04X-%04X (%s)' % (c.bank, c.addr, r.start, r.end, r.loc))

    def _index_ramcode(self):
        self.ramcodes = [r for b in range(self.nbanks) for r in self.regions[b] if r.kind == 'ramcode']
        marked = set()
        for i, a in enumerate(self.ramcodes):
            for c in self.ramcodes[i + 1:]:
                if a.runbank != c.runbank or not (a.runaddr < c.run_end and c.runaddr < a.run_end):
                    continue
                if a.runaddr != c.runaddr:
                    self.diag.error(c.loc, 'ramcode runtime range $%04X-$%04X partially overlaps $%04X-$%04X of %s: '
                                    'overlays must start at the same runaddr' % (
                                        c.runaddr, c.run_end, a.runaddr, a.run_end, a.loc))
                    continue
                marked.add((a.bank, a.idx))
                marked.add((c.bank, c.idx))
        for r in self.ramcodes:
            if (r.bank, r.idx) in marked:
                nm = 'RAMOVL_%04X' % r.runaddr + ('_B%d' % r.runbank if r.runbank is not None else '')
                self.union[(r.bank, r.idx)] = nm

    def ram_targets(self, addr: int) -> List[Region]:
        return [r for r in self.ramcodes if r.runaddr <= addr < r.run_end]

    def _index_ram(self):
        seen = {}
        for v in self.cfg.ram:
            if v.name in seen:
                self.diag.error(v.loc, 'RAM name %s already defined at %s' % (v.name, seen[v.name]))
                continue
            seen[v.name] = v.loc
            if v.addr in self.hw.io and (0xFF00 <= v.addr <= 0xFF7F or v.addr == 0xFFFF):
                self.diag.warn(v.loc, 'address $%04X already has the hardware name %s (hardware name wins)'
                               % (v.addr, self.hw.io[v.addr]))
            self.name_loc[v.name] = ('ram', v.addr)
            self.ram_exact.setdefault(v.addr, v)
        self.ram_sorted = sorted(self.cfg.ram, key=lambda v: (v.addr, v.name))
        self._ram_starts = [v.addr for v in self.ram_sorted]
        self._ram_maxsize = max([v.size for v in self.ram_sorted] or [1])

    def _index_banked(self):
        for v in self.cfg.ram_banked:
            prev = self.name_loc.get(v.name)
            if prev is not None:
                self.diag.error(v.loc, 'banked RAM name %s already defined (%s)' % (v.name, {'ram': 'RAM variable', 'const': 'const symbol'}.get(prev[0], 'label')))
                continue
            self.name_loc[v.name] = ('ram', v.addr)
            self.banked.setdefault((v.space, v.bank), []).append(v)
            self.banked_by_name[v.name] = v
        for k, lst in self.banked.items():
            lst.sort(key=lambda v: (v.addr, v.name))
            self._banked_starts[k] = [v.addr for v in lst]
            self._banked_maxsize[k] = max(v.size for v in lst)

    def banked_expr(self, space: str, bank: int, addr: int) -> Optional[Tuple[str, int]]:
        """Name expression for `addr` from the bank-qualified names of (space, bank): (text, value) or None."""
        lst = self.banked.get((space, bank))
        if not lst:
            return None
        starts = self._banked_starts[(space, bank)]
        i = bisect.bisect_right(starts, addr) - 1
        while i >= 0:
            v = lst[i]
            if v.addr <= addr < v.addr + v.size:
                return (v.name if v.addr == addr else '%s + %d' % (v.name, addr - v.addr)), addr
            if v.addr + self._banked_maxsize[(space, bank)] <= addr:
                break
            i -= 1
        return None

    def _index_context(self):
        """config/ram_context.tsv: a row is applied only if it covers `code` bytes exclusively, starts on an instruction boundary and ends on
        one (or at the inline bytes of a convention call, or at the end of its region); the claim is then attached to each instruction start
        inside it.  A row that violates this is *stale* (the region table changed after tools/rambank_infer.py ran): it is ignored with a
        warning (an error under --strict) so that a region edit can never break generation, and it never produces a name."""
        for c in self.cfg.ram_context:
            regs = [r for r in self.regions[c.bank] if r.start < c.end and c.start < r.end]
            bad = next((r for r in regs if r.kind != 'code'), None)
            if bad is not None:
                self.diag.warn(c.loc, 'stale context ignored: range %02X:%04X-%04X covers the %s region %04X-%04X (contexts apply to `code` regions only; re-run tools/rambank_infer.py)'
                               % (c.bank, c.start, c.end, bad.kind, bad.start, bad.end))
                continue
            bound = self.bound[c.bank]
            last = self.region_at(c.bank, c.end - 1)
            if c.start not in bound:
                self.diag.warn(c.loc, 'stale context ignored: range %02X:%04X-%04X does not start on an instruction boundary (re-run tools/rambank_infer.py)'
                               % (c.bank, c.start, c.end))
                continue
            if c.end not in bound and c.end not in self.inline_cover[c.bank] and not (last is not None and c.end == last.end):
                self.diag.warn(c.loc, 'stale context ignored: range %02X:%04X-%04X does not end on an instruction boundary (re-run tools/rambank_infer.py)'
                               % (c.bank, c.start, c.end))
                continue
            for r in regs:
                for sa, it in self.insns[(c.bank, r.idx)]:
                    if it.flow == 'inline' or not (c.start <= sa < c.end):
                        continue
                    w0, s0, ws0, ss0 = self.ctx_at.get((c.bank, sa), (None, None, '', ''))
                    self.ctx_at[(c.bank, sa)] = (c.wram if c.wram is not None else w0, c.sram if c.sram is not None else s0,
                                                 c.status if c.wram is not None else ws0, c.status if c.sram is not None else ss0)

    def ram_expr(self, addr: int) -> Optional[Tuple[str, int]]:
        """Name expression for a RAM address from config/ram: (text, value) or None."""
        v = self.ram_exact.get(addr)
        if v is not None:
            return v.name, addr
        i = bisect.bisect_right(self._ram_starts, addr) - 1
        while i >= 0:
            v = self.ram_sorted[i]
            if v.addr <= addr < v.addr + v.size:
                return '%s + %d' % (v.name, addr - v.addr), addr
            if v.addr + self._ram_maxsize <= addr:      # nothing that far away can enclose it
                break
            i -= 1
        return None

    # ----------------------------------------------------------------- labels
    def add_label(self, bank: int, addr: int, name: str, origin: str, loc: str):
        r = self.region_at(bank, addr)
        if r is None:
            self.diag.error(loc, 'label %s: address %02X:%04X is outside the bank window' % (name, bank, addr))
            return
        cov = self.inline_cover[bank].get(addr)
        if cov is not None and not cov[1]:
            self.diag.error(loc, 'label %s at %02X:%04X is inside the inline data of the convention call at %02X:%04X: '
                            'inline bytes are data, nothing can be labelled there' % (name, bank, addr, bank, cov[0]))
            return
        if r.kind in ('code', 'ramcode') and addr not in self.bound[bank]:
            self.diag.error(loc, 'label %s at %02X:%04X is not on an instruction boundary of the %s region %04X-%04X '
                            '(split the region or fix the address)' % (name, bank, addr, r.kind, r.start, r.end))
            return
        if r.kind in ('words', 'ptrtable') and (addr - r.start) % 2:
            self.diag.error(loc, 'label %s at %02X:%04X is not word-aligned inside the %s region %04X-%04X'
                            % (name, bank, addr, r.kind, r.start, r.end))
            return
        prev = self.name_loc.get(name)
        if prev is not None:
            if prev == (bank, addr):
                return
            self.diag.error(loc, 'label collision: name %s already used (%s)%s' % (
                name, {'const': 'const symbol', 'ram': 'RAM variable'}.get(prev[0]) or self.cite(*prev),
                '; overlays of one bank sharing a runaddr need distinct symbols' if origin == 'generic' else ''))
            return
        ra = self.run_addr(bank, addr)
        m = mtcfg.GENERIC.match(name)
        if m and origin != 'generic' and (int(m.group(2), 16), int(m.group(3), 16)) != (bank, ra):
            self.diag.error(loc, 'name %s looks like a generic name for %s:%s but labels %02X:%04X; '
                            'use a different name or the matching address' % (name, m.group(2), m.group(3), bank, ra))
            return
        self.name_loc[name] = (bank, addr)
        self.name_val[name] = ra
        self.labels[bank].setdefault(addr, []).append(Label(name, origin, loc))

    def _collect_labels(self):
        for b in range(self.nbanks):
            for s in self.cfg.symbols.get(b, ()):
                if s.type == 'const':
                    if s.name in self.name_loc:
                        self.diag.error(s.loc, 'name %s already used' % s.name)
                        continue
                    self.name_loc[s.name] = ('const',)
                    self.consts.append(s)
                else:
                    self.add_label(b, s.addr, s.name, 'symbol', s.loc)
        for b in range(self.nbanks):
            for r in self.regions[b]:
                if r.label:
                    self.add_label(b, r.start, r.label, 'region', r.loc)

    def named_at(self, loc) -> Optional[str]:
        for lab in self.labels[loc[0]].get(loc[1], ()):
            if lab.origin != 'generic':
                return lab.name
        return None

    def name_at(self, loc) -> Optional[str]:
        labs = self.labels[loc[0]].get(loc[1])
        return labs[0].name if labs else None

    def has_label(self, loc) -> bool:
        return loc[1] in self.labels[loc[0]]

    # ------------------------------------------------------------ target rules
    def resolve_target(self, src_bank: int, src: Region, target: int) -> Optional[Tuple[int, int]]:
        """Map a CPU address referenced from `src` to ROM coordinates (bank, storage address), or None.

        ROM0 is always bank 0; ROMX addresses belong to the referencing bank when it is itself a
        ROMX bank (code in bank N cannot switch itself away); a reference from ROM0 or from RAM code
        into 4000-7FFF has no defined bank.  RAM addresses resolve only into a unique ramcode region.
        """
        if src.kind == 'ramcode' and src.runaddr <= target < src.run_end:
            return src_bank, src.start + (target - src.runaddr)
        if target < 0x8000:
            if target < 0x4000:
                loc = (0, target)
            elif src_bank != 0 and src.kind != 'ramcode':
                loc = (src_bank, target)
            else:
                return None
            r = self.region_at(*loc)
            if r is not None and r.kind == 'ramcode':
                return None        # bytes stored here run elsewhere: the ROM address is not a label
            return loc
        hits = self.ram_targets(target)
        if len(hits) == 1:
            h = hits[0]
            return h.bank, h.start + (target - h.runaddr)
        return None

    def _want(self, loc, kind: str, force: bool = False, where: str = '') -> bool:
        tb, ta = loc
        if self.has_label(loc):
            return True
        r = self.region_at(tb, ta)
        if r is None:
            return False
        if r.kind in ('code', 'ramcode'):
            if ta in self.bound[tb]:
                self.want[loc].add(kind)
                return True
            self.stats['targets_mid_instruction'] += 1
            return False
        if force:
            if r.kind in ('words', 'ptrtable') and (ta - r.start) % 2:
                self.diag.error(where, 'xref target %02X:%04X is not word-aligned inside its %s region' % (tb, ta, r.kind))
                return False
            self.want[loc].add(kind)
            return True
        return False

    def _insn_at(self, bank: int, addr: int):
        r = self.region_at(bank, addr)
        if r is None or r.kind not in ('code', 'ramcode') or addr not in self.bound[bank]:
            return None, None
        lst = self.insns[(bank, r.idx)]
        i = bisect.bisect_left(lst, addr, key=lambda t: t[0])
        return r, lst[i][1]

    def _resolve_xrefs(self):
        for x in self.cfg.xrefs:
            where = x.loc
            key = (x.bank, x.addr, x.kind)
            if key in self.xref:
                self.diag.error(where, 'duplicate xref for %02X:%04X %s' % (x.bank, x.addr, x.kind))
                continue
            value = None
            kind = 'imm'
            if x.kind == 'word':
                r = self.region_at(x.bank, x.addr)
                slot = self.inline_slots.get((x.bank, x.addr))
                if slot == 'inline_dw':
                    o = x.bank * BANK_SIZE + (x.addr - mtcfg.window(x.bank)[0])
                    value = self.rom[o] | (self.rom[o + 1] << 8)
                elif slot == 'farptr':
                    self.diag.error(where, 'xref word: %02X:%04X is the pointer of a farptr convention slot; it is labelled '
                                    'automatically when a label exists at exactly (bank byte, address)' % (x.bank, x.addr))
                    continue
                elif r is None or r.kind not in ('words', 'ptrtable') or (x.addr - r.start) % 2:
                    self.diag.error(where, 'xref word: %02X:%04X is not a word slot of a words/ptrtable region '
                                    'or an inline_dw convention slot' % (x.bank, x.addr))
                    continue
                else:
                    value = self.rom[r.off + (x.addr - r.start)] | (self.rom[r.off + (x.addr - r.start) + 1] << 8)
            else:
                r, ins = self._insn_at(x.bank, x.addr)
                if ins is None:
                    self.diag.error(where, 'xref: no instruction starts at %02X:%04X (stale xref?)' % (x.bank, x.addr))
                    continue
                if x.kind == 'branch':
                    value = ins.target
                    kind = 'call' if ins.flow in CALL_FLOWS else 'jump'
                elif x.kind == 'imm' and ins.imm16_kind == 'imm':
                    value = ins.imm16
                elif x.kind == 'mem' and ins.imm16_kind == 'mem':
                    value = ins.imm16
                if value is None:
                    self.diag.error(where, 'xref: instruction at %02X:%04X (%s) has no %s operand' % (
                        x.bank, x.addr, ins.text(), x.kind))
                    continue
            if x.taddr != value:
                self.diag.error(where, 'xref target address $%04X differs from the operand value $%04X at %02X:%04X: '
                                'a name must not change bytes' % (x.taddr, value, x.bank, x.addr))
                continue
            if x.tbank == 'RAM':
                ex = self.ram_expr(x.taddr)
                if ex is None:
                    self.diag.error(where, 'xref target RAM $%04X has no name in config/ram' % x.taddr)
                    continue
                self.xref[key] = ('ram', ex)
                continue
            if x.taddr >= 0x8000:
                hits = [h for h in self.ram_targets(x.taddr) if h.bank == x.tbank]
                if len(hits) != 1:
                    self.diag.error(where, 'xref target $%04X: expected exactly one ramcode region in bank %02X, found %d'
                                    % (x.taddr, x.tbank, len(hits)))
                    continue
                loc = (x.tbank, hits[0].start + (x.taddr - hits[0].runaddr))
            else:
                lo, hi = mtcfg.window(x.tbank)
                if not lo <= x.taddr < hi:
                    self.diag.error(where, 'xref target $%04X is not inside bank %02X window' % (x.taddr, x.tbank))
                    continue
                loc = (x.tbank, x.taddr)
            if self.run_addr(*loc) != x.taddr:
                self.diag.error(where, 'xref target %02X:%04X is stored in a ramcode region that runs at $%04X, not $%04X'
                                % (loc[0], loc[1], self.run_addr(*loc), x.taddr))
                continue
            if not self._want(loc, kind, True, where):
                self.diag.error(where, 'xref target %02X:%04X cannot be labelled (mid-instruction?)' % loc)
                continue
            self.xref[key] = ('loc', loc)
            self.stats['xrefs'] += 1

    def _check_xref_targets(self):
        for key, val in self.xref.items():
            if val[0] == 'loc' and not self.has_label(val[1]):
                raise GenError('internal: xref target %02X:%04X has no label' % val[1])

    def _collect_refs(self):
        for (b, ridx), lst in self.insns.items():
            r = self.regions[b][ridx]
            for sa, ins in lst:
                if ins.flow == 'inline':
                    self._collect_inline(b, ins)
                    continue
                if ins.target is None or (b, sa, 'branch') in self.xref:
                    continue
                loc = self.resolve_target(b, r, ins.target)
                if loc is None:
                    self.stats['branches_unresolved_bank'] += 1
                    continue
                self._want(loc, 'call' if ins.flow in CALL_FLOWS else 'jump')
        for (b, _e), it in sorted(self.inline_adopt.items()):
            self._collect_inline(b, it)
        for b in range(self.nbanks):
            for r in self.regions[b]:
                if r.kind != 'ptrtable':
                    continue
                for i in range(0, r.size, 2):
                    if (b, r.start + i, 'word') in self.xref:
                        continue
                    v = self.rom[r.off + i] | (self.rom[r.off + i + 1] << 8)
                    if v == 0:
                        continue        # $0000 is far more likely a null/empty slot than a pointer to 00:0000 (xref word forces it)
                    loc = self.resolve_target(b, r, v)
                    if loc is not None:
                        self._want(loc, 'ptr')

    MACRO_NAMES = ('farcall', 'farcall_raw', 'FARCALL_FN')     # macros / EQUS of constants/macros.inc + ram.inc (one namespace with labels)

    def _check_macro_names(self):
        """With macros on, no label, constant or RAM name may be one of MACRO_NAMES: rgbasm keeps macros, EQUS and labels in one
        symbol namespace, so the clash would only surface later as an rgbasm error in every bank (found by the verifier)."""
        if not self.macros:
            return
        for b in range(self.nbanks):
            for s in self.cfg.symbols.get(b, ()):
                if s.name in self.MACRO_NAMES:
                    self.diag.error(s.loc, 'name %r collides with a farcall macro of constants/macros.inc (rename it or use --no-macros)' % s.name)
        for v in list(self.cfg.ram) + list(self.cfg.ram_banked):
            if v.name in self.MACRO_NAMES:
                self.diag.error(v.loc, 'name %r collides with a farcall macro of constants/macros.inc (rename it or use --no-macros)' % v.name)

    def farcall_conv(self):
        """(convention, entry label name) of THE far call the `farcall` macros stand for, or None: macros are on, there
        is exactly one `farptr` convention in config/conventions.tsv and its entry has a label (the macro calls
        that label through the FARCALL_FN EQUS of ram.inc, so the name is never hard-coded)."""
        if self._fc is False:
            self._fc = None
            fcs = [c for c in self.cfg.conventions if c.layout == 'farptr']
            if self.macros and len(fcs) == 1:
                nm = self.name_at((fcs[0].bank, fcs[0].addr))
                if nm is not None and self.name_val.get(nm) == fcs[0].addr and fcs[0].bank == 0:
                    self._fc = (fcs[0], nm)
        return self._fc

    def far_loc(self, w: int, bb: int) -> Optional[Tuple[int, int]]:
        """ROM location (bank, address) a far pointer `dw w ; db bb` designates, or None when it does not name a
        ROM location: bank byte 0 = ROM0 (address must be < $4000), otherwise the address must lie in the window of
        ROM bank `bb` (a `$8000+` address selects a WRAM/SRAM bank, not a ROM bank).  Never a ramcode region: its
        ROM bytes run elsewhere and BANK() of a label inside a LOAD block is the RAM section's bank."""
        if bb >= self.nbanks:
            return None
        if bb == 0:
            if w >= 0x4000:
                return None
        elif not mtcfg.window(bb)[0] <= w < mtcfg.window(bb)[1]:
            return None
        r = self.region_at(bb, w)
        if r is None or r.kind == 'ramcode':
            return None
        return (bb, w)

    def _collect_inline(self, b: int, it: conv.InlineData):
        if it.conv.layout == 'farptr':
            loc = self.far_loc(it.word, it.raw[2])
            self.stats['inline_far_targets_unresolved' if loc is None else 'inline_far_targets'] += 1
            if loc is not None:
                self._want(loc, 'call')

    def _finalize_labels(self):
        for loc in sorted(self.want):
            tb, ta = loc
            if self.has_label(loc):
                continue
            r = self.region_at(tb, ta)
            kinds = self.want[loc]
            if r.kind in ('code', 'ramcode'):
                prefix = 'Function' if 'call' in kinds else 'Label'
            elif r.kind in ('words', 'ptrtable'):
                prefix = 'Table'
            elif r.kind == 'text':
                prefix = 'String'
            else:
                prefix = 'Data'
            name = '%s_%02X_%04X' % (prefix, tb, self.run_addr(tb, ta))
            self.add_label(tb, ta, name, 'generic', '')
            self.stats['generic_' + prefix] += 1
        self.diag.raise_if_errors()

    # ------------------------------------------------------------- operands
    def _hw_name(self, addr: int) -> Optional[Tuple[str, int]]:
        n = self.hw.io.get(addr)
        if n is not None:
            return n, addr
        if 0xFF30 < addr <= 0xFF3F and self.hw.io.get(0xFF30) == '_AUD3WAVERAM':
            return '_AUD3WAVERAM + %d' % (addr - 0xFF30), addr
        return None

    def _substitute(self, text: str, val: int, want: int, what: str) -> str:
        if val != want:
            raise GenError('internal: %s %s has value $%04X but the operand is $%04X' % (what, text, val, want))
        return text

    def render_insn(self, r: Region, sa: int, ins: sm83.Insn) -> str:
        b = r.bank
        st = self.stats

        def branch(t):
            x = self.xref.get((b, sa, 'branch'))
            if x is not None:
                loc = x[1]
            else:
                loc = self.resolve_target(b, r, t)
                if loc is None:
                    return None
            nm = self.name_at(loc)
            if nm is None:
                st['targets_unlabelled'] += 1
                return None
            st['branch_labels'] += 1
            return self._substitute(nm, self.name_val[nm], t, 'label')

        def imm16(v, kind):
            x = self.xref.get((b, sa, 'imm' if kind == 'imm' else 'mem'))
            if x is not None:
                if x[0] == 'ram':
                    st['xref_ram'] += 1
                    return self._substitute(x[1][0], x[1][1], v, 'ram name')
                nm = self.name_at(x[1])
                st['xref_labels'] += 1
                return self._substitute(nm, self.name_val[nm], v, 'label')
            if kind != 'mem':
                return None
            return self._mem_name(v, ins.fmt == 'ld [{i}], a', ctx=(b, sa))      # MBC names only for `ld [a16], a` (never `ld [a16], sp`)

        def hram(v):
            return self._mem_name(v, False, ldh=True)

        if ins.flow == 'rst':       # sm83 prints rst vectors numerically; use the label of the vector when there is one
            nm = branch(ins.target)
            return 'rst ' + nm if nm else ins.text()
        return ins.text(branch, imm16, hram)

    def _banked_name(self, addr: int, ctx) -> Optional[Tuple[str, int]]:
        """Bank-qualified name for an access at instruction `ctx` = (rom bank, storage addr), only when a context range declares
        the WRAM bank (addr in $D000-$DFFF) or the SRAM bank (addr in $A000-$BFFF) and a banked name of that bank covers addr."""
        if ctx is None or not self.banked:
            return None
        cx = self.ctx_at.get(ctx)
        if cx is None:
            return None
        if 0xD000 <= addr < 0xE000 and cx[0] is not None:
            e = self.banked_expr('w', cx[0], addr)
            st = cx[2]
        elif 0xA000 <= addr < 0xC000 and cx[1] is not None:
            e = self.banked_expr('s', cx[1], addr)
            st = cx[3]
        else:
            return None
        if e is not None:
            # independent re-evaluation of the expression from the row table (a name never changes the operand's value)
            m = re.fullmatch(r'([A-Za-z_][A-Za-z0-9_]*)(?: \+ (\d+))?', e[0])
            row = self.banked_by_name.get(m.group(1)) if m else None
            if row is None or row.addr + int(m.group(2) or 0) != addr:
                raise GenError('internal: banked name %s does not evaluate to $%04X' % (e[0], addr))
            self.stats['banked_names'] += 1
            self.stats['banked_names_' + st.lower()] += 1
        return e

    def _mem_name(self, addr: int, write: bool, ldh: bool = False, ctx=None) -> Optional[str]:
        st = self.stats
        if 0xFF00 <= addr <= 0xFF7F or addr == 0xFFFF:
            h = self._hw_name(addr)
            if h is not None:
                st['hw_names'] += 1
                return self._substitute(h[0], h[1], addr, 'hardware name')
        if write and not ldh and addr in self.hw.mbc:
            st['mbc_names'] += 1
            return self._substitute(self.hw.mbc[addr], addr, addr, 'MBC name')
        if addr >= 0x8000:
            e = self._banked_name(addr, ctx)
            if e is not None:
                return self._substitute(e[0], e[1], addr, 'banked ram name')
            e = self.ram_expr(addr)
            if e is not None:
                st['ram_names'] += 1
                return self._substitute(e[0], e[1], addr, 'ram name')
        return None

    def word_name(self, r: Region, addr: int, v: int) -> Optional[str]:
        """Symbol/label for a dw value in a words/ptrtable region (or None -> numeric)."""
        x = self.xref.get((r.bank, addr, 'word'))
        if x is not None:
            if x[0] == 'ram':
                return self._substitute(x[1][0], x[1][1], v, 'ram name')
            nm = self.name_at(x[1])
            return self._substitute(nm, self.name_val[nm], v, 'label')
        if v == 0:
            return None                 # never turn a null/empty slot into a label without an explicit xref word row
        loc = self.resolve_target(r.bank, r, v)
        if loc is None:
            return None
        nm = self.name_at(loc) if r.kind == 'ptrtable' else self.named_at(loc)
        if nm is None:
            return None
        self.stats['word_labels'] += 1
        return self._substitute(nm, self.name_val[nm], v, 'label')

    # ------------------------------------------------------------- line checks
    def _tok(self, t: str) -> int:
        t = t.strip()
        if t.startswith('$'):
            return int(t[1:], 16)
        m = re.fullmatch(r'BANK\(([A-Za-z_][A-Za-z0-9_]*)\)', t)
        if m:           # the ROM bank a label is stored in; only exact for labels outside LOAD blocks
            loc = self.name_loc.get(m.group(1))
            r = self.region_at(*loc) if loc and loc[0] not in ('const', 'ram') else None
            if r is None or r.kind == 'ramcode':
                raise GenError('internal: BANK(%s) is not a ROM label' % m.group(1))
            return loc[0]
        if t in self.name_val:
            return self.name_val[t]
        raise GenError('internal: cannot evaluate %r' % t)

    def verify_line(self, text: str, claim: bytes, absoff: int):
        text = text.split(' ;', 1)[0]
        if text.startswith('\tfarcall'):
            fc = self.farcall_conv()
            if fc is None:
                raise GenError('internal: %r without a far-call convention' % text)
            m = re.fullmatch(r'\tfarcall ([A-Za-z_][A-Za-z0-9_]*)', text)
            if m:
                args = [self._tok(m.group(1)), self._tok('BANK(%s)' % m.group(1))]
            else:
                m = re.fullmatch(r'\tfarcall_raw (\$[0-9A-F]{4}), (\$[0-9A-F]{2})', text)
                if not m:
                    raise GenError('internal: bad farcall line %r' % text)
                args = [self._tok(m.group(1)), self._tok(m.group(2))]
            got = b'\xCD' + fc[0].addr.to_bytes(2, 'little') + args[0].to_bytes(2, 'little') + bytes([args[1]])
        elif text.startswith('\tdb '):
            got = bytes(self._tok(t) for t in text[4:].split(','))
        elif text.startswith('\tdw '):
            got = b''.join(self._tok(t).to_bytes(2, 'little') for t in text[4:].split(','))
        elif text.startswith('\tds '):
            m = re.fullmatch(r'\tds \$([0-9A-F]+), \$([0-9A-F]{2})', text)
            if not m:
                raise GenError('internal: bad ds line %r' % text)
            got = bytes([int(m.group(2), 16)]) * int(m.group(1), 16)
        elif text.startswith('\tINCBIN '):
            m = re.fullmatch(r'\tINCBIN "([^"]+)", \$([0-9A-F]+), \$([0-9A-F]+)', text)
            if not m or m.group(1) != self.incbin:
                raise GenError('internal: bad INCBIN line %r' % text)
            off, n = int(m.group(2), 16), int(m.group(3), 16)
            if off != absoff:
                raise GenError('internal: INCBIN offset $%X but bank position is $%X' % (off, absoff))
            got = self.rom[off:off + n]
        else:
            return
        if got != claim:
            raise GenError('internal: line %r does not round-trip to the ROM bytes' % text)

    # ---------------------------------------------------------------- emission
    def _label_lines(self, out: BankOut, r: Region, addr: int):
        labs = self.labels[r.bank].get(addr)
        if not labs:
            return
        out.line('')
        cite = '%02X:%04X' % (r.bank, addr)
        if r.kind == 'ramcode':
            cite += ' (runs at $%04X)' % self.run_addr(r.bank, addr)
        for i, lab in enumerate(labs):
            out.line('%s::%s' % (lab.name, ' ; ' + cite if i == 0 and self.addr_comments else ''))

    def _segments(self, r: Region, extra=(), a: Optional[int] = None, z: Optional[int] = None) -> List[Tuple[int, int]]:
        """Pieces of r[a:z] (default: the whole region) cut at every label and at the `extra` addresses."""
        a = r.start if a is None else a
        z = r.end if z is None else z
        la = self.label_addrs.get(r.bank)
        if la is None:
            la = sorted(self.labels[r.bank])
        lo = bisect.bisect_right(la, a)
        hi = bisect.bisect_left(la, z)
        pts = sorted({a, z, *la[lo:hi], *(e for e in extra if a < e < z)})
        return list(zip(pts, pts[1:]))

    def inline_lines(self, bank: int, it: conv.InlineData) -> List[Tuple[str, bytes]]:
        """(text, bytes) lines for the inline bytes after a convention call."""
        raw, lay = it.raw, it.conv.layout
        if lay == 'farptr':
            w, bb = it.word, raw[2]
            loc = self.far_loc(w, bb)
            nm = self.name_at(loc) if loc is not None else None
            if nm is not None:
                # a label at exactly (bank byte, address): rgbasm/rgblink compute both bytes, the compare proves them
                self._substitute(nm, self.name_val[nm], w, 'label')
                if self.name_loc[nm] != loc:
                    raise GenError('internal: label %s is at %s, not at the far pointer target %s' % (
                        nm, self.cite(*self.name_loc[nm]), self.cite(*loc)))
                self.stats['inline_far_labelled'] += 1
                return [('dw ' + nm, raw[:2]), ('db BANK(%s)' % nm, raw[2:3])]
            return [('dw ' + hexw(w), raw[:2]), ('db ' + hexb(bb), raw[2:3])]
        if lay == 'inline_dw':
            x = self.xref.get((bank, it.slot, 'word'))
            if x is not None:       # explicit `xref word` row: the analyst says which bank the word means
                if x[0] == 'ram':
                    return [('dw ' + self._substitute(x[1][0], x[1][1], it.word, 'ram name'), raw)]
                nm = self.name_at(x[1])
                return [('dw ' + self._substitute(nm, self.name_val[nm], it.word, 'label'), raw)]
            return [('dw ' + hexw(it.word), raw)]
        if lay == 'inline_db':
            return [('db ' + hexb(raw[0]), raw)]
        raise GenError('internal: unhandled inline layout %s' % lay)

    def _emit_db(self, out: BankOut, chunk: bytes):
        for i in range(0, len(chunk), 16):
            part = chunk[i:i + 16]
            out.emit('\tdb ' + ', '.join(hexb(x) for x in part), part)

    def text_spec(self, r: Region) -> Tuple[str, str]:
        """(charset, layout) of a text region: config/text_charsets.tsv row containing its start, else sjis/nul."""
        for sp in self.cfg.textspecs:
            if sp.bank == r.bank and sp.start <= r.start < sp.end:
                if r.end > sp.end:
                    raise GenError('%s: text region %02X:%04X-%04X crosses the end of the text_charsets row %s' % (
                        r.loc, r.bank, r.start, r.end, sp.loc))
                return sp.charset, sp.layout
        return 'sjis', 'nul'

    def _emit_text(self, out: BankOut, r: Region, a: int, z: int):
        charset, layout = self.text_spec(r)
        key = (r.bank, r.idx)
        tab = self._text_items.get(key)
        data = self.bytes_of(r)
        if tab is None:
            tab = self._text_items[key] = textfmt.items(data, layout)
        for txt, claim in textfmt.render(data, layout, charset, a - r.start, z - r.start, self.text_comments, tab):
            out.emit('\t' + txt, claim)
            self.stats['text_lines'] += 1

    def _emit_words(self, out: BankOut, r: Region, a: int, z: int):
        per = 1 if r.kind == 'ptrtable' else 8
        vals = []
        for addr in range(a, z, 2):
            o = r.off + (addr - r.start)
            v = self.rom[o] | (self.rom[o + 1] << 8)
            vals.append((addr, v, self.word_name(r, addr, v) or hexw(v)))
        for i in range(0, len(vals), per):
            part = vals[i:i + per]
            claim = b''.join(v.to_bytes(2, 'little') for _, v, _ in part)
            out.emit('\tdw ' + ', '.join(t for _, _, t in part), claim)

    def _emit_region(self, out: BankOut, r: Region, a: Optional[int] = None, z: Optional[int] = None):
        """Emit the region, or its piece [a, z) (tree mode cuts regions at file boundaries; the caller has checked that
        the cuts are legal: instruction boundaries, outside inline data, not inside ramcode)."""
        a = r.start if a is None else a
        z = r.end if z is None else z
        hdr = '; ---- %s $%04X-$%04X (%d bytes)' % (r.kind, a, z, z - a) if self.addr_comments else '; ---- %s (%d bytes)' % (r.kind, z - a)
        if r.gap:
            hdr += ' [unclassified gap]'
        else:
            if r.status:
                hdr += ' [%s]' % r.status
            if r.note:
                hdr += ' %s' % r.note
        if (a, z) != (r.start, r.end):
            hdr += ' (part of region $%04X-$%04X)' % (r.start, r.end) if self.addr_comments else ' (part of a larger region)'
        out.line('')
        out.line(hdr)
        if r.kind == 'text' and self.text_comments and self.text_spec(r)[0] == 'halfwidth':
            out.line('; text comments (halfwidth): display only, A1-DF shown as half-width katakana, glyphs unproven (text_encoding.md section 6)')
        if r.kind in ('code', 'ramcode'):
            if r.kind == 'ramcode' and (a, z) != (r.start, r.end):
                raise GenError('internal: ramcode region %02X:%04X-%04X cannot be split' % (r.bank, r.start, r.end))
            self._emit_code(out, r, a, z)
            return
        adopt = self.inline_adopt.get((r.bank, r.start)) if r.kind == 'data' and a == r.start else None
        if adopt is not None:
            out.line('; inline %s bytes of the convention call%s (config/conventions.tsv, docs/FORMATS.md)' % (
                adopt.conv.layout, ' at %02X:%04X' % (r.bank, adopt.site) if self.addr_comments else ''))
        for sa, sz in self._segments(r, (r.start + adopt.length,) if adopt is not None else (), a, z):
            self._label_lines(out, r, sa)
            chunk = self.rom[r.off + (sa - r.start):r.off + (sz - r.start)]
            if adopt is not None and sa == r.start:
                for txt, claim in self.inline_lines(r.bank, adopt):
                    out.emit('\t' + txt, claim)
                continue
            if r.kind == 'zero':
                out.emit('\tds $%X, $00' % len(chunk), chunk)
            elif r.kind == 'raw':
                absoff = out.bank * BANK_SIZE + out.pos
                out.emit('\tINCBIN "%s", $%X, $%X' % (self.incbin, absoff, len(chunk)), chunk)
            elif r.kind == 'text':
                self._emit_text(out, r, sa, sz)
            elif r.kind in ('data', 'gfx'):
                self._emit_db(out, chunk)
            elif r.kind in ('words', 'ptrtable'):
                self._emit_words(out, r, sa, sz)
            else:
                raise GenError('internal: unhandled kind %s' % r.kind)

    def _emit_code(self, out: BankOut, r: Region, a: Optional[int] = None, z: Optional[int] = None):
        if r.kind == 'ramcode':
            area = mtcfg.ram_area(r.runaddr, r.size)
            spec = '%s[$%04X]' % (area[2], r.runaddr)
            if r.runbank is not None:
                spec += ', BANK[%d]' % r.runbank
            un = self.union.get((r.bank, r.idx))
            if un:
                out.line('\tLOAD UNION "%s", %s' % (un, spec))
            else:
                out.line('\tLOAD "RAM_%02X_%04X", %s' % (r.bank, r.start, spec))
        items = self.insns[(r.bank, r.idx)]
        fc = self.farcall_conv()
        skip = -1
        k0, k1 = 0, len(items)
        if (a, z) != (None, None) and (a, z) != (r.start, r.end):      # a piece of the region (tree mode); cuts are on instruction starts
            k0 = bisect.bisect_left(items, a, key=lambda t: t[0])
            k1 = bisect.bisect_left(items, z, key=lambda t: t[0])
        for k in range(k0, k1):
            sa, ins = items[k]
            if k == skip:
                continue
            if fc is not None and ins.flow == 'call' and k + 1 < len(items) and items[k + 1][1].flow == 'inline' \
                    and items[k + 1][1].conv is fc[0] and \
                    self.render_insn(r, sa, ins) == 'call ' + fc[1]:
                self._label_lines(out, r, sa)
                it = items[k + 1][1]
                lines = self.inline_lines(r.bank, it)
                if lines[1][0].startswith('db BANK(') and lines[0][0].startswith('dw ') and lines[0][0][3:] == lines[1][0][8:-1]:
                    txt = 'farcall ' + lines[0][0][3:]
                    self.stats['farcall_macro'] += 1
                else:
                    txt = 'farcall_raw %s, %s' % (lines[0][0][3:], lines[1][0][3:])
                    self.stats['farcall_raw_macro'] += 1
                out.emit('\t' + txt, ins.raw + it.raw)
                skip = k + 1
                continue
            if ins.flow == 'inline':
                for txt, claim in self.inline_lines(r.bank, ins):
                    out.emit('\t' + txt, claim)
                if items[k - 1][1].flow in TERMINATORS:      # inline bytes after a `jp`: the blank line comes after them
                    out.line('')
                continue
            self._label_lines(out, r, sa)
            txt = self.render_insn(r, sa, ins)
            if ins.flow == 'bad':
                txt += ' ; illegal opcode'
            out.emit('\t' + txt, ins.raw)
            if ins.flow in TERMINATORS and not (k + 1 < len(items) and items[k + 1][1].flow == 'inline'):
                out.line('')
        if r.kind == 'ramcode':
            out.line('\tENDL')

    def bank_source(self, b: int) -> str:
        out = BankOut(self, b)
        out.line(GENERATED_HEADER)
        out.line('; bank %02X' % b)
        out.line('')
        out.line('INCLUDE "constants/hardware.inc"')
        out.line('INCLUDE "ram.inc"')
        if self.farcall_conv() is not None:
            out.line('INCLUDE "constants/macros.inc"')
        cs = self.cfg.symbols.get(b, [])
        cs = [s for s in cs if s.type == 'const']
        if cs:
            out.line('')
            for s in cs:
                out.line('DEF %s EQU $%04X ; %s %s' % (s.name, s.addr, s.status, s.evidence))
                out.line('EXPORT %s' % s.name)
        out.line('')
        if b == 0:
            out.line('SECTION "Bank%02X", ROM0[$0000]' % b)
        else:
            out.line('SECTION "Bank%02X", ROMX[$4000], BANK[$%02X]' % (b, b))
        for r in self.regions[b]:
            self._emit_region(out, r)
        if out.pos != BANK_SIZE:
            raise GenError('internal: bank %02X emitted %d bytes instead of %d' % (b, out.pos, BANK_SIZE))
        return '\n'.join(out.lines).rstrip('\n') + '\n'

    def ram_inc(self) -> str:
        lines = [GENERATED_HEADER,
                 '; RAM / SRAM / HRAM variable names from config/ram/*.tsv (addresses only, no bytes).', '']
        for v in sorted(self.cfg.ram, key=lambda v: (v.addr, v.name)):
            lines.append('DEF %s EQU $%04X ; size %d %s %s %s' % (v.name, v.addr, v.size, v.type, v.status, v.evidence))
        if self.cfg.ram_banked:
            lines += ['', '; bank-qualified names from config/ram_banked/*.tsv: the same CPU address is a different object in every WRAM/SRAM bank;',
                      '; the names below are substituted only where config/ram_context.tsv declares the bank (addresses only, no bytes).']
            for v in sorted(self.cfg.ram_banked, key=lambda v: (v.space, v.bank, v.addr, v.name)):
                lines.append('DEF %s EQU $%04X ; bank %s%d size %d %s %s %s' % (v.name, v.addr, v.space.upper(), v.bank, v.size, v.type, v.status, v.evidence))
        fc = self.farcall_conv()
        if fc is not None:
            lines += ['', '; label of the far-call convention entry %02X:%04X (config/conventions.tsv); the farcall macros of' % (fc[0].bank, fc[0].addr),
                      '; constants/macros.inc call it through this EQUS', 'DEF FARCALL_FN EQUS "%s"' % fc[1]]
        return '\n'.join(lines).rstrip('\n') + '\n'

    def generate(self) -> Dict[str, str]:
        files = {'ram.inc': self.ram_inc()}
        for b in range(self.nbanks):
            files['bank%02x.asm' % b] = self.bank_source(b)
        return files


    # ------------------------------------------------------------------ tree mode
    # Files organised by subsystem (layout table), FLOATING sections (no address in the source), pinned to the original
    # addresses by an rgblink linker script.  docs/FORMATS.md, "Tree mode".

    def _cut_error(self, row, bank: int, x: int) -> Optional[str]:
        """Why the ROM address bank:x cannot be a file boundary, or None when it can."""
        cov = self.inline_cover[bank].get(x)
        if cov is not None:
            site = cov[0]
            end = x
            while self.inline_cover[bank].get(end, (None,))[0] == site:
                end += 1
            return ('%02X:%04X is inside the inline data of the convention call at %02X:%04X (or splits the call from its data): '
                    'a farcall and its bytes must stay in one file; move the cut to $%04X or before the call at $%04X'
                    % (bank, x, bank, site, end, site))
        r = self.region_at(bank, x)
        if r is None or r.start == x:
            return None
        if r.kind == 'ramcode':
            return ('%02X:%04X is inside the ramcode region %04X-%04X: RAM code stays one LOAD block; '
                    'cut at $%04X or at $%04X' % (bank, x, r.start, r.end, r.start, r.end))
        if r.kind == 'code' and x not in self.bound[bank]:
            items = self.insns[(bank, r.idx)]
            i = bisect.bisect_right(items, x, key=lambda t: t[0]) - 1
            sa, ins = items[i]
            return ('%02X:%04X is not an instruction boundary: it is inside %s at $%04X (%d bytes); '
                    'cut at $%04X or at $%04X' % (bank, x, ins.text() if ins.flow != 'inline' else 'inline data', sa, ins.length, sa, sa + ins.length))
        if r.kind in ('words', 'ptrtable') and (x - r.start) % 2:
            return ('%02X:%04X is not word-aligned inside the %s region %04X-%04X: cut at $%04X or at $%04X'
                    % (bank, x, r.kind, r.start, r.end, x - 1, x + 1))
        return None

    def tree_plan(self, lay: 'layoutlib.Layout'):
        """Check a layout against the ROM and the region table (all problems are reported together):
        every byte is covered by a row or is 0x00 and uncovered; every row boundary is a legal cut; no
        LOAD block lies in an uncovered range.  Returns the sections of `zero_labels.asm`: one per label that lies inside an uncovered
        all-zero range (from the label to the next label / the end of its region / the end of the range)."""
        diag = Diag()
        spans: List['layoutlib.Section'] = []
        for b in range(self.nbanks):
            lo, hi = mtcfg.window(b)
            rows = lay.rows.get(b, [])
            cuts = set()
            for row in rows:
                cuts.add((row.start, row))
                cuts.add((row.end, row))
            for x, row in sorted(cuts, key=lambda t: (t[0], t[1].start)):
                if x in (lo, hi):
                    continue
                msg = self._cut_error(row, b, x)
                if msg:
                    diag.error(row.loc, 'layout cut %s' % msg)
            pos = lo
            gaps = []
            for row in rows:
                if row.start > pos:
                    gaps.append((pos, row.start))
                pos = row.end
            if pos < hi:
                gaps.append((pos, hi))
            la = sorted(self.labels[b])
            for g0, g1 in gaps:
                blob = self.rom[b * BANK_SIZE + (g0 - lo):b * BANK_SIZE + (g1 - lo)]
                if any(blob):
                    at = g0 + next(i for i, v in enumerate(blob) if v)
                    diag.error(lay.source, 'uncovered non-zero byte at %02X:%04X (range %02X:%04X-%04X is not covered by any layout row and is not all 0x00)'
                               % (b, at, b, g0, g1))
                    continue
                i = bisect.bisect_left(la, g0)
                while i < len(la) and la[i] < g1:            # a label in an uncovered zero range still needs a home (see zero_labels.asm)
                    a = la[i]
                    j = bisect.bisect_right(la, a)
                    z = min(la[j] if j < len(la) else g1, self.region_at(b, a).end, g1)
                    spans.append(layoutlib.Section('zero_labels.asm', b, a, z, []))
                    i = j
                for r in self.regions[b]:
                    if r.kind == 'ramcode' and r.start < g1 and g0 < r.end:
                        diag.error(lay.source, 'ramcode region %02X:%04X-%04X overlaps the uncovered range %04X-%04X: cover it with a layout row'
                                   % (b, r.start, r.end, g0, g1))
        diag.raise_if_errors()
        return spans

    def _tree_section_text(self, s: 'layoutlib.Section') -> List[str]:
        b = s.bank
        base = mtcfg.window(b)[0]
        out = BankOut(self, b)
        out.pos = s.start - base
        out.line('SECTION "%s", %s' % (s.name, 'ROM0' if b == 0 else 'ROMX'))
        if self.addr_comments:
            out.line('; ROM %02X:%04X-%04X (%d bytes); the linker script (layout.link) pins this section there' % (b, s.start, s.end, s.size))
        regs = self.regions[b]
        prev_note = ''
        for row in (s.rows or [layoutlib.Row(b, s.start, s.end, s.path, '', '')]):
            if row.note and row.note != prev_note:
                out.line('')
                out.line('; %s' % row.note)
            prev_note = row.note
            i = bisect.bisect_right(regs, row.start, key=lambda r: r.end)     # first region ending after row.start
            while i < len(regs) and regs[i].start < row.end:
                r = regs[i]
                self._emit_region(out, r, max(r.start, row.start), min(r.end, row.end))
                i += 1
        if out.pos - 0 != s.end - base:
            raise GenError('internal: section %r emitted up to %04X instead of %04X' % (s.name, out.pos + base, s.end))
        return out.lines

    def ram_tree_files(self) -> Dict[str, str]:
        """ram.asm + ram/*.asm: the same DEF ... EQU lines as ram.inc, grouped by memory area (addresses only, no bytes)."""
        areas = [('ram/vram.asm', 'VRAM $8000-$9FFF', 0x8000, 0xA000), ('ram/sram.asm', 'SRAM $A000-$BFFF', 0xA000, 0xC000),
                 ('ram/wram.asm', 'WRAM $C000-$DFFF', 0xC000, 0xE000), ('ram/hram.asm', 'echo/OAM/IO/HRAM $E000-$FFFF', 0xE000, 0x10000)]
        files: Dict[str, str] = {}
        inc = []
        for path, title, lo, hi in areas:
            vs = sorted((v for v in self.cfg.ram if lo <= v.addr < hi), key=lambda v: (v.addr, v.name))
            if not vs:
                continue
            lines = [TREE_HEADER, '; %s variable names from config/ram/*.tsv (DEF ... EQU: addresses only, no bytes).' % title, '']
            lines += ['DEF %s EQU $%04X ; size %d %s %s %s' % (v.name, v.addr, v.size, v.type, v.status, v.evidence) for v in vs]
            files[path] = '\n'.join(lines) + '\n'
            inc.append('INCLUDE "%s"' % path)
        if self.cfg.ram_banked:
            lines = [TREE_HEADER, '; bank-qualified names from config/ram_banked/*.tsv: the same CPU address is a different object in every WRAM/SRAM bank;',
                     '; the names below are substituted only where config/ram_context.tsv declares the bank (addresses only, no bytes).', '']
            for v in sorted(self.cfg.ram_banked, key=lambda v: (v.space, v.bank, v.addr, v.name)):
                lines.append('DEF %s EQU $%04X ; bank %s%d size %d %s %s %s' % (v.name, v.addr, v.space.upper(), v.bank, v.size, v.type, v.status, v.evidence))
            files['ram/banked.asm'] = '\n'.join(lines) + '\n'
            inc.append('INCLUDE "ram/banked.asm"')
        lines = [TREE_HEADER, '; RAM / SRAM / HRAM variable names (equates only), one file per memory area under ram/.', ''] + inc
        fc = self.farcall_conv()
        if fc is not None:
            lines += ['', '; label of the far-call convention entry %02X:%04X (config/conventions.tsv); the farcall macros of' % (fc[0].bank, fc[0].addr),
                      '; constants/macros.inc call it through this EQUS', 'DEF FARCALL_FN EQUS "%s"' % fc[1]]
        files['ram.asm'] = '\n'.join(lines).rstrip('\n') + '\n'
        return files

    def generate_tree(self, lay: 'layoutlib.Layout', addr_comments: bool = True) -> Dict[str, str]:
        """Tree of source files for a layout: {relative path: text}.  Contains the layout files, includes.asm, ram.asm + ram/*.asm,
        consts.asm (const symbols, if any), padding.asm (only when the last ROM bank has no section), main.asm, layout.link,
        tree.mk (object list for make) and the manifest of the generated paths."""
        zspans = self.tree_plan(lay)
        self.addr_comments = addr_comments
        try:
            files: Dict[str, str] = {}
            order: List[str] = []              # object-producing files, in (bank, address) order of their first section
            for s in lay.sections:
                if s.path not in files:
                    files[s.path] = ''
                    order.append(s.path)
            for path in order:
                lines = [TREE_HEADER, '; %s' % path, '']
                for k, s in enumerate(lay.files[path]):
                    if k:
                        lines.append('')
                    if len(lay.files[path]) > 1:
                        lines.append('; ---- section %d of %d: bank %02X' % (k + 1, len(lay.files[path]), s.bank))
                    lines += self._tree_section_text(s)
                files[path] = '\n'.join(lines).rstrip('\n') + '\n'
            objs = list(order)
            if zspans:
                zspans.sort(key=lambda z: (z.bank, z.start))
                layoutlib.assign_names('zero_labels.asm', zspans)
                lines = [TREE_HEADER, '; zero_labels.asm', '; Labels that name bytes inside an all-zero range which the layout leaves uncovered (the linker pads it with 0x00).',
                         '; Each section holds only the zero bytes from the label to the next label / the end of its region / the end of the range,',
                         '; so the ROM is unchanged; give the range to a layout row to move these labels into a real file.']
                for k, z in enumerate(zspans):
                    lines.append('')
                    lines += self._tree_section_text(z)
                files['zero_labels.asm'] = '\n'.join(lines).rstrip('\n') + '\n'
                objs.append('zero_labels.asm')
            cs = [c for b in range(self.nbanks) for c in self.cfg.symbols.get(b, ()) if c.type == 'const']
            if cs:
                lines = [TREE_HEADER, '; numeric equates from config/symbols (type const); exported, never substituted into operands.', '']
                for c in cs:
                    lines.append('DEF %s EQU $%04X ; %s %s' % (c.name, c.addr, c.status, c.evidence))
                    lines.append('EXPORT %s' % c.name)
                files['consts.asm'] = '\n'.join(lines) + '\n'
                objs.append('consts.asm')
            last = self.nbanks - 1
            if last >= 1 and last not in lay.rows and not any(z.bank == last for z in zspans):
                files['padding.asm'] = '\n'.join([
                    TREE_HEADER,
                    '; The last ROM bank is entirely uncovered zero bytes.  rgblink sizes the ROM by the highest bank that holds a section',
                    '; (and pads it to the end of that bank), so one explicit 0x00 byte at the very end keeps the ROM at %d banks.' % self.nbanks,
                    'SECTION "padding", ROMX', '\tds 1, $00', ''])
                objs.append('padding.asm')
            for path, text in self.ram_tree_files().items():
                files[path] = text
            files['includes.asm'] = '\n'.join(
                [TREE_HEADER, '; Pre-included into every source file (rgbasm -P includes.asm, see the Makefile) and by main.asm.',
                 'INCLUDE "constants/hardware.inc"', 'INCLUDE "ram.asm"'] + (['INCLUDE "constants/macros.inc"'] if self.farcall_conv() is not None else [])) + '\n'
            files['main.asm'] = '\n'.join(
                [TREE_HEADER, '; The whole tree as one object:  rgbasm -I . -I <repo> -o main.o main.asm && rgblink -p 0x00 -l layout.link -o rom.gbc main.o',
                 '; (the Makefile assembles every file separately with `-P includes.asm`, which is equivalent and incremental).',
                 'INCLUDE "includes.asm"', ''] + ['INCLUDE "%s"' % p for p in objs]) + '\n'
            script = layoutlib.linker_script(lay.sections + zspans)
            if 'padding.asm' in files:
                script += '\nROMX $%02X\n\torg $7FFF\n\t"padding"\n' % last
            files['layout.link'] = script
            common = sorted(['includes.asm'] + [p for p in files if p == 'ram.asm' or p.startswith('ram/')])
            files['tree.mk'] = ('# Generated by tools/gen_asm.py --tree -- object list for the Makefile.\n'
                                'TREE_SRCS := %s\nTREE_COMMON := %s layout.link\n' % (' '.join(objs), ' '.join(common))
                                + ('# --header rgbfix: the cartridge header is written after linking\nTREE_RGBFIX := %s\n' % ' '.join(
                                    "'%s'" % a if re.search(r'[^A-Za-z0-9_.+-]', a) else a for a in self.rgbfix_args) if self.rgbfix_args else ''))
            files[MANIFEST] = '\n'.join(sorted(files)) + '\n'
            return files
        finally:
            self.addr_comments = True


# ------------------------------------------------------------------ cartridge header (tree mode, --header rgbfix)

HEADER_START, HEADER_END = 0x104, 0x150         # logo .. global checksum; 0100-0103 (`nop ; jp`) is code and stays in the source


def rgbfix_header_args(rom: bytes) -> Tuple[List[str], List[str]]:
    """rgbfix options that write the header bytes 0104-014F of `rom` (decoded from those very bytes; nothing is assumed), and a
    readable description.  The caller must still prove the result: run rgbfix over a header-blanked copy and compare (`prove_rgbfix`)."""
    h = rom[0x100:0x150]

    def b(a):
        return h[a - 0x100]

    args = ['-v']                                # logo + header checksum + global checksum
    desc = []
    cgb = b(0x143)
    if cgb == 0xC0:
        args.append('-C')
        desc.append('CGB flag $C0 (CGB only)')
    elif cgb == 0x80:
        args.append('-c')
        desc.append('CGB flag $80 (CGB compatible)')
    elif cgb != 0:
        raise GenError('header: CGB flag $%02X at 0143 is not one rgbfix writes (-C = $C0, -c = $80)' % cgb)
    def printable(x):
        return all(0x20 <= c < 0x7F for c in x)

    gid = b''
    if cgb:
        whole = bytes(h[0x134 - 0x100:0x143 - 0x100])                    # 15 bytes: a long title, or an 11 byte title + 4 byte game id
        if printable(whole.rstrip(b'\x00')) and b'\x00' not in whole.rstrip(b'\x00'):
            title = whole.rstrip(b'\x00')
        else:
            title, gid = bytes(h[0x134 - 0x100:0x13F - 0x100]).rstrip(b'\x00'), bytes(h[0x13F - 0x100:0x143 - 0x100])
    else:
        title = bytes(h[0x134 - 0x100:0x144 - 0x100]).rstrip(b'\x00')
    if not printable(title) or b'\x00' in title:
        raise GenError('header: the title bytes %s are not printable ASCII followed by NULs' % title.hex())
    if title:
        args += ['-t', title.decode('ascii')]
        desc.append('title "%s"' % title.decode('ascii'))
    if gid:
        if not printable(gid):
            raise GenError('header: the game id bytes %s at 013F are not printable ASCII' % gid.hex())
        args += ['-i', gid.decode('ascii')]
        desc.append('game id "%s"' % gid.decode('ascii'))
    lic = bytes(h[0x144 - 0x100:0x146 - 0x100])
    if any(lic):
        if any(not 0x20 <= c < 0x7F for c in lic):
            raise GenError('header: the new licensee code %s at 0144 is not printable ASCII' % lic.hex())
        args += ['-k', lic.decode('ascii')]
        desc.append('new licensee "%s"' % lic.decode('ascii'))
    sgb = b(0x146)
    if sgb == 3:
        args.append('-s')
        desc.append('SGB flag $03')
    elif sgb != 0:
        raise GenError('header: SGB flag $%02X at 0146 is not one rgbfix writes (-s = $03)' % sgb)
    args += ['-m', '0x%02X' % b(0x147)]
    desc.append('cartridge type $%02X' % b(0x147))
    args += ['-r', str(b(0x149))]
    desc.append('RAM size code %d' % b(0x149))
    if b(0x14A) == 1:
        args.append('-j')
        desc.append('destination: non-Japan')
    elif b(0x14A) != 0:
        raise GenError('header: destination byte $%02X at 014A is not one rgbfix writes' % b(0x14A))
    else:
        desc.append('destination: Japan')
    if b(0x14B):
        args += ['-l', '0x%02X' % b(0x14B)]
        desc.append('old licensee $%02X' % b(0x14B))
    args += ['-n', str(b(0x14C))]
    desc.append('version %d' % b(0x14C))
    args += ['-p', '0']                          # ROM size byte (0148) comes from the file size; padding is a no-op for a power-of-two ROM
    desc.append('ROM size code $%02X and both checksums are computed by rgbfix' % b(0x148))
    return args, desc


def prove_rgbfix(rom: bytes, args: List[str]) -> None:
    """The header is written by rgbfix only if rgbfix reproduces the original bytes exactly: run it over a header-blanked copy."""
    blank = bytearray(rom)
    blank[HEADER_START:HEADER_END] = bytes(HEADER_END - HEADER_START)
    with tempfile.TemporaryDirectory(prefix='mthdr_') as d:
        p = os.path.join(d, 'blank.gbc')
        with open(p, 'wb') as fh:
            fh.write(blank)
        try:
            r = subprocess.run(['rgbfix'] + args + [p], capture_output=True, text=True)
        except OSError as e:
            raise GenError('--header rgbfix needs rgbfix in PATH: %s' % e)
        if r.returncode:
            raise GenError('rgbfix %s failed:\n%s' % (' '.join(args), r.stderr[:1000]))
        with open(p, 'rb') as fh:
            fixed = fh.read()
    if fixed != rom:
        first = next((i for i, (x, y) in enumerate(zip(fixed, rom)) if x != y), min(len(fixed), len(rom)))
        raise GenError('rgbfix %s does not reproduce the ROM header: first difference at file offset $%04X (rgbfix wrote $%02X, ROM has $%02X)%s'
                       % (' '.join(args), first, fixed[first] if first < len(fixed) else -1, rom[first] if first < len(rom) else -1,
                          '' if len(fixed) == len(rom) else ' (sizes %d / %d)' % (len(fixed), len(rom))))


def apply_header_rgbfix(cfg: mtcfg.Config, rom: bytes) -> Tuple[bytes, List[str]]:
    """--header rgbfix: the header range becomes one `zero` region (`ds`, written by rgbfix after linking).  Returns (ROM with the
    header blanked, rgbfix options).  Only data/raw/zero/gfx regions may cover the range (they are cut at its edges)."""
    args, desc = rgbfix_header_args(rom)
    prove_rgbfix(rom, args)
    regs = cfg.regions[0]
    hit = [r for r in regs if r.start < HEADER_END and HEADER_START < r.end]
    for r in hit:
        if r.kind not in ('data', 'raw', 'zero', 'gfx'):
            raise GenError('--header rgbfix: the %s region %02X:%04X-%04X (%s) overlaps the header 0104-014F: only data/raw/zero/gfx regions may' % (
                r.kind, r.bank, r.start, r.end, r.loc))
    new: List[Region] = []
    for r in regs:
        if r not in hit:
            new.append(r)
            continue
        if r.start < HEADER_START:
            new.append(Region(0, r.start, HEADER_START, r.kind, r.label, r.status, r.note, r.loc, r.gap))
        if r.start <= HEADER_START < r.end:
            note = 'cartridge header: rgbfix %s writes it after linking (%s)' % (' '.join(args), '; '.join(desc))
            new.append(Region(0, HEADER_START, HEADER_END, 'zero', r.label if r.start == HEADER_START else '', 'CONFIRMED', note, r.loc))
        if r.end > HEADER_END:
            new.append(Region(0, HEADER_END, r.end, r.kind, r.label if r.start == HEADER_END else '', r.status, r.note, r.loc, r.gap))
    new.sort(key=lambda r: r.start)
    for i, r in enumerate(new):
        r.idx = i
    cfg.regions[0] = new
    blank = bytearray(rom)
    blank[HEADER_START:HEADER_END] = bytes(HEADER_END - HEADER_START)
    return bytes(blank), args


# ------------------------------------------------------------------ front-end

def load_model(rom_path: Optional[str] = None, cfgdir: Optional[str] = None, hw_path: Optional[str] = None,
               strict: bool = False, extra_xrefs=(), rom: Optional[bytes] = None, macros: bool = True,
               text_comments: bool = True, contexts: bool = True, banked: bool = True, header: str = 'data'):
    """Load ROM + config and build the Model.  Returns (model, diag).  `header='rgbfix'` (tree mode): the cartridge header 0104-014F is
    not emitted as bytes but written by rgbfix after linking (`model.rgbfix_args`, proven byte-identical while loading)."""
    rom_path = rom_path or os.path.join(ROOT, 'baserom.gbc')
    cfgdir = cfgdir or os.path.join(ROOT, 'config')
    if rom is None:
        if not os.path.exists(rom_path):
            raise GenError('missing ROM %s (run `make baserom`)' % rom_path)
        with open(rom_path, 'rb') as fh:
            rom = fh.read()
    if len(rom) < BANK_SIZE or len(rom) % BANK_SIZE:
        raise GenError('ROM size %d is not a positive multiple of 16 KiB' % len(rom))
    hw = mtcfg.load_hardware(hw_path)
    diag = Diag(strict)
    cfg = mtcfg.load_config(cfgdir, len(rom) // BANK_SIZE, hw, diag, extra_xrefs, contexts, banked)
    diag.raise_if_errors()
    rgbfix_args = None
    if header == 'rgbfix':
        rom, rgbfix_args = apply_header_rgbfix(cfg, rom)
    elif header != 'data':
        raise GenError('unknown --header mode %r (data|rgbfix)' % header)
    model = Model(rom, cfg, hw, os.path.basename(rom_path), strict, macros, text_comments)
    model.rgbfix_args = rgbfix_args
    return model, diag


def write_files(files: Dict[str, str], outdir: str) -> int:
    os.makedirs(outdir, exist_ok=True)
    changed = 0
    for name, text in sorted(files.items()):
        path = os.path.join(outdir, name)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        if os.path.exists(path):
            with open(path, encoding='utf-8') as fh:
                if fh.read() == text:
                    continue
        with open(path, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(text)
        changed += 1
    return changed


def assemble(files: Dict[str, str], workdir: str, rom_dir: str, jobs: Optional[int] = None) -> Tuple[str, List[str]]:
    """Write `files` to workdir/src, assemble each bank and link.  Returns (rom_path, log)."""
    src, obj = os.path.join(workdir, 'src'), os.path.join(workdir, 'obj')
    os.makedirs(src, exist_ok=True)
    os.makedirs(obj, exist_ok=True)
    write_files(files, src)
    banks = sorted(n for n in files if n.endswith('.asm'))

    def one(name):
        o = os.path.join(obj, name[:-4] + '.o')
        p = subprocess.run(['rgbasm', '-I', src, '-I', rom_dir, '-I', ROOT, '-o', o, os.path.join(src, name)],
                           capture_output=True, text=True, cwd=workdir)
        return name, o, p

    objs, log = [], []
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs or min(16, os.cpu_count() or 4)) as ex:
        for name, o, p in ex.map(one, banks):
            if p.returncode:
                raise GenError('rgbasm failed on %s:\n%s' % (name, p.stderr[:3000]))
            if p.stderr.strip():
                log.append('%s: %s' % (name, p.stderr.strip()[:500]))
            objs.append(o)
    rom = os.path.join(workdir, 'out.gbc')
    p = subprocess.run(['rgblink', '-p', '0x00', '-n', os.path.join(workdir, 'out.sym'), '-o', rom] + objs, capture_output=True, text=True, cwd=workdir)
    if p.returncode:
        raise GenError('rgblink failed:\n%s' % p.stderr[:3000])
    return rom, log


def assemble_tree(files: Dict[str, str], workdir: str, rom_dir: str, jobs: Optional[int] = None, onefile: bool = False) -> Tuple[str, List[str]]:
    """Write a generated tree to workdir/tree, assemble it and link it with its layout.link (`rgblink -p 0x00 -l layout.link`).
    `onefile` assembles main.asm as one object, otherwise every source of tree.mk is assembled separately with `-P includes.asm`."""
    tree, obj = os.path.join(workdir, 'tree'), os.path.join(workdir, 'obj')
    os.makedirs(tree, exist_ok=True)
    shutil.rmtree(obj, ignore_errors=True)
    os.makedirs(obj)
    write_files(files, tree)
    m = re.search(r'^TREE_SRCS := (.*)$', files['tree.mk'], re.M)
    srcs = m.group(1).split() if m else []
    inc = ['-I', tree, '-I', rom_dir, '-I', ROOT]

    def one(name):
        o = os.path.join(obj, name[:-4] + '.o')
        os.makedirs(os.path.dirname(o), exist_ok=True)
        p = subprocess.run(['rgbasm', '-P', 'includes.asm', *inc, '-o', o, os.path.join(tree, name)], capture_output=True, text=True, cwd=tree)
        return name, o, p

    objs, log = [], []
    if onefile:
        o = os.path.join(obj, 'main.o')
        p = subprocess.run(['rgbasm', *inc, '-o', o, os.path.join(tree, 'main.asm')], capture_output=True, text=True, cwd=tree)
        if p.returncode:
            raise GenError('rgbasm failed on main.asm:\n%s' % p.stderr[:3000])
        objs.append(o)
    else:
        with concurrent.futures.ThreadPoolExecutor(max_workers=jobs or min(16, os.cpu_count() or 4)) as ex:
            for name, o, p in ex.map(one, srcs):
                if p.returncode:
                    raise GenError('rgbasm failed on %s:\n%s' % (name, p.stderr[:3000]))
                if p.stderr.strip():
                    log.append('%s: %s' % (name, p.stderr.strip()[:500]))
                objs.append(o)
    rom = os.path.join(workdir, 'out.gbc')
    p = subprocess.run(['rgblink', '-p', '0x00', '-l', os.path.join(tree, 'layout.link'), '-n', os.path.join(workdir, 'out.sym'),
                        '-m', os.path.join(workdir, 'out.map'), '-o', rom] + objs, capture_output=True, text=True, cwd=workdir)
    if p.returncode:
        raise GenError('rgblink failed:\n%s' % p.stderr[:3000])
    if p.stderr.strip():
        log.append('rgblink: %s' % p.stderr.strip()[:500])
    m = re.search(r'^TREE_RGBFIX := (.*)$', files['tree.mk'], re.M)
    if m:                       # --header rgbfix: the header is not in the sources
        import shlex
        p = subprocess.run(['rgbfix'] + shlex.split(m.group(1)) + [rom], capture_output=True, text=True, cwd=workdir)
        if p.returncode:
            raise GenError('rgbfix failed:\n%s' % p.stderr[:3000])
    return rom, log


def write_tree(files: Dict[str, str], outdir: str) -> Tuple[int, int]:
    """Write a generated tree; files of the previous run's manifest that are no longer generated are removed (only those).
    Returns (files rewritten, stale files removed)."""
    old = []
    mp = os.path.join(outdir, MANIFEST)
    if os.path.exists(mp):
        with open(mp, encoding='utf-8') as fh:
            old = [l.strip() for l in fh if l.strip()]
    changed = write_files(files, outdir)
    removed = 0
    for rel in old:
        if rel in files or os.path.isabs(rel) or '..' in rel.split('/'):
            continue
        path = os.path.join(outdir, rel)
        if os.path.isfile(path):
            os.remove(path)
            removed += 1
            d = os.path.dirname(path)
            while os.path.abspath(d) != os.path.abspath(outdir):
                try:
                    os.rmdir(d)
                except OSError:
                    break
                d = os.path.dirname(d)
    return changed, removed


def assemble_and_compare(files, rom: bytes, rom_path: str, cfgdir: str, workdir: str, quiet=False, tree: bool = False, onefile: bool = False) -> bool:
    import compare_rom
    rd = os.path.dirname(os.path.abspath(rom_path))
    built_path, log = assemble_tree(files, workdir, rd, onefile=onefile) if tree else assemble(files, workdir, rd)
    for line in log[:10]:
        print('rgbasm warning: ' + line, file=sys.stderr)
    with open(built_path, 'rb') as fh:
        built = fh.read()
    return compare_rom.compare(rom, built, cfgdir, out=(lambda *a, **k: None) if quiet else print)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('mode', nargs='?', default='regen', choices=('regen', 'verify', 'check'))
    ap.add_argument('--config', default=os.path.join(ROOT, 'config'))
    ap.add_argument('--out', default=os.path.join(ROOT, 'src'))
    ap.add_argument('--rom', default=os.path.join(ROOT, 'baserom.gbc'))
    ap.add_argument('--fast', action='store_true', help='regen: skip the rgbasm/rgblink check')
    ap.add_argument('--strict', action='store_true', help='treat config warnings as errors')
    ap.add_argument('--xrefs', action='append', default=[], help='additional xrefs file (same format as config/xrefs.tsv)')
    ap.add_argument('--keep', help='verify: keep the temp build in this directory')
    ap.add_argument('--no-macros', action='store_true', help='emit `call FarCall` + dw + db instead of the farcall macros')
    ap.add_argument('--no-text-comments', action='store_true', help='omit the decoded-text comment after each line of a text region')
    ap.add_argument('--tree', metavar='OUTDIR', help='tree mode: files by subsystem, floating sections pinned by layout.link (see docs/FORMATS.md); '
                    'regen writes OUTDIR, verify builds in a temp dir')
    ap.add_argument('--layout', default=os.path.join(ROOT, 'analysis', 'layout', 'layout.tsv'), help='tree mode: layout table (bank start end path note)')
    ap.add_argument('--tree-no-addr-comments', action='store_true', help='tree mode: omit the ROM-address comments (region headers, label cites)')
    ap.add_argument('--header', choices=('data', 'rgbfix'), default='data',
                    help='tree mode: `data` (default) keeps the header bytes 0104-014F in the source; `rgbfix` emits `ds` there and writes the '
                    'header with rgbfix after linking (options decoded from the ROM header and proven to reproduce it; see docs/FORMATS.md)')
    ap.add_argument('--onefile', action='store_true', help='tree mode: check by assembling main.asm as one object instead of every file separately')
    ap.add_argument('-q', '--quiet', action='store_true')
    a = ap.parse_args(argv)

    if a.mode == 'regen' and not os.environ.get('MT_LEGACY_REGEN'):
        # the generated tree was committed as the hand-maintained source: writing into the repository (other than build/) would overwrite it
        target = os.path.realpath(a.tree if a.tree else a.out)
        root = os.path.realpath(ROOT)
        if (target == root or target.startswith(root + os.sep)) and not (target + os.sep).startswith(os.path.join(root, 'build') + os.sep):
            print('error: refusing to write %s: the source of this repository is FROZEN (hand-maintained); this generator is the bootstrap pipeline, kept as history.\n'
                  '       Generate into a directory outside the repository (or under build/), or set MT_LEGACY_REGEN=1 if you really mean it.' % target, file=sys.stderr)
            return 2

    try:
        model, diag = load_model(a.rom, a.config, None, a.strict, a.xrefs, macros=not a.no_macros, text_comments=not a.no_text_comments,
                                 header=a.header if a.tree else 'data')
        for w in (diag.warnings + model.diag.warnings)[:25]:
            print('warning: ' + w, file=sys.stderr)
        if a.tree:
            lay = layoutlib.load_layout(a.layout, model.nbanks, Diag(a.strict))
            files = model.generate_tree(lay, not a.tree_no_addr_comments)
        else:
            files = model.generate()
    except GenError as e:
        print('error: %s' % e, file=sys.stderr)
        return 1

    if a.mode == 'check':
        if not a.quiet:
            print('check OK: %d banks generated in memory, structural round-trip passed%s' % (
                model.nbanks, ' (tree: %d files, %d sections)' % (len(files), len(lay.sections)) if a.tree else ''))
        return 0

    with open(a.rom, 'rb') as fh:
        rom = fh.read()
    if a.mode == 'verify' or not a.fast:
        tmp = a.keep or tempfile.mkdtemp(prefix='mtgen_')
        try:
            os.makedirs(tmp, exist_ok=True)
            ok = assemble_and_compare(files, rom, a.rom, a.config, tmp, quiet=(a.mode == 'regen'), tree=bool(a.tree), onefile=a.onefile)
        except GenError as e:
            print('error: %s' % e, file=sys.stderr)
            ok = False
        finally:
            if not a.keep:
                shutil.rmtree(tmp, ignore_errors=True)
        if not ok:
            print('error: generated sources do not rebuild the ROM byte-identically%s' % (
                '; nothing was written' if a.mode == 'regen' else ''), file=sys.stderr)
            return 1
        if a.mode == 'verify' and a.tree:
            return 0
        if a.mode == 'verify':
            stale = []
            for name, text in files.items():
                p = os.path.join(a.out, name)
                if not os.path.exists(p) or open(p, encoding='utf-8').read() != text:
                    stale.append(name)
            if stale:
                print('note: %d file(s) in %s differ from the generated sources (run `make regen`)' % (
                    len(stale), os.path.relpath(a.out, ROOT) if a.out.startswith(ROOT) else a.out))
            return 0

    if a.tree:
        changed, removed = write_tree(files, a.tree)
        if not a.quiet:
            print('tree OK: %d files (%d sections), %d rewritten, %d stale removed in %s%s' % (
                len(files), len(lay.sections), changed, removed, a.tree, '' if a.fast else ' (assemble+link check passed)'))
        return 0
    changed = write_files(files, a.out)
    if not a.quiet:
        print('regen OK: %d banks, %d file(s) rewritten in %s%s' % (
            model.nbanks, changed, a.out, '' if a.fast else ' (assemble+link check passed)'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
