#!/usr/bin/env python3
"""PNG -> binary rules: the single manifest (gfx/png_rules.tsv) behind the Makefile's PNG rules (gfx/png.mk) and `make png-export`.

    python3 tools/png_rules.py rules            # (maintainers) rewrite gfx/png_rules.tsv + gfx/png.mk from gfx/assets.tsv.  Baseline
                                                #   hashes are taken from the binaries on disk, so run it on an UNEDITED tree (make checks the ROM hash)
    python3 tools/png_rules.py mk-check         # png_rules.tsv / png.mk are in sync with assets.tsv and the files on disk
    python3 tools/png_rules.py export [--force] # (maintainers) binaries -> PNGs (tile sheets, font sheets); refuses to overwrite a PNG that holds
                                                #   edits not yet built into its binary unless --force
    python3 tools/png_rules.py edited           # list the binaries whose bytes differ from the original ROM's (= edited through their PNG); exit 0 if any

One line of png_rules.tsv per generated binary:  out  png  kind  cells  start  pad  size  sha256
    out      binary that the .asm INCBINs (.2bpp / .1bpp / .bin)            png    its editable PNG source
    kind     tiles (rgbgfx)  font12 | font8x16 | font6x12 (tools/font_png.py)
    cells    font sheets: glyph slots of the sheet       start  font sheets: bank address (hex) of the first byte of `out`
    pad      tiles: blank tiles that complete the last PNG row (rgbgfx -x pad)
    size     bytes of `out` (the ROM layout needs exactly this many)        sha256  hash of `out` in the byte-identical (original) state
"""
import argparse
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import gfx_export as G  # noqa: E402
import font_png  # noqa: E402
import pnglib  # noqa: E402

RULES = 'gfx/png_rules.tsv'
MK = 'gfx/png.mk'
COLS = ['out', 'png', 'kind', 'cells', 'start', 'pad', 'size', 'sha256']
FONT_TYPES = ('font12', 'font8x16', 'font6x12')


def sha(path):
    """Hash of the BYTES an asset contributes to the ROM (a .pal text file: the words its RGB lines assemble to)."""
    if path.endswith('.pal'):
        data = G.palette_bytes(open(path, encoding='utf-8').read())
    else:
        data = open(path, 'rb').read()
    return hashlib.sha256(data).hexdigest()


def set_root(root):
    global ROOT
    ROOT = os.path.abspath(root)
    G.ROOT = ROOT


def read_rules():
    rows = []
    p = os.path.join(ROOT, RULES)
    if not os.path.exists(p):
        return rows
    for line in open(p, encoding='utf-8'):
        if line.startswith('#') or not line.strip() or line.startswith('out\t'):
            continue
        f = line.rstrip('\n').split('\t')
        f += [''] * (len(COLS) - len(f))
        rows.append(dict(zip(COLS, f)))
    return rows


def build_rules(keep_hash=True):
    rows = G.read_manifest()
    old = {r['out']: r for r in read_rules()}
    fc = G.font_cells(rows)
    out = []
    for path, r in sorted(rows.items()):
        t = r['type']
        if t == 'tiles' and r['png'] == 'exact':
            rule = dict(out=path, png=G.png_path_of(path, 'exact'), kind='tiles', cells='', start='', pad=r['pad'])
        elif t in FONT_TYPES and r['png'] in ('sheet', 'view'):
            png = G.png_path_of(path, 'sheet')
            rule = dict(out=path, png=png, kind=t, cells=str(fc[png]), start=r['addr'].lower(), pad='')
        elif t in ('tilemap', 'attrmap', 'palette'):
            # no PNG rule: hand-editable (.pal text) or edited through tools/screen_png.py; listed so that an edit is an EXPLAINED ROM difference
            rule = dict(out=path, png='-', kind=t, cells='', start='', pad='')
        else:
            continue
        full = os.path.join(ROOT, path)
        rule['size'] = str(os.path.getsize(full))
        rule['sha256'] = old[path]['sha256'] if (keep_hash and path in old) else sha(full)
        out.append(rule)
    return out


def rules_text(rules):
    lines = ['# gfx/png_rules.tsv -- written by tools/png_rules.py (do not edit by hand); read by gfx/png.mk, tools/png_check.py, `make png-export`',
             '# out = binary the .asm INCBINs, png = its editable source ("-" = no PNG rule: tilemap / attrmap / palette rows only make an edit an explained ROM difference), kind = tiles (rgbgfx, `pad` = -x) | font12 | font8x16 | font6x12 (tools/font_png.py;',
             '# cells = glyph slots of the sheet, start = bank address of the first byte of out).  size = bytes of out (must not change),',
             '# sha256 = hash of out in the original, byte-identical ROM state (edited = differs).  See docs/EDITING_IMAGES.md.',
             '\t'.join(COLS)]
    for r in rules:
        lines.append('\t'.join(r[c] for c in COLS))
    return '\n'.join(lines) + '\n'


MK_HEAD = """# gfx/png.mk -- GENERATED by tools/png_rules.py from gfx/png_rules.tsv (do not edit by hand); included by the Makefile.
#
# PNG is the editable source of every graphic listed in gfx/png_rules.tsv: the binary the .asm INCBINs is rebuilt from its PNG whenever the PNG
# is newer (rgbgfx for tile sheets, tools/font_png.py for font sheets).  A fresh git checkout has arbitrary mtimes, so the rules may run for every
# file; they are deterministic and give back the committed bytes (the old file is kept when the bytes are identical).  The size of a binary must
# not change (the ROM layout is pinned by layout.link): a PNG that converts to another size is refused with an explanation.
#
# Variables used (defined in the Makefile): RGBGFX, PYTHON, Q.  Without rgbgfx / python3 the rules are not included (the committed binaries are used).

# rebuild $@ from $<: $@.tmp was written by the converter; size must be PNG_SIZE; identical bytes keep the old file (only touched)
define png_finish
got=$$(wc -c < $@.tmp); \\
if [ "$$got" != "$(PNG_SIZE)" ]; then \\
	echo "error: $< converts to $$got bytes but the ROM needs exactly $(PNG_SIZE) for $@: do not resize the image or add/remove tiles/glyphs"; \\
	if [ -n "$(PYTHON_OK)" ]; then $(PYTHON) tools/png_check.py --file $<; fi; \\
	rm -f $@.tmp; exit 1; fi; \\
if cmp -s $@.tmp $@ 2>/dev/null; then rm -f $@.tmp; touch $@; \\
else \\
	if [ -n "$(PYTHON_OK)" ]; then $(PYTHON) tools/png_check.py --file $< || { rm -f $@.tmp; exit 1; }; fi; \\
	mv -f $@.tmp $@; echo "  -> $@ changed"; \\
fi
endef

"""


def wrap_list(name, items):
    out = [name + ' := \\']
    for i in items:
        out.append('\t' + i + ' \\')
    out.append('')
    return '\n'.join(out) + '\n'


def mk_text(rules):
    tiles = [r for r in rules if r['kind'] == 'tiles']
    fonts = [r for r in rules if r['kind'] in FONT_TYPES]
    o = [MK_HEAD]
    if tiles:
        o.append('ifneq ($(RGBGFX_VERSION),)')
        o.append(wrap_list('PNG_TILE_OUTS', [r['out'] for r in tiles]))
        for r in tiles:
            o.append('%s: PNG_SIZE := %s' % (r['out'], r['size']))
            if r['pad'] not in ('', '0'):
                o.append('%s: PNG_PAD := -x %s' % (r['out'], r['pad']))
        o.append('')
        o.append('%.2bpp: %.png')
        o.append('\t@echo "rgbgfx $<"')
        o.append('\t$(Q)$(RGBGFX) -c embedded $(PNG_PAD) -o $@.tmp $< || { rm -f $@.tmp; if [ -n "$(PYTHON_OK)" ]; then $(PYTHON) tools/png_check.py --file $<; fi; echo "error: $< cannot be converted to $@ (make png-check lists every problem)"; exit 1; }')
        o.append('\t$(Q)$(png_finish)')
        o.append('endif')
        o.append('')
    if fonts:
        o.append('ifneq ($(PYTHON_OK),)')
        o.append(wrap_list('PNG_FONT_OUTS', [r['out'] for r in fonts]))
        for r in fonts:
            o.append('%s: PNG_SIZE := %s' % (r['out'], r['size']))
            o.append('%s: %s' % (r['out'], r['png']))
            o.append('\t@echo "font_png $<"')
            o.append('\t$(Q)$(PYTHON) tools/font_png.py import --type %s --cells %s --start %s --size %s $< $@.tmp || { rm -f $@.tmp; exit 1; }'
                     % (r['kind'], r['cells'], r['start'], r['size']))
            o.append('\t$(Q)$(png_finish)')
            o.append('')
        o.append('endif')
        o.append('')
    o.append('PNG_OUTS := $(PNG_TILE_OUTS) $(PNG_FONT_OUTS)')
    o.append('')
    return '\n'.join(o)


def cmd_rules(a):
    rules = build_rules(keep_hash=not a.rebaseline)
    with open(os.path.join(ROOT, RULES), 'w', encoding='utf-8') as f:
        f.write(rules_text(rules))
    with open(os.path.join(ROOT, MK), 'w', encoding='utf-8') as f:
        f.write(mk_text(rules))
    n = {}
    for r in rules:
        n[r['kind']] = n.get(r['kind'], 0) + 1
    print('wrote %s and %s: %s' % (RULES, MK, ', '.join('%d %s' % (v, k) for k, v in sorted(n.items()))))
    return 0


def cmd_mkcheck(a):
    errs = []
    rules = read_rules()
    want = build_rules(keep_hash=True)
    if [dict(r) for r in rules] != want:
        errs.append('%s is out of date with gfx/assets.tsv / the files on disk (python3 tools/png_rules.py rules)' % RULES)
    p = os.path.join(ROOT, MK)
    if not os.path.exists(p) or open(p, encoding='utf-8').read() != mk_text(rules):
        errs.append('%s does not match %s (python3 tools/png_rules.py rules)' % (MK, RULES))
    for e in errs:
        print('ERROR', e)
    print('png_rules mk-check:', 'FAILED' if errs else 'OK (%d rules)' % len(rules))
    return 1 if errs else 0


def edited_rules():
    out = []
    for r in read_rules():
        full = os.path.join(ROOT, r['out'])
        if not os.path.exists(full) or sha(full) != r['sha256']:
            out.append(r)
    return out


def cmd_edited(a):
    ed = edited_rules()
    for r in ed:
        print(r['out'])
    return 0 if ed else 1


# ------------------------------------------------------------------------------------------------ export (binary -> PNG)

def tiles_png_bytes(data):
    w, h, img = G.render_tiles(data)
    return pnglib.png_bytes(w, h, img, G.SHADES)


def font_png_bytes(rules_of_png):
    r0 = rules_of_png[0]
    spans = [(int(r['start'], 16), open(os.path.join(ROOT, r['out']), 'rb').read()) for r in rules_of_png]
    w, h, img = font_png.render(r0['kind'], int(r0['cells']), spans)
    return pnglib.png_bytes(w, h, img, font_png.PALETTE)


def png_holds_unbuilt_edits(rules_of_png):
    """True when the existing PNG decodes to bytes different from the binaries it feeds (edits not built yet)."""
    r0 = rules_of_png[0]
    png_path = os.path.join(ROOT, r0['png'])
    if not os.path.exists(png_path):
        return False
    try:
        png = pnglib.read_png(png_path)
    except pnglib.PngError:
        return True
    if r0['kind'] == 'tiles':
        return None                  # decided by the caller through rgbgfx (see cmd_export)
    for r in rules_of_png:
        want = open(os.path.join(ROOT, r['out']), 'rb').read()
        got, errs = font_png.decode(r['kind'], png, int(r['cells']), int(r['start'], 16), int(r['size']))
        if errs or got != want:
            return True
    return False


def cmd_export(a):
    import subprocess
    import tempfile
    rules = read_rules()
    by_png = {}
    for r in rules:
        if r['png'] == '-':
            continue
        by_png.setdefault(r['png'], []).append(r)
    done = skipped = same = 0
    for png, rs in sorted(by_png.items()):
        r0 = rs[0]
        full = os.path.join(ROOT, png)
        new = tiles_png_bytes(open(os.path.join(ROOT, r0['out']), 'rb').read()) if r0['kind'] == 'tiles' else font_png_bytes(rs)
        if os.path.exists(full) and open(full, 'rb').read() == new:
            same += 1
            continue
        if os.path.exists(full) and not a.force:
            held = png_holds_unbuilt_edits(rs)
            if held is None:                                       # tiles: run rgbgfx on the existing PNG
                with tempfile.TemporaryDirectory() as td:
                    o = os.path.join(td, 'o.2bpp')
                    cmd = ['rgbgfx', '-c', 'embedded'] + (['-x', r0['pad']] if r0['pad'] not in ('', '0') else []) + ['-o', o, full]
                    p = subprocess.run(cmd, capture_output=True, text=True)
                    held = p.returncode != 0 or open(o, 'rb').read() != open(os.path.join(ROOT, r0['out']), 'rb').read()
            if held:
                print('skipped %s: it holds edits that are not built into %s yet (run make first, or use --force)' % (png, r0['out']))
                skipped += 1
                continue
        with open(full, 'wb') as f:
            f.write(new)
        done += 1
    print('png-export: %d written, %d already identical, %d skipped (unbuilt edits)' % (done, same, skipped))
    return 1 if skipped else 0


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('cmd', choices=['rules', 'mk-check', 'export', 'edited'])
    ap.add_argument('--root')
    ap.add_argument('--force', action='store_true', help='export: overwrite PNGs even if they hold unbuilt edits')
    ap.add_argument('--rebaseline', action='store_true', help='rules: take new baseline hashes from the binaries on disk')
    a = ap.parse_args(argv)
    if a.root:
        set_root(a.root)
    os.chdir(ROOT)
    return {'rules': cmd_rules, 'mk-check': cmd_mkcheck, 'export': cmd_export, 'edited': cmd_edited}[a.cmd](a)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
