#!/usr/bin/env python3
"""Reverse-engineering progress report.

usage: progress.py [--config DIR] [--rom FILE] [--out FILE | --no-write] [--strict]

Prints, and writes to docs/PROGRESS.md (deterministic: no dates):
  * bytes per region kind, raw-INCBIN bytes remaining (and how many of them are non-zero)
  * a per-bank table
  * number of named vs generic labels, RAM variables, xrefs, label-resolution statistics

Inputs: baserom.gbc and config/ (regions, symbols, ram, xrefs).  The numbers come
from the same model the generator uses, so a config that does not generate cleanly
is reported as an error instead of being counted.
"""
import argparse
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_asm                       # noqa: E402
from lib import mtcfg                # noqa: E402
from lib.mtcfg import GenError       # noqa: E402

KINDS = mtcfg.KINDS
ROOT = mtcfg.ROOT


def pct(a, b):
    return '%.1f%%' % (100.0 * a / b) if b else '-'


def collect(model):
    rom = model.rom
    total = len(rom)
    per_kind = {k: 0 for k in KINDS}
    raw_nonzero = 0
    per_bank = {}
    gap_bytes = 0
    for b in range(model.nbanks):
        row = {k: 0 for k in KINDS}
        rnz = 0
        for r in model.regions[b]:
            row[r.kind] += r.size
            per_kind[r.kind] += r.size
            if r.kind == 'raw':
                nz = sum(1 for x in model.bytes_of(r) if x)
                rnz += nz
                raw_nonzero += nz
                if r.gap:
                    gap_bytes += r.size
        nonzero = sum(1 for x in rom[b * 0x4000:(b + 1) * 0x4000] if x)
        per_bank[b] = (row, rnz, nonzero)
    named, generic_named, auto = [], [], {}
    for b in range(model.nbanks):
        for labs in model.labels[b].values():
            for lab in labs:
                if lab.origin == 'generic':
                    pre = lab.name.split('_')[0]
                    auto[pre] = auto.get(pre, 0) + 1
                elif mtcfg.GENERIC.match(lab.name):
                    generic_named.append(lab.name)
                else:
                    named.append(lab.name)
    return dict(total=total, per_kind=per_kind, raw_nonzero=raw_nonzero, per_bank=per_bank, gap=gap_bytes,
                named=len(named), generic_named=len(generic_named), auto=auto,
                consts=len(model.consts), ram=len(model.cfg.ram), xrefs=len(model.cfg.xrefs),
                regions=sum(1 for b in range(model.nbanks) for r in model.regions[b] if not r.gap),
                stats=dict(model.stats),
                insns=sum(len(v) for v in model.insns.values()),
                illegal=sum(1 for v in model.insns.values() for _, i in v if i.flow == 'bad'),
                nonzero_total=sum(v[2] for v in per_bank.values()))


def render(d, rom_sha, nbanks):
    total = d['total']
    out = ['# Progress', '',
           '_Generated by `tools/progress.py` from `config/` and `baserom.gbc` (SHA-256 `%s`); do not edit._' % rom_sha, '',
           '"Classified" = bytes inside a region of any kind other than `raw` (a region kind is a claim with a status in '
           '`config/regions`; see `docs/FORMATS.md`).  Unlisted gaps count as `raw`.', '']
    raw = d['per_kind']['raw']
    out += ['## Summary', '',
            '| metric | value |', '|---|---|',
            '| ROM size | %d bytes (%d banks) |' % (total, nbanks),
            '| classified (non-raw) | %d bytes (%s) |' % (total - raw, pct(total - raw, total)),
            '| raw INCBIN remaining | %d bytes (%s) |' % (raw, pct(raw, total)),
            '| raw bytes that are non-zero | %d |' % d['raw_nonzero'],
            '| raw bytes that are 0x00 (candidates for `zero`) | %d |' % (raw - d['raw_nonzero']),
            '| non-zero ROM bytes classified | %d of %d (%s) |' % (
                d['nonzero_total'] - d['raw_nonzero'], d['nonzero_total'], pct(d['nonzero_total'] - d['raw_nonzero'], d['nonzero_total'])),
            '| regions declared | %d |' % d['regions'],
            '| instructions decoded (code + ramcode) | %d (%d illegal opcodes emitted as `db`) |' % (d['insns'], d['illegal']),
            '']
    out += ['## Bytes per kind', '', '| kind | bytes | share |', '|---|---|---|']
    for k in KINDS:
        v = d['per_kind'][k]
        out.append('| %s | %d | %s |' % (k, v, pct(v, total)))
    out.append('')
    out += ['## Labels and names', '',
            '| item | count |', '|---|---|',
            '| named labels (symbols + region labels with non-generic names) | %d |' % d['named'],
            '| labels with generic-form names given in config | %d |' % d['generic_named'],
            '| auto-generated generic labels | %d |' % sum(d['auto'].values())]
    for pre in ('Function', 'Label', 'Data', 'Table', 'String'):
        if pre in d['auto']:
            out.append('| &nbsp;&nbsp;`%s_<bank>_<addr>` | %d |' % (pre, d['auto'][pre]))
    out += ['| `const` symbols | %d |' % d['consts'],
            '| RAM/HRAM/SRAM variables named (`config/ram`) | %d |' % d['ram'],
            '| xrefs (`config/xrefs.tsv`) | %d |' % d['xrefs'], '']
    st = d['stats']
    out += ['## Operand resolution', '',
            '| item | count |', '|---|---|',
            '| branch/call/rst operands emitted as labels | %d |' % st.get('branch_labels', 0),
            '| branch targets left numeric: no bank known (ROM0/RAM code into $4000-$7FFF, or ambiguous RAM overlay) | %d |'
            % st.get('branches_unresolved_bank', 0),
            '| branch targets left numeric: no label at the target (not code, or not a named location) | %d |'
            % st.get('targets_unlabelled', 0),
            '| branch targets inside an instruction (not labelled) | %d |' % st.get('targets_mid_instruction', 0),
            '| hardware register names substituted | %d |' % st.get('hw_names', 0),
            '| MBC5 register write names substituted | %d |' % st.get('mbc_names', 0),
            '| RAM names substituted | %d |' % st.get('ram_names', 0),
            '| `dw` operands emitted as labels | %d |' % st.get('word_labels', 0),
            '| xref substitutions | %d |' % (st.get('xref_labels', 0) + st.get('xref_ram', 0)), '']
    out += ['## Per bank', '',
            '| bank | ' + ' | '.join(KINDS) + ' | raw non-zero | classified |',
            '|---|' + '---|' * (len(KINDS) + 2)]
    for b in range(nbanks):
        row, rnz, nonzero = d['per_bank'][b]
        size = 0x4000
        out.append('| %02X | %s | %d | %s |' % (b, ' | '.join(str(row[k]) for k in KINDS), rnz, pct(size - row['raw'], size)))
    out.append('')
    return '\n'.join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--config', default=os.path.join(ROOT, 'config'))
    ap.add_argument('--rom', default=os.path.join(ROOT, 'baserom.gbc'))
    ap.add_argument('--out', default=os.path.join(ROOT, 'docs', 'PROGRESS.md'))
    ap.add_argument('--no-write', action='store_true')
    ap.add_argument('--strict', action='store_true')
    a = ap.parse_args(argv)
    try:
        model, diag = gen_asm.load_model(a.rom, a.config, None, a.strict)
        model.generate()      # fills the operand-resolution statistics and runs the structural checks
    except GenError as e:
        print('error: %s' % e, file=sys.stderr)
        return 1
    d = collect(model)
    sha = hashlib.sha256(model.rom).hexdigest()
    text = render(d, sha, model.nbanks)
    total, raw = d['total'], d['per_kind']['raw']
    print('ROM %d bytes, %d banks, sha256 %s' % (total, model.nbanks, sha))
    print('bytes per kind:')
    for k in KINDS:
        print('  %-9s %8d  %s' % (k, d['per_kind'][k], pct(d['per_kind'][k], total)))
    print('raw INCBIN remaining: %d bytes (%s), of which non-zero: %d' % (raw, pct(raw, total), d['raw_nonzero']))
    print('labels: %d named, %d generic-form in config, %d auto-generated %s; %d const, %d RAM vars, %d xrefs' % (
        d['named'], d['generic_named'], sum(d['auto'].values()), d['auto'] or '', d['consts'], d['ram'], d['xrefs']))
    print('%-4s %s' % ('bank', ' '.join('%8s' % k for k in KINDS) + '  rawNZ  done'))
    for b in range(model.nbanks):
        row, rnz, _nz = d['per_bank'][b]
        print('%02X   %s  %5d  %s' % (b, ' '.join('%8d' % row[k] for k in KINDS), rnz, pct(0x4000 - row['raw'], 0x4000)))
    if not a.no_write:
        os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
        old = open(a.out, encoding='utf-8').read() if os.path.exists(a.out) else None
        if old != text:
            with open(a.out, 'w', encoding='utf-8', newline='\n') as fh:
                fh.write(text)
        print('wrote %s' % os.path.relpath(a.out, ROOT) if a.out.startswith(ROOT) else 'wrote %s' % a.out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
