#!/usr/bin/env python3
"""Turn the numeric `db $83, $81, ...` text blocks of data/ and of the code files into readable strings:  db "メール", 0

    python3 tools/text_to_strings.py             # convert, then assemble the whole ROM and check the SHA-256 (restores on failure)
    python3 tools/text_to_strings.py --dry-run   # report what would change, write nothing
    python3 tools/text_to_strings.py --no-verify # convert without running make

The conversion is byte-exact by construction (the strings use the multi-byte Shift-JIS charmaps of
constants/sjis_charmap.asm, generated by tools/gen_sjis_charmap.py) and is **verified by assembling**: after the files are
written the script runs `make` and compares the ROM's SHA-256 with roms.sha256; if it differs every file is put back.

Rules (see also STYLE.md, "Text"):
  * Only regions whose header says `; ---- text ...` are converted, plus `data` regions of data/text/ that are nothing but
    clean NUL-terminated strings, plus the `[ASCII name][NUL][value byte]` item tables of data/html/keywords.asm
    (tools/gen_sjis_charmap.py `classify`).  Tables, records, cell data and images are not touched.
  * One string per line, ending with its terminator:  db "…", 0.  With --split-cr files (data/text, data/html) a line also ends
    after a CR (CR LF) that is followed by more text, so multi-line messages and HTML bodies read like their source.
  * Bytes that are not a plain character stay explicit tokens between the quoted parts:  db "ホーム", $FA, "みます", 0.
  * A `db` line that carries a hand-written comment (`; record header`) is left exactly as it is; the auto-generated decode
    comments (`; "メール"`) are dropped, the string is the text now.
  * `dw` lines, labels, comments and region headers are kept.  Each converted file gets `PUSHC sjis` (or `sjis_hw` for bank 6C)
    after its SECTION line and `POPC` at the end, so the charmap never reaches code.
  * Text blocks INSIDE code files (engine/, lib/, home/, audio/; ~180 blocks between code): only `; ---- text ...` regions are
    converted, and only when the numeric `db` lines that follow the header add up to exactly the header's byte count (a block
    that does not is reported and left alone).  These files mix code and data, so the charmap is pushed per block, not per file:
    `PUSHC sjis` directly before the first label/`db` line of the block and `POPC` directly after its last `db` line; no
    instruction, and no line of code, is ever between them.  Every code file is audited afterwards (--audit): PUSHC/POPC balanced,
    and no `"` in any code line outside a PUSHC..POPC pair, INCBIN/INCLUDE/SECTION/LOAD or a comment.  In code files a CR LF
    that is followed by more text also ends a line (as for data/text), which matters for the protocol strings of the SDK.
    A run of several db rows without any NUL (a table of characters such as Table_Text_HalfToFullWidth, not a string) keeps the
    source's rows (one `db "..."` per original row) instead of becoming one very long line.
  * Idempotent: a second run finds nothing left to convert.
"""
import argparse
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_sjis_charmap as G  # noqa: E402

ROOT = G.ROOT

DB_NUM = re.compile(r'^\tdb (\$[0-9A-F]{2}(?:, \$[0-9A-F]{2})*)(?: ; (.*))?$')
AUTO_COMMENT = re.compile(r'^".*"$')
SECTION_RE = re.compile(r'^SECTION "([^"]+)", (\w+)')
HTML_NAME = re.compile(r'^[a-z0-9_]+\.htm$')
KEEP_NOTE = ('; kept as raw bytes: text-like bytes mixed with header/control bytes, executed-read data of unknown content class, '
             'so not provably a string')
KEEP_NOTE_CODE = ('; kept as raw bytes: the bytes read as Shift-JIS/ASCII text, but the header does not say `text` (executed-read data of unknown content class, '
                  'or unclassified), so not provably a string')
HW_NOTE_OLD = '; text comments (halfwidth): display only, A1-DF shown as half-width katakana, glyphs unproven (text_encoding.md section 6)'
HW_NOTE_NEW = ('; written with the sjis_hw charmap: single bytes A1-DF appear as half-width katakana (JIS X 0201 order), '
               'other single bytes as $xx; glyphs unproven (text_encoding.md section 6)')


def split_cr_file(rel):
    """Files whose CR (CR LF) ends a line of the source: message text and HTML bodies (not the keyboard cell rows, where
    `$01, $0D` is an inline control)."""
    return rel.startswith('data/text/') or rel.startswith('data/html/pages_')


def render_line(tokens, last_is_end):
    parts = []
    buf = ''
    for k, (kind, val, n) in enumerate(tokens):
        if kind == 'c':
            buf += G.esc(val)
            continue
        if buf:
            parts.append('"%s"' % buf)
            buf = ''
        if val == 0 and k == len(tokens) - 1 and last_is_end:
            parts.append('0')
        else:
            parts.append('$%02X' % val)
    if buf:
        parts.append('"%s"' % buf)
    return '\tdb ' + ', '.join(parts)


def split_strings(tokens, split_cr):
    """Tokens -> list of lines (each a token list): a line ends after NUL, and after CR [LF] when more text follows."""
    lines = []
    cur = []
    i = 0
    n = len(tokens)
    while i < n:
        t = tokens[i]
        cur.append(t)
        i += 1
        if t == ('b', 0, 1):
            lines.append(cur)
            cur = []
        elif split_cr and t == ('b', 0x0D, 1):
            if i < n and tokens[i] == ('b', 0x0A, 1):
                cur.append(tokens[i])
                i += 1
            if i < n and tokens[i] != ('b', 0, 1):
                lines.append(cur)
                cur = []
    if cur:
        lines.append(cur)
    return lines


def text_of(line):
    return ''.join(t[1] for t in line if t[0] == 'c')


def to_bytes(line):
    out = bytearray()
    for kind, val, n in line:
        out += val.encode('cp932') if kind == 'c' else bytes([val])
    return bytes(out)


class Conv:
    def __init__(self, path):
        self.path = path
        self.rel = os.path.relpath(path, ROOT).replace(os.sep, '/')
        self.lines = open(path, encoding='utf-8').read().split('\n')
        self.log = []          # human readable notes
        self.n_strings = 0
        self.n_lines = 0
        self.n_regions = 0
        self.kept = []         # (where, why) for regions that stay db
        self.chars = set()     # characters emitted, per charmap requirement

    def regions(self):
        """[(header_index, Region, [indices of the numeric db lines], size_of_those_bytes)] for every header of the file."""
        bank = None
        res = []
        cur = None
        for i, line in enumerate(self.lines):
            m = G.BANK_RE.match(line)
            if m and bank is None:
                bank = int(m.group(1), 16)
            m = G.REGION_RE.match(line)
            if m:
                reg = G.Region(self.path, bank, m.group(1), int(m.group(2), 16), int(m.group(3), 16), line, m.group(5))
                cur = [i, reg, [], bytearray(), False]
                res.append(cur)
                continue
            if cur is None:
                continue
            m = DB_NUM.match(line)
            if m:
                cur[2].append(i)
                cur[3] += bytes(int(x[1:], 16) for x in m.group(1).split(', '))
            elif line.startswith('\tdw ') or line.startswith('\tds ') or (line.startswith('\tdb ') and not m):
                cur[4] = True  # other data lines (words, already converted strings, ...) in the region
        return res

    def convert(self):
        out = []
        regs = self.regions()
        conv_regions = {}
        notes = {}
        for hi, reg, idxs, data, other in regs:
            if not idxs:
                continue
            complete = (len(data) == reg.size) and not other
            if reg.kind == 'text':
                mode = 'text'
            else:
                mode = G.classify(reg, bytes(data)) if complete else None
            if mode is None:
                if reg.kind == 'data' and self.rel.startswith('data/text/') and complete:
                    nchar = sum(t[2] for t in G.tokenize(bytes(data), reg.hw, reg.arg1) if t[0] == 'c')
                    if nchar >= 2 and nchar * 10 >= len(data) * 6 and self.lines[hi + 1] != KEEP_NOTE:
                        self.kept.append((reg.where, 'data region left as db (not provably text)'))
                        notes[hi] = KEEP_NOTE
                continue
            conv_regions[hi] = (reg, mode, idxs)
        if not conv_regions:
            return False
        for hi, note in notes.items():
            self.lines[hi] = self.lines[hi] + '\n' + note

        hw_file = any(r.hw for r, _, _ in conv_regions.values())
        cr = split_cr_file(self.rel)
        html = self.rel.startswith('data/html/pages_')
        replace = {}      # line index -> list of replacement lines ([] deletes)
        for hi, (reg, mode, idxs) in conv_regions.items():
            self.n_regions += 1
            # runs of consecutive numeric db lines whose comment is empty or the auto decode
            run = []
            runs = []
            for i in idxs:
                m = DB_NUM.match(self.lines[i])
                auto = m.group(2) is None or AUTO_COMMENT.match(m.group(2))
                if auto and run and run[-1] == i - 1:
                    run.append(i)
                elif auto:
                    if run:
                        runs.append(run)
                    run = [i]
                else:
                    if run:
                        runs.append(run)
                    run = []
                    self.log.append('kept %s line %d: %s' % (reg.where, i + 1, self.lines[i].strip()))
            if run:
                runs.append(run)
            for run in runs:
                data = bytearray()
                for i in run:
                    m = DB_NUM.match(self.lines[i])
                    data += bytes(int(x[1:], 16) for x in m.group(1).split(', '))
                data = bytes(data)
                if mode == 'items':
                    items = G.parse_items(data)
                    new = []
                    for name, val in items:
                        new.append('\tdb "%s", 0, $%02X' % (''.join(G.esc(c) for c in name), val))
                        self.chars.add((False, name))
                    self.n_strings += len(items)
                else:
                    toks = G.tokenize(data, reg.hw, reg.arg1)
                    lines = split_strings(toks, cr)
                    new = []
                    for k, ln in enumerate(lines):
                        ends = ln[-1] == ('b', 0, 1)
                        if html and k > 0 and ends and HTML_NAME.match(text_of(ln)) and len(ln) == len(text_of(ln)) + 1:
                            new.append('')
                        new.append(render_line(ln, ends))
                        self.n_strings += 1 if ends else 0
                        self.chars.add((reg.hw, text_of(ln)))
                        assert to_bytes(ln) == bytes(to_bytes(ln))
                    # self check: the tokens re-encode to the original bytes
                    assert b''.join(to_bytes(l) for l in lines) == data, (reg.where, 'tokenizer round trip')
                replace[run[0]] = new
                for i in run[1:]:
                    replace[i] = []
                self.n_lines += len(new)
        # write out
        for i, line in enumerate(self.lines):
            if i in replace:
                out += replace[i]
            else:
                out.append(line)
        lines = out
        # the half-width note and the charmap discipline
        lines = [HW_NOTE_NEW if l == HW_NOTE_OLD else l for l in lines]
        cm = 'sjis_hw' if hw_file else 'sjis'
        if not any(l.startswith('PUSHC ') for l in lines):
            for i, l in enumerate(lines):
                if SECTION_RE.match(l):
                    lines[i + 1:i + 1] = ['', 'PUSHC %s' % cm]
                    break
            else:
                raise SystemExit('%s: no SECTION line' % self.rel)
            while lines and lines[-1] == '':
                lines.pop()
            lines += ['', 'POPC', '']
        self.new_text = '\n'.join(lines)
        return True


LABEL_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*::?(?: ;.*)?$')
DS_ZERO = re.compile(r'^\tds (\$[0-9A-F]+|\d+), \$00(?: ;.*)?$')   # NUL padding inside a text block ("211.005.001.117", 0 + 4 x 0)


class CodeConv(Conv):
    """Text blocks inside a code file: per-block PUSHC/POPC, only for blocks whose numeric db lines add up to the header size."""

    def convert(self):
        lines = self.lines
        bank = None
        for l in lines:
            m = G.BANK_RE.match(l)
            if m:
                bank = int(m.group(1), 16)
                break
        before = {}   # line index -> lines inserted before it
        after = {}    # line index -> lines inserted after it
        replace = {}  # line index -> replacement lines
        for hi, line in enumerate(lines):
            m = G.REGION_RE.match(line)
            if not m or m.group(1) not in ('text', 'data'):
                continue
            reg = G.Region(self.path, bank, m.group(1), int(m.group(2), 16), int(m.group(3), 16), line, m.group(5))
            # the block: labels, blank lines, comments at column 0 and numeric db lines, up to the header's byte count
            idxs, data = [], bytearray()
            have = 0       # bytes of the block seen: numeric db lines + `ds n, $00` padding lines (which stay as they are)
            j = hi + 1
            while j < len(lines) and have < reg.size:
                l = lines[j]
                d = DB_NUM.match(l)
                z = DS_ZERO.match(l)
                if G.REGION_RE.match(l):
                    break
                if d:
                    idxs.append(j)
                    b = bytes(int(x[1:], 16) for x in d.group(1).split(', '))
                    data += b
                    have += len(b)
                elif z:
                    have += int(z.group(1).replace('$', '0x'), 0)
                elif not (l == '' or l.startswith(';') or LABEL_RE.match(l)):
                    break
                j += 1
            if reg.kind == 'data':
                # a data region that only looks like text stays raw (its header does not say text); say so, as for data/text
                toks = G.tokenize(bytes(data), reg.hw, False)
                nchar = sum(t[2] for t in toks if t[0] == 'c')
                if idxs and have == reg.size and G.strict_text(toks) and nchar >= 2 and nchar * 10 >= len(data) * 6 \
                        and lines[hi + 1] != KEEP_NOTE_CODE:
                    after.setdefault(hi, []).append(KEEP_NOTE_CODE)
                    self.kept.append((reg.where, 'data region left as db (not provably text)'))
                continue
            if not idxs:
                continue      # already converted (a second run) or a block without numeric lines
            if have != reg.size:
                self.kept.append((reg.where, 'text block left as db: %d bytes after the header, header says %d' % (have, reg.size)))
                continue
            # runs of consecutive numeric db lines whose comment is empty or the auto decode
            runs, run = [], []
            for i in idxs:
                d = DB_NUM.match(lines[i])
                auto = d.group(2) is None or AUTO_COMMENT.match(d.group(2))
                if auto and run and run[-1] == i - 1:
                    run.append(i)
                elif auto:
                    if run:
                        runs.append(run)
                    run = [i]
                else:
                    if run:
                        runs.append(run)
                    run = []
                    self.log.append('kept %s line %d: %s' % (reg.where, i + 1, lines[i].strip()))
            if run:
                runs.append(run)
            if not runs:
                continue
            self.n_regions += 1
            for run in runs:
                blob = bytearray()
                for i in run:
                    blob += bytes(int(x[1:], 16) for x in DB_NUM.match(lines[i]).group(1).split(', '))
                blob = bytes(blob)
                toks = G.tokenize(blob, reg.hw, False)
                parts = split_strings(toks, True)
                if len(run) > 1 and ('b', 0, 1) not in toks:
                    # several rows and no NUL: a table of characters, not a string; keep the source's rows when each row is whole characters
                    rows = [G.tokenize(bytes(int(x[1:], 16) for x in DB_NUM.match(lines[i]).group(1).split(', ')), reg.hw, False)
                            for i in run]
                    if [t for r in rows for t in r] == toks:
                        parts = rows
                new = []
                for ln in parts:
                    ends = ln[-1] == ('b', 0, 1)
                    new.append(render_line(ln, ends))
                    self.n_strings += 1 if ends else 0
                    self.chars.add((reg.hw, text_of(ln)))
                assert b''.join(to_bytes(l) for l in parts) == blob, (reg.where, 'tokenizer round trip')
                replace[run[0]] = new
                for i in run[1:]:
                    replace[i] = []
                self.n_lines += len(new)
            # the charmap only around this block: before its first label/db line, after its last converted line
            first = next(k for k in range(hi + 1, runs[-1][-1] + 1) if lines[k] and not lines[k].startswith(';'))
            before.setdefault(first, []).append('PUSHC %s' % ('sjis_hw' if reg.hw else 'sjis'))
            after.setdefault(runs[-1][-1], []).append('POPC')
        if not replace and not after:
            return False
        out = []
        for i, line in enumerate(lines):
            out += before.get(i, [])
            out += replace[i] if i in replace else [line]
            out += after.get(i, [])
        self.new_text = '\n'.join(out)
        return True


def audit_code(root, files):
    """(problems, counts): PUSHC/POPC balanced and never around an instruction; no quote in code outside a pair."""
    problems = []
    n_pairs = n_quote_lines = 0
    ok_prefix = ('SECTION ', 'INCBIN ', 'INCLUDE ', 'LOAD ', 'PUSHC', 'POPC', 'ASSERT ', 'DEF ', 'NEWCHARMAP', 'CHARMAP')
    for path in files:
        rel = os.path.relpath(path, root).replace(os.sep, '/')
        depth = 0
        for n, line in enumerate(open(path, encoding='utf-8').read().split('\n'), 1):
            st = line.strip()
            if st.startswith('PUSHC'):
                depth += 1
                n_pairs += 1
                if depth > 1:
                    problems.append('%s:%d nested PUSHC' % (rel, n))
                continue
            if st == 'POPC':
                depth -= 1
                if depth < 0:
                    problems.append('%s:%d POPC without PUSHC' % (rel, n))
                    depth = 0
                continue
            code = line.split(';', 1)[0]
            if depth and st and not st.startswith(';') and not (LABEL_RE.match(st) and not line.startswith('\t')) \
                    and not re.match(r'^\t(db|dw|ds) ', line):
                problems.append('%s:%d instruction or directive inside PUSHC..POPC: %s' % (rel, n, st[:60]))
            if '"' in code and not depth and not st.startswith(ok_prefix):
                n_quote_lines += 1
                problems.append('%s:%d quote in code outside PUSHC..POPC: %s' % (rel, n, st[:60]))
        if depth != 0:
            problems.append('%s: unbalanced PUSHC/POPC at end of file' % rel)
    return problems, n_pairs


def charmap_entries(path):
    """({charmap name: set of characters}) parsed from constants/sjis_charmap.asm (own copy of RGBDS' inheritance)."""
    cur = None
    maps = {}
    for line in open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        m = re.match(r'^NEWCHARMAP (\w+)(?:, (\w+))?', line)
        if m:
            cur = m.group(1)
            maps[cur] = set(maps[m.group(2)]) if m.group(2) else set()
            continue
        m = re.match(r'^\tcharmap "((?:\\.|[^"\\])+)"', line)
        if m and cur:
            maps[cur].add(re.sub(r'\\(.)', r'\1', m.group(1)))
    return maps


def sha_ok(root):
    want = open(os.path.join(root, 'roms.sha256')).read().split()[0]
    import hashlib
    got = hashlib.sha256(open(os.path.join(root, 'mobile_trainer.gbc'), 'rb').read()).hexdigest()
    return want == got, got


def ensure_include(root):
    p = os.path.join(root, 'includes.asm')
    s = open(p, encoding='utf-8').read()
    line = 'INCLUDE "constants/sjis_charmap.asm"'
    if line in s:
        return False
    s = s.rstrip('\n') + '\n' + line + '\n'
    open(p, 'w', encoding='utf-8').write(s)
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--dry-run', action='store_true')
    ap.add_argument('--no-verify', action='store_true', help='do not run make afterwards')
    ap.add_argument('-v', '--verbose', action='store_true')
    ap.add_argument('--audit', action='store_true', help='only audit the code files (PUSHC/POPC pairs, quotes in code) and exit')
    ap.add_argument('--jobs', type=int, default=8)
    args = ap.parse_args()

    cmpath = os.path.join(ROOT, 'constants', 'sjis_charmap.asm')
    if not os.path.exists(cmpath):
        sys.exit('constants/sjis_charmap.asm is missing: run tools/gen_sjis_charmap.py first')
    maps = charmap_entries(cmpath)

    code_files = [p for p in G.source_files() if G.is_code_file(p)]
    if args.audit:
        problems, n_pairs = audit_code(ROOT, code_files)
        print('\n'.join(problems[:50]))
        print('audit: %d code files, %d PUSHC..POPC pairs, %d problems' % (len(code_files), n_pairs, len(problems)))
        return 1 if problems else 0

    changed = {}
    total = dict(files=0, regions=0, strings=0, lines=0)
    for path in G.source_files():
        c = (CodeConv if G.is_code_file(path) else Conv)(path)
        if not c.convert():
            continue
        # every character must have a charmap entry
        for hw, text in c.chars:
            cmap = maps['sjis_hw' if hw else 'sjis']
            miss = [ch for ch in text if ch not in cmap] if isinstance(text, str) else [ch for ch in text if ch not in cmap]
            if miss:
                sys.exit('%s: characters without a charmap entry: %s (re-run tools/gen_sjis_charmap.py)' % (c.rel, ''.join(miss)))
        old = open(path, encoding='utf-8').read()
        if c.new_text == old:
            continue
        changed[path] = (old, c)
        total['files'] += 1
        total['regions'] += c.n_regions
        total['strings'] += c.n_strings
        total['lines'] += c.n_lines
        print('%-42s %3d regions -> %4d string lines (%d strings)' % (c.rel, c.n_regions, c.n_lines, c.n_strings))
        for where, why in c.kept:
            if isinstance(c, CodeConv):
                print('    %s %s: %s' % ('NOT converted' if why.startswith('text') else 'kept raw', where, why))
        if args.verbose:
            for l in c.log + ['left as db: %s %s' % k for k in c.kept]:
                print('    ' + l)
    if not changed:
        print('nothing to convert (already done)')
        problems, n_pairs = audit_code(ROOT, code_files)
        print('\n'.join(problems[:50]))
        print('audit: %d code files, %d PUSHC..POPC pairs, %d problems' % (len(code_files), n_pairs, len(problems)))
        return 1 if problems else 0
    print('total: %(files)d files, %(regions)d regions, %(lines)d lines, %(strings)d NUL-terminated strings' % total)
    if args.dry_run:
        return 0

    incl_added = ensure_include(ROOT)
    for path, (old, c) in changed.items():
        open(path, 'w', encoding='utf-8').write(c.new_text)
    problems, n_pairs = audit_code(ROOT, code_files)
    print('audit: %d code files, %d PUSHC..POPC pairs, %d problems' % (len(code_files), n_pairs, len(problems)))
    if problems:
        print('\n'.join(problems[:50]))
        for path, (old, c) in changed.items():
            open(path, 'w', encoding='utf-8').write(old)
        print('AUDIT FAILED: restored the original files')
        return 1
    if args.no_verify:
        return 0
    print('verifying: make -j%d ...' % args.jobs)
    r = subprocess.run(['make', '-j%d' % args.jobs, 'checkhash'], cwd=ROOT, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    warn = [l for l in r.stdout.split('\n') if l.startswith(('warning', 'error')) or ': warning' in l or ': error' in l]
    ok = r.returncode == 0 and sha_ok(ROOT)[0]
    if warn:
        print('\n'.join(warn[:20]))
    if not ok:
        print(r.stdout[-2000:])
        print('VERIFY FAILED: restoring the original files')
        for path, (old, c) in changed.items():
            open(path, 'w', encoding='utf-8').write(old)
        return 1
    print('SHA-256 OK: the converted source assembles to the original ROM')
    return 0


if __name__ == '__main__':
    sys.exit(main())
