#!/usr/bin/env python3
"""Turn the numeric `db $83, $81, ...` text blocks of data/ into readable strings:  db "メール", 0

    python3 tools/text_to_strings.py             # convert, then assemble the whole ROM and check the SHA-256 (restores on failure)
    python3 tools/text_to_strings.py --dry-run   # report what would change, write nothing
    python3 tools/text_to_strings.py --no-verify # convert without running make

The conversion is byte-exact by construction (the strings use the multi-byte Shift-JIS charmaps of
constants/sjis_charmap.asm, generated by tools/gen_sjis_charmap.py) and is **verified by assembling**: after the files are
written the script runs `make` and compares the ROM's SHA-256 with roms.sha256; if it differs every file is put back.

Rules (see also STYLE.md, "Text"):
  * Only regions whose header says `; ---- text ...` are converted, plus `data` regions of data/text/ that are nothing but
    clean NUL-terminated strings, plus the `[ASCII name][NUL][value byte]` item tables of data/html/keywords.asm
    (tools/gen_sjis_charmap.py `classify`).  Tables, records, cell data and images are not touched.
  * One string per line, ending with its terminator:  db "…", 0.  With --split-cr files (data/text, data/html) a line also ends
    after a CR (CR LF) that is followed by more text, so multi-line messages and HTML bodies read like their source.
  * Bytes that are not a plain character stay explicit tokens between the quoted parts:  db "ホーム", $FA, "みます", 0.
  * A `db` line that carries a hand-written comment (`; record header`) is left exactly as it is; the auto-generated decode
    comments (`; "メール"`) are dropped, the string is the text now.
  * `dw` lines, labels, comments and region headers are kept.  Each converted file gets `PUSHC sjis` (or `sjis_hw` for bank 6C)
    after its SECTION line and `POPC` at the end, so the charmap never reaches code.
  * Idempotent: a second run finds nothing left to convert.
"""
import argparse
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_sjis_charmap as G  # noqa: E402

ROOT = G.ROOT

DB_NUM = re.compile(r'^\tdb (\$[0-9A-F]{2}(?:, \$[0-9A-F]{2})*)(?: ; (.*))?$')
AUTO_COMMENT = re.compile(r'^".*"$')
SECTION_RE = re.compile(r'^SECTION "([^"]+)", (\w+)')
HTML_NAME = re.compile(r'^[a-z0-9_]+\.htm$')
KEEP_NOTE = ('; kept as raw bytes: text-like bytes mixed with header/control bytes, executed-read data of unknown content class, '
             'so not provably a string')
HW_NOTE_OLD = '; text comments (halfwidth): display only, A1-DF shown as half-width katakana, glyphs unproven (text_encoding.md section 6)'
HW_NOTE_NEW = ('; written with the sjis_hw charmap: single bytes A1-DF appear as half-width katakana (JIS X 0201 order), '
               'other single bytes as $xx; glyphs unproven (text_encoding.md section 6)')


def split_cr_file(rel):
    """Files whose CR (CR LF) ends a line of the source: message text and HTML bodies (not the keyboard cell rows, where
    `$01, $0D` is an inline control)."""
    return rel.startswith('data/text/') or rel.startswith('data/html/pages_')


def render_line(tokens, last_is_end):
    parts = []
    buf = ''
    for k, (kind, val, n) in enumerate(tokens):
        if kind == 'c':
            buf += G.esc(val)
            continue
        if buf:
            parts.append('"%s"' % buf)
            buf = ''
        if val == 0 and k == len(tokens) - 1 and last_is_end:
            parts.append('0')
        else:
            parts.append('$%02X' % val)
    if buf:
        parts.append('"%s"' % buf)
    return '\tdb ' + ', '.join(parts)


def split_strings(tokens, split_cr):
    """Tokens -> list of lines (each a token list): a line ends after NUL, and after CR [LF] when more text follows."""
    lines = []
    cur = []
    i = 0
    n = len(tokens)
    while i < n:
        t = tokens[i]
        cur.append(t)
        i += 1
        if t == ('b', 0, 1):
            lines.append(cur)
            cur = []
        elif split_cr and t == ('b', 0x0D, 1):
            if i < n and tokens[i] == ('b', 0x0A, 1):
                cur.append(tokens[i])
                i += 1
            if i < n and tokens[i] != ('b', 0, 1):
                lines.append(cur)
                cur = []
    if cur:
        lines.append(cur)
    return lines


def text_of(line):
    return ''.join(t[1] for t in line if t[0] == 'c')


def to_bytes(line):
    out = bytearray()
    for kind, val, n in line:
        out += val.encode('cp932') if kind == 'c' else bytes([val])
    return bytes(out)


class Conv:
    def __init__(self, path):
        self.path = path
        self.rel = os.path.relpath(path, ROOT).replace(os.sep, '/')
        self.lines = open(path, encoding='utf-8').read().split('\n')
        self.log = []          # human readable notes
        self.n_strings = 0
        self.n_lines = 0
        self.n_regions = 0
        self.kept = []         # (where, why) for regions that stay db
        self.chars = set()     # characters emitted, per charmap requirement

    def regions(self):
        """[(header_index, Region, [indices of the numeric db lines], size_of_those_bytes)] for every header of the file."""
        bank = None
        res = []
        cur = None
        for i, line in enumerate(self.lines):
            m = G.BANK_RE.match(line)
            if m and bank is None:
                bank = int(m.group(1), 16)
            m = G.REGION_RE.match(line)
            if m:
                reg = G.Region(self.path, bank, m.group(1), int(m.group(2), 16), int(m.group(3), 16), line, m.group(5))
                cur = [i, reg, [], bytearray(), False]
                res.append(cur)
                continue
            if cur is None:
                continue
            m = DB_NUM.match(line)
            if m:
                cur[2].append(i)
                cur[3] += bytes(int(x[1:], 16) for x in m.group(1).split(', '))
            elif line.startswith('\tdw ') or line.startswith('\tds ') or (line.startswith('\tdb ') and not m):
                cur[4] = True  # other data lines (words, already converted strings, ...) in the region
        return res

    def convert(self):
        out = []
        regs = self.regions()
        conv_regions = {}
        notes = {}
        for hi, reg, idxs, data, other in regs:
            if not idxs:
                continue
            complete = (len(data) == reg.size) and not other
            if reg.kind == 'text':
                mode = 'text'
            else:
                mode = G.classify(reg, bytes(data)) if complete else None
            if mode is None:
                if reg.kind == 'data' and self.rel.startswith('data/text/') and complete:
                    nchar = sum(t[2] for t in G.tokenize(bytes(data), reg.hw, reg.arg1) if t[0] == 'c')
                    if nchar >= 2 and nchar * 10 >= len(data) * 6 and self.lines[hi + 1] != KEEP_NOTE:
                        self.kept.append((reg.where, 'data region left as db (not provably text)'))
                        notes[hi] = KEEP_NOTE
                continue
            conv_regions[hi] = (reg, mode, idxs)
        if not conv_regions:
            return False
        for hi, note in notes.items():
            self.lines[hi] = self.lines[hi] + '\n' + note

        hw_file = any(r.hw for r, _, _ in conv_regions.values())
        cr = split_cr_file(self.rel)
        html = self.rel.startswith('data/html/pages_')
        replace = {}      # line index -> list of replacement lines ([] deletes)
        for hi, (reg, mode, idxs) in conv_regions.items():
            self.n_regions += 1
            # runs of consecutive numeric db lines whose comment is empty or the auto decode
            run = []
            runs = []
            for i in idxs:
                m = DB_NUM.match(self.lines[i])
                auto = m.group(2) is None or AUTO_COMMENT.match(m.group(2))
                if auto and run and run[-1] == i - 1:
                    run.append(i)
                elif auto:
                    if run:
                        runs.append(run)
                    run = [i]
                else:
                    if run:
                        runs.append(run)
                    run = []
                    self.log.append('kept %s line %d: %s' % (reg.where, i + 1, self.lines[i].strip()))
            if run:
                runs.append(run)
            for run in runs:
                data = bytearray()
                for i in run:
                    m = DB_NUM.match(self.lines[i])
                    data += bytes(int(x[1:], 16) for x in m.group(1).split(', '))
                data = bytes(data)
                if mode == 'items':
                    items = G.parse_items(data)
                    new = []
                    for name, val in items:
                        new.append('\tdb "%s", 0, $%02X' % (''.join(G.esc(c) for c in name), val))
                        self.chars.add((False, name))
                    self.n_strings += len(items)
                else:
                    toks = G.tokenize(data, reg.hw, reg.arg1)
                    lines = split_strings(toks, cr)
                    new = []
                    for k, ln in enumerate(lines):
                        ends = ln[-1] == ('b', 0, 1)
                        if html and k > 0 and ends and HTML_NAME.match(text_of(ln)) and len(ln) == len(text_of(ln)) + 1:
                            new.append('')
                        new.append(render_line(ln, ends))
                        self.n_strings += 1 if ends else 0
                        self.chars.add((reg.hw, text_of(ln)))
                        assert to_bytes(ln) == bytes(to_bytes(ln))
                    # self check: the tokens re-encode to the original bytes
                    assert b''.join(to_bytes(l) for l in lines) == data, (reg.where, 'tokenizer round trip')
                replace[run[0]] = new
                for i in run[1:]:
                    replace[i] = []
                self.n_lines += len(new)
        # write out
        for i, line in enumerate(self.lines):
            if i in replace:
                out += replace[i]
            else:
                out.append(line)
        lines = out
        # the half-width note and the charmap discipline
        lines = [HW_NOTE_NEW if l == HW_NOTE_OLD else l for l in lines]
        cm = 'sjis_hw' if hw_file else 'sjis'
        if not any(l.startswith('PUSHC ') for l in lines):
            for i, l in enumerate(lines):
                if SECTION_RE.match(l):
                    lines[i + 1:i + 1] = ['', 'PUSHC %s' % cm]
                    break
            else:
                raise SystemExit('%s: no SECTION line' % self.rel)
            while lines and lines[-1] == '':
                lines.pop()
            lines += ['', 'POPC', '']
        self.new_text = '\n'.join(lines)
        return True


def charmap_entries(path):
    """({charmap name: set of characters}) parsed from constants/sjis_charmap.asm (own copy of RGBDS' inheritance)."""
    cur = None
    maps = {}
    for line in open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        m = re.match(r'^NEWCHARMAP (\w+)(?:, (\w+))?', line)
        if m:
            cur = m.group(1)
            maps[cur] = set(maps[m.group(2)]) if m.group(2) else set()
            continue
        m = re.match(r'^\tcharmap "((?:\\.|[^"\\])+)"', line)
        if m and cur:
            maps[cur].add(re.sub(r'\\(.)', r'\1', m.group(1)))
    return maps


def sha_ok(root):
    want = open(os.path.join(root, 'roms.sha256')).read().split()[0]
    import hashlib
    got = hashlib.sha256(open(os.path.join(root, 'mobile_trainer.gbc'), 'rb').read()).hexdigest()
    return want == got, got


def ensure_include(root):
    p = os.path.join(root, 'includes.asm')
    s = open(p, encoding='utf-8').read()
    line = 'INCLUDE "constants/sjis_charmap.asm"'
    if line in s:
        return False
    s = s.rstrip('\n') + '\n' + line + '\n'
    open(p, 'w', encoding='utf-8').write(s)
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--dry-run', action='store_true')
    ap.add_argument('--no-verify', action='store_true', help='do not run make afterwards')
    ap.add_argument('-v', '--verbose', action='store_true')
    ap.add_argument('--jobs', type=int, default=8)
    args = ap.parse_args()

    cmpath = os.path.join(ROOT, 'constants', 'sjis_charmap.asm')
    if not os.path.exists(cmpath):
        sys.exit('constants/sjis_charmap.asm is missing: run tools/gen_sjis_charmap.py first')
    maps = charmap_entries(cmpath)

    changed = {}
    total = dict(files=0, regions=0, strings=0, lines=0)
    for path in G.source_files():
        c = Conv(path)
        if not c.convert():
            continue
        # every character must have a charmap entry
        for hw, text in c.chars:
            cmap = maps['sjis_hw' if hw else 'sjis']
            miss = [ch for ch in text if ch not in cmap] if isinstance(text, str) else [ch for ch in text if ch not in cmap]
            if miss:
                sys.exit('%s: characters without a charmap entry: %s (re-run tools/gen_sjis_charmap.py)' % (c.rel, ''.join(miss)))
        old = open(path, encoding='utf-8').read()
        if c.new_text == old:
            continue
        changed[path] = (old, c)
        total['files'] += 1
        total['regions'] += c.n_regions
        total['strings'] += c.n_strings
        total['lines'] += c.n_lines
        print('%-42s %3d regions -> %4d string lines (%d strings)' % (c.rel, c.n_regions, c.n_lines, c.n_strings))
        if args.verbose:
            for l in c.log + ['left as db: %s %s' % k for k in c.kept]:
                print('    ' + l)
    if not changed:
        print('nothing to convert (already done)')
        return 0
    print('total: %(files)d files, %(regions)d regions, %(lines)d lines, %(strings)d NUL-terminated strings' % total)
    if args.dry_run:
        return 0

    incl_added = ensure_include(ROOT)
    for path, (old, c) in changed.items():
        open(path, 'w', encoding='utf-8').write(c.new_text)
    if args.no_verify:
        return 0
    print('verifying: make -j%d ...' % args.jobs)
    r = subprocess.run(['make', '-j%d' % args.jobs, 'checkhash'], cwd=ROOT, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    warn = [l for l in r.stdout.split('\n') if l.startswith(('warning', 'error')) or ': warning' in l or ': error' in l]
    ok = r.returncode == 0 and sha_ok(ROOT)[0]
    if warn:
        print('\n'.join(warn[:20]))
    if not ok:
        print(r.stdout[-2000:])
        print('VERIFY FAILED: restoring the original files')
        for path, (old, c) in changed.items():
            open(path, 'w', encoding='utf-8').write(old)
        return 1
    print('SHA-256 OK: the converted source assembles to the original ROM')
    return 0


if __name__ == '__main__':
    sys.exit(main())
