; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 28

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank28", ROMX[$4000], BANK[$28]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $A0000, $4000
