; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 08

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank08", ROMX[$4000], BANK[$08]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $20000, $4000
