; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 01

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank01", ROMX[$4000], BANK[$01]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $4000, $4000
