; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 5F

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank5F", ROMX[$4000], BANK[$5F]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $17C000, $4000
