; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 3F

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank3F", ROMX[$4000], BANK[$3F]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $FC000, $4000
