; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 6F

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank6F", ROMX[$4000], BANK[$6F]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $1BC000, $4000
