; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 18

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank18", ROMX[$4000], BANK[$18]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $60000, $4000
