; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 12

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank12", ROMX[$4000], BANK[$12]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $48000, $4000
