; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 13

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"
INCLUDE "constants/macros.inc"

SECTION "Bank13", ROMX[$4000], BANK[$13]

; ---- zero $4000-$8000 (16384 bytes) [CONFIRMED] bank is entirely 0x00 in the reference ROM
	ds $4000, $00
