; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 1A

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank1A", ROMX[$4000], BANK[$1A]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $68000, $4000
