; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 1A

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank1A", ROMX[$4000], BANK[$1A]

; ---- code $4000-$4163 (355 bytes) [CONFIRMED] 121 insn(s); 121 executed (in up to 1/18 scenarios); entry proven: target of an executed call/far call

Function_1A_4000:: ; 1A:4000
	xor a, a
	ld bc, $00FC
	ld hl, $C0D4
	call FillBytes
	call FarCall
	dw Function_48_48BB
	db BANK(Function_48_48BB)
	ld a, $01
	ld [wRam_C0D4], a
	ld [wRam_C0D6], a

Label_1A_4018:: ; 1A:4018
	ldh a, [rLCDC]
	and a, $9F
	ldh [rLCDC], a
	xor a, a
	ldh [rSCX], a
	ldh [rSCY], a
	ld a, $07
	ldh [rWX], a
	ld a, $90
	ldh [rWY], a
	call FarCall
	dw Function_00_09B6
	db BANK(Function_00_09B6)
	ld de, $8000
	ld hl, $4A90
	ld a, $1A
	ld b, $95
	ld c, $20
	call FarCall
	dw Function_00_0787
	db BANK(Function_00_0787)
	ld de, $8B01
	ld hl, $4C90
	ld a, $1A
	ld b, $92
	ld c, $40
	call FarCall
	dw Function_00_0787
	db BANK(Function_00_0787)
	ld de, $8F01
	ld hl, $5090
	ld a, $1A
	ld b, $94
	ld c, $30
	call FarCall
	dw Function_00_0787
	db BANK(Function_00_0787)
	ld bc, $0040
	ld de, $D800
	ld hl, $5390
	ld a, $1A
	call FarCall
	dw Function_4F_4000
	db BANK(Function_4F_4000)
	ld bc, $1214
	ld de, $D000
	ld hl, $47B5
	ld a, $1A
	call FarCall
	dw Function_00_08EA
	db BANK(Function_00_08EA)
	ld hl, $DA20
	ld de, $55A0
	ld a, $1A
	ld b, $80
	call FarCall
	dw Function_00_0A82
	db BANK(Function_00_0A82)
	ld hl, $DA30
	ld de, $55A0
	ld a, $1A
	ld b, $81
	call FarCall
	dw Function_00_0A82
	db BANK(Function_00_0A82)
	ld bc, $0040
	ld de, $D840
	ld hl, $53D0
	ld a, $1A
	call FarCall
	dw Function_4F_4000
	db BANK(Function_4F_4000)
	ld a, $00
	ld bc, $0A10
	ld de, $F000
	ld hl, $D0A1
	call FarCall
	dw Function_48_4679
	db BANK(Function_48_4679)
	ldh a, [rLCDC]
	call Function_00_082C
	ldh [hScratchA], a
	ldh a, [hWRAMBank]
	push af
	ldh a, [hScratchA]
	ld a, $02
	ldh [hWRAMBank], a
	ldh [rSVBK], a
	xor a, a
	ld bc, $0A00
	ld hl, $D000
	call FillBytes
	ld de, $9000
	ld hl, $D000
	ld a, $00
	ld b, $92
	ld c, $40
	call FarCall
	dw Function_00_0787
	db BANK(Function_00_0787)
	ld de, $9400
	ld hl, $D000
	ld a, $00
	ld b, $92
	ld c, $40
	call FarCall
	dw Function_00_0787
	db BANK(Function_00_0787)
	ld de, $8800
	ld hl, $D000
	ld a, $00
	ld b, $95
	ld c, $20
	call FarCall
	dw Function_00_0787
	db BANK(Function_00_0787)
	ldh [hScratchA], a
	pop af
	ldh [hWRAMBank], a
	ldh [rSVBK], a
	ldh a, [hScratchA]
	call Function_1A_4391
	call Function_1A_42DE
	call Function_1A_4317
	call FarCall
	dw Function_00_0956
	db BANK(Function_00_0956)
	call FarCall
	dw Function_4F_42B4
	db BANK(Function_4F_42B4)
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $001A
	call Function_00_20E8
	pop af
	ldh [rSVBK], a

Label_1A_414B:: ; 1A:414B
	call FarCall
	dw Function_00_0956
	db BANK(Function_00_0956)
	call Function_00_044B
	call FarCall
	dw Function_7D_7BA4
	db BANK(Function_7D_7BA4)
	call FarCall
	dw Function_7D_7BC1
	db BANK(Function_7D_7BC1)
	call JoypadDispatch

; ---- ptrtable $4163-$416D (10 bytes) [CONFIRMED] inline table of `call $056A` (JoypadDispatch) at 1A:4160: 5 entries; fixed length (5 words) by the routine

Table_1A_4163:: ; 1A:4163
	dw Label_1A_4177
	dw Label_1A_41CA
	dw Label_1A_41E2
	dw Label_1A_41E2
	dw Label_1A_416D

; ---- code $416D-$41F2 (133 bytes) [CONFIRMED] 65 insn(s); 65 executed (in up to 1/18 scenarios)

Label_1A_416D:: ; 1A:416D
	ldh a, [hJoyPressedRepeat]
	and a, $F0
	call nz, Function_1A_41E5
	jp Label_1A_414B

Label_1A_4177:: ; 1A:4177
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $002C
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	call FarCall
	dw Function_4F_4370
	db BANK(Function_4F_4370)
	ld a, [wRam_C0D4]
	dec a
	add a, a
	ld hl, $40B9
	add a, l
	ld l, a
	ld a, h
	adc a, $00
	ld h, a
	ld d, $3F
	ld a, d
	call ReadByteFar
	ld c, a
	ld a, d
	call ReadByteFar
	ld h, a
	ld l, c
	ld a, [wRam_C0D6]
	dec a
	ld b, a
	ld a, [wRam_C0E5]
	add a, b
	add a, l
	ld l, a
	ld a, h
	adc a, $00
	ld h, a
	ld a, $3F
	call ReadByteFar
	ld c, a
	ld b, $00
	ld a, $02
	call FarCall
	dw Function_4C_4F56
	db BANK(Function_4C_4F56)
	jp Label_1A_4018

Label_1A_41CA:: ; 1A:41CA
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $002E
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	call FarCall
	dw Function_4F_4370
	db BANK(Function_4F_4370)
	xor a, a
	ret

Label_1A_41E2:: ; 1A:41E2
	jp Label_1A_414B

Function_1A_41E5:: ; 1A:41E5
	bit 6, a
	jr nz, Label_1A_41F8
	bit 7, a
	jr nz, Label_1A_4238
	bit 4, a
	jp nz, Label_1A_4281

; ---- code $41F2-$4238 (70 bytes) [PROBABLE] 34 insn(s) reached by static flow only; seeds: exec x34; min discovery hops 0; fall-through of the jpcc at 1A:41EF (executed)
	bit 5, a
	jp nz, Label_1A_42B0
	ret

Label_1A_41F8:: ; 1A:41F8
	ld a, [wRam_C0D6]
	dec a
	jr z, Label_1A_4215
	ld [wRam_C0D6], a
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $0029
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	call Function_1A_42DE
	ret

Label_1A_4215:: ; 1A:4215
	ld a, [wRam_C0E5]
	or a, a
	ret z
	dec a
	ld [wRam_C0E5], a
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $0029
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	call Function_1A_4391
	call Function_1A_42DE
	call Function_1A_4317
	ret

; ---- code $4238-$4263 (43 bytes) [CONFIRMED] 23 insn(s); 23 executed (in up to 1/18 scenarios)

Label_1A_4238:: ; 1A:4238
	ld a, [wRam_C0D8]
	ld b, a
	ld a, [wRam_C0D6]
	ld c, a
	ld a, [wRam_C0E5]
	add a, c
	cp a, b
	ret z
	ld a, c
	cp a, $05
	jr z, Label_1A_4263
	inc a
	ld [wRam_C0D6], a
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $0029
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	call Function_1A_42DE
	ret

; ---- code $4263-$4281 (30 bytes) [PROBABLE] 14 insn(s) reached by static flow only; seeds: exec x14; min discovery hops 1; entered by jrcc from 1A:4249 (executed)

Label_1A_4263:: ; 1A:4263
	ld hl, $C0E5
	inc [hl]
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $0029
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	call Function_1A_4391
	call Function_1A_42DE
	call Function_1A_4317
	ret

; ---- code $4281-$4288 (7 bytes) [CONFIRMED] 3 insn(s); 3 executed (in up to 1/18 scenarios)

Label_1A_4281:: ; 1A:4281
	ld a, [wRam_C0D4]
	cp a, $0B
	jr nz, Label_1A_4289

; ---- code $4288-$4289 (1 bytes) [PROBABLE] 1 insn(s) reached by static flow only; seeds: exec x1; min discovery hops 0; fall-through of the jrcc at 1A:4286 (executed)
	xor a, a

; ---- code $4289-$42B0 (39 bytes) [CONFIRMED] 18 insn(s); 18 executed (in up to 1/18 scenarios)

Label_1A_4289:: ; 1A:4289
	inc a
	ld [wRam_C0D4], a
	ld a, $01
	ld [wRam_C0D6], a
	dec a
	ld [wRam_C0E5], a
	call Function_1A_4391
	call Function_1A_42DE
	call Function_1A_4317
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $0029
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	ret

; ---- code $42B0-$42DE (46 bytes) [PROBABLE] 21 insn(s) reached by static flow only; seeds: exec x21; min discovery hops 1; entered by jpcc from 1A:41F4 (PROBABLE code)

Label_1A_42B0:: ; 1A:42B0
	ld a, [wRam_C0D4]
	dec a
	jr nz, Label_1A_42B8
	ld a, $0B

Label_1A_42B8:: ; 1A:42B8
	ld [wRam_C0D4], a
	ld a, $01
	ld [wRam_C0D6], a
	dec a
	ld [wRam_C0E5], a
	call Function_1A_4391
	call Function_1A_42DE
	call Function_1A_4317
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $0029
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	ret

; ---- code $42DE-$4346 (104 bytes) [CONFIRMED] 49 insn(s); 49 executed (in up to 1/18 scenarios); entry proven: target of an executed call/far call

Function_1A_42DE:: ; 1A:42DE
	ld hl, $D4A1
	ld bc, $0A10
	ld de, $F800
	ld a, $07
	call FarCall
	dw Function_00_091C
	db BANK(Function_00_091C)
	ld a, [wRam_C0D6]
	dec a
	swap a
	ld h, a
	and a, $F0
	ld l, a
	ld a, h
	and a, $0F
	ld h, a
	add hl, hl
	add hl, hl
	ld de, $D4A1
	add hl, de
	ld bc, $0210
	ld de, $F801
	ld a, $07
	call FarCall
	dw Function_00_091C
	db BANK(Function_00_091C)
	ldh a, [rLCDC]
	call Function_00_082C
	ret

Function_1A_4317:: ; 1A:4317
	ld a, [wRam_C0D4]
	dec a
	add a, a
	ld hl, $437B
	add a, l
	ld l, a
	ld a, h
	adc a, $00
	ld h, a
	ld b, [hl]
	inc hl
	push hl
	ld de, $55A8
	ld hl, $DA40
	ld a, $1A
	call FarCall
	dw Function_00_0A82
	db BANK(Function_00_0A82)
	pop hl
	ld a, [hl]
	ld [wSpriteSlots + 65], a
	ld a, $15
	ld [wSpriteSlots + 64], a
	ld a, [wRam_C0E5]
	or a, a
	jr z, Label_1A_4351

; ---- code $4346-$4351 (11 bytes) [PROBABLE] 4 insn(s) reached by static flow only; seeds: exec x4; min discovery hops 0; fall-through of the jrcc at 1A:4344 (executed)
	ld de, $2048
	ld hl, $DA20
	call Function_00_0A65
	jr Label_1A_435A

; ---- code $4351-$437B (42 bytes) [CONFIRMED] 17 insn(s); 17 executed (in up to 1/18 scenarios)

Label_1A_4351:: ; 1A:4351
	ld de, $00A0
	ld hl, $DA20
	call Function_00_0A65

Label_1A_435A:: ; 1A:435A
	ld a, [wRam_C0D8]
	ld b, a
	ld a, [wRam_C0E5]
	add a, $05
	cp a, b
	jr nc, Label_1A_4371
	ld de, $7848
	ld hl, $DA30
	call Function_00_0A65
	jr Label_1A_437A

Label_1A_4371:: ; 1A:4371
	ld de, $00A0
	ld hl, $DA30
	call Function_00_0A65

Label_1A_437A:: ; 1A:437A
	ret

; ---- data $437B-$437F (4 bytes) [CONFIRMED] read as data by executed code (in up to 1/18 scenarios); content class unknown

Data_1A_437B:: ; 1A:437B
	db $00, $08, $01, $14

; ---- data $437F-$4391 (18 bytes) [HYPOTHESIS] UNCLASSIFIED 18 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_437F:: ; 1A:437F
	db $02, $20, $03, $2C, $04, $38, $05, $44, $06, $50, $07, $5C, $08, $68, $09, $74
	db $0A, $80

; ---- code $4391-$4439 (168 bytes) [CONFIRMED] 83 insn(s); 83 executed (in up to 1/18 scenarios); entry proven: target of an executed call/far call

Function_1A_4391:: ; 1A:4391
	ldh [hScratchA], a
	ldh a, [hWRAMBank]
	push af
	ldh a, [hScratchA]
	ld a, $02
	ldh [hWRAMBank], a
	ldh [rSVBK], a
	xor a, a
	ld bc, $0A00
	ld hl, $D000
	call FillBytes
	ld d, $00

Label_1A_43AA:: ; 1A:43AA
	ld a, [wRam_C0D4]
	ld hl, $4439
	dec a
	add a, a
	add a, l
	ld l, a
	ld a, h
	adc a, $00
	ld h, a
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, [hli]
	ld [wRam_C0D8], a
	ld a, [wRam_C0E5]
	add a, d
	add a, a
	add a, l
	ld l, a
	ld a, h
	adc a, $00
	ld h, a
	ld a, [hli]
	ld h, [hl]
	ld l, a
	push de
	ld a, d
	add a, a
	ldh [hRam_FFB1], a
	ld a, $05
	ldh [hRam_FFB2], a
	ld de, $D000
	ld a, $02
	ldh [hRam_FFB0], a
	ld bc, $0010
	ld a, $1A
	call FarCall
	dw Function_48_415A
	db BANK(Function_48_415A)
	call Function_00_0392
	pop de
	inc d
	ld a, d
	cp a, $05
	jr z, Label_1A_43F9
	ld b, a
	ld a, [wRam_C0D8]
	cp a, b
	jr nz, Label_1A_43AA

Label_1A_43F9:: ; 1A:43F9
	ld de, $9000
	ld hl, $D000
	ld a, $00
	ld b, $92
	ld c, $40
	call FarCall
	dw Function_00_0787
	db BANK(Function_00_0787)
	ld de, $9400
	ld hl, $D400
	ld a, $00
	ld b, $92
	ld c, $40
	call FarCall
	dw Function_00_0787
	db BANK(Function_00_0787)
	ld de, $8800
	ld hl, $D800
	ld a, $00
	ld b, $95
	ld c, $20
	call FarCall
	dw Function_00_0787
	db BANK(Function_00_0787)
	ldh [hScratchA], a
	pop af
	ldh [hWRAMBank], a
	ldh [rSVBK], a
	ldh a, [hScratchA]
	ret

; ---- data $4439-$443D (4 bytes) [CONFIRMED] read as data by executed code (in up to 1/18 scenarios); content class unknown

Data_1A_4439:: ; 1A:4439
	db $4F, $44, $C7, $44

; ---- data $443D-$444F (18 bytes) [HYPOTHESIS] UNCLASSIFIED 18 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_443D:: ; 1A:443D
	db $E0, $44, $3F, $45, $6B, $45, $A8, $45, $08, $46, $F9, $46, $05, $47, $1E, $47
	db $36, $47

; ---- data $444F-$4450 (1 bytes) [CONFIRMED] read as data by executed code (in up to 1/18 scenarios); content class unknown [clipped from 444F-445A by higher-priority evidence]

Data_1A_444F:: ; 1A:444F
	db $09

; ---- ptrtable $4450-$4462 (18 bytes) [PROBABLE] little-endian word table, 12 entries, monotone=0.82, 75% of targets on string start/after NUL, targets $4462..$4583; regular record stride between targets [clipped from 4450-4468 by higher-priority proposals]

Table_1A_4450:: ; 1A:4450
	dw String_1A_4462
	dw $446D
	dw $4476
	dw $447F
	dw $448E
	dw Data_1A_449D
	dw String_1A_44A4
	dw $44B1
	dw $44BC

; ---- text $4462-$449D (59 bytes) [PROBABLE] text: 5 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_4462:: ; 1A:4462
	db $83, $41, $83, $4A, $83, $45, $83, $93, $83, $67, $00, $82, $A0, $82, $C4, $82
	db $B3, $82, $AB, $00, $83, $41, $83, $68, $83, $8C, $83, $58, $00, $83, $41, $83
	db $68, $83, $8C, $83, $58, $82, $BF, $82, $E5, $82, $A4, $00, $83, $43, $83, $93
	db $83, $5E, $81, $5B, $83, $6C, $83, $62, $83, $67, $00

; ---- data $449D-$44A4 (7 bytes) [HYPOTHESIS] UNCLASSIFIED 7 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_449D:: ; 1A:449D
	db $83, $45, $83, $46, $83, $75, $00

; ---- text $44A4-$44C7 (35 bytes) [PROBABLE] text: 3 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_44A4:: ; 1A:44A4
	db $83, $45, $83, $46, $83, $75, $83, $54, $83, $43, $83, $67, $00, $83, $49, $83
	db $74, $83, $89, $83, $43, $83, $93, $00, $83, $49, $83, $93, $83, $89, $83, $43
	db $83, $93, $00

; ---- data $44C7-$44CC (5 bytes) [CONFIRMED] read as data by executed code (in up to 1/18 scenarios); content class unknown [clipped from 44C7-44E0 by higher-priority evidence]

Data_1A_44C7:: ; 1A:44C7
	db $02, $CC, $44, $D5, $44

; ---- text $44CC-$44E0 (20 bytes) [PROBABLE] text: 2 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_44CC:: ; 1A:44CC
	db $82, $A9, $82, $A8, $82, $E0, $82, $B6, $00, $83, $52, $83, $93, $83, $65, $83
	db $93, $83, $63, $00

; ---- data $44E0-$44FF (31 bytes) [HYPOTHESIS] UNCLASSIFIED 31 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_44E0:: ; 1A:44E0
	db $08, $F1, $44, $F8, $44, $FF, $44, $08, $45, $11, $45, $20, $45, $2D, $45, $36
	db $45, $83, $54, $81, $5B, $83, $6F, $00, $83, $54, $83, $43, $83, $67, $00

; ---- text $44FF-$453F (64 bytes) [PROBABLE] text: 6 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_44FF:: ; 1A:44FF
	db $83, $57, $83, $83, $83, $93, $83, $76, $00, $82, $B6, $82, $E3, $82, $B5, $82
	db $F1, $00, $82, $B5, $82, $E5, $82, $AB, $82, $C6, $82, $A4, $82, $EB, $82, $AD
	db $00, $83, $5A, $83, $4C, $83, $85, $83, $8A, $83, $65, $83, $42, $00, $82, $B9
	db $82, $C2, $82, $BC, $82, $AD, $00, $82, $BB, $82, $A4, $82, $B5, $82, $F1, $00

; ---- data $453F-$4546 (7 bytes) [HYPOTHESIS] UNCLASSIFIED 7 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_453F:: ; 1A:453F
	db $03, $46, $45, $4F, $45, $5C, $45

; ---- text $4546-$456B (37 bytes) [PROBABLE] text: 3 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_4546:: ; 1A:4546
	db $83, $5E, $83, $43, $83, $67, $83, $8B, $00, $83, $5F, $83, $45, $83, $93, $83
	db $8D, $81, $5B, $83, $68, $00, $82, $C2, $82, $A4, $82, $B5, $82, $F1, $83, $47
	db $83, $89, $81, $5B, $00

; ---- text $456B-$45A8 (61 bytes) [PROBABLE] text block: 7 string(s) (analysis/strings.tsv, per-string NUL termination noted there); Shift-JIS/ASCII [clipped from 4546-45A8 by higher-priority evidence]

String_1A_456B:: ; 1A:456B
	db $04, $74, $45, $81, $45, $8C, $45, $97, $45, $83, $6A, $83, $62, $83, $4E, $83
	db $6C, $81, $5B, $83, $80, $00, $82, $C9, $82, $F1, $82, $B5, $82, $E5, $82, $A4
	db $00, $83, $6C, $83, $60, $83, $50, $83, $62, $83, $67, $00, $83, $6C, $83, $62
	db $83, $67, $83, $54, $81, $5B, $83, $74, $83, $42, $83, $93, $00

; ---- data $45A8-$45B7 (15 bytes) [HYPOTHESIS] UNCLASSIFIED 15 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_45A8:: ; 1A:45A8
	db $07, $B7, $45, $C2, $45, $D1, $45, $DA, $45, $E5, $45, $F2, $45, $FB, $45

; ---- text $45B7-$4608 (81 bytes) [PROBABLE] text: 7 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_45B7:: ; 1A:45B7
	db $83, $70, $83, $58, $83, $8F, $81, $5B, $83, $68, $00, $83, $74, $83, $46, $83
	db $43, $83, $58, $83, $7D, $81, $5B, $83, $4E, $00, $83, $75, $83, $89, $83, $45
	db $83, $55, $00, $83, $76, $83, $8D, $83, $6F, $83, $43, $83, $5F, $00, $83, $79
	db $81, $5B, $83, $57, $83, $8A, $83, $58, $83, $67, $00, $82, $D6, $82, $F1, $82
	db $B5, $82, $F1, $00, $83, $7A, $81, $5B, $83, $80, $83, $79, $81, $5B, $83, $57
	db $00

; ---- data $4608-$4609 (1 bytes) [HYPOTHESIS] UNCLASSIFIED 1 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_4608:: ; 1A:4608
	db $0E

; ---- ptrtable $4609-$4625 (28 bytes) [PROBABLE] little-endian word table, 14 entries, monotone=1.00, 100% of targets on string start/after NUL, targets $4625..$46E4

Table_1A_4609:: ; 1A:4609
	dw String_1A_4625
	dw $462E
	dw Data_1A_4637
	dw String_1A_463E
	dw $464D
	dw $465A
	dw $4667
	dw $4674
	dw $467D
	dw $4692
	dw $46AB
	dw $46C0
	dw $46D1
	dw $46E4

; ---- text $4625-$4637 (18 bytes) [PROBABLE] text: 2 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_4625:: ; 1A:4625
	db $83, $81, $81, $5B, $83, $89, $81, $5B, $00, $83, $81, $83, $8B, $82, $C6, $82
	db $E0, $00

; ---- data $4637-$463E (7 bytes) [HYPOTHESIS] UNCLASSIFIED 7 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_4637:: ; 1A:4637
	db $83, $81, $81, $5B, $83, $8B, $00

; ---- text $463E-$46F9 (187 bytes) [PROBABLE] text: 11 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_463E:: ; 1A:463E
	db $83, $81, $81, $5B, $83, $8B, $83, $41, $83, $68, $83, $8C, $83, $58, $00, $83
	db $81, $81, $5B, $83, $8B, $83, $54, $81, $5B, $83, $6F, $00, $83, $81, $81, $5B
	db $83, $8B, $83, $5C, $83, $74, $83, $67, $00, $83, $81, $83, $93, $83, $65, $83
	db $69, $83, $93, $83, $58, $00, $83, $82, $83, $6F, $83, $43, $83, $8B, $00, $83
	db $82, $83, $6F, $83, $43, $83, $8B, $83, $41, $83, $5F, $83, $76, $83, $5E, $82
	db $66, $82, $61, $00, $83, $82, $83, $6F, $83, $43, $83, $8B, $83, $54, $83, $7C
	db $81, $5B, $83, $67, $83, $5A, $83, $93, $83, $5E, $81, $5B, $00, $83, $82, $83
	db $6F, $83, $43, $83, $8B, $83, $56, $83, $58, $83, $65, $83, $80, $82, $66, $82
	db $61, $00, $83, $82, $83, $6F, $83, $43, $83, $8B, $83, $5A, $83, $93, $83, $5E
	db $81, $5B, $00, $83, $82, $83, $6F, $83, $43, $83, $8B, $83, $67, $83, $8C, $81
	db $5B, $83, $69, $81, $5B, $00, $83, $82, $83, $6F, $83, $43, $83, $8B, $83, $7A
	db $81, $5B, $83, $80, $83, $79, $81, $5B, $83, $57, $00

; ---- text $46F9-$4705 (12 bytes) [PROBABLE] text block: 12 string(s) (analysis/strings.tsv, per-string NUL termination noted there); Shift-JIS/ASCII [clipped from 463E-4705 by higher-priority evidence]

String_1A_46F9:: ; 1A:46F9
	db $01, $FC, $46, $83, $86, $81, $5B, $83, $55, $81, $5B, $00

; ---- data $4705-$4711 (12 bytes) [HYPOTHESIS] UNCLASSIFIED 12 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_4705:: ; 1A:4705
	db $02, $0A, $47, $11, $47, $83, $8A, $83, $93, $83, $4E, $00

; ---- text $4711-$471E (13 bytes) [PROBABLE] text: 1 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_4711:: ; 1A:4711
	db $83, $8D, $83, $4F, $83, $43, $83, $93, $82, $68, $82, $63, $00

; ---- text $471E-$4736 (24 bytes) [PROBABLE] text block: 2 string(s) (analysis/strings.tsv, per-string NUL termination noted there); Shift-JIS/ASCII [clipped from 4711-4736 by higher-priority evidence]

String_1A_471E:: ; 1A:471E
	db $01, $21, $47, $83, $8F, $81, $5B, $83, $8B, $83, $68, $83, $8F, $83, $43, $83
	db $68, $83, $45, $83, $46, $83, $75, $00

; ---- data $4736-$4737 (1 bytes) [HYPOTHESIS] UNCLASSIFIED 1 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_4736:: ; 1A:4736
	db $0A

; ---- ptrtable $4737-$474B (20 bytes) [PROBABLE] little-endian word table, 10 entries, monotone=1.00, 100% of targets on string start/after NUL, targets $474B..$47A4; regular record stride between targets

Table_1A_4737:: ; 1A:4737
	dw String_1A_474B
	dw String_1A_475A
	dw String_1A_4763
	dw Data_1A_477E
	dw $4785
	dw $478C
	dw $4793
	dw $479A
	dw $47A1
	dw String_1A_47A4

; ---- text $474B-$475A (15 bytes) [PROBABLE] text: 1 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_474B:: ; 1A:474B
	db $82, $83, $82, $84, $82, $8D, $82, $81, $82, $6E, $82, $8E, $82, $85, $00

; ---- text $475A-$4763 (9 bytes) [PROBABLE] text block: 3 string(s) (analysis/strings.tsv, per-string NUL termination noted there); Shift-JIS/ASCII [clipped from 474B-477E by higher-priority evidence]

String_1A_475A:: ; 1A:475A
	db $82, $63, $82, $68, $82, $6E, $82, $6D, $00

; ---- text $4763-$477E (27 bytes) [CONFIRMED] text: 1 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_4763:: ; 1A:4763
	db $82, $63, $82, $68, $82, $6E, $82, $6D, $83, $82, $83, $6F, $83, $43, $83, $8B
	db $82, $66, $82, $61, $83, $52, $81, $5B, $83, $58, $00

; ---- data $477E-$47A4 (38 bytes) [HYPOTHESIS] UNCLASSIFIED 38 bytes: no code/data evidence (see analysis/mapper/unknown_spans.tsv for the hint)

Data_1A_477E:: ; 1A:477E
	db $82, $68, $82, $72, $82, $6F, $00, $82, $6F, $82, $63, $82, $62, $00, $82, $6F
	db $82, $67, $82, $72, $00, $82, $76, $82, $85, $82, $82, $00, $82, $76, $82, $76
	db $82, $76, $00, $81, $97, $00

; ---- text $47A4-$47B5 (17 bytes) [CONFIRMED] text: 1 string(s) of analysis/strings.tsv (Shift-JIS/ASCII, NUL terminated)

String_1A_47A4:: ; 1A:47A4
	db $82, $AB, $82, $B2, $82, $A4, $82, $CC, $82, $E6, $82, $DD, $82, $A9, $82, $BD
	db $00

; ---- data $47B5-$4A85 (720 bytes) [CONFIRMED] tilemap+attr: 1 call site(s); first: copy_tilemap_rect_pair at 1A:4083: hl=$47B5 a=$1A b=18 rows c=20 cols (tiles then attrs) de=$D000

Data_1A_47B5:: ; 1A:47B5
	db $B0, $B1, $B2, $B3, $BD, $B4, $B5, $B6, $B7, $B8, $B9, $BA, $BB, $BC, $BD, $BD
	db $B3, $B2, $BE, $BF, $C0, $C1, $C2, $C3, $BD, $C4, $C5, $C6, $C7, $C8, $C9, $CA
	db $CB, $CC, $CD, $BD, $C3, $C2, $CE, $CF, $D0, $D1, $D2, $D3, $D4, $D5, $D6, $D4
	db $D5, $D6, $D4, $D5, $D6, $D4, $D5, $D6, $D7, $D8, $D9, $D0, $D0, $DA, $DB, $DC
	db $DD, $DE, $DF, $E0, $E1, $E2, $E3, $E4, $E5, $E6, $E7, $E8, $E9, $EA, $EB, $D0
	db $EC, $ED, $EE, $EF, $F0, $F1, $F2, $F3, $F4, $F5, $F6, $F7, $F8, $F9, $FA, $FB
	db $FC, $FD, $FE, $EC, $D0, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
	db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $D0, $D0, $1C, $1C, $1C, $1C, $1C, $1C, $1C
	db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $D0, $D0, $1C, $1C, $1C
	db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $D0
	db $D0, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
	db $1C, $1C, $1C, $D0, $D0, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
	db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $D0, $D0, $1C, $1C, $1C, $1C, $1C, $1C, $1C
	db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $D0, $D0, $1C, $1C, $1C
	db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $D0
	db $D0, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
	db $1C, $1C, $1C, $D0, $D0, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C
	db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $D0, $D0, $1C, $1C, $1C, $1C, $1C, $1C, $1C
	db $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $1C, $D0, $FF, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $FF
	db $01, $1A, $1A, $1A, $1A, $1A, $1A, $1A, $02, $03, $04, $05, $06, $07, $08, $09
	db $0A, $0B, $0C, $0D, $BD, $BD, $BD, $BD, $BD, $BD, $BD, $BD, $0E, $0F, $10, $11
	db $12, $13, $14, $15, $16, $17, $18, $19, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A, $2A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A, $2A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $2A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	db $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A, $0A

; ---- gfx $4A85-$4A90 (11 bytes) [PROBABLE] tiles-2bpp: heuristic: 69 coherent tiles (hsim2=0.685 vsim2=0.637, 0 blank) parity 1; 1205/1216 bytes also covered by call-site blocks [clipped from 4A81-4F41 by higher-priority evidence]

Data_1A_4A85:: ; 1A:4A85
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

; ---- gfx $4A90-$4C90 (512 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 1A:403D: hl=$4A90 a=$1A c=$20 de=$8000 (dest VRAM $8000, vbank=0)

Data_1A_4A90:: ; 1A:4A90
	db $00, $00, $1F, $1F, $20, $3F, $2F, $30, $2F, $30, $2F, $30, $2F, $30, $2F, $30
	db $00, $00, $F0, $F0, $08, $F8, $E8, $18, $E8, $18, $E8, $18, $E8, $18, $E8, $18
	db $00, $00, $FF, $FF, $00, $FF, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $00, $00, $00, $00, $00, $00, $7F, $7F, $7F, $41, $7F, $7D, $1F, $15, $1F, $15
	db $00, $00, $00, $00, $00, $00, $38, $38, $7F, $6F, $7F, $41, $7F, $6D, $3F, $2D
	db $00, $00, $00, $00, $00, $00, $3E, $3E, $7F, $6B, $7F, $41, $7F, $6B, $3E, $2A
	db $00, $00, $00, $00, $00, $00, $3F, $3F, $3F, $21, $3F, $2D, $3F, $2D, $7F, $61
	db $00, $00, $00, $00, $00, $00, $0E, $0E, $7F, $7B, $7F, $41, $7F, $7B, $0E, $0A
	db $00, $00, $00, $00, $00, $00, $3E, $3E, $3E, $2A, $3E, $2A, $3E, $2A, $7F, $6B
	db $00, $00, $00, $00, $00, $00, $7F, $7F, $7F, $41, $7F, $7D, $07, $05, $0F, $0D
	db $00, $00, $00, $00, $00, $00, $38, $38, $7F, $6F, $7F, $41, $7F, $6D, $3F, $2D
	db $00, $00, $00, $00, $00, $00, $7F, $7F, $7F, $41, $7F, $7F, $7F, $41, $7F, $7D
	db $00, $00, $00, $00, $00, $00, $7F, $7F, $7F, $41, $7F, $5D, $77, $55, $77, $55
	db $00, $00, $00, $00, $00, $00, $7F, $7F, $FF, $CC, $FF, $B5, $FF, $B5, $FF, $B4
	db $00, $00, $00, $00, $00, $00, $DE, $DE, $FF, $73, $FF, $AD, $FF, $AD, $FF, $6F
	db $2F, $30, $2F, $30, $2F, $30, $2F, $30, $2F, $30, $2F, $30, $5F, $60, $3F, $40
	db $E8, $18, $E8, $18, $E8, $18, $E8, $18, $E8, $18, $E8, $18, $F4, $0C, $F8, $04
	db $03, $00, $07, $03, $0F, $04, $1C, $0B, $38, $17, $70, $2F, $7F, $3F, $7F, $00
	db $C0, $00, $E0, $C0, $F0, $20, $18, $F0, $0C, $F8, $06, $FC, $FE, $FC, $FE, $00
	db $1F, $13, $1E, $16, $3C, $34, $3C, $2C, $38, $38, $00, $00, $00, $00, $00, $00
	db $3F, $2D, $3F, $2D, $3F, $2D, $3F, $2D, $3F, $3F, $00, $00, $00, $00, $00, $00
	db $3E, $3A, $1E, $1A, $3E, $3A, $3E, $26, $3C, $3C, $00, $00, $00, $00, $00, $00
	db $7F, $5D, $7F, $7D, $1F, $1B, $1E, $16, $1C, $1C, $00, $00, $00, $00, $00, $00
	db $0E, $0A, $0E, $0A, $3E, $3A, $3E, $26, $3C, $3C, $00, $00, $00, $00, $00, $00
	db $7F, $5D, $77, $55, $77, $55, $77, $55, $77, $77, $00, $00, $00, $00, $00, $00
	db $3F, $3B, $3E, $2A, $3E, $36, $1E, $1A, $0E, $0E, $00, $00, $00, $00, $00, $00
	db $3F, $2B, $3E, $2E, $38, $28, $38, $28, $38, $38, $00, $00, $00, $00, $00, $00
	db $07, $05, $07, $05, $3F, $3D, $3F, $23, $3E, $3E, $00, $00, $00, $00, $00, $00
	db $77, $75, $07, $05, $3F, $3D, $3F, $23, $3E, $3E, $00, $00, $00, $00, $00, $00
	db $FF, $B5, $FF, $85, $FF, $B5, $FF, $B4, $FF, $FF, $00, $00, $00, $00, $00, $00
	db $FF, $AF, $FF, $AD, $FF, $AD, $FF, $73, $DE, $DE, $00, $00, $00, $00, $00, $00

; ---- gfx $4C90-$5090 (1024 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 1A:404F: hl=$4C90 a=$1A c=$40 de=$8B01 (dest VRAM $8B00, vbank=1)

Data_1A_4C90:: ; 1A:4C90
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FE, $01, $FC, $03
	db $F2, $07, $F2, $07, $F3, $07, $F3, $06, $F3, $06, $F3, $06, $33, $C6, $93, $C6
	db $00, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $04, $FE, $04, $FE, $FC, $FE, $FC, $06, $0C, $06, $0C, $06, $0C, $06, $0C, $06
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $07, $FC, $04, $FC, $04, $FF, $07
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FE, $FF, $03, $03, $03, $03, $3F, $3F
	db $FF, $00, $FF, $00, $FF, $0F, $F9, $09, $F9, $F9, $29, $21, $25, $27, $23, $27
	db $FF, $00, $FF, $00, $FF, $E0, $3F, $20, $3F, $23, $3C, $26, $38, $FC, $E8, $F0
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $FF, $64, $64, $64, $64, $64, $E4
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $8F, $F9, $89, $F9, $89, $F9, $89
	db $FF, $00, $FF, $00, $FF, $FE, $93, $92, $93, $93, $92, $92, $FE, $FE, $FF, $03
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $FF, $01, $01, $01, $01, $8F, $CF
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $F0, $9F, $90, $9F, $90, $9F, $9E
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $4F, $E0, $4F, $E0, $CF, $E0, $CF, $60, $CF, $60, $CF, $60, $CC, $63, $C9, $67
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $7F, $80, $3F, $80
	db $FD, $03, $FC, $03, $FE, $00, $FF, $00, $F0, $00, $E0, $0F, $CF, $1F, $97, $3C
	db $D3, $C6, $93, $C6, $33, $06, $F3, $06, $03, $0E, $07, $FC, $FE, $F8, $FC, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $0C, $06, $0C, $06, $0C, $06, $0C, $06, $0C, $06, $0C, $06, $0C, $06, $0C, $06
	db $FC, $04, $FC, $04, $FF, $07, $FF, $01, $FF, $01, $FF, $01, $FF, $00, $FF, $00
	db $03, $03, $02, $03, $3E, $3E, $3E, $3E, $02, $02, $02, $82, $FF, $FF, $FF, $00
	db $23, $23, $21, $33, $31, $71, $51, $79, $79, $49, $79, $49, $FF, $CF, $FF, $00
	db $00, $01, $01, $03, $F3, $F2, $F3, $12, $F3, $12, $F3, $12, $FF, $1E, $FF, $00
	db $E4, $A4, $E4, $24, $E4, $24, $C4, $64, $C4, $4C, $CC, $4C, $FB, $7F, $FF, $00
	db $F9, $89, $F9, $89, $E9, $F9, $99, $99, $18, $18, $30, $3C, $FF, $E7, $FF, $00
	db $FF, $78, $CF, $48, $CF, $48, $CF, $C8, $0F, $08, $0F, $18, $FF, $F0, $FF, $00
	db $8F, $98, $9F, $90, $9F, $98, $9F, $8F, $81, $C1, $C1, $61, $FF, $3F, $FF, $00
	db $81, $83, $81, $81, $81, $89, $99, $99, $98, $98, $94, $9C, $FF, $F7, $FF, $00
	db $FF, $00, $FF, $00, $FF, $00, $FF, $C0, $7F, $40, $7F, $40, $FF, $C0, $FF, $00
	db $CB, $67, $C9, $67, $CC, $60, $CF, $60, $C0, $70, $E0, $3F, $7F, $1F, $3F, $00
	db $BF, $80, $3F, $80, $7F, $00, $FF, $00, $0F, $00, $07, $F0, $F3, $F8, $E9, $3C
	db $96, $3C, $96, $3C, $96, $3C, $96, $3C, $96, $3C, $96, $3C, $96, $3C, $96, $3C
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $0F, $00, $1F, $0F
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $E0, $00, $F1, $E0
	db $0C, $07, $06, $03, $03, $01, $01, $00, $00, $00, $00, $00, $FE, $00, $FF, $FE
	db $00, $00, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $0F, $00, $1F, $0F
	db $00, $00, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $E0, $00, $F1, $E0
	db $00, $00, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $FE, $00, $FF, $FE
	db $30, $E0, $60, $C0, $C0, $80, $80, $00, $00, $00, $00, $00, $0F, $00, $1F, $0F
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $FF, $00, $FF, $FF
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $F0, $00, $F8, $F0
	db $30, $1F, $30, $18, $30, $1F, $30, $1E, $30, $1E, $30, $1E, $30, $1E, $30, $1E
	db $1B, $F1, $1B, $31, $1B, $B1, $1B, $B1, $1B, $B1, $1B, $71, $1B, $F1, $1B, $F1
	db $01, $FF, $01, $DF, $01, $83, $01, $DB, $01, $DB, $01, $DB, $01, $DB, $01, $DB
	db $B0, $1F, $B0, $1D, $B0, $18, $B0, $1D, $B0, $1D, $B0, $1F, $B0, $1F, $B0, $1F
	db $1B, $F1, $1B, $71, $1B, $31, $1B, $71, $1B, $71, $1B, $71, $1B, $71, $1B, $71
	db $01, $FF, $01, $C3, $01, $DB, $01, $DB, $01, $C3, $01, $BB, $01, $FB, $01, $F7
	db $B0, $1F, $B0, $1F, $B0, $18, $B0, $1F, $B0, $1F, $B0, $1F, $B0, $1F, $B0, $1F
	db $1B, $F1, $1B, $71, $1B, $31, $1B, $71, $1B, $71, $1B, $71, $1B, $71, $1B, $71
	db $01, $FF, $01, $D7, $01, $D7, $01, $D7, $01, $D7, $01, $BB, $01, $BB, $01, $BB
	db $B0, $1F, $B0, $18, $B0, $1F, $B0, $1F, $B0, $1F, $B0, $1F, $B0, $1D, $B0, $1E
	db $1B, $F1, $1B, $31, $1B, $B1, $1B, $B1, $1B, $B1, $1B, $71, $1B, $71, $1B, $F1
	db $01, $FF, $01, $DF, $01, $83, $01, $DB, $01, $DB, $01, $D7, $01, $DF, $01, $DF
	db $B0, $1F, $B0, $18, $B0, $1F, $B0, $18, $B0, $1F, $B0, $1F, $B0, $1F, $B0, $1F
	db $1B, $F1, $1B, $31, $1B, $F1, $1B, $31, $1B, $B1, $1B, $B1, $1B, $B1, $1B, $B1
	db $01, $FF, $01, $83, $01, $BB, $01, $BB, $01, $BB, $01, $FB, $01, $FB, $01, $FB
	db $B0, $1F, $B0, $1C, $B0, $1B, $B0, $1B, $B0, $1B, $B0, $1B, $B0, $18, $B0, $1B
	db $00, $FF, $00, $C7, $00, $5A, $00, $5A, $00, $46, $00, $5A, $00, $5A, $00, $5A
	db $0C, $F8, $0C, $38, $0C, $D8, $0C, $D8, $0C, $F8, $0C, $F8, $0C, $D8, $0C, $D8
	db $93, $3E, $91, $3F, $90, $3F, $91, $3F, $93, $3E, $96, $3C, $96, $3C, $96, $3C
	db $F0, $1D, $F0, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $1F, $F1, $1E, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $01, $DB, $00, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00

; ---- gfx $5090-$5390 (768 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 1A:4061: hl=$5090 a=$1A c=$30 de=$8F01 (dest VRAM $8F00, vbank=1)

Data_1A_5090:: ; 1A:5090
	db $F0, $1C, $E0, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $1F, $F1, $0E, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $01, $EF, $00, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $F0, $1C, $E0, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $1F, $F1, $0E, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $01, $BB, $00, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $F0, $1F, $E0, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $1F, $71, $0E, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $01, $DF, $00, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $F0, $1C, $E0, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $1F, $71, $0E, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $01, $C7, $00, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $F0, $1B, $E0, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $00, $47, $00, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $0F, $38, $07, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00
	db $96, $3C, $96, $3C, $96, $3C, $96, $3C, $93, $3E, $91, $3F, $88, $3F, $C7, $1F
	db $00, $00, $00, $00, $00, $00, $00, $00, $FF, $00, $FF, $FF, $00, $FF, $FF, $FF
	db $E0, $0F, $F0, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $00, $FF, $00, $00, $FB, $07, $F4, $0C, $E9, $1B, $F2, $14, $F5, $15, $F5, $15
	db $00, $FF, $00, $00, $F7, $F8, $6B, $1C, $E5, $FE, $12, $1F, $CA, $CF, $CA, $CF
	db $00, $FF, $00, $00, $FF, $00, $FB, $07, $BE, $7C, $E0, $41, $C0, $5F, $E0, $45
	db $00, $FF, $00, $00, $FF, $00, $BF, $C7, $FD, $78, $00, $02, $00, $BF, $00, $0A
	db $00, $FF, $00, $00, $FF, $00, $7F, $9F, $F0, $E0, $00, $09, $00, $3C, $00, $18
	db $00, $FF, $00, $00, $FF, $00, $BF, $C0, $DF, $60, $6F, $30, $2F, $B0, $6F, $30
	db $00, $FF, $00, $00, $F7, $0F, $E8, $18, $D3, $37, $E0, $28, $EB, $2B, $EB, $2B
	db $00, $FF, $00, $00, $EF, $F0, $D7, $38, $EB, $FC, $15, $3E, $95, $9E, $95, $9E
	db $00, $FF, $00, $00, $FF, $00, $DB, $3C, $AF, $66, $C3, $51, $80, $BC, $C0, $90
	db $00, $FF, $00, $00, $FF, $00, $FF, $7F, $DA, $80, $80, $A5, $00, $25, $00, $38
	db $00, $FF, $00, $00, $FF, $00, $FE, $FF, $C3, $01, $01, $3D, $01, $11, $01, $3C
	db $07, $F0, $0F, $00, $FF, $00, $FF, $00, $7F, $80, $7F, $80, $7F, $80, $BF, $C0
	db $FC, $14, $FD, $15, $F5, $1D, $F5, $1D, $EB, $1F, $F4, $0F, $FB, $07, $FC, $03
	db $0A, $0F, $CA, $CF, $4A, $CF, $4A, $CF, $74, $FF, $09, $FE, $F3, $FC, $07, $F8
	db $B0, $75, $D4, $33, $F0, $11, $F1, $16, $F8, $10, $EF, $1F, $F0, $0F, $FF, $00
	db $00, $0A, $08, $06, $00, $02, $02, $0C, $F1, $60, $9F, $FF, $60, $9F, $FF, $00
	db $00, $28, $00, $29, $20, $19, $08, $06, $F1, $E0, $1F, $FF, $60, $9F, $FF, $00
	db $4F, $70, $5F, $60, $5F, $60, $DF, $60, $9F, $E0, $3F, $C0, $7F, $80, $FF, $00
	db $F8, $28, $FB, $2B, $EB, $3B, $E8, $38, $D7, $3F, $E8, $1F, $F7, $0F, $F8, $07
	db $15, $3E, $95, $9E, $95, $9E, $15, $3E, $E9, $FE, $13, $FC, $E7, $F8, $0F, $F0
	db $80, $BC, $C0, $91, $40, $D1, $E0, $4E, $B1, $60, $DF, $3F, $E0, $1F, $FF, $00
	db $20, $40, $00, $40, $00, $40, $80, $3C, $C3, $81, $7E, $FF, $00, $FF, $FF, $00
	db $00, $42, $28, $12, $00, $2A, $21, $1C, $C3, $81, $7E, $FF, $00, $FF, $FF, $00
	db $BF, $C0, $BF, $C0, $BF, $C0, $BF, $C0, $3F, $C0, $7F, $80, $FF, $00, $FF, $00
	db $00, $FF, $00, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

; ---- data $5390-$539A (10 bytes) [CONFIRMED] read as data by executed code (in up to 1/18 scenarios); content class unknown [clipped from 4A90-5461 by higher-priority evidence]

Data_1A_5390:: ; 1A:5390
	db $FF, $7F, $4A, $29, $B5, $56, $00, $00, $9F, $01

; ---- data $539A-$55A0 (518 bytes) [PROBABLE] CGB palette data (RGB555 words): heuristic: 288 RGB555 words as 72 palette group(s) of 4 (bit15 clear, contains $7FFF, monotone luminance) [clipped from 539A-55DA by higher-priority proposals]

Data_1A_539A:: ; 1A:539A
	db $4A, $29, $B5, $56, $FF, $7F, $FF, $7F, $2A, $03, $E0, $01, $00, $00, $00, $00
	db $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F, $00, $00
	db $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F, $00, $00
	db $4A, $29, $B5, $56, $FF, $7F, $E0, $7F, $FF, $7F, $2A, $03, $00, $00, $E0, $7F
	db $FE, $1F, $FF, $5E, $14, $00, $E0, $7F, $FF, $7F, $1F, $00, $00, $00, $00, $00
	db $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F, $00, $00
	db $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F, $00, $00
	db $4A, $29, $B5, $56, $FF, $7F, $14, $54, $1D, $54, $02, $00, $00, $12, $02, $00
	db $08, $13, $02, $02, $FF, $00, $12, $02, $FF, $08, $13, $02, $02, $00, $2E, $01
	db $08, $2F, $54, $38, $54, $02, $00, $00, $12, $42, $00, $08, $13, $42, $02, $01
	db $00, $12, $42, $01, $08, $13, $42, $02, $00, $2E, $01, $08, $48, $54, $06, $00
	db $03, $04, $01, $08, $03, $14, $01, $00, $00, $00, $00, $00, $08, $01, $00, $08
	db $00, $10, $00, $08, $08, $11, $00, $01, $00, $04, $66, $54, $06, $00, $03, $05
	db $01, $08, $03, $15, $01, $00, $00, $00, $00, $00, $08, $01, $00, $08, $00, $10
	db $00, $08, $08, $11, $00, $01, $00, $04, $84, $54, $06, $00, $03, $06, $01, $08
	db $03, $16, $01, $00, $00, $00, $00, $00, $08, $01, $00, $08, $00, $10, $00, $08
	db $08, $11, $00, $01, $00, $04, $A2, $54, $06, $00, $03, $07, $01, $08, $03, $17
	db $01, $00, $00, $00, $00, $00, $08, $01, $00, $08, $00, $10, $00, $08, $08, $11
	db $00, $01, $00, $04, $C0, $54, $06, $00, $03, $08, $01, $08, $03, $18, $01, $00
	db $00, $00, $00, $00, $08, $01, $00, $08, $00, $10, $00, $08, $08, $11, $00, $01
	db $00, $04, $DE, $54, $06, $00, $03, $09, $01, $08, $03, $19, $01, $00, $00, $00
	db $00, $00, $08, $01, $00, $08, $00, $10, $00, $08, $08, $11, $00, $01, $00, $04
	db $FC, $54, $06, $00, $03, $0A, $01, $08, $03, $1A, $01, $00, $00, $00, $00, $00
	db $08, $01, $00, $08, $00, $10, $00, $08, $08, $11, $00, $01, $00, $04, $1A, $55
	db $06, $00, $03, $0B, $01, $08, $03, $1B, $01, $00, $00, $00, $00, $00, $08, $01
	db $00, $08, $00, $10, $00, $08, $08, $11, $00, $01, $00, $04, $38, $55, $06, $00
	db $03, $0C, $01, $08, $03, $1C, $01, $00, $00, $00, $00, $00, $08, $01, $00, $08
	db $00, $10, $00, $08, $08, $11, $00, $01, $00, $04, $56, $55, $06, $00, $03, $0D
	db $01, $08, $03, $1D, $01, $00, $00, $00, $00, $00, $08, $01, $00, $08, $00, $10
	db $00, $08, $08, $11, $00, $01, $00, $04, $74, $55, $0A, $00, $04, $0E, $01, $00
	db $0C, $0F, $01, $08, $04, $1E, $01, $08, $0C, $1F, $01, $00, $00, $00, $00, $08
	db $00, $10, $00, $00, $08, $02, $00, $08, $08, $03, $00, $00, $10, $00, $20, $08
	db $10, $10, $20, $01, $00, $04

; ---- data $55A0-$55DA (58 bytes) [PROBABLE] palette-rgb555: heuristic: 288 RGB555 words as 72 palette group(s) of 4 (bit15 clear, contains $7FFF, monotone luminance) [clipped from 539A-55DA by higher-priority evidence]

Data_1A_55A0:: ; 1A:55A0
	db $10, $54, $26, $54, $2B, $54, $41, $54, $46, $54, $61, $54, $64, $54, $7F, $54
	db $82, $54, $9D, $54, $A0, $54, $BB, $54, $BE, $54, $D9, $54, $DC, $54, $F7, $54
	db $FA, $54, $15, $55, $18, $55, $33, $55, $36, $55, $51, $55, $54, $55, $6F, $55
	db $72, $55, $9D, $55, $00, $00, $00, $00, $00, $00

; ---- zero $55DA-$8000 (10790 bytes) [PROBABLE] trailing 0x00 padding to end of bank [clipped from 55D4-8000 by higher-priority proposals]
	ds $2A26, $00
