; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 7E

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank7E", ROMX[$4000], BANK[$7E]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $1F8000, $4000
