; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 25

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank25", ROMX[$4000], BANK[$25]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $94000, $4000
