; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 17

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank17", ROMX[$4000], BANK[$17]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $5C000, $4000
