; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 0D

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank0D", ROMX[$4000], BANK[$0D]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $34000, $4000
