; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 2B

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank2B", ROMX[$4000], BANK[$2B]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $AC000, $4000
