; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 52

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank52", ROMX[$4000], BANK[$52]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $148000, $4000
