; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 56

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank56", ROMX[$4000], BANK[$56]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $158000, $4000
