; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 06

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank06", ROMX[$4000], BANK[$06]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $18000, $4000
