; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 1E

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank1E", ROMX[$4000], BANK[$1E]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $78000, $4000
