; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 51

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"
INCLUDE "constants/macros.inc"

SECTION "Bank51", ROMX[$4000], BANK[$51]

; ---- code $4000-$404A (74 bytes) [CONFIRMED] 32 insn(s) reached by static flow only; seeds: exec x32; min discovery hops 1; entered by far from 24:4168 (PROBABLE code) [executed in 4 scenarios]

CommTime_ShowSummary:: ; 51:4000
	call CommTime_DrawSummaryScreen
	call CommTime_AddTimerA
	ldh a, [hRam_FFB0]
	ld [wRam_C2D8], a
	ldh a, [hRam_FFB1]
	ld [wRam_C2D9], a
	ldh a, [hRam_FFB2]
	ld [wRam_C2DA], a
	xor a, a
	ld [wTimerAFrames], a
	ld [wRam_C2D5], a
	ld [wRam_C2D6], a
	ld [wRam_C2D7], a
	ld a, $0A
	ldh [hSRAMEnable], a
	ld [rRAMG], a
	ld a, $01
	ldh [hSRAMBank], a
	ld [rRAMB], a
	ld hl, $A9F8
	ld a, [wRam_C2D8]
	ld [hli], a
	ld a, [wRam_C2D9]
	ld [hli], a
	ld a, [wRam_C2DA]
	ld [hli], a
	ld a, [wRam_C2DB]
	ld [hli], a
	xor a, a
	ldh [hSRAMEnable], a
	ld [rRAMG], a
	ret

; ---- code $404A-$40BF (117 bytes) [CONFIRMED] 42 insn(s); 42 executed (in up to 4/18 scenarios); entry proven: target of an executed call/far call

CommTime_DrawSummaryScreen:: ; 51:404A
Function_51_404A::
	call LCDOff
	ldh a, [rLCDC]
	and a, $9F
	ldh [rLCDC], a
	xor a, a
	ldh [rSCX], a
	ldh [rSCY], a
	ld a, $07
	ldh [rWX], a
	ld a, $90
	ldh [rWY], a
	farcall Function_00_09B6
	call LCDOn
	call CommTime_TimerAIsNonZero
	or a, a
	jp z, Label_51_41D3
	ld a, [wRam_C2C3]
	cp a, $01
	jr z, Label_51_40BF
	ld de, $9001
	ld hl, Data_51_4DB0
	ld a, $51
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld de, $9401
	ld hl, Data_51_51B0
	ld a, $51
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld bc, $0040
	ld de, $D800
	ld hl, Data_51_5880
	ld a, $51
	farcall Palette_LoadToBuffer
	ld bc, $1214
	ld de, $D000
	ld hl, Tilemap_CommTime_SummaryB
	ld a, $51
	farcall Function_00_08EA
	jr Label_51_4105

; ---- code $40BF-$4105 (70 bytes) [CONFIRMED] 22 insn(s) reached by static flow only; seeds: exec x22; min discovery hops 1; entered by jrcc from 51:4075 (executed) [executed in 1 scenarios]

Label_51_40BF:: ; 51:40BF
	ld de, $9001
	ld hl, Data_51_42A0
	ld a, $51
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld de, $9401
	ld hl, Data_51_46A0
	ld a, $51
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld bc, $0040
	ld de, $D800
	ld hl, Data_51_4D70
	ld a, $51
	farcall Palette_LoadToBuffer
	ld bc, $1214
	ld de, $D000
	ld hl, Tilemap_CommTime_SummaryA
	ld a, $51
	farcall Function_00_08EA

; ---- code $4105-$4112 (13 bytes) [CONFIRMED] 6 insn(s); 6 executed (in up to 2/18 scenarios)

Label_51_4105:: ; 51:4105
	ld a, [wRam_C2D6]
	ld l, a
	ld h, $00
	cp a, $3C
	ld a, [wRam_C2D5]
	jr c, Label_51_4117

; ---- code $4112-$4117 (5 bytes) [PROBABLE] 2 insn(s) reached by static flow only; seeds: exec x2; min discovery hops 0; fall-through of the jrcc at 51:4110 (executed)
	ld hl, $003B
	ld a, $3B

; ---- code $4117-$4125 (14 bytes) [CONFIRMED] 6 insn(s); 6 executed (in up to 2/18 scenarios)

Label_51_4117:: ; 51:4117
	ldh [hRam_FFB1], a
	ld a, [wRam_C2C3]
	cp a, $01
	jr z, Label_51_4125
	ld de, $D162
	jr Label_51_4128

; ---- code $4125-$4128 (3 bytes) [CONFIRMED] 1 insn(s) reached by static flow only; seeds: exec x1; min discovery hops 1; entered by jrcc from 51:411E (executed) [executed in 1 scenarios]

Label_51_4125:: ; 51:4125
	ld de, $D162

; ---- code $4128-$4147 (31 bytes) [CONFIRMED] 13 insn(s); 13 executed (in up to 2/18 scenarios)

Label_51_4128:: ; 51:4128
	xor a, a
	ldh [hRam_FFB4], a
	ld bc, $FF9C
	call CommTime_DrawNumber
	ld bc, $FFF6
	call CommTime_DrawNumber
	ld a, l
	call CommTime_PutDigit
	ld a, [wRam_C2C3]
	cp a, $01
	jr z, Label_51_4147
	ld de, $D167
	jr Label_51_414A

; ---- code $4147-$414A (3 bytes) [CONFIRMED] 1 insn(s) reached by static flow only; seeds: exec x1; min discovery hops 1; entered by jrcc from 51:4140 (executed) [executed in 1 scenarios]

Label_51_4147:: ; 51:4147
	ld de, $D167

; ---- code $414A-$4186 (60 bytes) [CONFIRMED] 25 insn(s); 25 executed (in up to 2/18 scenarios)

Label_51_414A:: ; 51:414A
	ldh a, [hRam_FFB1]
	ld l, a
	ld h, $00
	xor a, a
	ldh [hRam_FFB4], a
	ld bc, $FFF6
	call CommTime_DrawNumber
	ld a, l
	call CommTime_PutDigit
	ldh a, [rLCDC]
	call Function_00_07CB
	farcall Function_00_0956
	farcall Palette_FadeInFromWhite
	ld a, [wRam_C2C3]
	cp a, $01
	jr z, Label_51_4186
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $000D
	call Function_00_20E8
	pop af
	ldh [rSVBK], a
	jr Label_51_4196

; ---- code $4186-$4196 (16 bytes) [CONFIRMED] 8 insn(s) reached by static flow only; seeds: exec x8; min discovery hops 1; entered by jrcc from 51:4172 (executed) [executed in 1 scenarios]

Label_51_4186:: ; 51:4186
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $000D
	call Function_00_20E8
	pop af
	ldh [rSVBK], a

; ---- code $4196-$41B1 (27 bytes) [CONFIRMED] 7 insn(s); 7 executed (in up to 2/18 scenarios)

Label_51_4196:: ; 51:4196
	xor a, a
	ldh [hRam_FFF6], a

Label_51_4199:: ; 51:4199
	farcall Function_00_0956
	call Function_00_044B
	farcall Joypad_UpdateIdleFrames
	farcall Joypad_UpdateUnsaved
	call JoypadDispatch

; ---- ptrtable $41B1-$41BB (10 bytes) [CONFIRMED] inline table of `call $056A` (JoypadDispatch) at 51:41AE: 5 entries; fixed length (5 words) by the routine

Table_51_41B1:: ; 51:41B1
	dw Label_51_41BB
	dw Label_51_41BE
	dw Label_51_41C1
	dw Label_51_41C4
	dw Label_51_4199

; ---- code $41BB-$41BE (3 bytes) [CONFIRMED] 1 insn(s); 1 executed (in up to 2/18 scenarios)

Label_51_41BB:: ; 51:41BB
	jp Label_51_41C7

; ---- code $41BE-$41C7 (9 bytes) [PROBABLE] 3 insn(s) reached by static flow only; seeds: exec x3; min discovery hops 1; entered by table from 51:41AE (executed)

Label_51_41BE:: ; 51:41BE
	jp Label_51_4199

Label_51_41C1:: ; 51:41C1
	jp Label_51_4199

Label_51_41C4:: ; 51:41C4
	jp Label_51_4199

; ---- code $41C7-$41E6 (31 bytes) [CONFIRMED] 14 insn(s); 14 executed (in up to 4/18 scenarios)

Label_51_41C7:: ; 51:41C7
	farcall Palette_FadeOutToWhite
	farcall Function_00_09B6

Label_51_41D3:: ; 51:41D3
	ldh [hRam_FFA7], a
	ldh a, [hRam_FFF6]
	ret

CommTime_DrawNumber:: ; 51:41D8
	inc a
	add hl, bc
	bit 7, h
	jr z, CommTime_DrawNumber
	dec a
	jr nz, Label_51_41E8
	ldh a, [hRam_FFB4]
	or a, a
	jr z, Label_51_41F3

; ---- code $41E6-$41F3 (13 bytes) [PROBABLE] 8 insn(s) reached by static flow only; seeds: exec x8; min discovery hops 0; fall-through of the jrcc at 51:41E4 (executed)
	ld a, $00

Label_51_41E8:: ; 51:41E8
	push bc
	push hl
	call CommTime_PutDigit
	pop hl
	pop bc
	ld a, $FF
	ldh [hRam_FFB4], a

; ---- code $41F3-$4225 (50 bytes) [CONFIRMED] 39 insn(s); 39 executed (in up to 2/18 scenarios)

Label_51_41F3:: ; 51:41F3
	inc de
	dec bc
	ld a, c
	cpl
	ld c, a
	ld a, b
	cpl
	ld b, a
	add hl, bc
	xor a, a
	ret

CommTime_PutDigit:: ; 51:41FE
	push bc
	push de
	ld h, d
	ld l, e
	add a, a
	add a, $25
	ld e, a
	ld a, $00
	adc a, $42
	ld d, a
	ld a, [de]
	ld [hl], a
	inc de
	ld bc, $0400
	add hl, bc
	ld a, $08
	ld [hl], a
	ld bc, $FC20
	add hl, bc
	ld a, [de]
	ld [hl], a
	ld bc, $0400
	add hl, bc
	ld a, $08
	ld [hl], a
	pop de
	pop bc
	ret

; ---- data $4225-$4239 (20 bytes) [PROBABLE] byte_pair_table: 10 x 2 bytes, indexed by the code at 51:4200-4224 (de = $4225 + 2*a via add a,a / add a,$25 / adc a,$42, two ld a,[de] reads); end = start of the next function at 51:4239; meaning of the values unknown (verified structure, layout from engine code)

Table_CommTime_DigitTiles:: ; 51:4225
Data_51_4225::
	db $67, $77, $68, $78, $69, $79, $69, $6F, $6A, $7A, $6B, $7B, $6C, $7C, $6D, $7D
	db $6E, $7E, $6E, $7F

; ---- code $4239-$426C (51 bytes) [CONFIRMED] 26 insn(s); 26 executed (in up to 7/18 scenarios); entry proven: target of an executed call/far call

CommTime_TimerAIsNonZero:: ; 51:4239
Function_51_4239::
	push hl
	ld hl, $C2D4
	ld a, [hli]
	or a, [hl]
	inc hl
	or a, [hl]
	inc hl
	or a, [hl]
	pop hl
	ret

CommTime_Reset:: ; 51:4245
	xor a, a
	ld [wRam_C2D8], a
	ld [wRam_C2D9], a
	ld [wRam_C2DA], a
	ld [wRam_C2DB], a
	ld [wTimerAFrames], a
	ld [wRam_C2D5], a
	ld [wRam_C2D6], a
	ld [wRam_C2D7], a
	ret

CommTime_AddTimerA:: ; 51:425F
	ld hl, $C2D8
	ld a, [wTimerAFrames]
	add a, [hl]
	ldh [hRam_FFB0], a
	sub a, $3C
	jr c, Label_51_426F

; ---- code $426C-$426F (3 bytes) [PROBABLE] 2 insn(s) reached by static flow only; seeds: exec x2; min discovery hops 0; fall-through of the jrcc at 51:426A (executed)
	ldh [hRam_FFB0], a
	xor a, a

; ---- code $426F-$427B (12 bytes) [CONFIRMED] 7 insn(s); 7 executed (in up to 5/18 scenarios)

Label_51_426F:: ; 51:426F
	ccf
	inc hl
	ld a, [wRam_C2D5]
	adc a, [hl]
	ldh [hRam_FFB1], a
	sub a, $3C
	jr c, Label_51_427E

; ---- code $427B-$427E (3 bytes) [PROBABLE] 2 insn(s) reached by static flow only; seeds: exec x2; min discovery hops 0; fall-through of the jrcc at 51:4279 (executed)
	ldh [hRam_FFB1], a
	xor a, a

; ---- code $427E-$428C (14 bytes) [CONFIRMED] 8 insn(s); 8 executed (in up to 5/18 scenarios)

Label_51_427E:: ; 51:427E
	ccf
	inc hl
	ld a, [wRam_C2D6]
	adc a, [hl]
	ldh [hRam_FFB2], a
	jr c, Label_51_428C
	cp a, $3C
	jr c, Label_51_4292

; ---- code $428C-$4292 (6 bytes) [PROBABLE] 3 insn(s) reached by static flow only; seeds: exec x3; min discovery hops 0; entered by jrcc from 51:4286 (executed)

Label_51_428C:: ; 51:428C
	ld a, $3B
	ldh [hRam_FFB2], a
	ldh [hRam_FFB1], a

; ---- code $4292-$429A (8 bytes) [CONFIRMED] 5 insn(s); 5 executed (in up to 5/18 scenarios)

Label_51_4292:: ; 51:4292
	ldh a, [hRam_FFB2]
	ld l, a
	ld h, $00
	ldh a, [hRam_FFB1]
	ret

; ---- zero $429A-$42A0 (6 bytes) [PROBABLE] 6 x 00 between the code ending at 429A (ret at 4299) and the tile block at 51:42A0 (alignment)
	ds $6, $00

; ---- gfx $42A0-$46A0 (1024 bytes) [PROBABLE] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 51:40CB: hl=$42A0 a=$51 c=$40 de=$9001 (dest VRAM $9000, vbank=1) [verifier: call site never executed in a trace -> PROBABLE]

Data_51_42A0:: ; 51:42A0
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $00, $00, $00, $FF, $FF, $00, $FE, $01, $FD, $03, $FF, $02, $FE, $02, $FE, $02
	db $00, $00, $00, $FF, $FF, $00, $F7, $F8, $9B, $0C, $6F, $64, $67, $64, $67, $64
	db $00, $00, $00, $FF, $FF, $00, $FF, $20, $FF, $BE, $63, $62, $BF, $2A, $FD, $28
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FE, $02, $FE, $02, $FE, $02, $FE, $02, $FE, $02, $FF, $03, $FC, $00, $FF, $00
	db $67, $64, $07, $04, $07, $04, $67, $64, $67, $64, $9F, $9C, $63, $00, $FF, $00
	db $DF, $08, $FF, $08, $FF, $48, $F7, $54, $FF, $94, $EB, $A2, $5D, $00, $FF, $00
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $E0, $C0, $87, $80, $9F, $0F, $3E, $11, $3B, $21, $71, $21, $79, $23, $6E, $3F
	db $00, $00, $FF, $00, $FF, $FF, $00, $FF, $0F, $FF, $0F, $F8, $00, $FF, $00, $FF
	db $00, $00, $FF, $00, $FF, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $FF, $00, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F
	db $00, $00, $00, $FF, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $7F, $E0, $9F, $90
	db $00, $00, $00, $FF, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $F1, $00, $F5, $00, $F1, $00, $FF, $00, $01
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $01
	db $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $FF, $00, $F7, $00, $B7
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $76, $FC, $9E, $C4, $8E, $84, $DC, $84, $7C, $88, $F9, $F0, $E1, $01, $07, $03
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $9F, $00, $6F, $00, $6F, $00, $9F, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $9F, $00, $6F, $00, $6F, $00, $9F, $00, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $6E, $3F, $79, $23, $71, $21, $3B, $21, $3E, $11, $9F, $0F, $87, $80, $E0, $C0
	db $FF, $90, $EF, $88, $FF, $88, $77, $04, $FF, $04, $FB, $00, $FF, $00, $FF, $00
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $00, $FD, $00, $FD, $00, $FD, $00, $FB, $00, $FB, $00, $F7, $00, $8F, $00, $FF
	db $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $01, $00, $FF
	db $00, $B7, $00, $BB, $00, $BB, $00, $BB, $00, $7D, $00, $7D, $00, $7D, $00, $FF

; ---- gfx $46A0-$4AA0 (1024 bytes) [PROBABLE] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 51:40DD: hl=$46A0 a=$51 c=$40 de=$9401 (dest VRAM $9400, vbank=1) [verifier: call site never executed in a trace -> PROBABLE]

Data_51_46A0:: ; 51:46A0
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FD, $00, $FB
	db $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $FF, $00, $81, $00, $BD
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $BF, $00, $BF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $C7
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $87, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $BF, $00, $BF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $EF, $00, $EF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $DF, $00, $DB
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $87, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $7D, $00, $7D
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F7, $00, $01
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $DF, $00, $DF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $83
	db $00, $F7, $00, $CF, $00, $2F, $00, $EF, $00, $EF, $00, $EF, $00, $EF, $00, $FF
	db $00, $BD, $00, $4D, $00, $F5, $00, $F9, $00, $FB, $00, $F7, $00, $8F, $00, $FF
	db $00, $B3, $00, $8F, $00, $BF, $00, $7F, $00, $7F, $00, $7F, $00, $83, $00, $FF
	db $00, $AB, $00, $6D, $00, $6D, $00, $6D, $00, $6D, $00, $6D, $00, $9B, $00, $FF
	db $00, $03, $00, $FD, $00, $FD, $00, $FD, $00, $FB, $00, $F7, $00, $CF, $00, $FF
	db $00, $83, $00, $7D, $00, $FD, $00, $FD, $00, $FD, $00, $FB, $00, $C7, $00, $FF
	db $00, $BF, $00, $BF, $00, $BF, $00, $BD, $00, $BD, $00, $BB, $00, $C7, $00, $FF
	db $00, $DF, $00, $DF, $00, $9F, $00, $AD, $00, $AD, $00, $6D, $00, $73, $00, $FF
	db $00, $0D, $00, $B5, $00, $B7, $00, $77, $00, $77, $00, $F7, $00, $CF, $00, $FF
	db $00, $77, $00, $43, $00, $35, $00, $75, $00, $55, $00, $E3, $00, $CF, $00, $FF
	db $00, $83, $00, $7D, $00, $FD, $00, $FD, $00, $FD, $00, $FB, $00, $C7, $00, $FF
	db $00, $7D, $00, $7D, $00, $7D, $00, $BD, $00, $FB, $00, $F7, $00, $CF, $00, $FF
	db $00, $F7, $00, $F7, $00, $F1, $00, $F7, $00, $87, $00, $73, $00, $8D, $00, $FF
	db $00, $F7, $00, $01, $00, $F7, $00, $F7, $00, $87, $00, $73, $00, $8D, $00, $FF
	db $00, $03, $00, $BF, $00, $B1, $00, $BF, $00, $7F, $00, $6F, $00, $71, $00, $FF
	db $00, $FD, $00, $FB, $00, $FF, $00, $FF, $00, $BF, $00, $BF, $00, $C1, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $DF, $00, $DB
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $7B
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $B5, $00, $BF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FB, $00, $7B
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $CF, $00, $F7
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $FF, $00, $0F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $FF, $00, $01
	db $00, $FF, $00, $FF, $00, $FF, $42, $81, $00, $81, $00, $99, $00, $99, $00, $99
	db $00, $FF, $00, $FF, $00, $FF, $00, $F3, $10, $E3, $20, $C3, $40, $83, $00, $F3
	db $00, $FF, $00, $FF, $00, $FF, $42, $81, $00, $81, $00, $99, $00, $99, $08, $F1
	db $00, $FF, $00, $FF, $00, $FF, $00, $F3, $10, $E3, $00, $E3, $20, $C3, $00, $C3
	db $00, $FF, $00, $FF, $00, $FF, $00, $81, $00, $81, $00, $9F, $00, $9F, $00, $9F
	db $00, $FF, $00, $FF, $00, $FF, $42, $81, $00, $81, $00, $99, $00, $99, $00, $9F
	db $00, $FF, $00, $FF, $00, $FF, $00, $81, $00, $81, $00, $99, $00, $99, $08, $F1
	db $00, $FF, $00, $FF, $00, $FF, $42, $81, $00, $81, $00, $99, $00, $99, $00, $99
	db $00, $E3, $02, $E1, $08, $F1, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF
	db $00, $0D, $00, $B5, $00, $B7, $00, $77, $00, $77, $00, $F7, $00, $CF, $00, $FF
	db $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $6F, $00, $9F, $00, $FF
	db $00, $BF, $00, $BF, $00, $BF, $00, $BD, $00, $BD, $00, $BB, $00, $C7, $00, $FF
	db $00, $41, $00, $7B, $00, $7B, $00, $63, $00, $59, $00, $5B, $00, $67, $00, $FF
	db $00, $F7, $00, $EF, $00, $AF, $00, $B5, $00, $75, $00, $75, $00, $CF, $00, $FF
	db $00, $DB, $00, $B9, $00, $7B, $00, $7B, $00, $7B, $00, $77, $00, $8F, $00, $FF
	db $00, $EF, $00, $DF, $00, $DF, $00, $DF, $00, $DF, $00, $EF, $00, $F3, $00, $FF
	db $00, $99, $00, $99, $00, $99, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF
	db $00, $F3, $00, $F3, $00, $F3, $00, $F3, $00, $F3, $00, $F3, $00, $F3, $00, $FF
	db $12, $E1, $24, $C3, $08, $C7, $40, $8F, $10, $8F, $00, $81, $00, $81, $00, $FF
	db $50, $83, $00, $93, $00, $93, $00, $81, $00, $81, $00, $F3, $00, $F3, $00, $FF
	db $02, $81, $00, $81, $00, $99, $00, $F9, $00, $99, $00, $81, $42, $81, $00, $FF
	db $02, $81, $00, $81, $00, $99, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF
	db $02, $F1, $10, $E3, $04, $E3, $00, $E7, $00, $E7, $00, $E7, $00, $E7, $00, $FF
	db $00, $C3, $42, $81, $00, $99, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF
	db $00, $81, $40, $81, $00, $F9, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF

; ---- data $4AA0-$4D70 (720 bytes) [PROBABLE] tilemap+attr: 1 call site(s); first: copy_tilemap_rect_pair at 51:40FF: hl=$4AA0 a=$51 b=18 rows c=20 cols (tiles then attrs) de=$D000 [verifier: call site never executed in a trace -> PROBABLE]

Tilemap_CommTime_SummaryA:: ; 51:4AA0
Data_51_4AA0::
	db $00, $01, $02, $03, $04, $05, $06, $06, $06, $06, $06, $06, $06, $06, $05, $04
	db $03, $02, $01, $00, $10, $11, $12, $13, $13, $12, $12, $12, $12, $12, $12, $12
	db $12, $12, $12, $13, $13, $12, $11, $10, $20, $21, $22, $23, $23, $23, $23, $23
	db $23, $23, $23, $23, $23, $23, $23, $23, $23, $22, $21, $20, $30, $31, $16, $32
	db $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $16, $31, $30
	db $24, $25, $16, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32
	db $32, $16, $25, $24, $14, $15, $44, $45, $46, $47, $48, $46, $49, $4A, $4B, $4C
	db $4A, $46, $4D, $46, $4E, $32, $15, $14, $14, $15, $54, $55, $56, $57, $58, $56
	db $59, $5A, $5B, $5C, $5A, $56, $5D, $56, $5E, $36, $15, $14, $14, $15, $16, $32
	db $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $16, $15, $14
	db $14, $15, $16, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32
	db $32, $16, $15, $14, $14, $15, $16, $4F, $47, $60, $61, $43, $44, $45, $46, $47
	db $62, $60, $47, $63, $16, $16, $15, $14, $14, $15, $16, $5F, $57, $70, $71, $53
	db $54, $55, $56, $57, $72, $70, $57, $73, $16, $16, $15, $14, $14, $15, $16, $32
	db $32, $64, $47, $32, $32, $65, $4C, $4A, $66, $46, $4E, $16, $16, $16, $15, $14
	db $14, $15, $16, $32, $32, $74, $57, $32, $32, $75, $5C, $5A, $76, $56, $5E, $35
	db $16, $16, $15, $14, $24, $25, $26, $32, $32, $32, $32, $32, $32, $32, $32, $32
	db $32, $32, $32, $32, $32, $26, $25, $24, $27, $28, $16, $32, $32, $32, $32, $32
	db $32, $32, $32, $32, $32, $32, $32, $32, $32, $16, $28, $27, $37, $38, $22, $23
	db $23, $23, $23, $23, $23, $23, $23, $23, $23, $23, $23, $23, $23, $22, $33, $34
	db $0D, $0E, $0F, $29, $2A, $2A, $2A, $2A, $2A, $2A, $2A, $2A, $2A, $2A, $2A, $2A
	db $2A, $2A, $2A, $2A, $1D, $1E, $1F, $39, $3A, $3A, $3A, $3A, $3A, $3A, $3A, $3A
	db $3A, $3A, $3A, $3A, $3A, $3A, $3A, $3A, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $28, $28, $28, $28, $28, $28, $28, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $28, $28
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $28, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $28
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $28, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $28, $28, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $28, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $28, $28, $28, $08, $08, $48, $48, $48, $48, $48, $48, $48, $48, $48, $48
	db $48, $48, $48, $48, $68, $68, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08

; ---- data $4D70-$4DB0 (64 bytes) [PROBABLE] palette-rgb555: heuristic: 32 RGB555 words as 8 palette group(s) of 4 (bit15 clear, contains $7FFF, monotone luminance)

Data_51_4D70:: ; 51:4D70
	db $00, $00, $4A, $41, $73, $42, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F
	db $00, $00, $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F
	db $00, $00, $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F
	db $00, $00, $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F

; ---- gfx $4DB0-$51B0 (1024 bytes) [PROBABLE] tiles-vram: 2 call site(s) (27:4F1D 51:4083); first: hdma_rom_to_vram at 27:4F1D: hl=$4DB0 a=$51 c=$40 de=$9001 (dest VRAM $9000, vbank=1) [verifier: call site never executed in a trace -> PROBABLE]

Data_51_4DB0:: ; 51:4DB0
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FE, $FE, $FE, $FE, $FE, $FE, $FE
	db $FF, $FF, $FF, $FF, $C0, $80, $B9, $3E, $61, $40, $DE, $BE, $A3, $A3, $A3, $A3
	db $FF, $FF, $FF, $FF, $FF, $7F, $7F, $3F, $BC, $18, $D9, $0B, $5B, $0A, $59, $0B
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $FF, $FE, $FF, $FF, $FF, $FF, $FF, $FF
	db $3F, $BF, $23, $A3, $AB, $23, $AB, $23, $48, $00, $BF, $00, $C0, $80, $FF, $C0
	db $5C, $08, $5E, $0C, $5E, $0E, $5E, $0E, $BE, $0E, $7F, $1E, $FF, $3F, $FF, $7F
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $E0, $C0, $87, $80, $9F, $0F, $3E, $11, $3B, $21, $71, $21, $79, $23, $6E, $3F
	db $00, $00, $FF, $00, $FF, $FF, $00, $FF, $0F, $FF, $0F, $F8, $00, $FF, $00, $FF
	db $00, $00, $FF, $00, $FF, $FF, $00, $FF, $FF, $FF, $FF, $00, $00, $FF, $00, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F
	db $FF, $FF, $FF, $FF, $FF, $FF, $C7, $83, $10, $38, $FF, $EF, $FF, $04, $FF, $AF
	db $FF, $FF, $FF, $FF, $FF, $FF, $8E, $86, $20, $71, $FF, $DF, $FF, $0C, $FF, $5E
	db $FF, $FF, $FF, $FF, $FF, $FF, $07, $03, $F3, $F9, $F9, $6C, $FD, $34, $F9, $7C
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $F1, $00, $F5, $00, $F1, $00, $FF, $00, $01
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $01
	db $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $FF, $00, $F7, $00, $B7
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F, $60, $3F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $76, $FC, $9E, $C4, $8E, $84, $DC, $84, $7C, $88, $F9, $F0, $E1, $01, $07, $03
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $9F, $00, $6F, $00, $6F, $00, $9F, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $9F, $00, $6F, $00, $6F, $00, $9F, $00, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $6E, $3F, $79, $23, $71, $21, $3B, $21, $3E, $11, $9F, $0F, $87, $80, $E0, $C0
	db $FF, $AF, $BF, $CF, $FF, $EF, $EF, $9F, $70, $F9, $06, $00, $FF, $06, $FF, $FF
	db $FF, $5D, $7F, $9D, $FD, $DE, $DF, $3F, $E0, $F1, $0E, $00, $FF, $06, $FF, $FF
	db $FB, $78, $FB, $69, $FB, $69, $73, $99, $E7, $F1, $0F, $03, $FF, $07, $FF, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $00, $FD, $00, $FD, $00, $FD, $00, $FB, $00, $FB, $00, $F7, $00, $8F, $00, $FF
	db $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $01, $00, $FF
	db $00, $B7, $00, $BB, $00, $BB, $00, $BB, $00, $7D, $00, $7D, $00, $7D, $00, $FF

; ---- gfx $51B0-$55B0 (1024 bytes) [PROBABLE] tiles-vram: 2 call site(s) (27:4F2F 51:4095); first: hdma_rom_to_vram at 27:4F2F: hl=$51B0 a=$51 c=$40 de=$9401 (dest VRAM $9400, vbank=1) [verifier: call site never executed in a trace -> PROBABLE]

Data_51_51B0:: ; 51:51B0
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FD, $00, $FB
	db $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $FF, $00, $81, $00, $BD
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $BF, $00, $BF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $C7
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $87, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $BF, $00, $BF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $EF, $00, $EF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $DF, $00, $DB
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $87, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $7D, $00, $7D
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F7, $00, $01
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $DF, $00, $DF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $83
	db $00, $F7, $00, $CF, $00, $2F, $00, $EF, $00, $EF, $00, $EF, $00, $EF, $00, $FF
	db $00, $BD, $00, $4D, $00, $F5, $00, $F9, $00, $FB, $00, $F7, $00, $8F, $00, $FF
	db $00, $B3, $00, $8F, $00, $BF, $00, $7F, $00, $7F, $00, $7F, $00, $83, $00, $FF
	db $00, $AB, $00, $6D, $00, $6D, $00, $6D, $00, $6D, $00, $6D, $00, $9B, $00, $FF
	db $00, $03, $00, $FD, $00, $FD, $00, $FD, $00, $FB, $00, $F7, $00, $CF, $00, $FF
	db $00, $83, $00, $7D, $00, $FD, $00, $FD, $00, $FD, $00, $FB, $00, $C7, $00, $FF
	db $00, $BF, $00, $BF, $00, $BF, $00, $BD, $00, $BD, $00, $BB, $00, $C7, $00, $FF
	db $00, $DF, $00, $DF, $00, $9F, $00, $AD, $00, $AD, $00, $6D, $00, $73, $00, $FF
	db $00, $0D, $00, $B5, $00, $B7, $00, $77, $00, $77, $00, $F7, $00, $CF, $00, $FF
	db $00, $77, $00, $43, $00, $35, $00, $75, $00, $55, $00, $E3, $00, $CF, $00, $FF
	db $00, $83, $00, $7D, $00, $FD, $00, $FD, $00, $FD, $00, $FB, $00, $C7, $00, $FF
	db $00, $7D, $00, $7D, $00, $7D, $00, $BD, $00, $FB, $00, $F7, $00, $CF, $00, $FF
	db $00, $F7, $00, $F7, $00, $F1, $00, $F7, $00, $87, $00, $73, $00, $8D, $00, $FF
	db $00, $F7, $00, $01, $00, $F7, $00, $F7, $00, $87, $00, $73, $00, $8D, $00, $FF
	db $00, $03, $00, $BF, $00, $B1, $00, $BF, $00, $7F, $00, $6F, $00, $71, $00, $FF
	db $00, $FD, $00, $FB, $00, $FF, $00, $FF, $00, $BF, $00, $BF, $00, $C1, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $DF, $00, $DB
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $7B
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $B5, $00, $BF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FB, $00, $7B
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $CF, $00, $F7
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $FF, $00, $0F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $F5, $00, $F5, $00, $FF, $00, $01
	db $00, $FF, $00, $FF, $00, $FF, $42, $81, $00, $81, $00, $99, $00, $99, $00, $99
	db $00, $FF, $00, $FF, $00, $FF, $00, $F3, $10, $E3, $20, $C3, $40, $83, $00, $F3
	db $00, $FF, $00, $FF, $00, $FF, $42, $81, $00, $81, $00, $99, $00, $99, $08, $F1
	db $00, $FF, $00, $FF, $00, $FF, $00, $F3, $10, $E3, $00, $E3, $20, $C3, $00, $C3
	db $00, $FF, $00, $FF, $00, $FF, $00, $81, $00, $81, $00, $9F, $00, $9F, $00, $9F
	db $00, $FF, $00, $FF, $00, $FF, $42, $81, $00, $81, $00, $99, $00, $99, $00, $9F
	db $00, $FF, $00, $FF, $00, $FF, $00, $81, $00, $81, $00, $99, $00, $99, $08, $F1
	db $00, $FF, $00, $FF, $00, $FF, $42, $81, $00, $81, $00, $99, $00, $99, $00, $99
	db $00, $E3, $02, $E1, $08, $F1, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF
	db $00, $0D, $00, $B5, $00, $B7, $00, $77, $00, $77, $00, $F7, $00, $CF, $00, $FF
	db $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $7D, $00, $6F, $00, $9F, $00, $FF
	db $00, $BF, $00, $BF, $00, $BF, $00, $BD, $00, $BD, $00, $BB, $00, $C7, $00, $FF
	db $00, $41, $00, $7B, $00, $7B, $00, $63, $00, $59, $00, $5B, $00, $67, $00, $FF
	db $00, $F7, $00, $EF, $00, $AF, $00, $B5, $00, $75, $00, $75, $00, $CF, $00, $FF
	db $00, $DB, $00, $B9, $00, $7B, $00, $7B, $00, $7B, $00, $77, $00, $8F, $00, $FF
	db $00, $EF, $00, $DF, $00, $DF, $00, $DF, $00, $DF, $00, $EF, $00, $F3, $00, $FF
	db $00, $99, $00, $99, $00, $99, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF
	db $00, $F3, $00, $F3, $00, $F3, $00, $F3, $00, $F3, $00, $F3, $00, $F3, $00, $FF
	db $12, $E1, $24, $C3, $08, $C7, $40, $8F, $10, $8F, $00, $81, $00, $81, $00, $FF
	db $50, $83, $00, $93, $00, $93, $00, $81, $00, $81, $00, $F3, $00, $F3, $00, $FF
	db $02, $81, $00, $81, $00, $99, $00, $F9, $00, $99, $00, $81, $42, $81, $00, $FF
	db $02, $81, $00, $81, $00, $99, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF
	db $02, $F1, $10, $E3, $04, $E3, $00, $E7, $00, $E7, $00, $E7, $00, $E7, $00, $FF
	db $00, $C3, $42, $81, $00, $99, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF
	db $00, $81, $40, $81, $00, $F9, $00, $99, $00, $99, $00, $81, $42, $81, $00, $FF

; ---- data $55B0-$5880 (720 bytes) [PROBABLE] tilemap+attr: 2 call site(s) (27:4F51 51:40B7); first: copy_tilemap_rect_pair at 27:4F51: hl=$55B0 a=$51 b=18 rows c=20 cols (tiles then attrs) de=$D000 [verifier: call site never executed in a trace -> PROBABLE]

Tilemap_CommTime_SummaryB:: ; 51:55B0
Data_51_55B0::
	db $00, $01, $02, $03, $04, $05, $06, $06, $06, $06, $06, $06, $06, $06, $05, $04
	db $03, $02, $01, $00, $10, $11, $12, $13, $13, $12, $12, $12, $12, $12, $12, $12
	db $12, $12, $12, $13, $13, $12, $11, $10, $20, $21, $22, $23, $23, $23, $23, $23
	db $23, $23, $23, $23, $23, $23, $23, $23, $23, $22, $21, $20, $30, $31, $16, $32
	db $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $16, $31, $30
	db $24, $25, $16, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32
	db $32, $16, $25, $24, $14, $15, $44, $45, $46, $47, $48, $46, $49, $4A, $4B, $4C
	db $4A, $46, $4D, $46, $4E, $32, $15, $14, $14, $15, $54, $55, $56, $57, $58, $56
	db $59, $5A, $5B, $5C, $5A, $56, $5D, $56, $5E, $36, $15, $14, $14, $15, $16, $32
	db $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $16, $15, $14
	db $14, $15, $16, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32, $32
	db $32, $16, $15, $14, $14, $15, $16, $4F, $47, $60, $61, $43, $44, $45, $46, $47
	db $62, $60, $47, $63, $16, $16, $15, $14, $14, $15, $16, $5F, $57, $70, $71, $53
	db $54, $55, $56, $57, $72, $70, $57, $73, $16, $16, $15, $14, $14, $15, $16, $32
	db $32, $64, $47, $32, $32, $65, $4C, $4A, $66, $46, $4E, $16, $16, $16, $15, $14
	db $14, $15, $16, $32, $32, $74, $57, $32, $32, $75, $5C, $5A, $76, $56, $5E, $35
	db $16, $16, $15, $14, $24, $25, $26, $32, $32, $32, $32, $32, $32, $32, $32, $32
	db $32, $32, $32, $32, $32, $26, $25, $24, $27, $28, $16, $32, $32, $32, $32, $32
	db $32, $32, $32, $32, $32, $32, $32, $32, $32, $16, $28, $27, $37, $38, $22, $23
	db $23, $23, $23, $23, $23, $23, $23, $23, $23, $23, $23, $23, $23, $22, $33, $34
	db $07, $08, $0A, $09, $09, $09, $09, $0A, $0A, $0A, $0A, $0B, $0C, $0D, $0E, $0F
	db $29, $2A, $2B, $2C, $17, $18, $1A, $19, $19, $19, $19, $1A, $1A, $1A, $1A, $1B
	db $1C, $1D, $1E, $1F, $39, $3A, $3B, $3C, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $28, $28, $28, $28, $28, $28, $28, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $28, $28
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $28, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $28
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $28, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $28, $28, $28, $28, $28, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28, $28, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $28, $28, $28
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $28, $28, $28, $08, $08, $48, $48, $48, $48, $48, $48, $48, $48, $48, $48
	db $48, $48, $48, $48, $68, $68, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08

; ---- data $5880-$58C0 (64 bytes) [CONFIRMED] read as data by executed code (in up to 2/18 scenarios); content class unknown [clipped from 4DB0-58C0 by higher-priority evidence]

Data_51_5880:: ; 51:5880
	db $00, $00, $1F, $01, $FF, $02, $FF, $7F, $00, $00, $32, $00, $9F, $01, $FF, $7F
	db $00, $00, $1F, $00, $5F, $02, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F
	db $00, $00, $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F
	db $00, $00, $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F

; ---- gfx $58C0-$5CC0 (1024 bytes) [PROBABLE] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 69:40EC: hl=$58C0 a=$51 c=$40 de=$8200 (dest VRAM $8200, vbank=0) [verifier: call site never executed in a trace -> PROBABLE]

Data_51_58C0:: ; 51:58C0
	db $00, $00, $00, $00, $00, $00, $00, $03, $00, $07, $00, $0F, $03, $1C, $04, $18
	db $00, $00, $00, $00, $C6, $39, $02, $01, $80, $07, $02, $C1, $01, $00, $00, $80
	db $00, $00, $00, $00, $00, $00, $00, $C0, $00, $E0, $00, $F0, $00, $F8, $60, $18
	db $00, $00, $00, $00, $00, $00, $1F, $1C, $1C, $1B, $1A, $15, $18, $03, $10, $07
	db $00, $00, $00, $00, $8F, $70, $00, $00, $14, $E8, $00, $FF, $00, $FF, $02, $FD
	db $00, $00, $00, $00, $00, $00, $F8, $38, $38, $18, $18, $08, $10, $08, $18, $00
	db $00, $00, $00, $00, $30, $30, $23, $20, $00, $07, $00, $0F, $00, $1F, $01, $1E
	db $00, $00, $00, $00, $83, $7C, $00, $00, $40, $80, $01, $F0, $60, $81, $00, $01
	db $00, $00, $00, $00, $0C, $0C, $C4, $04, $00, $E0, $00, $F0, $80, $78, $40, $B8
	db $80, $80, $40, $40, $00, $00, $03, $00, $05, $00, $08, $03, $11, $00, $10, $00
	db $00, $00, $00, $00, $E1, $1E, $98, $60, $01, $FE, $00, $FF, $01, $FE, $02, $7C
	db $01, $01, $02, $02, $00, $00, $C0, $00, $20, $00, $10, $C0, $90, $08, $18, $00
	db $00, $00, $00, $00, $00, $00, $01, $02, $07, $00, $0F, $00, $0F, $10, $1F, $00
	db $00, $00, $00, $00, $7E, $81, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $00, $00, $00, $00, $00, $00, $80, $40, $E0, $00, $F0, $00, $F0, $08, $F8, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $3B, $10, $20, $00, $24, $00, $20, $20, $0B, $2A, $04, $00, $20, $10, $20
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $50, $00, $10, $00, $00
	db $18, $04, $18, $04, $18, $04, $18, $04, $18, $04, $10, $0C, $10, $0C, $20, $1C
	db $22, $01, $20, $03, $20, $07, $28, $07, $20, $0F, $20, $0F, $00, $2F, $10, $2F
	db $08, $F5, $10, $ED, $40, $82, $00, $C0, $28, $C5, $25, $C2, $00, $E0, $00, $E0
	db $18, $04, $18, $04, $18, $04, $18, $04, $18, $84, $18, $24, $18, $04, $30, $0C
	db $12, $2C, $10, $2C, $00, $30, $10, $20, $00, $30, $00, $30, $08, $30, $00, $3C
	db $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $02, $00, $03
	db $40, $BC, $80, $7C, $00, $FC, $00, $FC, $00, $FC, $00, $FC, $00, $FC, $80, $7C
	db $20, $00, $20, $00, $20, $00, $20, $01, $20, $03, $20, $01, $00, $20, $10, $20
	db $20, $1C, $10, $6C, $08, $F0, $02, $FC, $00, $FF, $00, $FF, $02, $FC, $84, $78
	db $18, $04, $18, $04, $18, $04, $18, $04, $18, $04, $18, $04, $18, $04, $30, $0C
	db $1F, $20, $3F, $00, $3F, $00, $3F, $00, $3F, $00, $3F, $00, $3F, $00, $1F, $20
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $F8, $04, $FC, $00, $FC, $00, $FC, $00, $FC, $00, $FC, $00, $FC, $00, $F8, $04
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $10, $08, $10, $04, $08, $02, $04, $00, $03, $00, $00, $00, $00, $00, $00
	db $48, $30, $04, $78, $40, $3C, $27, $18, $FE, $01, $00, $FF, $00, $00, $00, $00
	db $20, $18, $60, $18, $C0, $30, $80, $60, $00, $C0, $00, $00, $00, $00, $00, $00
	db $00, $17, $08, $13, $15, $18, $1A, $1C, $1C, $1F, $00, $00, $00, $00, $00, $00
	db $00, $E0, $20, $C0, $20, $C0, $23, $40, $FE, $01, $00, $FF, $00, $00, $00, $00
	db $30, $08, $60, $18, $C8, $38, $98, $78, $38, $F8, $00, $00, $00, $00, $00, $00
	db $02, $1C, $00, $1E, $00, $0F, $00, $07, $20, $23, $30, $30, $00, $00, $00, $00
	db $00, $03, $02, $01, $01, $00, $83, $00, $FE, $01, $00, $FF, $00, $00, $00, $00
	db $00, $78, $40, $38, $C0, $30, $80, $60, $04, $C4, $0C, $0C, $00, $00, $00, $00
	db $00, $10, $08, $10, $04, $08, $02, $04, $00, $03, $00, $00, $40, $40, $80, $80
	db $00, $78, $04, $38, $00, $1C, $03, $0C, $FE, $01, $00, $FF, $00, $00, $00, $00
	db $30, $08, $60, $18, $C0, $30, $80, $60, $00, $C0, $00, $00, $02, $02, $01, $01
	db $1F, $00, $0F, $10, $0F, $00, $07, $00, $01, $02, $00, $00, $00, $00, $00, $00
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $7E, $81, $00, $00, $00, $00
	db $F8, $00, $F0, $08, $F0, $00, $E0, $00, $80, $40, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

; ---- gfx $5CC0-$5EC0 (512 bytes) [PROBABLE] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 69:40FE: hl=$5CC0 a=$51 c=$20 de=$8600 (dest VRAM $8600, vbank=0) [verifier: call site never executed in a trace -> PROBABLE]

Data_51_5CC0:: ; 51:5CC0
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

; ---- data $5EC0-$5EE0 (32 bytes) [PROBABLE] palette-rgb555: heuristic: 16 RGB555 words as 4 palette group(s) of 4 (bit15 clear, contains $7FFF, monotone luminance)

Data_51_5EC0:: ; 51:5EC0
	db $00, $00, $4A, $29, $B5, $56, $FF, $7F, $F3, $7F, $45, $6A, $80, $40, $7F, $03
	db $C9, $40, $F3, $7F, $AE, $69, $33, $46, $00, $7C, $FF, $7F, $1F, $58, $00, $00

; ---- zero $5EE0-$5EE1 (1 bytes) [HYPOTHESIS] single $00 byte right after the palette-like block ending at 5EE0 and before the tile data (5EE1); purpose unknown (padding?)
	ds $1, $00

; ---- gfx $5EE1-$70E0 (4607 bytes) [PROBABLE] tile data: heuristic: 175 coherent tiles (hsim2=0.751 vsim2=0.738, 102 blank) parity 1 [boundary trimmed 5EE1-70E1 -> 5EE1-70E0 against proven code]

Data_51_5EE1:: ; 51:5EE1
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $C0, $00, $E0, $40, $D0, $40, $1F
	db $00, $20, $00, $40, $00, $82, $00, $80, $00, $80, $00, $40, $00, $21, $00, $00
	db $00, $80, $00, $40, $00, $3C, $00, $72, $70, $0E, $7C, $7C, $00, $80, $00, $0D
	db $03, $0F, $03, $0A, $06, $08, $06, $09, $07, $0C, $07, $0C, $07, $07, $03, $43
	db $87, $47, $3E, $2E, $18, $3E, $04, $66, $5C, $6E, $5C, $FC, $D8, $D8, $80, $C0
	db $C0, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $7C, $6C, $9E, $DA, $3B, $DF, $3E, $EF, $1C, $7C, $82, $30, $48, $20, $10, $1F
	db $00, $20, $00, $40, $00, $84, $00, $80, $00, $80, $00, $40, $00, $21, $00, $90
	db $40, $48, $20, $58, $30, $2B, $10, $2C, $10, $10, $00, $10, $00, $13, $00, $0C
	db $00, $1A, $08, $31, $10, $61, $30, $C9, $78, $C7, $7E, $86, $7D, $4F, $38, $00
	db $00, $00, $00, $00, $00, $00, $00, $E0, $00, $20, $C0, $40, $80, $80, $00, $E0
	db $00, $F0, $E0, $70, $E0, $E0, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $C0, $00, $E0, $40, $D0, $40, $04
	db $04, $1F, $1F, $1F, $1F, $07, $07, $07, $07, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $02, $3E, $0D, $7F, $7F, $9E, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $80, $90
	db $40, $48, $20, $58, $30, $2B, $10, $2C, $10, $10, $00, $13, $00, $15, $03, $12
	db $00, $12, $00, $62, $00, $82, $00, $01, $00, $00, $00, $80, $00, $41, $81, $00
	db $00, $00, $00, $00, $00, $00, $00, $80, $00, $80, $00, $80, $00, $80, $00, $07
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $07
	db $07, $07, $07, $07, $07, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $01, $00, $01, $00, $01, $00, $00, $80, $80, $80, $80, $04
	db $7C, $1A, $FE, $FE, $3D, $FE, $3C, $FC, $1A, $7C, $82, $30, $48, $20, $10, $0C
	db $7C, $36, $FE, $EA, $6F, $FC, $7A, $FC, $32, $7C, $82, $30, $48, $20, $10, $12
	db $00, $12, $00, $62, $00, $82, $00, $01, $00, $00, $00, $00, $00, $81, $01, $38
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $0F, $00, $10, $00, $20, $00, $41, $00, $40, $00, $00
	db $00, $00, $00, $00, $00, $80, $00, $40, $00, $20, $00, $1E, $00, $39, $38, $90
	db $40, $48, $20, $58, $30, $2B, $10, $2C, $10, $10, $00, $10, $00, $10, $00, $00
	db $00, $00, $00, $7F, $00, $80, $00, $00, $00, $00, $00, $00, $00, $01, $01, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $F8, $00, $04, $00, $0F
	db $03, $0A, $06, $08, $06, $09, $07, $0C, $07, $0C, $07, $07, $03, $03, $00, $43
	db $07, $27, $1E, $2E, $18, $7E, $44, $6E, $5C, $FC, $D8, $D8, $80, $80, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $1F
	db $00, $20, $00, $40, $00, $81, $00, $80, $00, $80, $00, $40, $00, $21, $00, $00
	db $00, $80, $00, $40, $00, $38, $00, $74, $70, $1C, $F8, $78, $80, $80, $00, $40
	db $40, $00, $00, $02, $03, $0D, $0E, $23, $1C, $0F, $30, $1F, $20, $1F, $02, $20
	db $10, $20, $50, $60, $90, $D0, $38, $FC, $3C, $DC, $3C, $E8, $18, $E0, $00, $E0
	db $E0, $20, $20, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $3F
	db $00, $78, $38, $C4, $7C, $C0, $7F, $81, $7F, $4F, $3E, $3E, $00, $00, $00, $00
	db $00, $C0, $00, $40, $00, $C0, $80, $D0, $A0, $E0, $00, $00, $00, $00, $00, $80
	db $00, $00, $00, $70, $00, $8F, $00, $80, $00, $80, $00, $80, $00, $00, $00, $07
	db $3E, $3E, $00, $C0, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $08
	db $00, $08, $07, $04, $03, $03, $00, $00, $00, $00, $00, $00, $00, $00, $00, $03
	db $0F, $07, $FE, $0E, $F8, $F8, $00, $00, $00, $00, $00, $00, $00, $00, $00, $02
	db $00, $04, $00, $F8, $00, $00, $00, $1E, $00, $61, $00, $80, $00, $80, $00, $02
	db $00, $11, $00, $03, $03, $00, $03, $03, $00, $0C, $00, $F0, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $80, $80, $80, $80, $C0, $C0, $00
	db $00, $00, $00, $0E, $F1, $D6, $39, $FF, $3C, $DF, $3C, $E8, $18, $E0, $00, $00
	db $03, $00, $07, $07, $09, $1F, $21, $FF, $00, $FF, $00, $07, $00, $00, $00, $20
	db $E0, $D0, $F0, $F0, $E8, $F0, $E0, $F0, $C0, $E0, $10, $80, $40, $00, $00, $90
	db $40, $48, $20, $58, $30, $2B, $10, $2C, $10, $10, $00, $10, $00, $10, $00, $12
	db $00, $12, $00, $62, $00, $82, $00, $01, $00, $00, $00, $00, $00, $01, $01, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $1C, $00, $2A, $1C, $00
	db $00, $10, $00, $30, $20, $60, $C0, $A0, $80, $C0, $00, $00, $00, $00, $00, $40
	db $40, $E0, $E0, $E0, $E0, $40, $40, $00, $00, $40, $40, $00, $00, $00, $00, $07
	db $07, $03, $03, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $80
	db $80, $C0, $C0, $00, $00, $40, $40, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $38, $00, $54, $38, $76, $34, $A2, $60, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $40
	db $40, $00, $00, $02, $03, $0D, $0E, $23, $1C, $0F, $30, $1F, $20, $1F, $00, $00
	db $00, $3F, $40, $7F, $80, $D6, $38, $FC, $3C, $DC, $3C, $E8, $18, $E0, $00, $7F
	db $9E, $7E, $8D, $FE, $01, $D8, $24, $00, $00, $00, $00, $00, $00, $00, $00, $18
	db $18, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $08
	db $00, $08, $07, $04, $03, $03, $00, $00, $00, $00, $00, $00, $00, $00, $00, $03
	db $0F, $07, $FE, $0E, $F8, $F8, $00, $00, $00, $00, $00, $00, $00, $00, $00, $3A
	db $18, $51, $30, $41, $30, $4B, $3A, $63, $3A, $67, $3E, $3E, $1C, $1C, $00, $00
	db $00, $10, $00, $30, $20, $30, $E0, $70, $E0, $E0, $C0, $C0, $00, $00, $00, $00
	db $00, $1F, $00, $71, $11, $A0, $70, $81, $7F, $C2, $7E, $6F, $1F, $1F, $00, $00
	db $00, $00, $00, $88, $00, $C8, $90, $C8, $B0, $D0, $A0, $E0, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $82
	db $60, $D6, $74, $CE, $7C, $A3, $74, $7D, $3A, $56, $38, $38, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $C0, $00, $E0, $40, $D0, $40, $1F
	db $00, $20, $00, $40, $00, $82, $00, $80, $00, $80, $00, $40, $00, $21, $00, $00
	db $00, $80, $00, $40, $00, $3C, $00, $72, $70, $1E, $7C, $7C, $00, $80, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $30, $30, $00, $00, $00, $00, $00, $00, $18
	db $00, $1C, $08, $12, $08, $0E, $04, $0B, $06, $0B, $06, $05, $02, $05, $02, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $F0, $00, $80
	db $F8, $38, $C6, $7C, $83, $FB, $07, $7F, $07, $6B, $17, $41, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $80, $80, $80, $00, $C0, $C0, $00, $60, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $03, $00, $00
	db $00, $00, $00, $00, $00, $10, $00, $28, $00, $28, $00, $34, $10, $B4, $10, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $0C, $00, $1A, $08, $00
	db $00, $00, $00, $00, $00, $00, $00, $01, $02, $00, $01, $00, $00, $00, $00, $2C
	db $FC, $E2, $1E, $B0, $7F, $FD, $7A, $DE, $58, $B4, $78, $78, $80, $00, $00, $10
	db $0E, $00, $1E, $30, $08, $E0, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $1E, $00, $21, $00, $40, $00, $44, $00, $80, $00, $00
	db $00, $00, $00, $18, $00, $6C, $08, $94, $18, $78, $60, $20, $00, $40, $00, $90
	db $40, $48, $20, $58, $30, $2B, $10, $2C, $10, $10, $00, $13, $00, $15, $03, $12
	db $00, $12, $00, $62, $00, $82, $00, $01, $00, $00, $00, $80, $00, $41, $81, $00
	db $00, $00, $00, $00, $00, $00, $00, $80, $00, $80, $00, $80, $00, $80, $00, $00
	db $00, $00, $00, $01, $00, $03, $01, $06, $03, $04, $03, $04, $03, $03, $01, $02
	db $00, $04, $00, $FC, $00, $0E, $08, $85, $86, $03, $FE, $05, $FE, $1E, $F8, $0C
	db $00, $02, $00, $01, $00, $00, $00, $00, $00, $00, $00, $1C, $7C, $C1, $3E, $00
	db $00, $00, $00, $00, $00, $80, $00, $80, $00, $40, $00, $40, $00, $20, $00, $10
	db $20, $00, $3C, $3A, $46, $75, $0B, $6D, $1F, $5E, $3F, $5A, $3B, $2D, $1E, $07
	db $03, $0B, $07, $0A, $06, $08, $06, $0A, $07, $06, $03, $05, $03, $05, $03, $E4
	db $90, $6C, $58, $2C, $18, $2C, $18, $B4, $A8, $78, $E0, $18, $A0, $D4, $E0, $12
	db $08, $16, $0C, $1E, $0C, $2E, $0C, $4F, $0E, $81, $00, $80, $00, $90, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $80, $00, $80, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $38, $00, $00
	db $00, $00, $00, $00, $00, $60, $60, $30, $30, $10, $10, $00, $00, $08, $08, $80
	db $00, $80, $00, $40, $00, $43, $00, $4C, $00, $50, $00, $90, $00, $A0, $00, $40
	db $00, $80, $00, $80, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $0F
	db $03, $0A, $06, $08, $06, $09, $07, $0C, $07, $0C, $07, $07, $03, $03, $00, $43
	db $07, $27, $1E, $2E, $18, $7E, $44, $6E, $5C, $FC, $D8, $D8, $80, $80, $00, $80
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $F8
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $3E
	db $00, $00, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $00, $00, $98
	db $00, $84, $00, $02, $00, $01, $00, $01, $00, $01, $00, $09, $00, $81, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $02
	db $01, $01, $00, $00, $00, $01, $00, $01, $00, $01, $00, $01, $00, $F9, $00, $A2
	db $C0, $C2, $00, $81, $00, $01, $00, $01, $80, $01, $80, $01, $C0, $01, $C0, $80
	db $00, $80, $00, $40, $00, $21, $00, $19, $00, $05, $00, $04, $00, $04, $00, $80
	db $00, $80, $00, $80, $00, $01, $00, $01, $00, $1F, $00, $F9, $18, $BC, $7C, $64
	db $20, $B2, $70, $DF, $7C, $8F, $FD, $8C, $FB, $89, $F6, $59, $E6, $EA, $04, $00
	db $00, $00, $00, $80, $00, $80, $00, $80, $00, $00, $00, $00, $00, $00, $00, $01
	db $00, $02, $00, $02, $00, $04, $00, $04, $00, $04, $00, $04, $00, $04, $00, $30
	db $00, $38, $30, $08, $00, $0C, $08, $0C, $08, $1C, $18, $06, $08, $0F, $06, $00
	db $00, $00, $00, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $3E
	db $00, $04, $00, $00, $00, $00, $00, $08, $08, $08, $08, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $01, $00, $01, $00, $01, $00, $00, $80, $80, $00
	db $00, $04, $7C, $1A, $FE, $F4, $37, $FC, $3E, $FC, $1A, $78, $86, $30, $48, $00
	db $00, $00, $00, $00, $00, $00, $00, $08, $08, $08, $08, $04, $04, $04, $04, $00
	db $00, $00, $01, $00, $03, $01, $03, $03, $05, $02, $05, $03, $04, $03, $00, $82
	db $00, $54, $30, $58, $30, $58, $30, $68, $20, $68, $20, $30, $00, $00, $00, $02
	db $00, $7C, $02, $F8, $7E, $C0, $7E, $78, $00, $04, $00, $02, $00, $01, $00, $04
	db $00, $02, $00, $01, $00, $00, $00, $43, $00, $04, $00, $08, $00, $F0, $00, $82
	db $40, $C2, $40, $8C, $00, $30, $00, $C0, $00, $00, $00, $00, $00, $00, $00, $02
	db $00, $02, $00, $01, $00, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $C0, $00, $3F, $00, $00, $00, $00, $00, $14
	db $08, $18, $00, $10, $00, $20, $00, $C0, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $44, $00, $28, $00, $10, $00, $28, $00, $44, $00, $00, $00, $04
	db $00, $02, $00, $02, $00, $05, $02, $0D, $06, $0D, $06, $1A, $0C, $1A, $0C, $19
	db $09, $1C, $0C, $3A, $0E, $D9, $0F, $10, $0F, $08, $07, $0B, $07, $07, $00, $00
	db $00, $01, $01, $00, $01, $78, $78, $3C, $3C, $00, $00, $00, $00, $00, $00, $80
	db $00, $80, $00, $C0, $80, $C0, $80, $40, $00, $C0, $80, $80, $00, $00, $00, $80
	db $80, $40, $40, $00, $00, $00, $01, $0D, $0E, $23, $1C, $01, $30, $00, $20, $20
	db $10, $20, $10, $20, $50, $60, $90, $D0, $38, $FC, $3C, $DC, $3C, $E8, $18, $04
	db $04, $40, $40, $E0, $E0, $E0, $E0, $20, $20, $00, $00, $20, $20, $04, $00, $01
	db $02, $01, $02, $00, $02, $02, $04, $00, $04, $00, $0C, $10, $1C, $1B, $17, $00
	db $00, $00, $00, $01, $01, $01, $01, $00, $00, $00, $00, $04, $04, $08, $0C, $80
	db $00, $C0, $00, $40, $80, $40, $80, $C0, $00, $C0, $00, $80, $00, $80, $00, $00
	db $00, $00, $00, $00, $00, $06, $06, $03, $03, $00, $00, $00, $00, $00, $00, $01
	db $01, $26, $E6, $D8, $F8, $A4, $B8, $F8, $E0, $D8, $E0, $F0, $00, $E0, $10, $00
	db $00, $00, $00, $00, $00, $00, $00, $7F, $00, $7F, $00, $80, $00, $80, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $FC, $00, $FC, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $14
	db $08, $14, $08, $18, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $02
	db $02, $07, $07, $07, $07, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $E0
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $0C
	db $02, $1E, $00, $3E, $01, $7E, $03, $3F, $03, $3B, $07, $11, $0F, $10, $0F, $2F
	db $33, $3D, $23, $1E, $20, $1F, $20, $1F, $20, $2E, $30, $0E, $10, $0C, $10, $19
	db $1E, $16, $1F, $0B, $1B, $0F, $1F, $06, $1F, $05, $0A, $03, $04, $01, $00, $80
	db $00, $81, $41, $C0, $00, $5A, $3D, $7F, $3C, $1B, $3C, $3F, $00, $0F, $00, $00
	db $00, $80, $80, $C0, $C0, $28, $F0, $80, $78, $F8, $00, $F0, $00, $C0, $00, $C0
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $80, $00, $80, $00, $7F, $00, $7F, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $FC, $00, $FC, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $01, $00, $01, $00, $01, $00, $01, $00, $00, $00, $3F
	db $00, $40, $00, $80, $00, $40, $00, $00, $00, $18, $18, $12, $33, $8C, $3F, $00
	db $00, $80, $00, $40, $00, $A0, $00, $20, $00, $20, $00, $20, $00, $40, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $04, $04, $02, $02, $01, $01, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $20, $20, $10, $10, $00, $00, $08, $08, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $03, $0F, $18, $1F, $28, $2F, $30, $3F, $00
	db $00, $00, $00, $00, $00, $00, $00, $80, $C0, $60, $E0, $50, $D0, $30, $F0, $00
	db $00, $00, $00, $00, $00, $00, $00, $80, $C0, $00, $E0, $40, $B0, $30, $C0, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $02, $00, $40
	db $1E, $33, $00, $12, $00, $12, $00, $21, $00, $C0, $00, $00, $00, $00, $00, $80
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $C0, $00, $20, $00, $10, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $18, $00, $14, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $30, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $03, $0F, $00, $1F, $08, $37, $30, $0F, $11
	db $29, $33, $03, $10, $00, $08, $00, $03, $00, $03, $00, $03, $00, $06, $01, $A0
	db $D0, $30, $00, $20, $00, $40, $00, $00, $00, $00, $00, $00, $00, $00, $80, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $02
	db $00, $0F, $00, $11, $01, $33, $13, $30, $1F, $38, $1F, $1E, $0F, $0F, $00, $00
	db $00, $00, $00, $80, $00, $40, $9E, $5E, $BF, $7F, $80, $80, $00, $00, $00, $10
	db $00, $3C, $00, $62, $20, $B3, $72, $87, $7E, $8F, $7E, $5E, $3C, $3C, $00, $1A
	db $08, $16, $0C, $15, $0C, $0B, $06, $09, $06, $05, $02, $06, $00, $04, $00, $28
	db $00, $34, $10, $22, $18, $16, $0C, $13, $0E, $0B, $06, $05, $02, $02, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $03, $03, $03, $03, $00, $00, $01
	db $0F, $10, $3F, $47, $78, $1F, $60, $3F, $00, $9F, $80, $08, $00, $00, $00, $C0
	db $C0, $E0, $F0, $20, $F8, $E0, $18, $F0, $00, $E7, $07, $43, $03, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

; ---- code $70E0-$73D1 (753 bytes) [PROBABLE] 500 insn(s) reached by static flow only; seeds: exec x500; min discovery hops 1; entered by far from 4C:4E56 (PROBABLE code)

Bmp_Validate:: ; 51:70E0
	ld a, $03
	ldh [hSRAMBank], a
	ld [rRAMB], a
	call Bmp_ParseHeader
	or a, a
	ret z
	call Bmp_CheckSize
	or a, a
	ret z
	ld a, $01
	ret

Bmp_ParseHeader:: ; 51:70F4
	push hl
	ld a, [hli]
	cp a, $42
	jr nz, Label_51_7157
	ld a, [hli]
	cp a, $4D
	jr nz, Label_51_7157
	ld de, $0008
	add hl, de
	ld a, [hli]
	ld c, a
	ld a, [hli]
	ld b, a
	ld a, [hli]
	or a, [hl]
	jr nz, Label_51_7157
	ld de, $0005
	add hl, de
	ld a, [hli]
	ldh [hRam_FFD6], a
	ld a, [hli]
	ld e, a
	ld a, [hli]
	or a, e
	ld a, [hli]
	or a, e
	jr nz, Label_51_7157
	ld a, [hli]
	ldh [hRam_FFD7], a
	ld a, [hli]
	ld e, a
	ld a, [hli]
	and a, e
	ld a, [hli]
	and a, e
	jr z, Label_51_712E
	cp a, $FF
	jr nz, Label_51_7157
	ld [wRam_C33F], a
	jr Label_51_7132

Label_51_712E:: ; 51:712E
	xor a, a
	ld [wRam_C33F], a

Label_51_7132:: ; 51:7132
	ld a, [hli]
	dec a
	or a, [hl]
	jr nz, Label_51_7157
	inc hl
	ld a, [hli]
	dec a
	or a, [hl]
	jr nz, Label_51_7157
	inc hl
	ld a, [hli]
	or a, [hl]
	inc hl
	or a, [hl]
	inc hl
	or a, [hl]
	jr nz, Label_51_7157
	ld de, $000D
	add hl, de
	ld a, [hli]
	or a, [hl]
	inc hl
	or a, [hl]
	inc hl
	or a, [hl]
	jr nz, Label_51_7157
	pop hl
	add hl, bc
	ld a, $01
	ret

Label_51_7157:: ; 51:7157
	xor a, a
	ldh [hRam_FFD6], a
	ldh [hRam_FFD7], a
	ld [wRam_C33F], a
	pop hl
	ret

Bmp_CheckSize:: ; 51:7161
	ldh a, [hRam_FFD6]
	cp a, $91
	jr nc, Label_51_7175
	ld d, a
	ldh a, [hRam_FFD7]
	or a, a
	jr z, Label_51_7175
	cp a, $61
	jr nc, Label_51_7175
	ld e, a
	ld a, $01
	ret

Label_51_7175:: ; 51:7175
	xor a, a
	ret

Bmp_ConvertToTiles:: ; 51:7177
	ld a, l
	ld [wRam_C337], a
	ld a, h
	ld [wRam_C338], a
	push hl
	call Bmp_Validate
	pop de
	or a, a
	ret z
	dec hl
	dec hl
	dec hl
	dec hl
	ld a, [wRam_C33F]
	or a, a
	jp nz, Label_51_73CB
	push hl
	push de
	ld hl, $000E
	add hl, de
	ld a, [hli]
	ld e, a
	ld a, [hld]
	ld d, a
	add hl, de
	call Bmp_ColorSum
	push de
	call Bmp_ColorSum
	pop hl
	dec hl
	ld a, l
	cpl
	ld l, a
	ld a, h
	cpl
	ld h, a
	add hl, de
	pop de
	ld a, l
	ld [wRam_C330], a
	ld a, h
	ld [wRam_C331], a
	ld hl, $0017
	add hl, de
	ld a, $FF
	ld [hli], a
	ld [hli], a
	ld [hli], a
	ld a, $03
	ldh [hSRAMBank], a
	ld [rRAMB], a
	ldh a, [hRam_FFD6]
	add a, $07
	jp c, Label_51_73CE
	and a, $F8
	rrca
	rrca
	rrca
	ld [wRam_C334], a
	add a, $03
	jp c, Label_51_73CE
	and a, $FC
	ld [wRam_C335], a
	ldh a, [hRam_FFD7]
	call Bmp_RoundUpToTextRow
	ld [wRam_C333], a
	ld e, a
	ldh a, [hRam_FFD6]
	call Bmp_RoundUpToTextRow
	ld [wRam_C332], a
	add a, $07
	jp c, Label_51_73CE
	and a, $F8
	rrca
	rrca
	rrca
	add a, $03
	jp c, Label_51_73CE
	and a, $FC
	ldh [hRam_FFD4], a
	ld d, $00
	call Multiply8x16
	ld c, l
	ld b, h
	pop hl
	push hl
	ld a, c
	ld [hli], a
	ld a, b
	ld [hli], a
	ldh a, [hRam_FFD4]
	and a, $1F
	rlca
	rlca
	rlca
	ld [wRam_C336], a
	ld [hli], a
	ld a, [wRam_C333]
	ld [hli], a
	push bc
	push hl
	push hl
	inc hl
	inc hl
	inc hl
	inc hl
	inc hl
	ld a, l
	ld [wRam_C33B], a
	ld a, h
	ld [wRam_C33C], a
	call Function_00_0392
	ld a, $03
	ldh [hWRAMBank], a
	ldh [rSVBK], a
	ld hl, $D000
	ld a, $FF
	call FillBytes
	ldh a, [hRam_FFD7]
	dec a
	ld e, a
	ldh a, [hRam_FFD4]
	ld d, $00
	call Multiply8x16
	ld de, $D000
	add hl, de
	ld e, l
	ld d, h
	pop hl

Label_51_7251:: ; 51:7251
	call Function_00_0392
	ld a, [wRam_C334]
	ld c, a
	ld b, $00
	push hl
	push de
	push de
	call CopyBytes
	pop hl
	ld a, [wRam_C331]
	bit 7, a
	jr z, Label_51_7276
	ld a, [wRam_C334]
	or a, a
	jr z, Label_51_7276
	ld c, a

Label_51_726F:: ; 51:726F
	ld a, [hl]
	xor a, $FF
	ld [hli], a
	dec c
	jr nz, Label_51_726F

Label_51_7276:: ; 51:7276
	ldh a, [hRam_FFD6]
	and a, $07
	jr z, Label_51_7287
	dec de
	ld c, a
	ld b, $00
	ld hl, Table_Bmp_RowEndMask
	add hl, bc
	ld a, [de]
	or a, [hl]
	ld [de], a

Label_51_7287:: ; 51:7287
	pop de
	pop hl
	ld a, [wRam_C335]
	ld c, a
	ld b, $00
	add hl, bc
	ldh a, [hRam_FFD4]
	ld c, a
	ld a, e
	sub a, c
	ld e, a
	ld a, d
	sbc a, $00
	ld d, a
	cp a, $D0
	jr nc, Label_51_7251
	call Function_00_0392
	pop de
	pop bc
	inc hl
	inc hl
	push de
	push hl
	ld a, [wRam_C337]
	ld l, a
	ld a, [wRam_C338]
	ld h, a
	ld de, $000A
	add hl, de
	ld d, a
	ld a, [wRam_C337]
	ld e, a
	ld a, [hli]
	ld h, [hl]
	ld l, a
	add hl, bc
	push hl
	add hl, de
	ld a, h
	pop hl
	cp a, $C0
	jr c, Label_51_72D4
	dec de
	dec de
	xor a, a
	ld [de], a
	inc de
	ld [de], a
	inc de
	ld [de], a
	inc de
	ld [de], a
	inc de
	pop hl
	pop de
	jp Label_51_73CE

Label_51_72D4:: ; 51:72D4
	dec de
	dec de
	push bc
	inc hl
	inc hl
	ld a, [de]
	cpl
	ld c, a
	ld a, l
	ld [de], a
	inc de
	ld a, [de]
	cpl
	ld b, a
	ld a, h
	ld [de], a
	dec hl
	dec hl
	inc bc
	inc bc
	inc bc
	add hl, bc
	ld a, l
	ld [wRam_C339], a
	ld a, h
	ld [wRam_C33A], a
	pop bc
	pop hl
	push hl
	push bc
	ld e, c
	ld d, b

Label_51_72F8:: ; 51:72F8
	ld a, [wRam_C33B]
	add a, c
	ld a, [wRam_C33C]
	adc a, b
	cp a, $C0
	jr nc, Label_51_7383
	ld a, b
	cp a, $10
	jp nc, Label_51_7383
	ld e, c
	ld d, b
	ld a, [hli]
	ld a, [hli]
	ld a, [hli]
	or a, a
	jp z, Label_51_7383
	inc bc
	inc bc

Label_51_7315:: ; 51:7315
	inc bc
	ld a, [hli]
	or a, a
	jr nz, Label_51_7315
	push bc
	push de
	push hl
	ld e, l
	ld d, h
	ld a, $04
	ldh [hWRAMBank], a
	ldh [rSVBK], a
	ldh a, [hRam_FFCE]
	ld c, a
	ldh a, [hRam_FFCF]
	ld b, a
	or a, c
	jr z, Label_51_7365
	ldh a, [hRam_FFCC]
	ld l, a
	ldh a, [hRam_FFCD]
	ld h, a

Label_51_7334:: ; 51:7334
	ldh a, [hRam_FFBA]
	call BankSwitch_H
	push bc
	push hl
	ld bc, $0008
	add hl, bc
	ld a, [hl]
	cp a, $04
	jr nz, Label_51_735A
	ld bc, $0003
	add hl, bc
	ld a, [hli]
	cp a, e
	jr nz, Label_51_735A
	ld a, [hld]
	cp a, d
	jr nz, Label_51_735A
	ld a, [wRam_C339]
	add a, e
	ld [hli], a
	ld a, [wRam_C33A]
	adc a, d
	ld [hli], a

Label_51_735A:: ; 51:735A
	pop hl
	ld bc, $0010
	add hl, bc
	pop bc
	dec bc
	ld a, b
	or a, c
	jr nz, Label_51_7334

Label_51_7365:: ; 51:7365
	ld a, $03
	ldh [hWRAMBank], a
	ldh [rSVBK], a
	pop hl
	pop de
	pop bc
	inc bc
	inc bc
	inc bc
	inc bc
	inc bc
	push de
	ld a, [hli]
	ld e, a
	add a, c
	ld c, a
	ld a, [hli]
	ld d, a
	adc a, b
	ld b, a
	add hl, de
	pop de
	inc hl
	inc hl
	jp Label_51_72F8

Label_51_7383:: ; 51:7383
	ld c, e
	ld b, d
	pop de
	dec de
	ld a, e
	cpl
	ld [wRam_C339], a
	ld a, d
	cpl
	ld [wRam_C33A], a
	ld hl, $D001
	add hl, de
	ld e, l
	ld d, h
	pop hl
	dec hl
	dec hl
	push bc
	ld a, [wRam_C339]
	add a, c
	ld c, a
	ld a, [wRam_C33A]
	adc a, b
	ld b, a
	or a, c
	jr z, Label_51_73AB
	call CopyBytes

Label_51_73AB:: ; 51:73AB
	pop bc
	call Function_00_0392
	pop de
	ld hl, $D000
	call CopyBytes
	xor a, a
	ld [de], a
	inc de
	ld [de], a
	inc de
	ld [de], a
	inc de
	ld [de], a
	inc de
	ld [de], a
	ld a, [wRam_C333]
	ldh [hRam_FFD7], a
	ld a, [wRam_C336]
	ldh [hRam_FFD6], a
	pop hl

Label_51_73CB:: ; 51:73CB
	ld a, $01
	ret

Label_51_73CE:: ; 51:73CE
	pop hl
	xor a, a
	ret

; ---- data $73D1-$73DA (9 bytes) [PROBABLE] CGB palette data (RGB555 words): heuristic: 12 RGB555 words as 3 palette group(s) of 4 (bit15 clear, contains $7FFF, monotone luminance) [boundary trimmed 73D1-73E9 -> 73D1-73DA against proven code]

Table_Bmp_RowEndMask:: ; 51:73D1
Data_51_73D1::
	db $FF, $7F, $3F, $1F, $0F, $07, $03, $01, $00

; ---- code $73DA-$740C (50 bytes) [CONFIRMED] 43 insn(s) reached by static flow only; seeds: exec x43; min discovery hops 2; entered by call from 51:719C (PROBABLE code) [executed in 1 scenarios]

Bmp_ColorSum:: ; 51:73DA
	ld a, [hli]
	ld e, a
	ld a, [hli]
	ld d, a
	ld a, [hli]
	ld c, a
	ld a, [hli]
	push hl
	ld hl, $0000
	ld b, l
	add hl, bc
	add hl, bc
	ld c, d
	add hl, bc
	add hl, bc
	ld c, e
	add hl, bc
	add hl, bc
	ld e, l
	ld d, h
	pop hl
	ret

Bmp_RoundUpToTextRow:: ; 51:73F2
	push de
	ld e, a
	ld hl, $000C
	ld d, h
	ld c, h
	ld b, h
	call Divide32by15
	ld a, c
	or a, c
	jr z, Label_51_7402
	inc de

Label_51_7402:: ; 51:7402
	ld l, e
	ld h, d
	add hl, hl
	add hl, hl
	add hl, de
	add hl, de
	add hl, hl
	ld a, l
	pop de
	ret

; ---- data $740C-$740D (1 bytes) [HYPOTHESIS] single $FF byte between the ret at 740B and the function at 740D (ldh [$FFD0],a ...); probably padding, not referenced, not an instruction reached by flow

Data_51_740C:: ; 51:740C
	db $FF

; ---- code $740D-$7900 (1267 bytes) [PROBABLE] 822 insn(s) reached by static flow only; seeds: site x822; min discovery hops 1; entered by far from 4E:5B5C (PROBABLE code)

Image_BlitToTileCanvas:: ; 51:740D
	ldh [hRam_FFD0], a
	ld a, $03
	ldh [hSRAMBank], a
	ld [rRAMB], a
	call Image_MakeEdgeMasks
	call Function_00_0392
	push bc
	ld a, d
	and a, $07
	xor a, $07
	inc a
	ld c, a
	add a, b
	and a, $07
	ldh [hRam_FFD5], a
	ld b, $00
	ld a, c
	and a, $07
	jr z, Label_51_7431
	inc b

Label_51_7431:: ; 51:7431
	ld c, a
	ldh a, [hRam_FFD6]
	sub a, c
	add a, $07
	and a, $F8
	rrca
	rrca
	rrca
	add a, b
	ldh [hRam_FFD4], a
	pop bc
	inc hl
	inc hl
	ld a, [hli]
	add a, $07
	and a, $F8
	rrca
	rrca
	rrca
	ldh [hRam_FFD3], a
	inc hl
	ld a, c
	or a, a
	jr z, Label_51_745D
	push de
	ldh a, [hRam_FFD3]
	ld e, a
	ld d, $00
	ld a, c

Label_51_7458:: ; 51:7458
	add hl, de
	dec a
	jr nz, Label_51_7458
	pop de

Label_51_745D:: ; 51:745D
	push de
	ld a, d
	and a, $07
	ld d, a
	ld a, b
	sub a, d
	cp a, $F9
	jr nc, Label_51_7473
	and a, $F8
	rrca
	rrca
	rrca
	ld e, a
	ld d, $00
	add hl, de
	jr Label_51_7474

Label_51_7473:: ; 51:7473
	dec hl

Label_51_7474:: ; 51:7474
	pop de
	push hl
	ld h, e
	ldh a, [hRam_FFD7]
	add a, e
	ld l, a
	push hl
	ld a, e
	cp a, $60
	jr c, Label_51_7487
	ld a, $03
	ld h, $C1
	jr Label_51_748B

Label_51_7487:: ; 51:7487
	ld a, $02
	ld h, $D0

Label_51_748B:: ; 51:748B
	ldh [hWRAMBank], a
	ldh [rSVBK], a
	ld a, e
	and a, $07
	rlca
	ld l, a
	ld a, e
	and a, $F8
	jr z, Label_51_74A3
	rrca
	rrca
	rrca
	ld bc, $0140

Label_51_749F:: ; 51:749F
	add hl, bc
	dec a
	jr nz, Label_51_749F

Label_51_74A3:: ; 51:74A3
	ld a, d
	and a, $F8
	ld b, $00
	rla
	rl b
	ld c, a
	add hl, bc
	pop bc
	pop de

Label_51_74AF:: ; 51:74AF
	call Function_00_0392
	push de
	push hl
	push bc
	call Image_BlitEdgeStrip
	pop bc
	pop hl
	pop de
	inc b
	ld a, b
	and a, $07
	jr nz, Label_51_74D8
	ld a, l
	add a, $32
	ld l, a
	ld a, h
	adc a, $01
	ld h, a
	cp a, $DF
	jr c, Label_51_74DA
	sub a, $0F
	ld h, a
	ld a, $03
	ldh [hWRAMBank], a
	ldh [rSVBK], a
	jr Label_51_74DA

Label_51_74D8:: ; 51:74D8
	inc l
	inc l

Label_51_74DA:: ; 51:74DA
	ldh a, [hRam_FFD3]
	add a, e
	ld e, a
	jr nc, Label_51_74E1
	inc d

Label_51_74E1:: ; 51:74E1
	ld a, c
	cp a, b
	jr nz, Label_51_74AF
	ret

Image_MakeEdgeMasks:: ; 51:74E6
	push bc
	ld a, d
	and a, $07
	jr z, Label_51_74F9
	xor a, $07
	inc a
	ld b, a
	ld a, $01

Label_51_74F2:: ; 51:74F2
	rlca
	dec b
	jr nz, Label_51_74F2
	dec a
	jr Label_51_74FB

Label_51_74F9:: ; 51:74F9
	ld a, $FF

Label_51_74FB:: ; 51:74FB
	ldh [hRam_FFD1], a
	ldh a, [hRam_FFD6]
	ld b, a
	ld a, d
	add a, b
	and a, $07
	jr z, Label_51_7511
	ld b, a
	ld a, $01

Label_51_7509:: ; 51:7509
	rrca
	dec b
	jr nz, Label_51_7509
	dec a
	cpl
	jr Label_51_7513

Label_51_7511:: ; 51:7511
	ld a, $FF

Label_51_7513:: ; 51:7513
	ldh [hRam_FFD2], a
	pop bc
	ret

Image_BlitEdgeStrip:: ; 51:7517
	ldh a, [hRam_FFD4]
	ld c, a
	cp a, $02
	jr nc, Label_51_7584
	ldh a, [hRam_FFD5]
	ld c, a
	ld a, [de]
	ld b, a
	inc de
	ld a, [de]
	dec c
	inc c
	jr z, Label_51_752F

Label_51_7529:: ; 51:7529
	rla
	rl b
	dec c
	jr nz, Label_51_7529

Label_51_752F:: ; 51:752F
	push de
	ldh a, [hRam_FFD1]
	ld d, a
	ldh a, [hRam_FFD2]
	and a, d
	ld d, a
	cpl
	ld e, a
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_7549
	bit 4, a
	jr nz, Label_51_7546
	xor a, a
	jr Label_51_7553

Label_51_7546:: ; 51:7546
	ld a, b
	jr Label_51_7553

Label_51_7549:: ; 51:7549
	bit 4, a
	jr nz, Label_51_7551
	ld a, b
	cpl
	jr Label_51_7553

Label_51_7551:: ; 51:7551
	ld a, $01

Label_51_7553:: ; 51:7553
	and a, d
	ld c, a
	ld a, [hl]
	and a, e
	or a, c
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_7569
	bit 5, a
	jr nz, Label_51_7566
	xor a, a
	jr Label_51_7573

Label_51_7566:: ; 51:7566
	ld a, b
	jr Label_51_7573

Label_51_7569:: ; 51:7569
	bit 5, a
	jr nz, Label_51_7571
	ld a, b
	cpl
	jr Label_51_7573

Label_51_7571:: ; 51:7571
	ld a, $01

Label_51_7573:: ; 51:7573
	and a, d
	ld c, a
	ld a, [hl]
	and a, e
	or a, c
	ld [hli], a
	pop de
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_7581
	inc h

Label_51_7581:: ; 51:7581
	jp Label_51_76AA

Label_51_7584:: ; 51:7584
	ldh a, [hRam_FFD1]
	cp a, $FF
	jr z, Label_51_75F1
	push bc
	ldh a, [hRam_FFD5]
	ld c, a
	ld a, [de]
	ld b, a
	inc de
	ld a, [de]
	dec c
	inc c
	jr z, Label_51_759C

Label_51_7596:: ; 51:7596
	rla
	rl b
	dec c
	jr nz, Label_51_7596

Label_51_759C:: ; 51:759C
	push de
	ldh a, [hRam_FFD1]
	ld d, a
	ld a, [$740C]
	and a, d
	ld d, a
	cpl
	ld e, a
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_75B7
	bit 4, a
	jr nz, Label_51_75B4
	xor a, a
	jr Label_51_75C1

Label_51_75B4:: ; 51:75B4
	ld a, b
	jr Label_51_75C1

Label_51_75B7:: ; 51:75B7
	bit 4, a
	jr nz, Label_51_75BF
	ld a, b
	cpl
	jr Label_51_75C1

Label_51_75BF:: ; 51:75BF
	ld a, $01

Label_51_75C1:: ; 51:75C1
	and a, d
	ld c, a
	ld a, [hl]
	and a, e
	or a, c
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_75D7
	bit 5, a
	jr nz, Label_51_75D4
	xor a, a
	jr Label_51_75E1

Label_51_75D4:: ; 51:75D4
	ld a, b
	jr Label_51_75E1

Label_51_75D7:: ; 51:75D7
	bit 5, a
	jr nz, Label_51_75DF
	ld a, b
	cpl
	jr Label_51_75E1

Label_51_75DF:: ; 51:75DF
	ld a, $01

Label_51_75E1:: ; 51:75E1
	and a, d
	ld c, a
	ld a, [hl]
	and a, e
	or a, c
	ld [hli], a
	pop de
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_75EF
	inc h

Label_51_75EF:: ; 51:75EF
	pop bc
	dec c

Label_51_75F1:: ; 51:75F1
	ldh a, [hRam_FFD2]
	cp a, $FF
	jr z, Label_51_75F8
	dec c

Label_51_75F8:: ; 51:75F8
	ld a, c
	or a, a
	jr z, Label_51_7640
	ldh a, [hRam_FFD5]
	bit 2, a
	jr nz, Label_51_7622
	bit 1, a
	jr nz, Label_51_7614
	bit 0, a
	jr nz, Label_51_760F
	call Image_BlitStripShift0
	jr Label_51_7640

Label_51_760F:: ; 51:760F
	call Image_BlitStripShift1
	jr Label_51_7640

Label_51_7614:: ; 51:7614
	bit 0, a
	jr nz, Label_51_761D
	call Image_BlitStripShift2
	jr Label_51_7640

Label_51_761D:: ; 51:761D
	call Image_BlitStripShift3
	jr Label_51_7640

Label_51_7622:: ; 51:7622
	bit 1, a
	jr nz, Label_51_7634
	bit 0, a
	jr nz, Label_51_762F
	call Image_BlitStripShift4
	jr Label_51_7640

Label_51_762F:: ; 51:762F
	call Image_BlitStripShift5
	jr Label_51_7640

Label_51_7634:: ; 51:7634
	bit 0, a
	jr nz, Label_51_763D
	call Image_BlitStripShift6
	jr Label_51_7640

Label_51_763D:: ; 51:763D
	call Image_BlitStripShift7

Label_51_7640:: ; 51:7640
	ldh a, [hRam_FFD2]
	cp a, $FF
	jr z, Label_51_76AA
	ldh a, [hRam_FFD5]
	ld c, a
	ld a, [de]
	ld b, a
	inc de
	ld a, [de]
	dec c
	inc c
	jr z, Label_51_7657

Label_51_7651:: ; 51:7651
	rla
	rl b
	dec c
	jr nz, Label_51_7651

Label_51_7657:: ; 51:7657
	push de
	ldh a, [hRam_FFD2]
	ld d, a
	ld a, [$740C]
	and a, d
	ld d, a
	cpl
	ld e, a
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_7672
	bit 4, a
	jr nz, Label_51_766F
	xor a, a
	jr Label_51_767C

Label_51_766F:: ; 51:766F
	ld a, b
	jr Label_51_767C

Label_51_7672:: ; 51:7672
	bit 4, a
	jr nz, Label_51_767A
	ld a, b
	cpl
	jr Label_51_767C

Label_51_767A:: ; 51:767A
	ld a, $01

Label_51_767C:: ; 51:767C
	and a, d
	ld c, a
	ld a, [hl]
	and a, e
	or a, c
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_7692
	bit 5, a
	jr nz, Label_51_768F
	xor a, a
	jr Label_51_769C

Label_51_768F:: ; 51:768F
	ld a, b
	jr Label_51_769C

Label_51_7692:: ; 51:7692
	bit 5, a
	jr nz, Label_51_769A
	ld a, b
	cpl
	jr Label_51_769C

Label_51_769A:: ; 51:769A
	ld a, $01

Label_51_769C:: ; 51:769C
	and a, d
	ld c, a
	ld a, [hl]
	and a, e
	or a, c
	ld [hli], a
	pop de
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_76AA
	inc h

Label_51_76AA:: ; 51:76AA
	ret

Image_BlitStripShift0:: ; 51:76AB
	ld a, [de]
	ld b, a
	inc de
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_76BE
	bit 4, a
	jr nz, Label_51_76BB
	xor a, a
	jr Label_51_76C8

Label_51_76BB:: ; 51:76BB
	ld a, b
	jr Label_51_76C8

Label_51_76BE:: ; 51:76BE
	bit 4, a
	jr nz, Label_51_76C6
	ld a, b
	cpl
	jr Label_51_76C8

Label_51_76C6:: ; 51:76C6
	ld a, $01

Label_51_76C8:: ; 51:76C8
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_76D9
	bit 5, a
	jr nz, Label_51_76D6
	xor a, a
	jr Label_51_76E3

Label_51_76D6:: ; 51:76D6
	ld a, b
	jr Label_51_76E3

Label_51_76D9:: ; 51:76D9
	bit 5, a
	jr nz, Label_51_76E1
	ld a, b
	cpl
	jr Label_51_76E3

Label_51_76E1:: ; 51:76E1
	ld a, $01

Label_51_76E3:: ; 51:76E3
	ld [hli], a
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_76EB
	inc h

Label_51_76EB:: ; 51:76EB
	dec c
	jr nz, Image_BlitStripShift0
	ret

Image_BlitStripShift1:: ; 51:76EF
	ld a, [de]
	ld b, a
	inc de
	ld a, [de]
	rla
	rl b
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_7706
	bit 4, a
	jr nz, Label_51_7703
	xor a, a
	jr Label_51_7710

Label_51_7703:: ; 51:7703
	ld a, b
	jr Label_51_7710

Label_51_7706:: ; 51:7706
	bit 4, a
	jr nz, Label_51_770E
	ld a, b
	cpl
	jr Label_51_7710

Label_51_770E:: ; 51:770E
	ld a, $01

Label_51_7710:: ; 51:7710
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_7721
	bit 5, a
	jr nz, Label_51_771E
	xor a, a
	jr Label_51_772B

Label_51_771E:: ; 51:771E
	ld a, b
	jr Label_51_772B

Label_51_7721:: ; 51:7721
	bit 5, a
	jr nz, Label_51_7729
	ld a, b
	cpl
	jr Label_51_772B

Label_51_7729:: ; 51:7729
	ld a, $01

Label_51_772B:: ; 51:772B
	ld [hli], a
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_7733
	inc h

Label_51_7733:: ; 51:7733
	dec c
	jr nz, Image_BlitStripShift1
	ret

Image_BlitStripShift2:: ; 51:7737
	ld a, [de]
	ld b, a
	inc de
	ld a, [de]
	rla
	rl b
	rla
	rl b
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_7751
	bit 4, a
	jr nz, Label_51_774E
	xor a, a
	jr Label_51_775B

Label_51_774E:: ; 51:774E
	ld a, b
	jr Label_51_775B

Label_51_7751:: ; 51:7751
	bit 4, a
	jr nz, Label_51_7759
	ld a, b
	cpl
	jr Label_51_775B

Label_51_7759:: ; 51:7759
	ld a, $01

Label_51_775B:: ; 51:775B
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_776C
	bit 5, a
	jr nz, Label_51_7769
	xor a, a
	jr Label_51_7776

Label_51_7769:: ; 51:7769
	ld a, b
	jr Label_51_7776

Label_51_776C:: ; 51:776C
	bit 5, a
	jr nz, Label_51_7774
	ld a, b
	cpl
	jr Label_51_7776

Label_51_7774:: ; 51:7774
	ld a, $01

Label_51_7776:: ; 51:7776
	ld [hli], a
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_777E
	inc h

Label_51_777E:: ; 51:777E
	dec c
	jr nz, Image_BlitStripShift2
	ret

Image_BlitStripShift3:: ; 51:7782
	ld a, [de]
	ld b, a
	inc de
	ld a, [de]
	rla
	rl b
	rla
	rl b
	rla
	rl b
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_779F
	bit 4, a
	jr nz, Label_51_779C
	xor a, a
	jr Label_51_77A9

Label_51_779C:: ; 51:779C
	ld a, b
	jr Label_51_77A9

Label_51_779F:: ; 51:779F
	bit 4, a
	jr nz, Label_51_77A7
	ld a, b
	cpl
	jr Label_51_77A9

Label_51_77A7:: ; 51:77A7
	ld a, $01

Label_51_77A9:: ; 51:77A9
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_77BA
	bit 5, a
	jr nz, Label_51_77B7
	xor a, a
	jr Label_51_77C4

Label_51_77B7:: ; 51:77B7
	ld a, b
	jr Label_51_77C4

Label_51_77BA:: ; 51:77BA
	bit 5, a
	jr nz, Label_51_77C2
	ld a, b
	cpl
	jr Label_51_77C4

Label_51_77C2:: ; 51:77C2
	ld a, $01

Label_51_77C4:: ; 51:77C4
	ld [hli], a
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_77CC
	inc h

Label_51_77CC:: ; 51:77CC
	dec c
	jr nz, Image_BlitStripShift3
	ret

Image_BlitStripShift4:: ; 51:77D0
	ld a, [de]
	and a, $0F
	ld b, a
	inc de
	ld a, [de]
	and a, $F0
	or a, b
	swap a
	ld b, a
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_77EC
	bit 4, a
	jr nz, Label_51_77E9
	xor a, a
	jr Label_51_77F6

Label_51_77E9:: ; 51:77E9
	ld a, b
	jr Label_51_77F6

Label_51_77EC:: ; 51:77EC
	bit 4, a
	jr nz, Label_51_77F4
	ld a, b
	cpl
	jr Label_51_77F6

Label_51_77F4:: ; 51:77F4
	ld a, $01

Label_51_77F6:: ; 51:77F6
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_7807
	bit 5, a
	jr nz, Label_51_7804
	xor a, a
	jr Label_51_7811

Label_51_7804:: ; 51:7804
	ld a, b
	jr Label_51_7811

Label_51_7807:: ; 51:7807
	bit 5, a
	jr nz, Label_51_780F
	ld a, b
	cpl
	jr Label_51_7811

Label_51_780F:: ; 51:780F
	ld a, $01

Label_51_7811:: ; 51:7811
	ld [hli], a
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_7819
	inc h

Label_51_7819:: ; 51:7819
	dec c
	jr nz, Image_BlitStripShift4
	ret

Image_BlitStripShift5:: ; 51:781D
	ld a, [de]
	and a, $07
	ld b, a
	inc de
	ld a, [de]
	and a, $F8
	or a, b
	rrca
	rrca
	rrca
	ld b, a
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_783A
	bit 4, a
	jr nz, Label_51_7837
	xor a, a
	jr Label_51_7844

Label_51_7837:: ; 51:7837
	ld a, b
	jr Label_51_7844

Label_51_783A:: ; 51:783A
	bit 4, a
	jr nz, Label_51_7842
	ld a, b
	cpl
	jr Label_51_7844

Label_51_7842:: ; 51:7842
	ld a, $01

Label_51_7844:: ; 51:7844
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_7855
	bit 5, a
	jr nz, Label_51_7852
	xor a, a
	jr Label_51_785F

Label_51_7852:: ; 51:7852
	ld a, b
	jr Label_51_785F

Label_51_7855:: ; 51:7855
	bit 5, a
	jr nz, Label_51_785D
	ld a, b
	cpl
	jr Label_51_785F

Label_51_785D:: ; 51:785D
	ld a, $01

Label_51_785F:: ; 51:785F
	ld [hli], a
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_7867
	inc h

Label_51_7867:: ; 51:7867
	dec c
	jr nz, Image_BlitStripShift5
	ret

Image_BlitStripShift6:: ; 51:786B
	ld a, [de]
	ld b, a
	inc de
	ld a, [de]
	rr b
	rra
	rr b
	rra
	ld b, a
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_7886
	bit 4, a
	jr nz, Label_51_7883
	xor a, a
	jr Label_51_7890

Label_51_7883:: ; 51:7883
	ld a, b
	jr Label_51_7890

Label_51_7886:: ; 51:7886
	bit 4, a
	jr nz, Label_51_788E
	ld a, b
	cpl
	jr Label_51_7890

Label_51_788E:: ; 51:788E
	ld a, $01

Label_51_7890:: ; 51:7890
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_78A1
	bit 5, a
	jr nz, Label_51_789E
	xor a, a
	jr Label_51_78AB

Label_51_789E:: ; 51:789E
	ld a, b
	jr Label_51_78AB

Label_51_78A1:: ; 51:78A1
	bit 5, a
	jr nz, Label_51_78A9
	ld a, b
	cpl
	jr Label_51_78AB

Label_51_78A9:: ; 51:78A9
	ld a, $01

Label_51_78AB:: ; 51:78AB
	ld [hli], a
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_78B3
	inc h

Label_51_78B3:: ; 51:78B3
	dec c
	jr nz, Image_BlitStripShift6
	ret

Image_BlitStripShift7:: ; 51:78B7
	ld a, [de]
	ld b, a
	inc de
	ld a, [de]
	rr b
	rra
	ld b, a
	ldh a, [hRam_FFD0]
	bit 0, a
	jr nz, Label_51_78CF
	bit 4, a
	jr nz, Label_51_78CC
	xor a, a
	jr Label_51_78D9

Label_51_78CC:: ; 51:78CC
	ld a, b
	jr Label_51_78D9

Label_51_78CF:: ; 51:78CF
	bit 4, a
	jr nz, Label_51_78D7
	ld a, b
	cpl
	jr Label_51_78D9

Label_51_78D7:: ; 51:78D7
	ld a, $01

Label_51_78D9:: ; 51:78D9
	ld [hli], a
	ldh a, [hRam_FFD0]
	bit 1, a
	jr nz, Label_51_78EA
	bit 5, a
	jr nz, Label_51_78E7
	xor a, a
	jr Label_51_78F4

Label_51_78E7:: ; 51:78E7
	ld a, b
	jr Label_51_78F4

Label_51_78EA:: ; 51:78EA
	bit 5, a
	jr nz, Label_51_78F2
	ld a, b
	cpl
	jr Label_51_78F4

Label_51_78F2:: ; 51:78F2
	ld a, $01

Label_51_78F4:: ; 51:78F4
	ld [hli], a
	ld a, $0E
	add a, l
	ld l, a
	jr nc, Label_51_78FC
	inc h

Label_51_78FC:: ; 51:78FC
	dec c
	jr nz, Image_BlitStripShift7
	ret

; ---- zero $7900-$8000 (1792 bytes) [PROBABLE] trailing 0x00 padding to end of bank
	ds $700, $00
