; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 7A

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank7A", ROMX[$4000], BANK[$7A]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $1E8000, $4000
