; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 0E

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"
INCLUDE "constants/macros.inc"

SECTION "Bank0E", ROMX[$4000], BANK[$0E]

; ---- code $4000-$4094 (148 bytes) [CONFIRMED] 70 insn(s); 70 executed (in up to 14/18 scenarios); entry proven: target of an executed call/far call

Title_Run:: ; 0E:4000
Function_0E_4000::
	ld [wRam_C280], a
	ld b, $15
	ld c, $03
	farcall Joypad_SetRepeatTiming
	ld a, [wRam_C280]
	or a, a
	jr nz, Label_0E_4019
	xor a, a
	ld [wRam_C27C], a
	jr Label_0E_401E

Label_0E_4019:: ; 0E:4019
	ld a, $03
	ld [wRam_C27C], a

Label_0E_401E:: ; 0E:401E
	call Title_StateLoop
	ld a, [wRam_C27D]
	ld hl, $BF00
	ld b, a
	ldh [hScratchA], a
	ldh a, [hSRAMEnable]
	push af
	ldh a, [hScratchA]
	ldh [hScratchA], a
	ldh a, [hSRAMBank]
	push af
	ldh a, [hScratchA]
	ld a, $01
	ldh [hSRAMBank], a
	ld [rRAMB], a
	ld a, $0A
	ldh [hSRAMEnable], a
	ld [rRAMG], a
	ld a, b
	ld [hl], a
	ldh [hScratchA], a
	pop af
	ldh [hSRAMBank], a
	ld [rRAMB], a
	ldh a, [hScratchA]
	ldh [hScratchA], a
	pop af
	ldh [hSRAMEnable], a
	ld [rRAMG], a
	ldh a, [hScratchA]
	ld a, [wRam_C27D]
	inc a
	ret

Title_StateLoop:: ; 0E:405F
	farcall Joypad_Update
	call Title_DispatchState
	farcall Function_00_0956
	call Function_00_044B
	ld a, [wRam_C27C]
	cp a, $FF
	jr nz, Title_StateLoop
	call Function_00_044B
	ld hl, $FF40
	ld a, [hl]
	and a, $FB
	ld [hl], a
	ret

Title_DispatchState:: ; 0E:4083
	ld a, [wRam_C27C]
	ld hl, Table_Title_States
	add a, a
	add a, l
	ld l, a
	ld a, $00
	adc a, h
	ld h, a
	ld a, [hli]
	ld h, [hl]
	ld l, a
	jp hl

; ---- ptrtable $4094-$40A2 (14 bytes) [PROBABLE] code-pointer table, 7 entries: 7/7 words hit own-bank code starts (survey pointer-table extent); 6/7 targets executed

Table_Title_States:: ; 0E:4094
Table_0E_4094::
	dw Title_StateLoadLogo
	dw Title_StateLogoWait
	dw Title_StateLogoFadeOut
	dw Title_StateLoadTitle
	dw Title_StateMenu
	dw Title_StateExit
	dw Title_StateTimeoutRestart

; ---- code $40A2-$4192 (240 bytes) [CONFIRMED] 114 insn(s); 114 executed (in up to 14/18 scenarios)

Title_StateLoadLogo:: ; 0E:40A2
	call Title_LoadLogoScreen
	farcall Palette_FadeInFromWhiteSlow
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $001B
	call Function_00_20E8
	pop af
	ldh [rSVBK], a
	xor a, a
	ld [wRam_C27E], a
	ld [wRam_C27F], a
	ld a, [wRam_C27C]
	inc a
	ld [wRam_C27C], a
	ret

Title_StateLogoWait:: ; 0E:40CA
	ld a, [wRam_C27E]
	ld b, a
	ld a, [wRam_C27F]
	ld c, a
	ld h, b
	ld l, c
	ld de, $00B4
	ld a, d
	cp a, b
	jr nz, Label_0E_40DD
	ld a, e
	cp a, c

Label_0E_40DD:: ; 0E:40DD
	jr z, Label_0E_4104
	inc hl
	ld a, h
	ld [wRam_C27E], a
	ld a, l
	ld [wRam_C27F], a
	ldh a, [hJoyPressedRepeat]
	bit 0, a
	jr nz, Label_0E_40F4
	bit 3, a
	jr nz, Label_0E_40F4
	jr Label_0E_410B

Label_0E_40F4:: ; 0E:40F4
	farcall Palette_FadeOutToWhite
	ld a, [wRam_C27C]
	add a, $02
	ld [wRam_C27C], a
	jr Label_0E_410B

Label_0E_4104:: ; 0E:4104
	ld a, [wRam_C27C]
	inc a
	ld [wRam_C27C], a

Label_0E_410B:: ; 0E:410B
	ret

Title_StateLogoFadeOut:: ; 0E:410C
	farcall Palette_FadeOutToWhiteSlow
	ld a, [wRam_C27C]
	inc a
	ld [wRam_C27C], a
	ret

Title_StateLoadTitle:: ; 0E:411A
	ld hl, $BF00
	ldh [hScratchA], a
	ldh a, [hSRAMEnable]
	push af
	ldh a, [hScratchA]
	ldh [hScratchA], a
	ldh a, [hSRAMBank]
	push af
	ldh a, [hScratchA]
	ld a, $01
	ldh [hSRAMBank], a
	ld [rRAMB], a
	ld a, $0A
	ldh [hSRAMEnable], a
	ld [rRAMG], a
	ld a, [hl]
	ld b, a
	ldh [hScratchA], a
	pop af
	ldh [hSRAMBank], a
	ld [rRAMB], a
	ldh a, [hScratchA]
	ldh [hScratchA], a
	pop af
	ldh [hSRAMEnable], a
	ld [rRAMG], a
	ldh a, [hScratchA]
	ld a, b
	ld [wRam_C27D], a
	call Title_LoadTitleScreen
	farcall Palette_FadeInFromWhite
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $0001
	call Function_00_20E8
	pop af
	ldh [rSVBK], a
	xor a, a
	ld [wRam_C27E], a
	ld [wRam_C27F], a
	ld a, [wRam_C27C]
	inc a
	ld [wRam_C27C], a
	ret

Title_StateMenu:: ; 0E:417B
	ld a, [wRam_C280]
	or a, a
	jr nz, Title_MenuHandleButtons
	ld a, [wRam_C27E]
	ld b, a
	ld a, [wRam_C27F]
	ld c, a
	ld h, b
	ld l, c
	ld de, $2A30
	ld a, d
	cp a, b
	jr nz, Label_0E_4194

; ---- code $4192-$4194 (2 bytes) [PROBABLE] 2 insn(s) reached by static flow only; seeds: exec x2; min discovery hops 0; fall-through of the jrcc at 0E:4190 (executed)
	ld a, e
	cp a, c

; ---- code $4194-$41B3 (31 bytes) [CONFIRMED] 16 insn(s); 16 executed (in up to 14/18 scenarios)

Label_0E_4194:: ; 0E:4194
	jr z, Title_MenuTimeout
	inc hl
	ld a, h
	ld [wRam_C27E], a
	ld a, l
	ld [wRam_C27F], a

Title_MenuHandleButtons:: ; 0E:419F
	ldh a, [hJoyPressedRepeat]
	bit 0, a
	jr nz, Title_MenuConfirm
	bit 3, a
	jr nz, Title_MenuConfirm
	bit 6, a
	jr nz, Title_MenuToggleSelection
	bit 7, a
	jr nz, Title_MenuToggleSelection
	jr Label_0E_41FD

; ---- code $41B3-$41BA (7 bytes) [PROBABLE] 3 insn(s) reached by static flow only; seeds: exec x3; min discovery hops 1; entered by jrcc from 0E:4194 (executed)

Title_MenuTimeout:: ; 0E:41B3
	ld a, $06
	ld [wRam_C27C], a
	jr Label_0E_41FD

; ---- code $41BA-$420A (80 bytes) [CONFIRMED] 35 insn(s); 35 executed (in up to 14/18 scenarios)

Title_MenuToggleSelection:: ; 0E:41BA
	xor a, a
	ld [wRam_C27E], a
	ld [wRam_C27F], a
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $0029
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	ld a, [wRam_C27D]
	xor a, $01
	ld [wRam_C27D], a
	call Title_PlaceCursor
	call Title_DrawMenuHighlight
	ldh a, [rLCDC]
	call Function_00_07CB
	jr Label_0E_41FD

Title_MenuConfirm:: ; 0E:41E6
	ldh a, [hWRAMBank]
	push af
	ld a, $01
	ldh [rSVBK], a
	ld bc, $002C
	call Function_00_20AC
	pop af
	ldh [rSVBK], a
	ld a, [wRam_C27C]
	inc a
	ld [wRam_C27C], a

Label_0E_41FD:: ; 0E:41FD
	ret

Title_StateExit:: ; 0E:41FE
	farcall Palette_FadeOutToWhite
	ld a, $FF
	ld [wRam_C27C], a
	ret

; ---- code $420A-$4215 (11 bytes) [PROBABLE] 4 insn(s) reached by static flow only; seeds: site x4; min discovery hops 0; run starts at a raw `CD D1 06` (far-call) pattern site whose target agrees with decoded code

Title_StateTimeoutRestart:: ; 0E:420A
	farcall Palette_FadeOutToWhite
	xor a, a
	ld [wRam_C27C], a
	ret

; ---- code $4215-$4330 (283 bytes) [CONFIRMED] 98 insn(s); 98 executed (in up to 14/18 scenarios); entry proven: target of an executed call/far call

Title_LoadTitleScreen:: ; 0E:4215
Function_0E_4215::
	call Function_00_044B
	ld hl, $FF40
	ld a, [hl]
	or a, $04
	ld [hl], a
	farcall Function_00_09B6
	ld de, $8000
	ld hl, Gfx_Title_Tiles0
	ld a, $0E
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld de, $8800
	ld hl, Gfx_Title_Tiles1
	ld a, $0E
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld de, $8001
	ld hl, $49C0
	ld a, $0E
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld de, $8801
	ld hl, Gfx_Title_Tiles2
	ld a, $0E
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld de, $8C01
	ld hl, Gfx_Title_Tiles4
	ld a, $0E
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld de, $9001
	ld hl, Gfx_Title_Tiles5
	ld a, $0E
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld de, $9401
	ld hl, Gfx_Title_Tiles6
	ld a, $0E
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld bc, $0040
	ld de, $D800
	ld hl, Palette_Title_Bg
	ld a, $0E
	farcall Palette_LoadToBuffer
	ld bc, $0040
	ld de, $D840
	ld hl, $5F70
	ld a, $0E
	farcall Palette_LoadToBuffer
	ld bc, $1214
	ld de, $D000
	ld hl, Tilemap_Title_Screen
	ld a, $0E
	farcall Function_00_08EA
	call Title_DrawMenuHighlight
	ldh a, [rLCDC]
	call Function_00_07CB
	ld hl, $DA10
	ld de, $5FB0
	ld a, $0E
	ld b, $81
	farcall Function_00_0A82
	call Title_PlaceCursor
	ld hl, $DA20
	ld de, $5FB0
	ld a, $0E
	ld b, $82
	farcall Function_00_0A82
	ld de, $0000
	ld hl, $DA20
	call Function_00_0A65
	farcall Function_00_0956
	ret

Title_DrawMenuHighlight:: ; 0E:4311
	ld a, [wRam_C27D]
	ld de, $D185
	ld bc, $040A
	ld hl, Table_Title_HighlightTilemaps
	add a, a
	add a, l
	ld l, a
	ld a, $00
	adc a, h
	ld h, a
	ld a, [hli]
	ld h, [hl]
	ld l, a
	ld a, $0E
	farcall Function_00_08EA
	ret

; ---- data $4330-$4334 (4 bytes) [CONFIRMED] read as data by executed code (in up to 14/18 scenarios); content class unknown

Table_Title_HighlightTilemaps:: ; 0E:4330
Data_0E_4330::
	db $90, $5E, $E0, $5E

; ---- code $4334-$434B (23 bytes) [CONFIRMED] 14 insn(s); 14 executed (in up to 14/18 scenarios); entry proven: target of an executed call/far call

Title_PlaceCursor:: ; 0E:4334
Function_0E_4334::
	ld a, [wRam_C27D]
	ld hl, Table_Title_CursorPositions
	add a, a
	add a, l
	ld l, a
	ld a, $00
	adc a, h
	ld h, a
	ld a, [hli]
	ld d, [hl]
	ld e, a
	ld hl, $DA10
	call Function_00_0A65
	ret

; ---- data $434B-$434F (4 bytes) [CONFIRMED] read as data by executed code (in up to 14/18 scenarios); content class unknown

Table_Title_CursorPositions:: ; 0E:434B
Data_0E_434B::
	db $18, $60, $18, $70

; ---- code $434F-$43B1 (98 bytes) [CONFIRMED] 32 insn(s); 32 executed (in up to 14/18 scenarios); entry proven: target of an executed call/far call

Title_LoadLogoScreen:: ; 0E:434F
Function_0E_434F::
	call Function_00_044B
	ld hl, $FF40
	ld a, [hl]
	or a, $04
	ld [hl], a
	farcall Function_00_09B6
	ld de, $9001
	ld hl, Gfx_TitleLogo_Tiles0
	ld a, $0E
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld de, $9401
	ld hl, Gfx_TitleLogo_Tiles1
	ld a, $0E
	ld b, $92
	ld c, $40
	farcall Function_00_0787
	ld bc, $0040
	ld de, $D800
	ld hl, Palette_TitleLogo
	ld a, $0E
	farcall Palette_LoadToBuffer
	ld bc, $1214
	ld de, $D000
	ld hl, Tilemap_TitleLogo_Screen
	ld a, $0E
	farcall Function_00_08EA
	ldh a, [rLCDC]
	call Function_00_07CB
	farcall Function_00_0956
	ret

; ---- zero $43B1-$43C0 (15 bytes) [PROBABLE] 15 zero bytes: padding between the ret at 43B0 and the tile block at 43C0 (all bytes are $00)
	ds $F, $00

; ---- gfx $43C0-$47C0 (1024 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 0E:4231: hl=$43C0 a=$0E c=$40 de=$8000 (dest VRAM $8000, vbank=0)

Gfx_Title_Tiles0:: ; 0E:43C0
Data_0E_43C0::
	db $00, $00, $00, $00, $00, $00, $03, $03, $07, $07, $0F, $0F, $0F, $0F, $3F, $1F
	db $3F, $1F, $1F, $1F, $7D, $3D, $7E, $3E, $75, $35, $7A, $3A, $55, $15, $6A, $2A
	db $00, $00, $60, $00, $E8, $E0, $F4, $F0, $FC, $F8, $FA, $F8, $D6, $D4, $EA, $E8
	db $57, $54, $AB, $A8, $57, $54, $A3, $A0, $53, $50, $83, $80, $43, $40, $02, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $10, $0F, $40, $3F, $80, $7F, $00, $FF
	db $80, $7F, $C1, $3E, $FE, $00, $FF, $00, $FA, $00, $FD, $00, $EA, $00, $F4, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $20, $C0, $00, $E0, $30, $C0, $78, $80
	db $A8, $00, $50, $00, $80, $00, $40, $00, $80, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $01, $01, $01, $03, $03, $07, $06, $07, $0E
	db $0F, $1C, $1F, $18, $3F, $30, $3F, $70, $7F, $E0, $FF, $E0, $FF, $E0, $FF, $F0
	db $00, $00, $03, $00, $07, $00, $1F, $00, $03, $3C, $00, $FF, $00, $FF, $00, $7F
	db $00, $3F, $00, $3F, $00, $1F, $00, $1F, $00, $1F, $00, $0F, $00, $0F, $00, $0F
	db $C1, $00, $C3, $00, $C3, $00, $C3, $00, $C3, $00, $C3, $00, $43, $80, $43, $80
	db $43, $80, $43, $80, $42, $81, $42, $81, $42, $81, $02, $81, $02, $81, $02, $81
	db $00, $00, $00, $00, $00, $00, $00, $F0, $00, $FE, $00, $FF, $01, $FF, $01, $FF
	db $03, $FF, $07, $FF, $0F, $FF, $0F, $FF, $1F, $FF, $3F, $FC, $7F, $F8, $7F, $F8
	db $00, $07, $00, $07, $00, $03, $00, $03, $00, $02, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $03, $00, $03, $00, $03, $00, $07, $00, $07, $00, $0F, $00, $0F, $00, $1F
	db $00, $3F, $01, $7F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $FF, $FC, $FF, $FE, $78, $78, $30, $30, $30, $30, $30, $30, $30, $30, $30, $30
	db $30, $30, $30, $30, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $FF, $0F, $FF, $07, $0F, $03, $07, $03, $07, $07, $07, $07, $07, $07, $07, $07
	db $07, $07, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $FF, $FC, $FF, $FE, $F0, $F0, $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0
	db $E0, $E0, $60, $60, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $FF, $00, $FF, $00, $1F, $00, $0F, $00, $0F, $00, $0F, $08, $0D, $0E, $0F, $0F
	db $0F, $0F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $FF, $FE, $06, $05, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $FC, $18, $F8, $30, $B0, $20, $70, $60, $F0, $C0, $D0, $A0, $90, $60, $90, $60
	db $00, $E0, $00, $E0, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $55, $15, $68, $28, $74, $34, $40, $00, $30, $10, $20, $00, $18, $00, $0F, $00
	db $0C, $00, $1C, $00, $08, $10, $00, $18, $20, $18, $08, $30, $00, $30, $40, $30
	db $06, $00, $04, $00, $0C, $00, $08, $00, $18, $00, $30, $00, $E0, $00, $80, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $81, $00, $FF, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $C0, $00, $FF, $00, $FF, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $FF, $00, $FF, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $06, $06, $07, $07, $07, $07
	db $07, $07, $07, $07, $07, $07, $07, $07, $07, $07, $07, $03, $FE, $01, $FF, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $E0, $E0, $E0, $E0
	db $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0, $E0, $F0, $F0, $FF, $FF, $9F, $7E
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $03, $F8, $07, $FC, $03
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $06, $00, $06
	db $00, $0C, $00, $1C, $00, $38, $00, $70, $00, $F0, $00, $E0, $00, $C0, $00, $80
	db $1F, $00, $1F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $10, $00, $30, $00, $20, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $03, $00
	db $07, $00, $0F, $01, $0F, $00, $0F, $01, $0F, $00, $0F, $01, $0F, $00, $0F, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $FC, $00, $FF, $28, $FF, $54
	db $FF, $BA, $FF, $7D, $FF, $FE, $FF, $7D, $FF, $FE, $FF, $7D, $FF, $AA, $FF, $54
	db $FF, $00, $FF, $00, $FF, $00, $7F, $00, $1F, $00, $00, $00, $C0, $00, $FC, $38
	db $FE, $06, $FE, $02, $70, $00, $70, $00, $30, $00, $20, $00, $00, $00, $00, $00
	db $00, $70, $90, $60, $00, $E0, $00, $E0, $00, $E0, $20, $C0, $C0, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $02, $01, $01, $02, $02, $01, $04, $03, $00, $07, $00, $0F, $00, $0F, $00, $1F
	db $00, $3F, $00, $7E, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $E8, $E8, $D4, $D4, $E8, $E8, $D0, $20, $A0, $5E, $D0, $2F, $A0, $5E, $C0, $3C
	db $A0, $5C, $40, $B8, $80, $70, $40, $A0, $80, $60, $00, $C0, $00, $80, $00, $00

; ---- gfx $47C0-$4BC0 (1024 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 0E:4243: hl=$47C0 a=$0E c=$40 de=$8800 (dest VRAM $8800, vbank=0)

Gfx_Title_Tiles1:: ; 0E:47C0
Data_0E_47C0::
	db $00, $FF, $00, $FF, $01, $FE, $03, $FD, $07, $FA, $07, $FA, $02, $FD, $07, $FA
	db $17, $FA, $3A, $FD, $7B, $FD, $7B, $FD, $7B, $FD, $7D, $BE, $2E, $DF, $1F, $E0
	db $00, $FF, $00, $FF, $F9, $06, $FF, $F9, $FB, $06, $FB, $06, $C7, $3A, $FB, $06
	db $FB, $06, $C7, $3A, $DF, $3A, $FB, $06, $FB, $06, $06, $F9, $F9, $06, $FF, $00
	db $00, $FF, $00, $FF, $B6, $49, $FF, $B6, $B6, $49, $B6, $49, $81, $7E, $BB, $65
	db $BB, $66, $BB, $66, $B8, $67, $BB, $64, $BA, $65, $65, $9B, $9B, $67, $FF, $00
	db $00, $FF, $00, $FF, $1C, $E3, $3F, $DC, $ED, $33, $DD, $63, $BB, $C5, $77, $89
	db $F7, $09, $F7, $09, $74, $CB, $F7, $4A, $F7, $4A, $4A, $B5, $B5, $CE, $FF, $00
	db $00, $FF, $00, $FF, $F8, $07, $FD, $FA, $FA, $25, $FB, $25, $FB, $25, $FB, $24
	db $FB, $24, $FB, $24, $FB, $24, $FD, $22, $BD, $62, $62, $9D, $9D, $63, $FF, $00
	db $00, $FF, $00, $FF, $66, $99, $FF, $66, $EE, $99, $FF, $00, $FF, $00, $66, $99
	db $EE, $99, $E8, $9F, $EF, $9E, $FE, $81, $BE, $41, $41, $BE, $BE, $C1, $FF, $00
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $FD, $02, $FF, $FC, $FF, $82, $FE, $81
	db $86, $79, $FE, $09, $F6, $39, $FE, $41, $FD, $42, $43, $BC, $BE, $C1, $FF, $00
	db $00, $FF, $00, $FF, $7F, $80, $FF, $7F, $FF, $80, $FF, $80, $98, $67, $F7, $48
	db $F4, $4B, $F6, $49, $FF, $46, $BE, $41, $DE, $21, $21, $DE, $DE, $E1, $FF, $00
	db $00, $FF, $00, $FF, $33, $CC, $FF, $33, $77, $CA, $77, $CA, $F7, $4A, $F7, $4A
	db $F7, $4A, $F7, $4A, $F7, $4A, $FB, $46, $DB, $26, $66, $99, $BD, $C2, $FF, $00
	db $00, $FF, $00, $FF, $00, $FF, $80, $7F, $40, $BF, $A0, $5F, $A0, $5F, $A0, $5F
	db $A8, $5F, $AC, $5F, $AE, $5F, $AE, $5F, $AE, $5F, $5E, $BD, $B4, $7B, $F8, $07
	db $00, $FF, $00, $FF, $00, $FF, $01, $FE, $03, $FD, $03, $FD, $01, $FE, $00, $FF
	db $1F, $FF, $3E, $FF, $7D, $FE, $7B, $FD, $7B, $FD, $7D, $BE, $2E, $DF, $1F, $E0
	db $03, $FC, $00, $FF, $FC, $03, $FE, $FD, $FD, $02, $FD, $02, $0D, $F2, $ED, $13
	db $5D, $A3, $FB, $44, $FD, $82, $EE, $11, $D6, $29, $A9, $D6, $D6, $39, $FF, $00
	db $00, $00, $00, $FF, $7E, $81, $FF, $7E, $FE, $81, $FE, $81, $E6, $99, $EE, $19
	db $DE, $21, $3E, $C1, $FE, $71, $FD, $82, $FA, $85, $85, $7B, $7B, $87, $FF, $00
	db $00, $00, $00, $FF, $00, $FF, $00, $FF, $80, $7F, $80, $7F, $FE, $01, $FF, $7E
	db $FE, $81, $FE, $81, $81, $7E, $7E, $81, $80, $FF, $FF, $FF, $FF, $FF, $FF, $00
	db $C0, $3F, $00, $FF, $30, $CF, $78, $B7, $F4, $4B, $F4, $4B, $F7, $48, $FF, $4F
	db $FF, $40, $FF, $40, $F0, $4F, $F7, $48, $F4, $4B, $4B, $B7, $B7, $CF, $FF, $00
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $80, $7F
	db $58, $BF, $5C, $BF, $BE, $7F, $7E, $FF, $FE, $FF, $FE, $FD, $F4, $FB, $F8, $07
	db $00, $00, $F7, $00, $D6, $63, $D6, $63, $D6, $63, $D6, $63, $D6, $63, $D6, $63
	db $D6, $63, $D6, $63, $D6, $63, $D6, $63, $D6, $63, $D6, $63, $F7, $00, $00, $00
	db $00, $00, $00, $00, $80, $00, $40, $80, $20, $C0, $10, $E0, $08, $F0, $04, $F8
	db $04, $F8, $08, $F0, $10, $E0, $20, $C0, $40, $80, $80, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $F6, $00, $D7, $62, $D6, $63, $D6, $63, $D6, $63, $D6, $63
	db $D6, $63, $D6, $63, $D6, $63, $D6, $63, $D7, $62, $F6, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $80, $00, $40, $80, $20, $C0, $10, $E0
	db $10, $E0, $20, $C0, $40, $80, $80, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $F6, $00, $D7, $62, $D6, $63, $D6, $63, $D6, $63
	db $D6, $63, $D6, $63, $D6, $63, $D7, $62, $F6, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $80, $00, $40, $80, $20, $C0
	db $20, $C0, $40, $80, $80, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $F6, $00, $D7, $62, $D6, $63, $D6, $63
	db $D6, $63, $D6, $63, $D7, $62, $F6, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $80, $00, $40, $80
	db $40, $80, $80, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

; ---- gfx $4BC0-$4DC0 (512 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 0E:4255: hl=$49C0 a=$0E c=$40 de=$8001 (dest VRAM $8000, vbank=1) [clipped from 49C0-4DC0 by higher-priority evidence]

Gfx_Title_Tiles2:: ; 0E:4BC0
Data_0E_4BC0::
	db $00, $FF, $00, $FF, $00, $FF, $00, $C0, $1F, $BF, $3F, $A0, $3F, $A0, $3F, $A0
	db $3F, $A0, $1F, $BC, $27, $9C, $1F, $C4, $1F, $BC, $3F, $A0, $3F, $A0, $3F, $A0
	db $00, $FF, $00, $FF, $00, $FF, $00, $00, $FF, $FF, $FF, $00, $FF, $00, $FF, $00
	db $FF, $00, $FF, $7F, $C0, $7F, $FF, $40, $FF, $7F, $FF, $00, $FF, $00, $FF, $00
	db $00, $FF, $00, $FF, $00, $FF, $00, $38, $83, $D7, $C3, $56, $C3, $56, $C3, $56
	db $C3, $56, $83, $D6, $47, $96, $8D, $06, $CD, $E6, $E7, $2C, $E7, $2C, $FF, $2C
	db $13, $8F, $0C, $C6, $05, $FD, $01, $01, $D5, $ED, $EF, $39, $EF, $39, $FF, $29
	db $FF, $29, $EB, $2C, $E7, $2C, $EF, $24, $EF, $24, $A5, $66, $A3, $66, $CB, $62
	db $FE, $FE, $01, $03, $FD, $FD, $FD, $25, $FD, $25, $FD, $25, $FD, $25, $FD, $25
	db $FD, $FD, $E1, $43, $D0, $60, $BF, $6F, $AF, $78, $EF, $38, $EF, $38, $EF, $38
	db $FE, $00, $FE, $00, $77, $0F, $7C, $08, $29, $9B, $3B, $92, $13, $36, $35, $66
	db $EF, $CC, $9F, $18, $2F, $70, $BF, $C0, $FF, $00, $FF, $01, $FF, $03, $FE, $03
	db $3F, $00, $1F, $00, $FF, $FF, $00, $00, $EB, $F7, $F7, $1C, $F7, $1C, $F7, $1C
	db $F7, $1C, $DF, $34, $E7, $34, $E7, $64, $D7, $D4, $A7, $B4, $47, $74, $47, $74
	db $BF, $3F, $FE, $7F, $FF, $FF, $00, $00, $AE, $DF, $DF, $71, $DF, $71, $DF, $71
	db $DF, $71, $DF, $71, $DF, $71, $DF, $71, $DF, $71, $DF, $71, $DF, $71, $DF, $71
	db $03, $FC, $01, $FE, $87, $FF, $48, $FC, $49, $7B, $4B, $7A, $4B, $7A, $4B, $7A
	db $4B, $7A, $4B, $7A, $7B, $7A, $83, $02, $7F, $FA, $7B, $8E, $7B, $8E, $7B, $8E
	db $F0, $0F, $F8, $07, $FC, $F3, $0C, $1B, $C8, $EF, $E8, $2F, $E8, $2F, $E8, $2F
	db $E8, $2F, $EF, $2F, $E3, $20, $FD, $3E, $F7, $0F, $FF, $00, $FF, $00, $FF, $00
	db $03, $FC, $01, $FE, $0F, $FF, $10, $F8, $13, $F7, $17, $F4, $17, $F4, $17, $F4
	db $17, $F4, $F7, $F4, $77, $F4, $07, $04, $EF, $F4, $77, $FC, $F7, $1C, $F7, $1C
	db $FF, $00, $FF, $00, $FF, $E0, $1F, $30, $9F, $D0, $D7, $58, $D1, $5E, $D0, $5F
	db $D0, $5F, $DF, $5F, $D4, $58, $DB, $57, $D3, $56, $D3, $56, $D3, $56, $D3, $56
	db $9F, $70, $FF, $20, $FF, $00, $FF, $00, $FF, $00, $FE, $01, $FC, $03, $78, $87
	db $00, $FF, $F1, $FF, $0F, $1F, $D0, $E0, $FF, $2F, $EF, $38, $EF, $38, $EF, $38
	db $FC, $1B, $F8, $33, $B8, $27, $F0, $67, $D0, $CF, $90, $AF, $10, $6F, $11, $6E
	db $E0, $EE, $E0, $EE, $E0, $FE, $00, $00, $FE, $FF, $FF, $01, $FF, $01, $FF, $01
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $00, $7F, $FF
	db $FF, $80, $FF, $80, $FF, $80, $FF, $80, $FF, $80, $FF, $FF, $00, $FF, $00, $00
	db $00, $FF, $00, $FF, $00, $FF, $00, $83, $38, $7D, $7C, $45, $7C, $44, $FF, $C7
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $87, $FC, $87, $FC, $84

; ---- gfx $4DC0-$4FC0 (512 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 0E:4267: hl=$4BC0 a=$0E c=$40 de=$8801 (dest VRAM $8800, vbank=1) [clipped from 4BC0-4FC0 by higher-priority evidence]

Gfx_Title_Tiles3:: ; 0E:4DC0
Data_0E_4DC0::
	db $3F, $A0, $1F, $BC, $37, $8C, $07, $CC, $07, $EC, $07, $EC, $07, $EC, $07, $EC
	db $15, $E6, $06, $F3, $03, $F9, $00, $FC, $01, $FE, $00, $FF, $00, $FF, $00, $FF
	db $FF, $00, $FF, $7F, $C0, $7F, $C0, $40, $FF, $7F, $80, $7F, $FF, $00, $FF, $00
	db $FF, $00, $FF, $00, $FF, $FF, $00, $FF, $00, $00, $00, $FF, $00, $FF, $00, $FF
	db $FB, $2C, $EF, $F8, $1F, $F8, $5F, $30, $DF, $F0, $5E, $F1, $DF, $71, $DD, $73
	db $DE, $73, $DD, $76, $DA, $FC, $24, $D9, $20, $03, $00, $FF, $00, $FF, $00, $FF
	db $E3, $4A, $63, $CA, $52, $CB, $82, $DB, $C2, $9B, $A3, $9B, $01, $BB, $81, $3B
	db $41, $3B, $01, $7B, $01, $FB, $02, $F9, $00, $FC, $00, $FF, $00, $FF, $00, $FF
	db $CF, $38, $CF, $3F, $F0, $1F, $F0, $18, $F0, $1B, $F0, $1B, $F0, $1B, $F0, $1B
	db $F0, $1B, $F0, $1B, $F0, $FB, $08, $F3, $00, $07, $00, $FF, $00, $FF, $00, $FF
	db $FE, $03, $FE, $E3, $3E, $E3, $3E, $23, $3E, $A3, $3E, $A3, $3E, $A3, $3E, $A3
	db $3E, $A3, $3E, $A3, $1E, $BF, $21, $9E, $00, $C0, $07, $FF, $03, $F8, $01, $FC
	db $4F, $64, $47, $6C, $4B, $5C, $5F, $58, $5F, $50, $5F, $50, $5F, $50, $5F, $50
	db $5E, $51, $5F, $51, $5E, $53, $5C, $5E, $45, $D9, $E7, $C2, $FF, $3C, $FF, $00
	db $DF, $71, $DF, $71, $DF, $71, $DF, $71, $DF, $71, $DE, $71, $7F, $D0, $9F, $D0
	db $DF, $90, $1F, $90, $4F, $5F, $D0, $CF, $C0, $60, $FF, $3F, $FF, $00, $FF, $00
	db $7B, $8E, $7B, $8E, $7B, $8E, $7B, $8E, $7B, $8E, $FF, $0A, $FF, $0A, $EB, $1A
	db $F3, $1A, $A3, $72, $C9, $EB, $5A, $99, $78, $2C, $FF, $C7, $FF, $00, $FF, $00
	db $F7, $38, $FF, $3F, $FF, $27, $E1, $20, $EE, $2F, $EF, $2F, $E8, $2F, $E8, $2F
	db $E8, $2F, $E8, $2F, $C8, $EF, $28, $CF, $08, $1F, $FC, $F3, $FF, $00, $FF, $00
	db $F7, $1C, $77, $9C, $F7, $FC, $BF, $74, $87, $04, $F7, $F4, $17, $F4, $17, $F4
	db $17, $F4, $17, $F4, $13, $F7, $14, $F3, $10, $F8, $0F, $FF, $00, $FF, $E1, $1E
	db $C3, $56, $D5, $46, $C7, $4C, $DB, $4C, $F7, $78, $FF, $60, $FF, $00, $FF, $01
	db $FF, $03, $F6, $0F, $F8, $FE, $04, $F9, $0F, $03, $FF, $FF, $FF, $07, $FF, $07
	db $EF, $38, $EF, $38, $EF, $3F, $F0, $2F, $A0, $60, $CF, $6F, $FE, $CE, $8C, $DE
	db $1C, $BD, $3A, $79, $70, $FB, $F0, $F7, $E8, $E7, $C0, $EF, $80, $DF, $00, $BF
	db $FF, $01, $FF, $01, $FE, $FF, $01, $FE, $00, $00, $00, $FF, $80, $7F, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $7E, $01, $7D, $01, $7B, $0F, $06, $3B, $7C, $7F, $40, $7F, $40, $7F, $40
	db $7F, $40, $7E, $41, $3F, $7F, $40, $3F, $00, $80, $00, $FF, $00, $FF, $00, $FF
	db $FC, $85, $7C, $85, $FC, $05, $F4, $0D, $F8, $0D, $EC, $19, $F0, $1B, $F8, $33
	db $E0, $77, $C0, $EF, $40, $9F, $80, $3F, $80, $7F, $00, $FF, $00, $FF, $00, $FF

; ---- gfx $4FC0-$53C0 (1024 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 0E:4279: hl=$4FC0 a=$0E c=$40 de=$8C01 (dest VRAM $8C00, vbank=1)

Gfx_Title_Tiles4:: ; 0E:4FC0
Data_0E_4FC0::
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $3F, $80, $DF
	db $C0, $5F, $C0, $5F, $C0, $5F, $C0, $40, $FF, $7F, $FF, $C0, $FF, $C0, $7F, $40
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $03, $F8, $FD, $FC, $05, $FC, $05, $FC, $05
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $04, $F8, $08, $F3
	db $02, $F4, $00, $F5, $02, $F4, $08, $F3, $04, $F8, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $21, $1E, $12, $CC
	db $43, $2C, $00, $EF, $41, $2E, $12, $CC, $22, $1C, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $04, $38, $09, $92
	db $09, $92, $A9, $12, $49, $32, $89, $72, $04, $18, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $10, $E3, $24, $49
	db $24, $49, $24, $49, $24, $49, $24, $49, $10, $E3, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $80, $1F, $40, $9F
	db $40, $9F, $40, $9F, $40, $9F, $40, $9F, $40, $9F, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $21, $CE, $21, $C6, $21, $C6
	db $21, $CA, $21, $CA, $21, $CC, $20, $CC, $20, $CE, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $20, $4F, $20, $4F, $00, $7F
	db $24, $49, $24, $48, $24, $49, $24, $49, $24, $49, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $08, $F3, $10, $E1
	db $08, $33, $49, $92, $49, $92, $49, $92, $48, $93, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $82, $0C, $12, $64, $02, $04, $02, $7C, $82, $04, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $02, $9C, $24, $49, $24, $C9, $24, $C9, $22, $CC, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $40, $9F, $40, $9F, $40, $9F
	db $04, $18, $48, $93, $48, $93, $48, $93, $04, $18, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $7F, $80, $3F, $80, $3F, $80, $3F, $00, $7F, $00, $FF, $00, $FF, $00, $FF
	db $7F, $40, $7F, $40, $3F, $7F, $40, $3F, $00, $80, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $F0, $00, $FD, $00, $FD, $00, $FD, $00, $FD, $00, $FF, $00, $FF
	db $FC, $05, $FC, $05, $F8, $FD, $04, $F9, $00, $03, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $5D, $00, $C9, $00, $D5, $00, $DD, $00, $DD, $00, $FF, $00, $FF
	db $00, $FF, $07, $FF, $18, $FF, $20, $FF, $20, $FF, $40, $FF, $40, $FF, $40, $FF
	db $40, $FF, $60, $FF, $60, $FF, $38, $FF, $3F, $FF, $1F, $FF, $07, $FF, $00, $FF
	db $00, $FF, $E0, $FF, $78, $FF, $1C, $FF, $1C, $FF, $0E, $FF, $0E, $FF, $0E, $FF
	db $0E, $FF, $1E, $FF, $1E, $FF, $7C, $FF, $FC, $FF, $F8, $FF, $E0, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $12, $E1, $0C, $E1, $04, $E9, $04, $E9, $04, $E9, $04, $E9
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $80, $3D, $BE, $1F, $BF
	db $2F, $9F, $17, $AF, $2B, $B7, $B5, $3B, $7A, $3D, $3D, $7E, $7E, $7F, $7F, $7F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $80, $7F, $02, $01, $F4, $F8
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $7F, $FF, $BF, $7F, $5E, $BF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $08, $07
	db $E8, $F0, $FF, $FF, $FF, $FF, $FE, $FF, $FB, $FC, $ED, $F3, $B7, $CF, $DF, $3F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $3F, $80, $BF, $80, $BF, $00, $BF, $00, $BF, $80, $3F, $40, $3F, $00, $7F
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $03, $FF, $0F, $FF, $1F, $FF, $3F, $FF, $3C, $FF, $70, $FF, $60, $FF
	db $C0, $FF, $C0, $FF, $80, $FF, $80, $FF, $80, $FF, $80, $FF, $80, $FF, $C0, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $0F, $FF, $03, $FF, $01, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $C0, $FF, $F0, $FF, $F8, $FF, $FC, $FF, $FC, $FF, $FE, $FF, $FE, $FF
	db $FF, $FF, $FF, $FF, $7F, $FF, $7F, $FF, $7F, $FF, $7F, $FF, $7F, $FF, $FF, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $01, $FF, $03, $FF, $03, $FF, $07, $FF, $07, $FF, $07, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $07, $FF, $1F, $FF, $3F, $FF
	db $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FE, $FF, $FC, $FF, $FC, $FF

; ---- gfx $53C0-$57C0 (1024 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 0E:428B: hl=$53C0 a=$0E c=$40 de=$9001 (dest VRAM $9000, vbank=1)

Gfx_Title_Tiles5:: ; 0E:53C0
Data_0E_53C0::
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $01, $FE, $04, $F8, $0B, $F0, $17, $E3, $0F, $E7, $1F, $CF, $5F, $8F, $3F, $9F
	db $10, $0F, $E0, $07, $F8, $E3, $FC, $F1, $FD, $F8, $FE, $F8, $FE, $FC, $FE, $FC
	db $04, $E9, $04, $E9, $0C, $E0, $2F, $C0, $18, $C7, $10, $CF, $97, $48, $97, $4B
	db $00, $FF, $00, $FF, $00, $00, $FF, $00, $01, $FE, $00, $FF, $FE, $01, $FE, $FF
	db $00, $FF, $01, $FE, $80, $7E, $40, $3E, $80, $3E, $80, $3E, $80, $3E, $80, $3E
	db $7F, $7F, $7F, $7F, $FF, $7F, $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $C0, $00
	db $BB, $C4, $FD, $C3, $FF, $C3, $DB, $E7, $FF, $FF, $FF, $FF, $FF, $FF, $3C, $18
	db $7F, $FF, $FF, $FF, $FE, $FF, $FF, $FE, $FE, $FE, $FE, $FE, $FE, $FE, $7C, $3E
	db $80, $7F, $80, $7F, $80, $7F, $B8, $43, $76, $11, $FF, $3C, $FE, $7E, $7B, $63
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $80, $3F, $E0, $9F
	db $40, $FF, $60, $FF, $30, $FF, $3C, $FF, $1F, $FF, $0F, $FF, $03, $FF, $00, $FF
	db $00, $FF, $01, $FF, $03, $FF, $0F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $FE, $FF, $FE, $FF, $FC, $FF, $FC, $FF, $F8, $FF, $F0, $FF, $C0, $FF, $00, $FF
	db $0F, $FF, $0F, $FF, $0F, $FF, $0F, $FF, $0F, $FF, $0F, $FF, $0F, $FF, $0F, $FF
	db $F8, $FF, $F8, $FF, $F8, $FF, $F8, $FF, $F8, $FF, $F8, $FF, $F8, $FF, $F8, $FF
	db $02, $FF, $06, $FF, $0C, $FF, $3C, $FF, $F8, $FE, $F0, $FC, $C1, $F8, $02, $F1
	db $BF, $1F, $BF, $1F, $7F, $3F, $7F, $3F, $7F, $3F, $7F, $3F, $7F, $3F, $7F, $3F
	db $FF, $FC, $FF, $FC, $FF, $FC, $FF, $FC, $FF, $FC, $FF, $FC, $FF, $F8, $FE, $F8
	db $17, $4B, $17, $4B, $17, $4B, $17, $4B, $17, $4B, $17, $4B, $17, $4B, $97, $4B
	db $FE, $FF, $FE, $FF, $FE, $FF, $FE, $FF, $FE, $FF, $FE, $FF, $FE, $FF, $FE, $FF
	db $81, $3E, $80, $3C, $81, $38, $80, $33, $81, $26, $AA, $04, $80, $0C, $95, $08
	db $00, $00, $40, $3F, $1F, $E0, $40, $80, $1F, $07, $7F, $3F, $FF, $7F, $FF, $FF
	db $00, $00, $24, $C3, $C0, $3F, $0A, $05, $ED, $E2, $E6, $E1, $F1, $C0, $FC, $00
	db $EC, $0C, $3D, $81, $0F, $E3, $07, $F7, $07, $EE, $0F, $4C, $1B, $18, $9F, $38
	db $FF, $C1, $FF, $80, $7F, $80, $FF, $00, $FF, $00, $F9, $06, $F0, $0F, $E0, $19
	db $F0, $CF, $E8, $E3, $BE, $39, $FF, $1C, $FE, $0E, $FB, $03, $FF, $01, $3F, $00
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $80, $3F, $E0, $9F, $F0, $CF, $E8, $E3
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $07, $FF, $07, $FF, $07, $FF, $03, $FF, $03, $FF, $01, $FF, $00, $FF, $00, $FF
	db $FC, $FF, $FC, $FF, $FE, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $7F, $FF
	db $15, $E2, $00, $E6, $2A, $C4, $20, $CC, $05, $C8, $14, $C9, $14, $C9, $14, $C9
	db $7F, $3F, $7F, $3F, $7F, $3F, $7F, $1F, $BF, $1F, $3F, $8F, $1F, $C0, $2F, $C0
	db $FE, $F8, $FD, $F2, $FE, $F1, $F8, $E1, $F9, $C0, $F5, $80, $E3, $08, $87, $10
	db $90, $4F, $57, $08, $57, $0F, $97, $0F, $10, $8F, $FC, $03, $FF, $00, $FF, $00
	db $73, $8C, $FF, $70, $FF, $60, $FF, $40, $FF, $3C, $FF, $FF, $FF, $FF, $FF, $7F
	db $C1, $18, $CB, $10, $CB, $10, $CB, $10, $CB, $10, $CB, $10, $CB, $90, $CB, $90
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $FE, $00, $FF, $00, $FF, $00, $FF, $00, $FE, $01, $FC, $03, $F8, $07, $F9, $06
	db $BF, $70, $FF, $60, $DF, $E0, $FF, $C0, $FE, $81, $FE, $01, $FC, $03, $F8, $06
	db $C0, $30, $C0, $60, $80, $60, $00, $C0, $00, $80, $00, $00, $00, $00, $00, $00
	db $1F, $60, $0F, $38, $03, $1C, $01, $06, $00, $03, $00, $01, $00, $00, $00, $00
	db $BF, $79, $FF, $1C, $FE, $0F, $FB, $07, $FF, $01, $3F, $C0, $9F, $E0, $CF, $F0
	db $00, $FF, $00, $FF, $80, $3F, $E0, $9F, $F0, $CF, $E8, $E3, $BE, $39, $FF, $1C
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $3F, $FF, $1F, $FF, $07, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $14, $C9, $14, $C9, $14, $C9, $14, $C9, $05, $C8, $20, $CC, $2A, $C4, $00, $E6
	db $2C, $C0, $1C, $C1, $1A, $C1, $58, $83, $38, $83, $38, $83, $B4, $03, $70, $07
	db $57, $77, $0F, $EF, $0F, $EF, $0F, $EF, $0F, $EF, $0F, $EF, $0F, $EF, $0F, $EF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $C0, $FF, $C0, $FF, $E0, $DF, $E0, $DF, $C0, $DF, $D0, $CF, $D0, $CF, $D0, $CF
	db $CB, $90, $CB, $90, $CB, $91, $CB, $91, $CB, $91, $CB, $91, $8B, $93, $AB, $93
	db $FF, $00, $FF, $00, $FF, $00, $FF, $F0, $FF, $FE, $FF, $FF, $FE, $FF, $FE, $FF
	db $F3, $0C, $E7, $18, $C7, $38, $CF, $30, $9F, $60, $1F, $E0, $1F, $E0, $0F, $F0
	db $F0, $0C, $F0, $18, $E0, $18, $C0, $30, $C0, $60, $E0, $20, $F0, $00, $F8, $04
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $02, $00, $01, $00, $2A, $00, $05
	db $03, $0C, $01, $16, $03, $AE, $07, $54, $07, $B8, $0F, $50, $1F, $F0, $3F, $60
	db $FE, $0E, $FF, $07, $FF, $06, $FF, $04, $FA, $09, $FC, $19, $DC, $13, $F8, $27
	db $80, $7F, $80, $7F, $00, $7F, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $E0, $FF, $F8, $FF, $FC, $FF

; ---- gfx $57C0-$5BC0 (1024 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 0E:429D: hl=$57C0 a=$0E c=$40 de=$9401 (dest VRAM $9400, vbank=1)

Gfx_Title_Tiles6:: ; 0E:57C0
Data_0E_57C0::
	db $15, $E2, $00, $F3, $0A, $F1, $00, $F9, $05, $F8, $00, $FC, $00, $FE, $00, $FF
	db $70, $07, $70, $07, $E8, $07, $E0, $0F, $E0, $0F, $E0, $07, $70, $03, $28, $11
	db $17, $F7, $07, $F3, $03, $F1, $09, $F8, $02, $FA, $01, $F9, $0D, $F9, $06, $F0
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $7F, $3E, $8E, $00, $F0, $C0, $FC, $FC
	db $D8, $CF, $D8, $8F, $DC, $9F, $BD, $1F, $3E, $3E, $7E, $3E, $7F, $3F, $7F, $3F
	db $23, $93, $83, $33, $17, $23, $47, $27, $2F, $47, $8F, $4F, $5F, $8F, $9F, $1F
	db $FC, $FF, $F8, $FF, $F0, $FF, $F0, $FF, $E0, $FF, $C3, $FC, $87, $F8, $87, $F8
	db $FF, $F8, $FF, $FC, $FF, $FE, $FF, $FF, $FF, $FF, $FF, $CF, $FF, $07, $FF, $07
	db $FC, $02, $FF, $00, $FF, $00, $FF, $00, $FF, $80, $FF, $C0, $FF, $E0, $F7, $F8
	db $00, $00, $00, $00, $C0, $4A, $C0, $20, $F0, $02, $FC, $05, $FC, $02, $FF, $00
	db $00, $AB, $00, $15, $00, $AF, $01, $57, $03, $BE, $03, $5C, $07, $F8, $0F, $F0
	db $3F, $C0, $7F, $80, $FE, $01, $FF, $01, $FE, $03, $FF, $06, $F7, $0C, $FF, $09
	db $D0, $4F, $E0, $CF, $E0, $9F, $C0, $3F, $80, $7F, $00, $7F, $00, $FF, $00, $FF
	db $FF, $FF, $F0, $FF, $C0, $FF, $80, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $FE, $FF, $1F, $FF, $07, $FF, $03, $FF, $01, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $80, $FF, $C0, $FF, $C0, $FF, $E0, $FF, $60, $FF, $60, $FF
	db $00, $FE, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $FF, $00, $3F, $00, $5F, $80, $07, $E0, $09, $F0, $02, $FC, $00, $FF, $00, $FF
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $7F, $00, $8F, $00, $10, $E0
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
	db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FE, $00, $F1, $00, $08, $07
	db $FF, $00, $FC, $00, $FA, $01, $E0, $07, $90, $0F, $40, $3F, $00, $FF, $00, $FF
	db $00, $7F, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $80, $FF, $C0, $FF, $F0, $FF, $FF, $FF
	db $00, $FF, $00, $FF, $00, $FF, $01, $FF, $03, $FF, $07, $FF, $1F, $FF, $FE, $FF
	db $60, $FF, $60, $FF, $E0, $FF, $C0, $FF, $C0, $FF, $80, $FF, $00, $FF, $00, $FF
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $FC, $FF, $F8, $FF, $E0, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
	db $00, $FF, $01, $FE, $03, $FD, $06, $FA, $06, $FA, $02, $FD, $06, $FA, $16, $FA
	db $00, $FF, $F9, $06, $FF, $F9, $02, $06, $02, $06, $06, $3A, $02, $06, $02, $06
	db $00, $FF, $B6, $49, $FF, $B6, $00, $49, $00, $49, $01, $7E, $23, $65, $22, $66
	db $00, $FF, $1C, $E3, $3F, $DC, $E1, $33, $C1, $63, $83, $C5, $07, $89, $07, $09
	db $00, $FF, $F8, $07, $FD, $FA, $22, $25, $23, $25, $23, $25, $23, $24, $23, $24
	db $00, $FF, $66, $99, $FF, $66, $88, $99, $00, $00, $00, $00, $00, $99, $88, $99
	db $00, $FF, $00, $FF, $00, $FF, $FD, $02, $FF, $FC, $87, $82, $82, $81, $80, $79
	db $00, $FF, $7F, $80, $FF, $7F, $80, $80, $80, $80, $88, $67, $E7, $48, $C4, $4B
	db $00, $FF, $33, $CC, $FF, $33, $46, $CA, $46, $CA, $C6, $4A, $C6, $4A, $C6, $4A
	db $00, $FF, $00, $FF, $80, $7F, $40, $BF, $20, $5F, $20, $5F, $20, $5F, $28, $5F
	db $00, $FF, $00, $FF, $01, $FE, $03, $FD, $03, $FD, $01, $FE, $00, $FF, $1F, $FF
	db $03, $FC, $FC, $03, $FE, $FD, $01, $02, $01, $02, $01, $F2, $E1, $13, $41, $A3
	db $00, $00, $7E, $81, $FF, $7E, $80, $81, $80, $81, $80, $99, $08, $19, $00, $21
	db $00, $00, $00, $FF, $00, $FF, $80, $7F, $80, $7F, $FE, $01, $FF, $7E, $80, $81
	db $C0, $3F, $30, $CF, $78, $B7, $C4, $4B, $C4, $4B, $C7, $48, $CF, $4F, $C0, $40
	db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $80, $7F, $58, $BF
	db $3A, $FD, $7B, $FD, $7B, $FD, $7B, $FD, $7D, $FE, $7E, $BF, $2F, $DF, $10, $E0
	db $06, $3A, $1E, $3A, $02, $06, $82, $06, $06, $F9, $F9, $06, $06, $FF, $00, $00
	db $22, $66, $20, $67, $23, $64, $22, $65, $65, $9B, $9B, $67, $67, $FF, $00, $00
	db $47, $09, $44, $CB, $C6, $4A, $C6, $4A, $4A, $B5, $B5, $CE, $CE, $FF, $00, $00
	db $23, $24, $23, $24, $61, $22, $B1, $62, $62, $9D, $9D, $63, $63, $FF, $00, $00
	db $88, $9F, $8F, $9E, $C0, $81, $A0, $41, $41, $BE, $BE, $C1, $C1, $FF, $00, $00
	db $F8, $09, $F0, $39, $C2, $41, $C5, $42, $43, $BC, $BE, $C1, $C1, $FF, $00, $00
	db $C6, $49, $CF, $46, $A0, $41, $D0, $21, $21, $DE, $DE, $E1, $E1, $FF, $00, $00
	db $C6, $4A, $C6, $4A, $C2, $46, $C2, $26, $66, $99, $BD, $C2, $C2, $FF, $00, $00
	db $2C, $5F, $2E, $5F, $2E, $5F, $2E, $5F, $5E, $BF, $BE, $7D, $74, $FB, $08, $07
	db $3E, $FF, $7D, $FE, $7B, $FD, $7B, $FD, $7D, $FE, $7E, $BF, $2F, $DF, $10, $E0
	db $C3, $44, $81, $82, $00, $11, $10, $29, $A9, $D6, $D6, $39, $39, $FF, $00, $00
	db $20, $C1, $F0, $71, $81, $82, $83, $85, $85, $7B, $7B, $87, $87, $FF, $00, $00
	db $80, $81, $81, $7E, $7E, $81, $81, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00
	db $C0, $40, $C0, $4F, $C7, $48, $C4, $4B, $4B, $B7, $B7, $CF, $CF, $FF, $00, $00
	db $5C, $BF, $BE, $7F, $7E, $FF, $FE, $FF, $FE, $FF, $FE, $FD, $F4, $FB, $08, $07

; ---- data $5BC0-$5E90 (720 bytes) [CONFIRMED] tilemap+attr: 1 call site(s); first: copy_tilemap_rect_pair at 0E:42D0: hl=$5BC0 a=$0E b=18 rows c=20 cols (tiles then attrs) de=$D000

Tilemap_Title_Screen:: ; 0E:5BC0
Data_0E_5BC0::
	db $C2, $C2, $C2, $C2, $C2, $E4, $E6, $E8, $EA, $EC, $EE, $F0, $F2, $F4, $C2, $C2
	db $3F, $3E, $FE, $C2, $C2, $FA, $F8, $F6, $C2, $E5, $E7, $E9, $EB, $ED, $EF, $F1
	db $F3, $F5, $C2, $4F, $4E, $4D, $FF, $FD, $C2, $FB, $F9, $F7, $01, $02, $03, $04
	db $05, $06, $07, $08, $09, $0A, $C2, $5A, $59, $58, $0F, $0E, $C2, $0D, $0C, $10
	db $11, $12, $13, $14, $15, $16, $17, $18, $19, $1A, $1B, $5D, $5C, $5B, $1F, $1E
	db $C2, $C2, $C2, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $2A, $2B, $2C
	db $5F, $5E, $2F, $C2, $C2, $C2, $C2, $30, $31, $32, $33, $34, $35, $36, $37, $38
	db $39, $3A, $3B, $3C, $3D, $C2, $C2, $C2, $C2, $C2, $C2, $40, $41, $42, $43, $44
	db $45, $46, $47, $48, $49, $4A, $4B, $4C, $C2, $C2, $C2, $C2, $C2, $80, $82, $84
	db $86, $88, $8A, $8C, $8E, $90, $92, $94, $96, $98, $9A, $9C, $9E, $C0, $C2, $C2
	db $C2, $81, $83, $85, $87, $89, $8B, $8D, $8F, $91, $93, $95, $97, $99, $9B, $9D
	db $9F, $C1, $C3, $C2, $C2, $A0, $A2, $A4, $A6, $A8, $AA, $AC, $AE, $B0, $B2, $B4
	db $B6, $B8, $BA, $BC, $BE, $DC, $DE, $C2, $C2, $A1, $A3, $A5, $A7, $A9, $AB, $AD
	db $AF, $B1, $B3, $B5, $B7, $B9, $BB, $BD, $BF, $DD, $DF, $C2, $C2, $C2, $C2, $C2
	db $C2, $C2, $50, $51, $52, $53, $54, $55, $56, $57, $C2, $E0, $E2, $C2, $C2, $C2
	db $C2, $FE, $3E, $3F, $C2, $C2, $C2, $6A, $6B, $6C, $6D, $6E, $6F, $C2, $C2, $E1
	db $E3, $C2, $C2, $C2, $FD, $FF, $4D, $4E, $4F, $C2, $C2, $7A, $7B, $7C, $7D, $7E
	db $7F, $C2, $C2, $C2, $C2, $C2, $C2, $C2, $0E, $0F, $58, $59, $5A, $60, $61, $62
	db $63, $64, $65, $66, $67, $68, $69, $C2, $F6, $F8, $FA, $C2, $1E, $1F, $5B, $5C
	db $5D, $70, $71, $72, $73, $74, $75, $76, $77, $78, $79, $C2, $F7, $F9, $FB, $C2
	db $C2, $2F, $5E, $5F, $C4, $C6, $C8, $CA, $CC, $CE, $D0, $D2, $D4, $D6, $D8, $DA
	db $0B, $0C, $0D, $C2, $C2, $C2, $C2, $C2, $C5, $C7, $C9, $CB, $CD, $CF, $D1, $D3
	db $D5, $D7, $D9, $DB, $C2, $C2, $C2, $C2, $08, $08, $08, $08, $08, $08, $08, $08
	db $09, $09, $09, $0B, $08, $08, $08, $08, $28, $28, $28, $08, $08, $28, $28, $28
	db $08, $08, $0B, $0B, $0B, $09, $09, $09, $0B, $08, $08, $28, $28, $28, $28, $28
	db $08, $28, $28, $28, $0B, $0B, $0B, $0B, $0B, $09, $09, $09, $0A, $0A, $08, $28
	db $28, $28, $28, $28, $08, $28, $28, $0B, $0B, $0B, $0B, $0B, $0B, $0B, $0B, $0A
	db $0E, $0A, $0A, $28, $28, $28, $28, $28, $08, $08, $08, $0B, $0B, $0B, $0B, $0B
	db $0B, $08, $08, $0E, $0F, $0F, $0E, $0A, $28, $28, $28, $08, $08, $08, $08, $0B
	db $0B, $0C, $0C, $0C, $0B, $08, $08, $0F, $0E, $0F, $0F, $0A, $0A, $08, $08, $08
	db $08, $08, $08, $0B, $0B, $0C, $0C, $0C, $0B, $08, $0A, $0E, $0F, $0F, $0E, $0A
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $0F, $0A, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $0D, $0D, $0D, $0D, $0D
	db $0D, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $09
	db $09, $09, $09, $09, $09, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $09, $09, $09, $09, $09, $09, $09, $09, $09, $09, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $0D, $0D, $0D, $0D
	db $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $08, $08, $08, $08, $08, $08, $08, $08
	db $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $08, $08, $08, $08

; ---- gfx $5E90-$5F30 (160 bytes) [PROBABLE] tiles-2bpp: heuristic: 33 coherent tiles (hsim2=0.616 vsim2=0.870, 0 blank) parity 0; 368/528 bytes also covered by call-site blocks [clipped from 5D20-5F30 by higher-priority evidence]

Tilemap_Title_HighlightStart:: ; 0E:5E90
Data_0E_5E90::
	db $00, $00, $6A, $6B, $6C, $6D, $6E, $6F, $00, $00, $00, $00, $7A, $7B, $7C, $7D
	db $7E, $7F, $00, $00, $80, $82, $84, $86, $88, $8A, $8C, $8E, $90, $92, $81, $83
	db $85, $87, $89, $8B, $8D, $8F, $91, $93, $0D, $0D, $09, $09, $09, $09, $09, $09
	db $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $03, $03, $03, $03
	db $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03

Tilemap_Title_HighlightSettings:: ; 0E:5EE0
	db $00, $00, $94, $96, $98, $9A, $9C, $9E, $00, $00, $00, $00, $95, $97, $99, $9B
	db $9D, $9F, $00, $00, $60, $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, $71
	db $72, $73, $74, $75, $76, $77, $78, $79, $08, $08, $03, $03, $03, $03, $03, $03
	db $08, $08, $08, $08, $03, $03, $03, $03, $03, $03, $08, $08, $09, $09, $09, $09
	db $09, $09, $09, $09, $09, $09, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D, $0D

; ---- data $5F30-$60A0 (368 bytes) [PROBABLE] palette-rgb555: heuristic: 184 RGB555 words as 46 palette group(s) of 4 (bit15 clear, contains $7FFF, monotone luminance)

Palette_Title_Bg:: ; 0E:5F30
Data_0E_5F30::
	db $00, $00, $45, $78, $52, $7E, $FF, $7F, $00, $00, $71, $15, $52, $7E, $7F, $4F
	db $2C, $41, $05, $00, $52, $7E, $9F, $02, $00, $00, $2C, $41, $52, $7E, $FF, $7F
	db $00, $00, $03, $2C, $52, $7E, $0B, $7C, $00, $00, $60, $40, $52, $7E, $FF, $7F
	db $F9, $36, $05, $00, $91, $15, $9F, $02, $F9, $36, $05, $00, $91, $15, $AB, $00

Palette_Title_Obj:: ; 0E:5F70
	db $52, $7E, $00, $00, $1F, $00, $0F, $00, $E0, $7F, $05, $00, $41, $03, $9F, $02
	db $E0, $7F, $80, $7D, $41, $03, $9F, $02, $E0, $7F, $60, $40, $21, $02, $7A, $01
	db $C0, $7D, $6A, $08, $1F, $00, $67, $57, $E0, $7F, $0B, $7C, $21, $02, $D1, $7C
	db $E0, $7F, $05, $00, $21, $02, $7A, $01, $E0, $7F, $41, $03, $21, $02, $80, $7D

Objects_Title:: ; 0E:5FB0
	db $00, $00, $00, $00, $BC, $5F, $08, $60, $19, $60, $98, $60, $C4, $5F, $D5, $5F
	db $E6, $5F, $F7, $5F, $04, $00, $00, $00, $08, $00, $08, $02, $08, $00, $68, $00
	db $28, $00, $60, $02, $28, $04, $00, $00, $04, $08, $00, $08, $06, $08, $00, $68
	db $04, $28, $00, $60, $06, $28, $04, $00, $00, $08, $08, $00, $08, $0A, $08, $00
	db $68, $08, $28, $00, $60, $0A, $28, $04, $00, $00, $0C, $08, $00, $08, $0E, $08
	db $00, $68, $0C, $28, $00, $60, $0E, $28, $08, $00, $04, $01, $04, $02, $04, $03
	db $04, $03, $04, $02, $04, $01, $04, $00, $04, $1B, $60, $1F, $20, $50, $08, $01
	db $38, $48, $14, $01, $38, $50, $16, $01, $38, $58, $18, $01, $38, $60, $1A, $06
	db $40, $68, $1C, $06, $38, $70, $1E, $06, $20, $40, $0C, $02, $20, $38, $0A, $02
	db $30, $38, $10, $02, $18, $48, $04, $02, $18, $50, $06, $02, $48, $38, $24, $03
	db $48, $40, $26, $03, $48, $48, $28, $03, $48, $50, $2A, $03, $48, $58, $2C, $03
	db $48, $60, $2E, $03, $48, $68, $30, $03, $10, $20, $00, $04, $10, $28, $02, $04
	db $20, $20, $20, $04, $30, $20, $3A, $04, $20, $28, $22, $04, $38, $38, $32, $05
	db $20, $28, $34, $05, $20, $30, $36, $05, $30, $30, $38, $05, $28, $48, $3E, $07
	db $28, $48, $0E, $01, $30, $40, $12, $02, $01, $00, $04, $00, $00, $00, $00, $00

; ---- gfx $60A0-$64A0 (1024 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 0E:436B: hl=$60A0 a=$0E c=$40 de=$9001 (dest VRAM $9000, vbank=1)

Gfx_TitleLogo_Tiles0:: ; 0E:60A0
Data_0E_60A0::
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $10, $0F, $94, $78
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $10, $E0, $80, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $04, $03, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $40, $80, $84, $78, $14, $0F
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $80, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $39, $79, $1C, $3C, $16, $0F, $07, $03, $01, $00, $00, $00, $00, $00, $00, $00
	db $89, $C8, $44, $E0, $70, $30, $C8, $9C, $65, $E2, $5C, $38, $0A, $07, $01, $00
	db $FF, $FF, $FF, $7F, $5F, $3F, $00, $00, $00, $00, $00, $00, $80, $00, $20, $C0
	db $FC, $FE, $FC, $FC, $F0, $F8, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $FF, $7F, $7F, $FF, $FF, $FF, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $FF, $FF, $FE, $FF, $FA, $FC, $00, $00, $00, $00, $00, $00, $00, $00, $02, $01
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $03, $01
	db $02, $01, $0B, $07, $0F, $1E, $79, $3C, $F1, $7B, $E7, $F3, $E7, $E7, $C6, $EF
	db $C5, $E2, $08, $9C, $20, $70, $C4, $E0, $88, $C8, $18, $90, $B0, $30, $21, $70
	db $00, $00, $00, $00, $05, $03, $17, $0F, $1F, $3F, $3F, $7F, $7C, $FE, $FC, $FC
	db $00, $00, $00, $00, $FF, $FF, $FF, $FF, $FF, $FF, $80, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $DF, $8F, $CF, $9F, $1F, $9F, $1F, $1F, $1E, $1F, $3E, $1F
	db $00, $00, $00, $00, $FF, $FF, $FF, $FF, $FF, $FF, $0F, $07, $03, $07, $0F, $07
	db $51, $23, $08, $1C, $02, $87, $91, $C3, $C8, $C9, $CC, $C4, $C6, $C6, $82, $C7
	db $A0, $C0, $68, $F0, $78, $3C, $CF, $9E, $C7, $EF, $73, $E7, $F3, $73, $31, $7B
	db $00, $00, $00, $00, $00, $00, $00, $00, $80, $00, $80, $80, $80, $C0, $E0, $C0
	db $08, $89, $11, $03, $07, $06, $09, $1C, $53, $23, $1D, $0E, $A8, $70, $40, $80
	db $CE, $CF, $1C, $9E, $34, $78, $F0, $E0, $40, $80, $3B, $3A, $13, $13, $12, $12
	db $00, $00, $00, $00, $00, $00, $1B, $0A, $0E, $1B, $15, $1F, $15, $15, $15, $15
	db $00, $00, $00, $00, $00, $00, $7B, $33, $7A, $4A, $4B, $4B, $7A, $4A, $7B, $33
	db $00, $00, $00, $00, $00, $00, $A9, $29, $E9, $A9, $A9, $29, $E9, $A9, $2D, $AD
	db $00, $00, $00, $00, $00, $00, $CF, $C6, $0C, $08, $CE, $C4, $02, $06, $CE, $CC
	db $01, $03, $03, $03, $03, $03, $03, $03, $01, $03, $03, $01, $00, $01, $00, $00
	db $EF, $CE, $CE, $CE, $CE, $CE, $CE, $CE, $E7, $CE, $CE, $E7, $E3, $E7, $73, $F3
	db $71, $61, $F3, $61, $F1, $63, $F3, $63, $73, $63, $21, $73, $B3, $31, $99, $91
	db $FC, $F8, $F8, $F8, $F0, $F8, $F0, $F8, $F0, $F8, $F0, $F8, $FC, $F8, $FC, $FF
	db $00, $00, $00, $00, $7F, $3F, $FF, $7F, $FE, $7F, $3F, $3E, $7E, $3E, $7E, $FE
	db $FF, $7F, $7F, $FF, $FF, $7F, $7D, $3E, $7E, $3C, $3E, $7C, $3C, $7C, $7C, $7C
	db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $1F, $0F, $0F, $0F, $0F, $1F, $0F, $3F, $1F
	db $C7, $83, $07, $83, $C7, $83, $87, $C3, $C7, $C3, $C2, $C7, $86, $C6, $CC, $84
	db $7B, $39, $B9, $39, $B9, $39, $B9, $39, $73, $39, $39, $73, $E3, $73, $E7, $E7
	db $C0, $E0, $E0, $E0, $E0, $E0, $E0, $E0, $C0, $E0, $E0, $C0, $80, $C0, $00, $80
	db $00, $00, $00, $00, $00, $00, $AE, $A6, $E8, $AC, $EE, $44, $42, $46, $4E, $4C
	db $00, $00, $00, $00, $00, $00, $FD, $EC, $48, $49, $4D, $4D, $49, $49, $4D, $4D
	db $00, $00, $00, $00, $00, $00, $B1, $A0, $E3, $B1, $51, $F3, $53, $51, $51, $50
	db $00, $00, $00, $00, $00, $00, $CC, $EE, $2A, $0A, $6E, $6C, $3A, $2A, $EC, $CE
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $80, $80, $80, $80, $80, $80
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

; ---- gfx $64A0-$68A0 (1024 bytes) [CONFIRMED] tiles-vram: 1 call site(s); first: hdma_rom_to_vram at 0E:437D: hl=$64A0 a=$0E c=$40 de=$9401 (dest VRAM $9400, vbank=1)

Gfx_TitleLogo_Tiles1:: ; 0E:64A0
Data_0E_64A0::
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

; ---- data $68A0-$6B70 (720 bytes) [CONFIRMED] tilemap+attr: 1 call site(s); first: copy_tilemap_rect_pair at 0E:439F: hl=$68A0 a=$0E b=18 rows c=20 cols (tiles then attrs) de=$D000

Tilemap_TitleLogo_Screen:: ; 0E:68A0
Data_0E_68A0::
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $02
	db $03, $04, $05, $06, $07, $08, $09, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $0A, $0B, $0C, $0D, $0E, $0F
	db $1A, $1B, $2E, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $1C, $1D
	db $1E, $1F, $2A, $2B, $2C, $2D, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08, $08

; ---- data $6B70-$6BB0 (64 bytes) [PROBABLE] palette-rgb555: heuristic: 32 RGB555 words as 8 palette group(s) of 4 (bit15 clear, contains $7FFF, monotone luminance)

Palette_TitleLogo:: ; 0E:6B70
Data_0E_6B70::
	db $FF, $7F, $75, $7E, $CA, $7C, $45, $78, $FF, $7F, $75, $7E, $CA, $7C, $45, $78
	db $FF, $7F, $75, $7E, $CA, $7C, $45, $78, $FF, $7F, $4A, $29, $B5, $56, $FF, $7F
	db $FF, $7F, $4A, $29, $B5, $56, $FF, $7F, $FF, $7F, $4A, $29, $B5, $56, $FF, $7F
	db $FF, $7F, $4A, $29, $B5, $56, $FF, $7F, $00, $00, $4A, $29, $B5, $56, $FF, $7F

; ---- zero $6BB0-$8000 (5200 bytes) [PROBABLE] trailing 0x00 padding to end of bank
	ds $1450, $00
