; Generated by tools/gen_asm.py -- DO NOT EDIT (edit config/ and run `make regen`).
; bank 03

INCLUDE "constants/hardware.inc"
INCLUDE "ram.inc"

SECTION "Bank03", ROMX[$4000], BANK[$03]

; ---- raw $4000-$8000 (16384 bytes) [unclassified gap]
	INCBIN "baserom.gbc", $C000, $4000
